FROM node:22.7.0-alpine

# System
RUN apk update
RUN apk add \
    gettext  \
    moreutils \
    dos2unix

# Installer Angular CLI globalement
RUN npm install -g @angular/cli

WORKDIR /var/www/clien

# Project files
COPY ./client/package*.json ./

# install dependencies
RUN npm ci

# copy the reste of the application code
COPY ./client .

# Verify Angular CLI installation
RUN ng version

RUN node -v
RUN npm -v

#CMD tail -f /dev/null
CMD npm start
