import type { ToneKey } from './grimoire-emeraude';

// Typé d'après le thème de référence : une clé manquante ou en trop est une erreur de compilation.
export const atelierCuivre: Record<ToneKey, string> = {
  /* — navigation — */
  'nav.my_games': 'Mes expéditions',
  'nav.create_game': 'Initier une mission',
  'nav.logout': 'Couper la vapeur',
  'nav.calendar': 'Calendrier',
  'nav.account': 'Mon établi',
  'nav.characters': 'Automates',
  /* — dashboard — */
  'dashboard.title_invitations': 'Transmissions reçues',
  'dashboard.empty': 'Aucune manufacture active. Lancez la première…',
  'dashboard.role_prefix': 'Poste :',
  'dashboard.role_mj': 'Ingénieur',
  'dashboard.role_player': 'Mécanicien',
  'dashboard.status_closed_badge': 'Démantelée',
  /* — signalétique d'état (Story 29.7) — */
  'dashboard.section_awaiting': 'À traiter',
  'dashboard.section_ongoing': 'En service',
  'dashboard.section_upcoming': 'À venir',
  'dashboard.section_finished': 'Démantelées',
  /* — filtres, tri, favoris (Story 29.8) — */
  'dashboard.empty_filtered': 'Aucune manufacture ne répond à ces critères.',
  'dashboard.controls_toggle_aria': 'Afficher les filtres et le tri',
  'dashboard.filter_role_label': 'Poste',
  'dashboard.filter_role_all': 'Tous',
  'dashboard.filter_status_label': 'Statut',
  'dashboard.filter_status_all': 'Tous',
  'dashboard.sort_label': 'Trier par',
  'dashboard.sort_urgence': 'Urgence',
  'dashboard.sort_date': 'Date',
  'dashboard.sort_nom': 'Nom',
  'dashboard.sort_type': 'Type',
  'dashboard.sort_statut': 'Statut',
  'dashboard.hide_finished_label': 'Masquer les manufactures démantelées',
  'dashboard.show_finished_btn': 'Afficher les manufactures démantelées',
  'dashboard.favorite_add_aria': 'Marquer comme favori',
  'dashboard.favorite_remove_aria': 'Retirer des favoris',
  /* — barre de contrôles partagée (Story 29.9) — */
  'dashboard.search_label': 'Rechercher une manufacture',
  'dashboard.row_signal_count_aria': '{n} intervention(s) à mener',
  'list_control_bar.toggle_aria': 'Afficher les filtres et le tri',
  'list_control_bar.view_mode_group_aria': 'Densité d’affichage',
  'list_control_bar.view_mode_large_aria': 'Grande vignette',
  'list_control_bar.view_mode_medium_aria': 'Vignette intermédiaire',
  'list_control_bar.view_mode_compact_aria': 'Liste compacte',
  'list_control_bar.sort_label': 'Trier par',
  'list_control_bar.reset_pill_label': 'Réglages modifiés',
  /* — my-characters (Story 29.2) — */
  'my_characters.title': 'Mes automates',
  'my_characters.empty': 'Aucun automate assemblé. Construisez-en un depuis une mission…',
  'my_characters.no_match': 'Aucun automate ne répond à cette recherche.',
  'my_characters.search_label': 'Rechercher un automate',
  'my_characters.sort_niveau': 'Niveau',
  'my_characters.sort_partie': 'Mission',
  'my_characters.sort_nom': 'Nom',
  /* — section de création (Story 29.16) — */
  'my_characters.create_title': 'À assembler',
  'my_characters.create_entry': 'Assembler un automate-voyageur pour {partie}',
  'my_characters.create_more': 'Voir les {n} autres',
  'my_characters.create_more_one': 'Voir l’autre',
  'my_characters.create_less': 'Voir moins',
  'my_characters.empty_with_entries': 'Aucun automate assemblé pour l’instant.',
  /* — ligne de création de l'Homme Dragon (Story 33.5) — */
  'my_characters.create_entry_hd': 'Créer un Homme Dragon pour {partie}',
  /* — partie-form — */
  'partie.new_title': 'Nouvelle mission',
  'partie.edit_title': 'Recalibrer la mission',
  'partie.save_btn': 'Valider',
  'partie.cancel_btn': 'Annuler',
  'partie.name_label': 'Nom de la mission',
  'partie.system_label': 'Système de jeu',
  'partie.kind_label': 'Régime de la mission',
  'partie.description_label': 'Note de service (facultatif)',
  'partie.kind_ONE_SHOT': 'Mission unique',
  'partie.kind_CAMPAGNE_LINEAIRE': 'Programme',
  'partie.kind_CAMPAGNE_EPISODIQUE': 'Programme à cycles',
  'partie.kind_refusal_closed': 'Cette mission est close. Rouvrez-la avant d’en changer le régime.',
  'partie.kind_refusal_too_many_scenarios':
    'Cette mission compte {count} opérations ; une mission unique n’en a qu’une.',
  'partie.courant_choice_title': 'Quelle opération reste en cours ?',
  'partie.courant_choice_help':
    'Un programme n’exécute qu’une opération à la fois. Les autres repasseront « à venir » — leurs séances et leurs dates sont conservées.',
  'partie.courant_choice_confirm': 'Verrouiller ce réglage',
  'partie.cover_add': 'Ajouter une plaque d’identification',
  'partie.cover_change': 'Changer la plaque',
  'partie.cover_remove': 'Retirer la plaque',
  'partie.cover_uploading': 'Gravure de la plaque en cours…',
  'partie.cover_upload_error': 'La plaque n’a pu être gravée. Réessayez.',
  'partie.cover_remove_error': 'La plaque n’a pu être retirée. Réessayez.',
  'partie.cover_reject_type': 'Seuls les formats JPEG, PNG et WEBP sont admis.',
  'partie.cover_reject_size': 'Ce fichier dépasse 5 Mo : réduisez-le avant dépôt.',
  'partie.save_error': 'Cette mission n’a pu être enregistrée. Réessayez.',
  'partie.created_but_cover_failed':
    'La mission est bien enregistrée, mais sa plaque n’a pu être gravée. Vous pouvez la redéposer ici.',
  'partie.fields_saved_but_convert_failed':
    'Les autres modifications sont enregistrées, mais le régime de la mission n’a pu être changé. Réessayez.',
  /* — partie-detail — */
  'partie.scheduling_title': 'Prochaine mission',
  'partie.no_session': "Aucune mission planifiée. Interrogez l'automate.",
  'partie.members_title': '⚙ Équipage',
  'partie.no_members': 'Aucun mécanicien à bord.',
  'partie.remove_member_btn': 'Débarquer',
  'partie.no_description': 'Dossier technique vierge.',
  'partie.invite_title': 'Recruter un mécanicien',
  'partie.search_label': 'Matricule ou appellation',
  'partie.search_btn': 'Scanner',
  'partie.invite_btn': 'Enrôler',
  'partie.links_title': "Télégrammes d'invitation",
  'partie.generate_link': "Forger un badge d'accès",
  'partie.notice_invited': 'Télégramme envoyé à {name}.',
  'partie.invite_by_email_label': 'Adresse du destinataire',
  'partie.invite_by_email_btn': 'Expédier un télégramme',
  'partie.notice_invited_email': 'Télégramme expédié à {email}.',
  'partie.notice_invite_email_error': "Le télégramme n'a pas pu être expédié. Réessayez.",
  'partie.reference_sheets_title': 'Manuels de référence',
  'partie.asset_journal_cta': 'Journal',
  'partie.asset_carte_cta': 'Carte',
  'partie.asset_download_error': "Échec de l'impression du manuel. Réessayez.",
  'partie.prep_sheets_title': 'Manuels de préparation (MJ)',
  'partie.asset_monde_cta': 'Monde',
  'partie.asset_monstre_cta': 'Monstre',
  'partie.asset_ville_cta': 'Ville',
  'partie.asset_objectif_chasse_cta': 'Objectif — Chasse',
  'partie.asset_objectif_quete_cta': 'Objectif — Quête',
  'partie.asset_objectif_voyage_cta': 'Objectif — Voyage',
  'partie.asset_oeuf_de_bataille_cta': 'Œuf de bataille',
  'partie.asset_structure_cta': 'Structure',
  /* — zones de l'onglet Détails (Story 32.2) — noms CONTRACTUELS, identiques dans les trois
     thèmes (même principe que cta.destiny_mode, Story 36.9). */
  'partie.details_zone_action': 'Action',
  'partie.details_zone_consultation': 'Consultation',
  'partie.details_zone_reference': 'Référence',
  /* — états de scénario et de séance (Story 32.3) — libellés CONTRACTUELS, identiques dans les
     trois thèmes : cf. le commentaire complet dans `grimoire-emeraude`. */
  'status.scenario_brouillon': 'Brouillon',
  'status.scenario_a_venir': 'À venir',
  'status.scenario_courant': 'Courant',
  'status.scenario_passe': 'Passé',
  'status.seance_a_planifier': 'À planifier',
  'status.seance_answer_poll': 'Réponds au vote',
  'status.seance_poll_open': 'Vote en cours',
  'status.seance_inscriptions_ouvertes': 'Inscriptions ouvertes',
  'status.seance_programmee': 'Programmée',
  'status.seance_a_debriefer': 'À débriefer',
  'status.seance_jouee': 'Jouée',
  'partie.notice_copy': 'Badge copié dans le carnet de bord.',
  'partie.edit_btn': 'Recalibrer',
  'partie.visibility_btn': 'Verrouiller les plans',
  'partie.close_btn': "Mettre à l'arrêt",
  'partie.reopen_btn': 'Remettre en service',
  'partie.status_closed_label': "Cette machine est à l'arrêt.",
  /* — signaux d'état (Story 29.7, FR-12) — */
  'partie.signal_personnage_a_creer': 'Assembler son automate',
  'partie.signal_vote_en_cours_sans_reponse': 'Vote en attente',
  'partie.signal_compte_rendu_non_redige': 'Rapport à rédiger',
  'partie.signal_homme_dragon_a_creer': 'Assembler son Homme Dragon',
  'partie.signal_aucun_membre_invite': 'Aucun mécanicien recruté',
  'partie.signal_aucun_scenario_en_cours': 'Aucune mission en cours',
  'partie.signal_aucune_date_ni_vote': 'Aucune date ni vote',
  'partie.signal_rapport_fin_manquant': 'Rapport de fin manquant',
  'partie.signal_prochaine_seance_connue': 'Prochaine séance connue',
  'partie.signal_partie_terminee': 'Machine démantelée',
  'partie.signal_more_count': '+{n}',
  'partie.delete_btn': 'Démanteler',
  'partie.invitations_tab_label': 'Invitations',
  'partie.show_troupe': "Voir l'équipage",
  'partie.hide_troupe': "Masquer l'équipage",
  /* — calendrier & vote — */
  'cta.find_date': "Interroger l'automate des créneaux",
  'cta.guild_calendar': 'Consulter le registre de la mission',
  'cta.launch_vote': 'Actionner le registre de vote',
  'cta.save_constraint': 'Enregistrer dans le registre de vapeur',
  'cta.send_reminder': 'Envoyer un message pneumatique',
  'section.slots': "Créneaux validés par l'automate",
  'section.constraints': 'Registre de contraintes',
  'empty.no_slots': "L'automate ne détecte aucun créneau. Vérifiez les registres des membres.",
  'empty.no_constraints': 'Aucune contrainte dans le registre de vapeur.',
  'success.constraint_saved': 'Contrainte enregistrée dans le registre.',
  'alert.expiring_soon': 'La pression baisse — votre registre expire bientôt.',
  'alert.missing_player': "{name} n'a pas alimenté le registre.",
  'status.unavailable_label': 'Hors-service',
  'status.unknown_label': 'Signal inconnu',
  'cta.choose_date': "Verrouiller l'engrenage de la date",
  'cta.cancel_poll': 'Purger le registre de vote',
  'cta.restore_default_layers': "Réinitialiser l'affichage par défaut",
  'empty.no_poll': 'Aucun registre de vote actif.',
  'success.poll_created': 'Registre de vote activé. Message pneumatique envoyé.',
  'success.date_chosen': "L'engrenage est verrouillé. Séance confirmée.",
  'poll.status_title': 'Registre de vote actif',
  'poll.vote_pending': 'Registre de vote — réponse requise',
  'success.vote_cast': 'Réponse enregistrée dans le registre.',
  'cta.confirm_votes': 'Valider dans le registre',
  'cta.withdraw_vote': 'Retirer ma réponse',
  'success.vote_withdrawn': 'Réponse effacée du registre.',
  'poll.withdraw_error': 'Le retrait a échoué. Réessayez.',
  'poll.cast_error': 'Impossible d’enregistrer ta réponse. Réessayez.',
  'poll.vote_closed': 'Registre de vote verrouillé.',
  'alert.all_responded': "Tout l'équipage a répondu au registre.",
  'poll.status_summary': 'Registre ouvert — {responded}/{total} membres ont répondu',
  /* — mode Destinée et panneau réduit (Story 36.9) — */
  'cta.destiny_mode': 'Destinée',
  'poll.missing_prefix': 'N’ont pas alimenté le registre :',
  'poll.responded_prefix': 'Ont alimenté le registre :',
  /* — annonces (Epic 9) — */
  'announcement.scope_campaign_label': 'Toute la mission',
  'announcement.scope_oneshot_label': 'Cette opération',
  'announcement.scope_scenario_label': 'Ce dossier',
  'announcement.publish_cta': 'Diffuser une transmission',
  'announcement.text_placeholder': 'Rédiger une transmission...',
  'announcement.published_notice': 'Transmission diffusée.',
  'announcement.unseen_label': 'Non lue — cliquez pour accuser réception',
  /* — personnages (Palier P3) — */
  'character.create_cta': 'Assembler un automate-voyageur',
  'character.choice_deselect_hint': 'Toucher pour désélectionner',
  'character.choice_talents_label': 'Talents',
  'character.choice_advantages_label': 'Avantages',
  'character.choice_required_flag': 'Obligatoire',
  'character.choice_reference_toggle': 'Occupations et actions',
  'character.equipment_group_toggle': '{group}, {n} objets',
  'character.equipment_filter_all': 'Tout',
  'character.equipment_filter_mine': 'Ma sélection',
  'character.equipment_qty_less': 'Retirer un exemplaire de {name}',
  'character.equipment_qty_more': 'Ajouter un exemplaire de {name}',
  'character.recap_button': 'Récap',
  'character.recap_title': 'Récapitulatif',
  'character.recap_cart_title': 'Panier',
  'character.recap_remove': 'Retirer',
  'character.recap_total': 'Total',
  'character.recap_empty_hint':
    'Les statistiques dérivées apparaîtront une fois les attributs assignés.',
  'detail.row_attributes': 'Attributs',
  'detail.row_difficulty': 'Difficulté',
  'detail.row_effect': 'Effet',
  'detail.row_conditions': 'Conditions',
  'detail.narrative_show': 'Lire le récit',
  'detail.narrative_hide': 'Masquer le récit',
  'character.equipment_group_individual': 'Objets',
  'character.equipment_group_contenant': 'Contenants',
  'character.equipment_group_animal': 'Animaux',
  'character.equipment_search_label': 'Rechercher un objet',
  'character.equipment_search_placeholder': 'Rechercher un objet…',
  'character.equipment_budget': 'Budget · {spent} / {total} Po',
  'character.equipment_over_budget': '— dépassement de {n} Po',
  'character.equipment_search_empty': 'Aucun mécanisme ne porte ce nom dans l’atelier…',
  'character.tab_label': 'Personnages',
  'character.step_class': 'Choisir sa fonction',
  'character.step_type': 'Choisir son mécanisme',
  'character.step_magic': 'Calibrer le module magique',
  'character.step_portrait_intro':
    'Grave un portrait sur la plaque si tu le souhaites — étape optionnelle, ignorable sans conséquence.',
  'character.portrait_missing': 'Aucun portrait gravé sur la plaque',
  'character.portrait_edit_cta': 'Recalibrer le portrait',
  'character.pdf_crop_edit_cta': 'Recalibrer le cadrage PDF',
  'character.sheet_menu_trigger_aria': 'Actions de la fiche',
  'character.export_editable_cta': 'Exporter en PDF (éditable)',
  'character.export_2pages_cta': 'Exporter en PDF (2 pages)',
  'character.export_equipment_cta': "Exporter l'équipement en PDF",
  'character.export_notes_cta': 'Exporter les notes en PDF',
  'character.export_error': "Échec de l'impression pneumatique. Réessayez.",
  'character.owner_badge_mj': 'Ingénieur',
  /* « Homme Dragon » est un nom propre du système : jamais thématisé (Story 33.5). */
  'character.nature_dragon': 'Homme Dragon',
  'character.level_badge': 'Niv. {n}',
  'character.party_sheets_tab_label': 'Fiches',
  /* — bouton retour vers la partie depuis la fiche d'un personnage — */
  'character.back_to_partie_cta': 'Retour à la partie',
  /* — état vide "Fiches" (Story 29.15) — */
  'character.no_character_yet': 'Aucun automate-voyageur assemblé sur cette partie pour l’instant.',
  /* — Homme Dragon (Epic 10, Story 10.1) — */
  'homme-dragon.create_cta': 'Assembler mon Homme Dragon',
  'homme-dragon.race_label': 'Modèle',
  'homme-dragon.artefact_label': 'Composant emblématique',
  'homme-dragon.created_notice': 'Votre Homme Dragon est opérationnel.',
  /* — roster (Story 6.1) — */
  'roster.mj_badge': 'MJ',
  'roster.invite_slot': 'Recruter un mécanicien',
  'roster.collapse_label': "Replier l'équipage",
  'roster.expand_label': "Déplier l'équipage",
  'roster.levelup_badge': 'Calibrage niveau disponible',
  /* — slot d'initiale « créer mon personnage » (Story 29.15) — */
  'roster.create_slot_label': 'assembler mon automate-voyageur',
  /* — évolution du personnage (Story 6.2) — */
  'evolution.xp_distribute_cta': "Distribuer les crédits d'expérience",
  'evolution.xp_panel_title': "Distribution de crédits d'expérience",
  'evolution.xp_history_title': "Registre des crédits d'expérience",
  'evolution.xp_history_empty': 'Aucune distribution enregistrée dans le registre.',
  'evolution.xp_note_label': 'Note technique',
  'evolution.xp_confirm_btn': 'Valider la distribution',
  'evolution.xp_bonus_link': '+ bonus',
  'evolution.xp_levelup_warning': '{name} va être recalibré au niveau supérieur',
  /* — montée de niveau & historique (Story 6.3) — */
  'evolution.levelup_banner': 'Calibrage niveau [N] disponible',
  'evolution.levelup_cta': 'Recalibrer',
  'evolution.levelup_wizard_title': 'Recalibrage',
  'evolution.levelup_step_pv_pe': 'Répartir 3 points entre PV et PE',
  'evolution.levelup_step_capability': 'Choisir le module débloqué',
  'evolution.levelup_legendary_journey_text':
    'Une trajectoire légendaire est engagée — aucun réglage supplémentaire requis.',
  'evolution.levelup_confirm_cta': 'Valider le calibrage',
  /* — sous-navigation locale de la fiche (Story 29.5) — */
  'evolution.main_sheet_tab_label': 'Fiche technique',
  'evolution.history_tab_label': 'Journal de bord',
  'evolution.history_empty': 'Aucune entrée consignée pour le moment.',
  'evolution.mj_edit_trace': 'recalibré par le MJ',
  'evolution.landscape_section_title': 'Module paysage/climat',
  'evolution.immunity_section_title': 'Modules d’immunité',
  'evolution.other_capabilities_title': 'Modules installés',
  'evolution.derived_hidden': 'Statistiques verrouillées par le MJ',
  'evolution.hidden_marker': 'Verrouillé par le MJ',
  'evolution.inventory_section_title': 'Compartiment de fret',
  'evolution.inventory_add_cta': '+ Charger un composant',
  'evolution.inventory_empty': 'Aucun composant chargé pour le moment.',
  'evolution.inventory_overweight_label': 'Surcharge',
  'evolution.inventory_error': 'Le fret n’a pas pu être mis à jour. Réessayez.',
  'evolution.mj_edit_error': 'La modification n’a pas pu être enregistrée. Réessayez.',
  'evolution.mj_edit_warning_prefix': 'Avertissement : ',
  'evolution.inventory_mj_add_cta': '+ Charger un composant (MJ)',
  'evolution.narrative_edit_error': 'La modification n’a pas pu être enregistrée. Réessayez.',
  'evolution.notes_journal_title': 'Journal de bord personnel',
  'evolution.notes_journal_empty': 'Aucune entrée consignée pour le moment.',
  'evolution.notes_add_cta': '+ Consigner une entrée',
  'evolution.note_share_toggle': 'Diffuser à l’équipage',
  'evolution.note_private_label': 'Entrée confidentielle',
  'evolution.note_shared_label': 'Entrée diffusée à l’équipage',
  'evolution.notes_error': 'Le journal n’a pas pu être mis à jour. Réessayez.',
  /* — compte — */
  'account.title': 'Mon établi',
  'account.pseudo_label': 'Matricule',
  'account.email_label': 'Fréquence de contact',
  'account.display_name_label': 'Nom affiché aux autres membres',
  'account.save_btn': 'Riveter',
  'account.cancel_btn': 'Annuler',
  'account.saved': 'L’établi a retenu ce nom.',
  'account.error': 'L’établi n’a pas pu retenir ce changement. Réessayez.',
  'account.password_title': 'Recalibrer le code d’accès',
  'account.current_password_label': 'Code d’accès actuel',
  'account.new_password_label': 'Nouveau code d’accès',
  'account.password_save_btn': 'Recalibrer',
  'account.password_saved': 'Le code d’accès a été recalibré.',
  'account.password_wrong_current': 'Code d’accès actuel erroné.',
  'account.password_error': 'L’établi n’a pas pu recalibrer le code. Réessayez.',
  'account.email_change_title': 'Recalibrer la fréquence de contact',
  'account.current_password_for_email_label': 'Code d’accès actuel',
  'account.new_email_label': 'Nouvelle fréquence de contact',
  'account.email_change_save_btn': 'Transmettre',
  'account.email_change_saved': 'Un signal est parti vers la nouvelle fréquence.',
  'account.email_change_wrong_current': 'Code d’accès actuel erroné.',
  'account.email_change_taken': 'Cette fréquence est déjà occupée par un autre poste.',
  'account.email_change_error': 'L’établi n’a pas pu transmettre la demande. Réessayez.',
  // Story 34.1 — échecs de connexion : chaque texte nomme sa cause par un mot clair.
  'auth.login_invalid': 'L’établi ne vous reconnaît pas : identifiants invalides.',
  'auth.login_reset_required':
    'Ce poste doit être réinitialisé : utilisez « Mot de passe oublié ? » pour le remettre en marche.',
  'auth.login_throttled':
    'Trop de tentatives. Patientez une minute avant de relancer la connexion.',
  'auth.login_unavailable':
    'L’établi est indisponible pour le moment. Réessayez dans quelques instants.',
  'auth.login_unexpected': 'Une erreur est survenue. Réessayez.',
  // Story 34.2 — libellés du bouton de révélation du mot de passe : neutres, non thématisés.
  'auth.password_show': 'Afficher le mot de passe',
  'auth.password_hide': 'Masquer le mot de passe',
  // Story 34.3 — ligne d'orientation de la connexion et messages de validation des formulaires
  // d'authentification : libellé neutre de référence, identique dans les trois thèmes (chacun nomme
  // la règle) ; l'habillage thématique relève de la revue éditoriale de l'épic 35.
  'auth.login_invite_only': "L'inscription se fait sur invitation.",
  'auth.field_required': 'Renseignez ce champ.',
  'auth.field_email_invalid': 'Adresse e-mail invalide.',
  'auth.field_pseudo_min': '3 caractères minimum.',
  'auth.field_password_min': '8 caractères minimum.',
  // Story 34.4 — accroche de la bande d'authentification : une par thème (EXPERIENCE.md §3).
  'auth.tagline': 'On cale tout le monde, et on lance la machine\u00a0!',
  'account.calendar_layers_title': 'Ce qu’affiche mon calendrier',
  'account.calendar_layer.mes-indisponibilites': 'Mes indisponibilités',
  'account.calendar_layer.mes-disponibilites': 'Mes disponibilités',
  'account.calendar_layer.mes-seances': 'Mes séances confirmées',
  'account.calendar_layer.votes-en-cours': 'Les votes en cours',
  'account.calendar_layer.inscriptions-ouvertes': 'Les inscriptions ouvertes',
  'account.calendar_layer.disponibilite-groupe': 'La disponibilité du groupe',
  /* — vue Agenda (Story 36.11) — badges contractuels (EXPERIENCE.md §5), titres thématisés. */
  'calendar.agenda.section_awaiting': 'À traiter',
  'calendar.agenda.section_scheduled': 'Au programme',
  'calendar.agenda.section_past': 'Aux archives',
  'calendar.agenda.badge_answer_poll': 'Réponds au vote',
  'calendar.agenda.badge_poll_open': 'Vote en cours',
  'calendar.agenda.badge_signup': 'S’inscrire',
  'calendar.agenda.badge_signed_up': 'Inscrit',
  'calendar.agenda.badge_debrief': 'Débriefer',
  'calendar.agenda.empty': 'Aucune tâche, aucune échéance.',
  /* — Agenda du MJ (Story 36.12) — libellés d'état contractuels, appels à l'action thématisés. */
  'calendar.agenda.badge_to_seal': 'À sceller',
  'calendar.agenda.poll_open': 'Scrutin ouvert',
  'calendar.agenda.responded_count': '{n} sur {total} ont répondu',
  'calendar.agenda.slots_proposed': '{n} créneaux proposés',
  'calendar.agenda.missing_voters': 'il manque {names}',
  'calendar.agenda.no_date': 'sans date',
  'calendar.agenda.no_date_proposed': 'Aucune date proposée',
  'calendar.agenda.action_launch_poll': 'Ouvrir un scrutin',
  'calendar.agenda.action_seal': 'Verrouiller',
  'calendar.agenda.action_expand': 'Déployer',
  'calendar.agenda.action_collapse': 'Rétracter',
  'calendar.agenda.seal_confirm_title': 'Verrouiller l’engrenage sur ce créneau ?',
  'calendar.agenda.seal_confirm_body':
    'La séance sera fixée à ce créneau et le scrutin se refermera. Les autres créneaux proposés disparaîtront.',
  /* — Story 36.14 : la barre repliée, le panneau « Affichage » et la légende —
     🚨 Ces libellés sont IDENTIQUES dans les trois thèmes, comme les six
     `account.calendar_layer.*` : le contrat d'UI les fixe verbatim
     (`contrat-ui-calendrier.html:599-609`, `:655-665`, `:683-686`). La clé existe pour qu'un
     thème futur puisse les teinter — même motif que `cta.destiny_mode` (story 36.9). */
  'calendar.display.trigger': 'Affichage',
  'calendar.display.trigger_aria': "Régler l'affichage du calendrier",
  'calendar.display.section_visible': 'Ce que je vois',
  'calendar.display.show_legend': 'Afficher la légende',
  'calendar.display.filtered_badge': 'Affichage filtré · {n} sur {total} · Rétablir',
  'calendar.legend.title': 'Légende',
  'calendar.legend.group_obvious': 'Se passent d’explication',
  'calendar.legend.group_needs': 'Demandent la légende',
  'calendar.legend.entry.available': 'Je suis disponible',
  'calendar.legend.entry.unavailable': 'Je suis indisponible',
  'calendar.legend.entry.seance': 'Séance confirmée — tu es pris',
  'calendar.legend.entry.vote': 'Créneau proposé au vote',
  'calendar.legend.entry.poll_track': 'Participation : la piste = la troupe',
  'calendar.legend.entry.group': 'Disponibilité du groupe',
  'calendar.legend.entry.none': 'Personne ne s’est prononcé',
  'account.calendar_intents_subtitle': 'Ce que je veux voir en arrivant sur un calendrier.',
  'account.calendar_intent.disponibilites': 'Mes disponibilités & indisponibilités',
  'account.calendar_intent.seances': 'Mes séances confirmées',
  'account.calendar_intent.votes': 'Les votes en cours',
  'account.calendar_intent.groupe': 'La disponibilité du groupe',
  /* — identité — */
  'identity.character_label': 'Personnage',
  'identity.player_label': 'Joueur',
  'identity.homonymy_warning':
    'Un autre membre de cette compagnie porte le même nom affiché que vous.',
  'identity.homonymy_change_cta': 'Changer mon nom affiché',
  'identity.homonymy_ignore_cta': 'Ignorer',
};
