import type { ToneKey } from './grimoire-emeraude';

// Typé d'après le thème de référence : une clé manquante ou en trop est une erreur de compilation.
// Mêmes sections, même ordre que `grimoire-emeraude.ts`.
//
// VOIX — Atelier Cuivré : engrenages, vapeur, automates, registres. VOUVOIEMENT partout (jamais « tu »).
// Vocabulaire : mission (la partie), opération (le scénario), équipage (le groupe), Ingénieur (le MJ),
// mécanicien (le joueur), automate (le personnage), registre, scrutin, pneumatique, plaque, badge,
// composant, module, calibrage, verrouiller, consigner.
export const atelierCuivre: Record<ToneKey, string> = {
  /* ═══ Navigation et coque ═══ */
  /* — menu principal — */
  'nav.my_games': 'Mes expéditions',
  'nav.create_game': 'Initier une mission',
  'nav.logout': 'Couper la vapeur',
  'nav.calendar': 'Registre horaire',
  'nav.account': 'Mon établi',
  'nav.characters': 'Automates',
  /* — coque de l’application — */
  'shell.nav_main_aria': 'Navigation principale de l’atelier',
  'shell.banner_close_aria': 'Fermer le pneumatique de {partie}',
  'shell.badge_polls_aria': '{n} scrutin(s) en attente de réponse',
  'shell.badge_announcements_aria': '{n} transmission(s) non lue(s)',
  /* — titres de route — */
  'route.title_confirm_email_change': 'Confirmer la nouvelle fréquence',
  'route.title_rollback_email_change': 'Annuler le changement de fréquence',
  /* — surfaces partagées — */
  'shared.detail_close_window': 'Fermer la fenêtre de l’atelier',
  'shared.detail_close_sheet': 'Fermer le panneau de l’atelier',
  /* — barre de contrôles des listes — */
  'list_control_bar.toggle_aria': 'Afficher les filtres et le tri du registre',
  'list_control_bar.view_mode_group_aria': 'Densité de l’affichage',
  'list_control_bar.view_mode_large_aria': 'Grand cadran',
  'list_control_bar.view_mode_medium_aria': 'Cadran intermédiaire',
  'list_control_bar.view_mode_compact_aria': 'Liste compacte du registre',
  'list_control_bar.sort_label': 'Classer par',
  'list_control_bar.reset_pill_label': 'Réglages modifiés',

  /* ═══ Textes communs ═══ */
  /* — actions et mots courants — */
  'common.8_caracteres': '8 caractères minimum',
  'common.a_savoir': 'Avis technique',
  'common.accepter': 'Accepter l’affectation',
  'common.ajouter': 'Charger',
  'common.ajouter_une_aventure': 'Ajouter une mission',
  'common.annonces': 'Transmissions',
  'common.annuler': 'Annuler',
  'common.associer': 'Raccorder',
  'common.au': 'Au',
  'common.aucun_scenario_pour_l_instant': 'Aucune opération pour l’instant.',
  'common.aucune_description_disponible': 'Aucune description au dossier.',
  'common.ce_jour_uniquement': 'Ce jour uniquement',
  'common.changer': 'Substituer',
  'common.chargement': 'Mise en pression…',
  'common.chargement_2': 'Mise en pression...',
  'common.chargement_en_cours': 'Les rouages s’engagent',
  'common.choisir': '-- Choisir une fonction --',
  'common.cloturer_le_vote': 'Clôturer le scrutin',
  'common.confirmer': 'Verrouiller',
  'common.connexion': 'Entrer dans l’atelier',
  // Remplacer / Conserver / Au cas par cas : vocabulaire de la boîte de conflit (contrat d’UI, story 36.4).
  'common.conserver': 'Conserver',
  'common.copier': 'Copier le badge',
  'common.creer': 'Assembler',
  'common.creer_un_compte': 'Ouvrir un poste',
  'common.creneau': 'Plage',
  'common.creneaux_varies': 'plages variées',
  'common.date_a_definir': 'Date à régler',
  'common.date_a_definir_2': 'Date à régler.',
  'common.date_retenue_date': 'Date verrouillée : {date}',
  'common.designe_pour_le_vote': 'désigné pour le scrutin',
  'common.detail': 'Notice technique',
  'common.detail_du_jour': 'Relevé du jour',
  // Mots fonctionnels identiques : états de disponibilité, réponses de vote, libellés de champ courts.
  'common.disponible': 'Disponible',
  'common.dissocier': 'Désaccoupler',
  'common.du': 'Du',
  'common.effet_facultatif': 'Effet (optionnel)',
  'common.email': 'Fréquence (e-mail)',
  'common.en_savoir_plus': 'Voir la notice',
  'common.enregistrement': 'Consignation…',
  'common.enregistrer': 'Consigner',
  'common.envoi': 'Expédition…',
  'common.fermer': 'Clore',
  'common.heure': 'Heure',
  'common.homme_dragon_introuvable': 'Homme Dragon introuvable au registre.',
  'common.impossible_d_enregistrer_ce_choix_reessayez': 'Ce choix n’a pu être consigné. Réessayez.',
  'common.impossible_d_enregistrer_ces_disponibilites_reessayez':
    'Ces disponibilités n’ont pu être consignées. Réessayez.',
  'common.impossible_d_enregistrer_la_contrainte': 'La contrainte n’a pu être consignée.',
  'common.impossible_d_enregistrer_la_modification': 'La modification n’a pu être consignée.',
  'common.impossible_de_charger_la_partie_reessayez': 'Cette mission ne se charge pas. Réessayez.',
  'common.impossible_de_charger_le_scenario_reessayez':
    'Cette opération ne se charge pas. Réessayez.',
  'common.impossible_de_charger_les_scenarios_reessayez':
    'Les opérations ne se chargent pas. Réessayez.',
  'common.impossible_de_cloturer_le_vote_reessayez': 'Le scrutin n’a pu être clôturé. Réessayez.',
  'common.indisponible': 'Indisponible',
  'common.j_ai_deja_un_compte': 'J’ai déjà un poste à l’atelier',
  'common.lancer_le_vote': 'Ouvrir le scrutin',
  'common.lien_invalide': 'Lien invalide : le raccord est rompu.',
  'common.lien_invalide_ou_expire_merci_de_refaire_une_demande':
    'Lien invalide ou expiré. Veuillez relancer une demande.',
  'common.lieu': 'Lieu',
  'common.lire_la_suite': 'Lire la suite',
  'common.modifier': 'Ajuster',
  'common.mot_de_passe': 'Code d’accès',
  'common.mot_de_passe_oublie': 'Code d’accès égaré',
  'common.n_max_inscrits': '{n}/{max} inscrits à bord',
  'common.nom_de_l_animal': 'Désignation de l’animal',
  'common.nom_de_l_objet': 'Désignation de l’objet',
  'common.nom_du_contenant': 'Désignation du contenant',
  'common.non': 'Non',
  'common.nouveau_mot_de_passe': 'Nouveau code d’accès',
  'common.oui': 'Oui',
  'common.ouvrir_aux_joueurs': 'Ouvrir à l’équipage',
  'common.ouvrir_le_scenario_label': 'Ouvrir l’opération {label}',
  'common.ouvrir_le_scenario_label_info': 'Ouvrir l’opération {label} — {info}',
  'common.participants': 'Équipage présent',
  'common.partie_introuvable': 'Cette mission est introuvable.',
  'common.pas_encore_de_personnage': '(aucun automate assemblé)',
  'common.passer_cette_etape': 'Sauter cette phase',
  'common.peut_etre': 'Peut-être',
  'common.poids': 'Poids',
  'common.precedent': 'Phase précédente',
  'common.precedent_2': '❮ Phase précédente',
  'common.prix_facultatif': 'Prix (optionnel)',
  'common.rechercher': 'Scanner',
  'common.reduire': 'Réduire',
  'common.reessayer': 'Relancer',
  'common.refuser': 'Rejeter',
  'common.reinitialiser_la_date': 'Purger la date',
  'common.rejoindre': 'Rejoindre l’équipage',
  'common.remplacer': 'Remplacer',
  'common.renoncer': 'Abandonner',
  'common.repondre_au_vote_label': 'Répondre au scrutin — {label}',
  'common.repondre_au_vote_label_detail': 'Répondre au scrutin — {label} — {detail}',
  'common.resume_de_fin': 'Rapport de fin',
  'common.retirer': 'Démonter',
  'common.retour_a_la_connexion': 'Retour à l’entrée de l’atelier',
  'common.retour_a_la_partie': 'Retour à la mission',
  'common.revoquer': 'Désactiver',
  'common.scenario_introuvable_revenez_a_la_liste_des_brouillons':
    'Opération introuvable — revenez à la liste des Brouillons.',
  'common.seance_n': 'Séance {n}',
  'common.suivant': 'Phase suivante',
  'common.suivant_2': 'Phase suivante ❯',
  'common.supprimer': 'Purger',
  'common.title_seance_index': '{title} — Séance {index}',
  'common.titre': 'Titre',
  'common.type': 'Régime',
  'common.une_erreur_inattendue_est_survenue_reessayez':
    'Une défaillance inattendue est survenue. Réessayez.',
  'common.valider': 'Approuver',
  'common.vote_cloture_sans_date_retenue': 'Scrutin clôturé sans date retenue.',
  'common.vote_de_date': '· scrutin de date',
  'common.vue_agenda': 'Vue agenda',
  'common.vue_mois': 'Vue mois',
  'common.vue_semaine': 'Vue semaine',

  /* ═══ Authentification et invitation ═══ */
  /* — accroche de la bande — */
  'auth.tagline': 'On cale tout le monde, et on lance la machine !',
  /* — connexion — */
  'auth.login_invalid': 'L’établi ne vous reconnaît pas : identifiants invalides.',
  'auth.login_reset_required':
    'Ce poste doit être réinitialisé : utilisez « Code d’accès égaré ? » pour le remettre en marche.',
  'auth.login_throttled':
    'Trop de tentatives. Patientez une minute avant de relancer la connexion.',
  'auth.login_unavailable':
    'L’établi est indisponible pour le moment. Réessayez dans quelques instants.',
  'auth.login_unexpected': 'Une erreur est survenue. Relancez l’opération.',
  'auth.login_invite_only': 'L’accès à l’atelier se fait sur invitation.',
  'auth.login_identifier_label': 'Fréquence (e-mail) ou matricule',
  'auth.login_submit': 'Se connecter à l’atelier',
  'auth.login_forgot_link': 'Code d’accès égaré ?',
  /* — validation des champs — */
  'auth.field_required': 'Renseignez ce champ.',
  'auth.field_email_invalid': 'Adresse e-mail invalide.',
  'auth.field_pseudo_min': '3 caractères minimum.',
  'auth.field_password_min': '8 caractères minimum.',
  /* — révélation du mot de passe — */
  'auth.password_show': 'Afficher le mot de passe',
  'auth.password_hide': 'Masquer le mot de passe',
  /* — inscription — */
  'auth.register_invite_only':
    'L’inscription se fait uniquement sur invitation. Ouvrez un lien d’invitation pour ouvrir votre poste à l’atelier.',
  'auth.register_pseudo_label': 'Matricule',
  'auth.register_submit': 'Ouvrir mon poste',
  'auth.register_error':
    'Le compte n’a pu être créé (lien invalide, ou e-mail ou matricule déjà pris ?).',
  /* — mot de passe oublié et réinitialisation — */
  'auth.forgot_sent':
    'Si un compte existe pour cette adresse, un pneumatique de réinitialisation a été expédié.',
  'auth.forgot_submit': 'Expédier le pneumatique',
  'auth.forgot_error': 'La demande n’a pu être expédiée pour le moment. Réessayez plus tard.',
  'auth.reset_submit': 'Réinitialiser le code',
  'auth.reset_redo_link': 'Refaire une demande de code',
  /* — changement d’adresse e-mail — */
  'auth.confirm_email_title': 'Confirmer la nouvelle fréquence',
  'auth.confirm_email_done': 'Votre fréquence de contact a été changée.',
  'auth.rollback_email_title': 'Annuler le changement de fréquence',
  'auth.rollback_done':
    'Votre ancienne adresse a été restaurée : toutes les sessions actives ont été coupées.',
  'auth.rollback_continue_btn': 'Continuer vers la réinitialisation du code d’accès',
  'auth.rollback_warning':
    'Restaurer votre ancienne adresse coupera toutes les sessions actives et exigera une réinitialisation de votre code d’accès avant toute reconnexion.',
  'auth.rollback_submit': 'Restaurer mon ancienne adresse',
  'auth.rollback_error': 'Lien invalide ou expiré : le raccord a lâché.',
  /* — lien d’invitation — */
  'join.not_found_title': 'Badge introuvable',
  'join.not_found_text': 'Ce badge d’invitation n’existe pas.',
  'join.title': 'Rejoindre la mission « {name} »',
  'join.logged_as': 'Vous êtes connecté en tant que',
  'join.login_or_register': 'Connectez-vous ou créez un compte pour rejoindre cette mission.',
  'join.join_error':
    'Impossible de rejoindre cette mission (lien invalide, expiré, ou déjà à bord).',

  /* ═══ Compte ═══ */
  /* — profil, mot de passe et e-mail — */
  'account.title': 'Mon établi',
  'account.pseudo_label': 'Matricule',
  'account.email_label': 'Fréquence de contact',
  'account.display_name_label': 'Nom affiché aux autres mécaniciens',
  'account.cancel_btn': 'Annuler',
  'account.saved': 'L’établi a retenu ce nom.',
  'account.error': 'L’établi n’a pas pu retenir ce changement. Réessayez.',
  'account.password_title': 'Recalibrer le code d’accès',
  'account.current_password_label': 'Code d’accès actuel',
  'account.new_password_label': 'Nouveau code d’accès',
  'account.password_save_btn': 'Recalibrer',
  'account.password_saved': 'Le code d’accès a été recalibré.',
  'account.password_wrong_current': 'Code d’accès actuel erroné.',
  'account.password_error': 'L’établi n’a pas pu recalibrer le code. Réessayez.',
  'account.current_password_for_email_label': 'Code d’accès actuel',
  'account.new_email_label': 'Nouvelle fréquence de contact',
  'account.email_change_save_btn': 'Transmettre',
  'account.email_change_saved': 'Un signal est parti vers la nouvelle fréquence.',
  'account.email_change_wrong_current': 'Code d’accès actuel erroné.',
  'account.email_change_taken': 'Cette fréquence est déjà occupée par un autre poste.',
  'account.email_change_error': 'L’établi n’a pas pu transmettre la demande. Réessayez.',
  'account.appearance_label': 'Apparence de l’atelier',
  /* — calendrier du compte — */
  'account.calendar_layers_title': 'Ce qu’affiche mon calendrier',
  // Couches et intentions du calendrier : verbatim du contrat d’UI (story 36.14), volontairement identiques.
  'account.calendar_layer.mes-indisponibilites': 'Mes indisponibilités',
  'account.calendar_layer.mes-disponibilites': 'Mes disponibilités',
  'account.calendar_layer.mes-seances': 'Mes séances confirmées',
  'account.calendar_layer.votes-en-cours': 'Les votes en cours',
  'account.calendar_layer.inscriptions-ouvertes': 'Les inscriptions ouvertes',
  'account.calendar_layer.disponibilite-groupe': 'La disponibilité du groupe',
  'account.calendar_intents_subtitle': 'Ce que je veux voir en ouvrant le registre.',
  'account.calendar_intent.disponibilites': 'Mes disponibilités & indisponibilités',
  'account.calendar_intent.seances': 'Mes séances confirmées',
  'account.calendar_intent.votes': 'Les votes en cours',
  'account.calendar_intent.groupe': 'La disponibilité du groupe',
  /* — identité et homonymie — */
  'identity.character_label': 'Automate',
  'identity.player_label': 'Mécanicien',
  'identity.homonymy_warning':
    'Un autre mécanicien de cette mission porte le même nom affiché que vous.',
  'identity.homonymy_change_cta': 'Modifier mon nom affiché',
  'identity.homonymy_ignore_cta': 'Ignorer',

  /* ═══ Tableau de bord ═══ */
  /* — tableau de bord — */
  'dashboard.title_invitations': 'Transmissions reçues',
  'dashboard.empty': 'Aucune manufacture active. Lancez la première…',
  'dashboard.role_prefix': 'Poste :',
  'dashboard.role_mj': 'Ingénieur',
  'dashboard.role_player': 'Mécanicien',
  'dashboard.status_closed_badge': 'Démantelée',
  'dashboard.section_awaiting': 'À traiter',
  'dashboard.section_ongoing': 'En service',
  'dashboard.section_upcoming': 'En préparation',
  'dashboard.section_finished': 'Démantelées',
  'dashboard.empty_filtered': 'Aucune manufacture ne répond à ces critères.',
  'dashboard.filter_role_label': 'Poste',
  'dashboard.filter_role_all': 'Tous les postes',
  'dashboard.filter_status_label': 'État de service',
  'dashboard.filter_status_all': 'Tous les états',
  'dashboard.sort_urgence': 'Priorité',
  'dashboard.sort_date': 'Échéance',
  'dashboard.sort_nom': 'Désignation',
  'dashboard.sort_type': 'Régime',
  'dashboard.sort_statut': 'État de service',
  'dashboard.hide_finished_label': 'Masquer les manufactures démantelées',
  'dashboard.show_finished_btn': 'Afficher les manufactures démantelées',
  'dashboard.favorite_add_aria': 'Épingler au tableau (favori)',
  'dashboard.favorite_remove_aria': 'Retirer du tableau (favori)',
  'dashboard.search_label': 'Rechercher une manufacture',
  'dashboard.row_signal_count_aria': '{n} intervention(s) à mener',
  'dashboard.invitation_invited_by': 'recruté par {pseudo}',

  /* ═══ Parties ═══ */
  /* — formulaire de partie — */
  'partie.new_title': 'Nouvelle mission',
  'partie.edit_title': 'Recalibrer la mission',
  'partie.save_btn': 'Valider',
  'partie.cancel_btn': 'Annuler',
  'partie.name_label': 'Nom de la mission',
  'partie.system_label': 'Mécanique de jeu',
  'partie.kind_label': 'Régime de la mission',
  'partie.description_label': 'Note de service (facultatif)',
  'partie.kind_ONE_SHOT': 'Mission unique',
  'partie.kind_CAMPAGNE_LINEAIRE': 'Programme',
  'partie.kind_CAMPAGNE_EPISODIQUE': 'Programme à cycles',
  'partie.kind_refusal_closed': 'Cette mission est close. Rouvrez-la avant d’en changer le régime.',
  'partie.kind_refusal_too_many_scenarios':
    'Cette mission compte {count} opérations ; une mission unique n’en a qu’une.',
  'partie.courant_choice_title': 'Quelle opération reste en cours ?',
  'partie.courant_choice_help':
    'Un programme n’exécute qu’une opération à la fois. Les autres repasseront « à venir » — leurs séances et leurs dates sont conservées.',
  'partie.courant_choice_confirm': 'Verrouiller ce réglage',
  'partie.cover_add': 'Ajouter une plaque d’identification',
  'partie.cover_change': 'Changer la plaque',
  'partie.cover_remove': 'Retirer la plaque',
  'partie.cover_uploading': 'Gravure de la plaque en cours…',
  'partie.cover_upload_error': 'La plaque n’a pu être gravée. Réessayez.',
  'partie.cover_remove_error': 'La plaque n’a pu être retirée. Réessayez.',
  'partie.cover_reject_type': 'Seuls les formats JPEG, PNG et WEBP sont admis.',
  'partie.cover_reject_size': 'Ce fichier dépasse 5 Mo : réduisez-le avant dépôt.',
  'partie.save_error': 'Cette mission n’a pu être enregistrée. Réessayez.',
  'partie.created_but_cover_failed':
    'La mission est bien enregistrée, mais sa plaque n’a pu être gravée. Vous pouvez la redéposer ici.',
  'partie.fields_saved_but_convert_failed':
    'Les autres modifications sont enregistrées, mais le régime de la mission n’a pu être changé. Réessayez.',
  /* — détail de partie — */
  'partie.scheduling_title': 'Prochaine séance d’atelier',
  'partie.no_session': 'Aucune séance planifiée. Interrogez l’automate.',
  'partie.members_title': '⚙ Équipage',
  'partie.no_members': 'Aucun mécanicien à bord.',
  'partie.remove_member_btn': 'Débarquer',
  'partie.no_description': 'Dossier technique vierge.',
  'partie.invite_title': 'Recruter un mécanicien',
  'partie.search_label': 'Matricule ou appellation',
  'partie.search_btn': 'Scanner',
  'partie.invite_btn': 'Enrôler',
  'partie.links_title': "Télégrammes d'invitation",
  'partie.generate_link': "Forger un badge d'accès",
  'partie.notice_invited': 'Télégramme envoyé à {name}.',
  'partie.invite_by_email_label': 'Fréquence du destinataire',
  'partie.invite_by_email_btn': 'Expédier un télégramme',
  'partie.notice_invited_email': 'Télégramme expédié à {email}.',
  'partie.notice_invite_email_error': "Le télégramme n'a pas pu être expédié. Réessayez.",
  'partie.reference_sheets_title': 'Manuels de référence',
  // Noms des fiches de référence et de préparation Ryuutama : vocabulaire du système de jeu, identique.
  'partie.asset_journal_cta': 'Journal',
  'partie.asset_carte_cta': 'Carte',
  'partie.asset_download_error': "Échec de l'impression du manuel. Réessayez.",
  'partie.prep_sheets_title': 'Manuels de préparation (MJ)',
  'partie.asset_monde_cta': 'Monde',
  'partie.asset_monstre_cta': 'Monstre',
  'partie.asset_ville_cta': 'Ville',
  'partie.asset_objectif_chasse_cta': 'Objectif — Chasse',
  'partie.asset_objectif_quete_cta': 'Objectif — Quête',
  'partie.asset_objectif_voyage_cta': 'Objectif — Voyage',
  'partie.asset_oeuf_de_bataille_cta': 'Œuf de bataille',
  'partie.asset_structure_cta': 'Structure',
  'partie.notice_copy': 'Badge copié dans le carnet de bord.',
  'partie.edit_btn': 'Recalibrer',
  'partie.visibility_btn': 'Verrouiller les plans',
  'partie.close_btn': "Mettre à l'arrêt",
  'partie.reopen_btn': 'Remettre en service',
  'partie.status_closed_label': "Cette machine est à l'arrêt.",
  'partie.delete_btn': 'Démanteler',
  'partie.invitations_tab_label': 'Télégrammes',
  /* — zones de l’onglet Détails — */
  // Noms CONTRACTUELS des trois zones (Action / Consultation / Référence) : catégories nommées par l’épic,
  // identiques dans les trois thèmes.
  'partie.details_zone_action': 'Action',
  'partie.details_zone_consultation': 'Consultation',
  'partie.details_zone_reference': 'Référence',
  /* — signaux d’état — */
  'partie.signal_personnage_a_creer': 'Assembler son automate',
  'partie.signal_vote_en_cours_sans_reponse': 'Vote à renseigner',
  'partie.signal_compte_rendu_non_redige': 'Rapport à rédiger',
  'partie.signal_homme_dragon_a_creer': 'Assembler son Homme Dragon',
  'partie.signal_aucun_membre_invite': 'Aucun mécanicien recruté',
  'partie.signal_aucun_scenario_en_cours': 'Aucune mission en cours',
  'partie.signal_aucune_date_ni_vote': 'Aucune date ni scrutin',
  'partie.signal_rapport_fin_manquant': 'Rapport de fin manquant',
  'partie.signal_prochaine_seance_connue': 'Prochaine séance connue',
  'partie.signal_partie_terminee': 'Machine démantelée',
  'partie.signal_more_count': '+{n}',
  /* — états de scénario et de séance — */
  // Noms d’état CONTRACTUELS, IDENTIQUES dans les trois thèmes (story 32.3).
  // « Courant », JAMAIS « En cours » : « en cours » est réservé au VOTE.
  // La paire vote répondu / non répondu porte DEUX libellés distincts (EXPERIENCE.md §5) : la teinte ne
  // doit jamais être la seule différence.
  'status.scenario_brouillon': 'Brouillon',
  'status.scenario_a_venir': 'À venir',
  'status.scenario_courant': 'Courant',
  'status.scenario_passe': 'Passé',
  'status.seance_a_planifier': 'À planifier',
  'status.seance_answer_poll': 'Réponds au vote',
  'status.seance_poll_open': 'Vote en cours',
  'status.seance_inscriptions_ouvertes': 'Inscriptions ouvertes',
  'status.seance_programmee': 'Programmée',
  'status.seance_a_debriefer': 'À débriefer',
  'status.seance_jouee': 'Jouée',
  /* — confidentialité — */
  'parties.confirm_title': 'Validation requise',
  'parties.locks_title': 'Confidentialité des plans',
  'parties.locks_load_partie_error':
    'Les informations de la mission n’ont pu être chargées. Réessayez.',
  'parties.locks_load_schema_error':
    'Le schéma de la mécanique de jeu n’a pu être chargé. Réessayez.',
  'parties.locks_save_error': 'La configuration n’a pu être consignée. Réessayez.',
  'parties.locks_access_denied':
    'Accès refusé : seul l’Ingénieur de cette mission peut configurer la confidentialité.',
  'parties.locks_help':
    'Cochez les éléments de fiche à verrouiller pour les mécaniciens (hors Ingénieur et propriétaire de l’automate). L’enregistrement remplace l’ensemble des verrous actuels de cette mission.',
  'parties.locks_empty': 'Cette mécanique de jeu ne déclare aucun élément verrouillable.',
  /* — onglets, effectif et liens — */
  'parties.detail_polls_in_progress': '{count} scrutins de date en cours',
  'parties.detail_remove_member_confirm': 'Débarquer {name} de la mission « {partie} » ?',
  'parties.detail_delete_confirm':
    'Démanteler la mission « {partie} » ? Cette action est irréversible.',
  'parties.detail_link_expires_short': 'exp.',
  'parties.detail_tab_details': 'Dossier',
  'parties.detail_tab_scenario': 'Opération',
  'parties.detail_tab_scenarios': 'Opérations',
  'parties.detail_tab_timeline': 'Chronogramme',
  'parties.roster_aria_levelup': '{label} — calibrage de niveau disponible',
  'parties.roster_aria_role': '{label} — fonction : {role}',
  'parties.roster_aria_mj': '{name} — Ingénieur',
  'parties.roster_aria_no_character': '{name} — aucun automate assemblé',
  'parties.roster_aria_character': '{name} — {character}',
  'parties.roster_aria_character_class': '{name} — {character} ({class})',
  'parties.roster_aria_create': '{name} — {action}',
  /* — distribution d’XP — */
  'evolution.xp_distribute_cta': "Distribuer les crédits d'expérience",
  'evolution.xp_panel_title': "Distribution de crédits d'expérience",
  'evolution.xp_history_title': "Registre des crédits d'expérience",
  'evolution.xp_history_empty': 'Aucune distribution enregistrée dans le registre.',
  'evolution.xp_note_label': 'Note technique',
  'evolution.xp_confirm_btn': 'Valider la distribution',
  'evolution.xp_bonus_link': '+ prime',
  'evolution.xp_levelup_warning': '{name} va être recalibré au niveau supérieur',
  'parties.xp_suggested': 'Montant suggéré : {amount} XP',
  'parties.xp_current': '{xp} XP au compteur',
  'parties.xp_amount_label': 'Quantité',
  'parties.xp_select_one_error': 'Sélectionnez au moins un automate avant de distribuer.',
  'parties.xp_distribute_error': 'La distribution n’a pu être consignée. Réessayez.',
  'parties.xp_rules_title': 'Calcul par l’automate',
  'parties.xp_history_unknown_character': 'Automate inconnu',
  'parties.xp_history_bonus_badge': 'prime',

  /* ═══ Scénarios et séances ═══ */
  /* — formulaire et scénario unique — */
  'scenarios.fill_label': '{count} / {max} inscrits à bord (min. {min})',
  'scenarios.form_title': 'Nouvelle opération',
  'scenarios.form_description_label': 'Notice de l’opération (facultatif)',
  'scenarios.form_duree_heures_label': 'Durée en heures (optionnel)',
  'scenarios.form_duree_seances_label': 'Durée en séances (optionnel)',
  'scenarios.form_save_error': 'L’opération n’a pu être consignée.',
  'scenarios.one_shot_not_found': 'Aucune opération trouvée pour cette mission.',
  'scenarios.one_shot_open_error': 'L’opération n’a pu être ouverte à l’équipage. Réessayez.',
  /* — liste et chronologie — */
  'scenarios.list_title': 'Opérations',
  'scenarios.list_new_button': '+ Nouvelle opération',
  'scenarios.timeline_title': 'Chronogramme',
  'scenarios.timeline_load_error': 'Le chronogramme ne se charge pas. Réessayez.',
  'scenarios.timeline_count_one': '{n} opération',
  'scenarios.timeline_count_many': '{n} opérations',
  'scenarios.timeline_not_planned': 'Non planifié',
  'scenarios.timeline_since': 'en service depuis le {date}',
  'scenarios.timeline_from': 'à compter du {date}',
  /* — séances — */
  'scenarios.seances_delete_button': 'Purger cette séance',
  'scenarios.seances_min_aria': 'Nombre minimum de mécaniciens inscrits',
  'scenarios.seances_max_aria': 'Nombre maximum de mécaniciens inscrits',
  'scenarios.seances_set_capacity': 'Régler la capacité',
  'scenarios.seances_edit_capacity': 'Recalibrer la capacité',
  'scenarios.seances_desinscrire': 'Me désinscrire',
  'scenarios.seances_inscrire': 'M’inscrire',
  'scenarios.seances_heure_malformed':
    '⚠️ Valeur stockée non reconnue ("{raw}"), champ laissé vide — consigner sans la corriger l\'effacera.',
  'scenarios.seances_lieu_placeholder': 'à l’atelier de Marc, en visio…',
  'scenarios.seances_note_placeholder': 'pensez aux dés et à la clé à molette…',
  'scenarios.seances_save_infos': 'Consigner les informations pratiques',
  'scenarios.seances_compte_rendu_placeholder': 'Rapport de la séance…',
  'scenarios.seances_compte_rendu_aria': 'Rapport de la séance',
  'scenarios.seances_save_compte_rendu': 'Consigner le rapport',
  'scenarios.seances_compte_rendu_empty': 'Aucun rapport pour cette séance pour le moment.',
  'scenarios.seances_choose_error': 'Cette date n’a pu être verrouillée. Réessayez.',
  'scenarios.seances_capacity_error': 'La capacité n’a pu être réglée. Réessayez.',
  'scenarios.seances_inscrire_error': 'Votre inscription n’a pu être consignée. Réessayez.',
  'scenarios.seances_desinscrire_error': 'Votre désinscription n’a pu être consignée. Réessayez.',
  'scenarios.seances_delete_error': 'Cette séance n’a pu être purgée. Réessayez.',
  'scenarios.seances_reset_error': 'La date n’a pu être purgée. Réessayez.',
  'scenarios.seances_infos_error':
    'Les informations pratiques n’ont pu être consignées. Réessayez.',
  'scenarios.seances_compte_rendu_error': 'Le rapport n’a pu être consigné. Réessayez.',
  'scenarios.seances_refresh_error':
    'Action effectuée, mais l’affichage n’a pu être rafraîchi. Rechargez la page.',
  'scenarios.seances_delete_confirm_dated':
    'Cette séance a une date verrouillée. La purger quand même ? Cette action est définitive.',
  'scenarios.seances_delete_confirm': 'Purger cette séance ? Cette action est définitive.',
  'scenarios.seances_reset_confirm':
    'Purger la date de cette séance ? Un nouveau scrutin pourra être ouvert.',
  /* — lecture du scénario — */
  'scenarios.read_resume_empty': 'Aucun rapport de fin pour l’instant.',
  'scenarios.read_resume_edit': 'Ajuster le rapport de fin',
  'scenarios.read_resume_write': 'Rédiger le rapport de fin',
  'scenarios.read_journal_title': 'Journal de bord associé',
  'scenarios.read_auto_associate': 'Raccordement automatique',
  'scenarios.read_note_shared_aria': 'Note diffusée à l’équipage',
  'scenarios.read_note_private_aria': 'Note privée, confidentielle',
  'scenarios.read_note_private_hint':
    'Note confidentielle — déverrouillez-la (🔒) pour qu’elle figure dans la rétrospective.',
  'scenarios.read_journal_empty': 'Vous n’avez encore rien consigné au journal.',
  'scenarios.read_retrospective_title': 'Journal de la rétrospective',
  'scenarios.read_participate': 'Prendre part à cette opération',
  'scenarios.read_journal_load_error': 'Votre journal ne se charge pas.',
  'scenarios.read_participate_error': 'Votre participation à cette opération n’a pu aboutir.',
  'scenarios.read_setting_error': 'Ce réglage n’a pu être ajusté.',
  'scenarios.read_note_visibility_error': 'La visibilité de cette note n’a pu être ajustée.',
  'scenarios.read_note_association_error': 'Ce raccordement n’a pu être mis à jour.',
  /* — éditeur du scénario — */
  'scenarios.editor_pencil_title': 'le titre de l’opération',
  'scenarios.editor_pencil_duree_heures': 'la durée en heures',
  'scenarios.editor_pencil_duree_seances': 'la durée en séances',
  'scenarios.editor_mark_courant': 'Passer en Courant',
  'scenarios.editor_close': 'Clôturer cette opération',
  'scenarios.editor_add_seance': 'Ajouter une séance',
  'scenarios.editor_resume_empty_hint':
    'Aucun rapport de fin pour l’instant — rédigez-le pour clore la rétrospective.',
  'scenarios.editor_save_resume': 'Consigner le rapport de fin',
  'scenarios.editor_no_participants': 'Aucun mécanicien pour l’instant.',
  'scenarios.editor_documents_title': 'Dossiers de l’opération',
  'scenarios.editor_library_title': 'Archives du programme',
  'scenarios.editor_library_doc_suffix': '— archives du programme',
  'scenarios.editor_documents_load_error': 'Les dossiers ne se chargent pas. Réessayez.',
  'scenarios.editor_participants_load_error':
    'La liste des mécaniciens n’a pu être chargée. Réessayez.',
  'scenarios.editor_upload_error': 'Le dossier n’a pu être déposé. Réessayez.',
  'scenarios.editor_mark_courant_error': 'Cette opération n’a pu passer en Courant.',
  'scenarios.editor_close_error': 'Cette opération n’a pu être clôturée.',
  'scenarios.editor_add_seance_error': 'La séance n’a pu être ajoutée.',
  'scenarios.editor_resume_save_error': 'Le rapport de fin n’a pu être consigné.',
  'scenarios.editor_download_error': 'Le dossier n’a pu être récupéré.',

  /* ═══ Calendrier ═══ */
  /* — barre d’affichage et légende — */
  // Barre d’affichage et légende : verbatim du contrat d’UI (story 36.14), identiques sauf là où un
  // pronom impose le vouvoiement ou le tutoiement du thème.
  'calendar.display.trigger': 'Affichage',
  'calendar.display.trigger_aria': 'Régler l’affichage du registre',
  'calendar.display.section_visible': 'Ce que je vois',
  'calendar.display.show_legend': 'Afficher la légende',
  'calendar.display.filtered_badge': 'Affichage filtré · {n} sur {total} · Rétablir',
  'calendar.legend.title': 'Légende des cadrans',
  'calendar.legend.group_obvious': 'Lisibles sans notice',
  'calendar.legend.group_needs': 'Exigent la notice',
  'calendar.legend.entry.available': 'Je suis disponible',
  'calendar.legend.entry.unavailable': 'Je suis indisponible',
  'calendar.legend.entry.seance': 'Séance confirmée — vous êtes engagé',
  'calendar.legend.entry.vote': 'Créneau proposé au vote',
  'calendar.legend.entry.poll_track': 'Participation : la piste = l’équipage',
  'calendar.legend.entry.group': 'Disponibilité du groupe',
  'calendar.legend.entry.none': 'Personne ne s’est prononcé',
  /* — agenda — */
  'calendar.agenda.section_awaiting': 'À traiter',
  'calendar.agenda.section_scheduled': 'Au programme',
  'calendar.agenda.section_past': 'Aux archives',
  // Badges d’état de l’Agenda : CONTRACTUELS et identiques (EXPERIENCE.md §5, paire « Réponds au vote » / « Vote en cours »).
  'calendar.agenda.badge_answer_poll': 'Réponds au vote',
  'calendar.agenda.badge_poll_open': 'Vote en cours',
  'calendar.agenda.badge_signup': 'S’inscrire',
  'calendar.agenda.badge_signed_up': 'Inscrit',
  'calendar.agenda.badge_debrief': 'Débriefer',
  'calendar.agenda.empty': 'Aucune tâche, aucune échéance.',
  'calendar.agenda.badge_to_seal': 'À sceller',
  'calendar.agenda.poll_open': 'Scrutin ouvert',
  'calendar.agenda.responded_count': '{n} sur {total} membres ont répondu',
  'calendar.agenda.slots_proposed': '{n} plages proposées',
  'calendar.agenda.missing_voters': 'en attente de {names}',
  'calendar.agenda.no_date': 'date à régler',
  'calendar.agenda.no_date_proposed': 'Aucune plage proposée',
  'calendar.agenda.action_launch_poll': 'Ouvrir un scrutin',
  'calendar.agenda.action_seal': 'Verrouiller',
  'calendar.agenda.action_expand': 'Développer',
  'calendar.agenda.action_collapse': 'Rétracter',
  'calendar.agenda.seal_confirm_title': 'Verrouiller l’engrenage sur ce créneau ?',
  'calendar.agenda.seal_confirm_body':
    'La séance sera fixée à ce créneau et le scrutin se refermera. Les autres créneaux proposés disparaîtront.',
  'calendar.agenda_missing_more_one': '{listed} et {rest} autre mécanicien',
  'calendar.agenda_missing_more_many': '{listed} et {rest} autres mécaniciens',
  /* — vue calendrier (navigation, composition, chargement) — */
  'calendar.agg_counts_aria': 'Disponibilités enregistrées',
  'calendar.agg_available_title': 'Disponibles',
  'calendar.agg_unknown_title': 'Inconnus',
  'calendar.agg_unavailable_title': 'Indisponibles',
  'calendar.slots_list_aria': 'Plages disponibles',
  'calendar.rail_empty': 'Aucun jour à détailler',
  'calendar.rail_status_unknown': 'Rien au planning',
  'calendar.layer_group_aria': 'Couches affichées du registre',
  'calendar.view_back': '← Retour',
  'calendar.view_compose_arm': 'Ajouter des dates',
  'calendar.view_toggle_aria': 'Vue du registre',
  'calendar.view_toggle_month_short': 'Mois',
  'calendar.view_toggle_week_short': 'Sem.',
  'calendar.view_toggle_agenda_short': 'Agenda',
  'calendar.view_no_poll': 'Aucun scrutin de date en cours.',
  'calendar.view_locked_seance_hint':
    'Le scrutin de la séance sélectionnée s’ouvre depuis la fiche de l’opération.',
  'calendar.view_group_label': '{slot} — {available}/{total} membres disponibles',
  'calendar.view_group_unavailable_detail': '{n} indisponible(s)',
  'calendar.view_compose_target_poll': 'Plages du scrutin : {label}',
  'calendar.view_compose_target_new': 'Plages d’un nouveau scrutin',
  'calendar.view_compose_blocked_min': 'Un scrutin demande au moins deux plages.',
  'calendar.view_compose_blocked_max': 'Quarante plages au maximum.',
  'calendar.view_compose_blocked_no_seance':
    'Aucune séance n’attend de scrutin : un scrutin se rattache toujours à une séance.',
  'calendar.view_compose_stale_voters':
    'Une nouvelle réponse est parvenue depuis l’avertissement — revalidez pour obtenir le relevé à jour.',
  'calendar.view_compose_save_error': 'Ces plages n’ont pu être consignées. Réessayez.',
  'calendar.view_batch_conflict_labels':
    'Ces plages se contredisent entre elles ({labels}). Rien n’a été consigné.',
  'calendar.view_batch_conflict_plain':
    'Ces plages se contredisent entre elles. Rien n’a été consigné.',
  'calendar.view_conflict_in_progress':
    'Une résolution de conflit est déjà engagée. Terminez-la avant de relancer.',
  'calendar.view_cell_unknown': 'Plage inconnue',
  'calendar.view_selection_none': 'sur aucune plage',
  'calendar.view_selection_one': 'le {cell}',
  'calendar.view_selection_many': 'sur {n} plages, du {from} au {to}',
  'calendar.view_seal_error': 'Cette plage n’a pu être verrouillée. Réessayez.',
  'calendar.view_range_error': 'La date de début doit précéder ou égaler la date de fin.',
  'calendar.view_load_declarations_error': 'Les disponibilités ne se chargent pas.',
  'calendar.view_load_slots_error': 'Les plages ne se chargent pas.',
  'calendar.view_load_calendar_error': 'Le registre ne se charge pas pour cette période.',
  /* — vue mois — */
  'calendar.month_prev_aria': 'Mois précédent au registre',
  'calendar.month_next_aria': 'Mois suivant au registre',
  'calendar.month_today_aria': 'Revenir au mois actuel du registre',
  'calendar.month_cell_instructions':
    "Espace : sélectionner la journée entière. Touches 1, 2, 3 : sélectionner respectivement le matin, l'après-midi ou le soir. Maj plus flèches : étendre la sélection. Entrée : valider la sélection avec ce qu'affiche la barre. Échap : annuler.",
  'calendar.month_day_today_aria': "{day} (aujourd'hui)",
  'calendar.month_status_unknown': 'non consigné',
  /* — vue semaine — */
  'calendar.week_decl_available': 'Dispo',
  'calendar.week_decl_punctual': 'Ponctuel',
  'calendar.week_decl_recurring': 'Récurrent',
  'calendar.week_decl_unavailable': 'Indispo',
  'calendar.week_next_aria': 'Semaine suivante au registre',
  'calendar.week_prev_aria': 'Semaine précédente au registre',
  'calendar.week_status_available': 'disponible',
  'calendar.week_status_unavailable': 'indisponible',
  'calendar.week_status_unknown': 'inconnu',
  'calendar.week_today_aria': 'Revenir à la semaine actuelle du registre',
  /* — mots d’état et de participation — */
  'calendar.util_answer_yes': 'oui',
  'calendar.util_answer_maybe': 'peut-être',
  'calendar.util_answer_no': 'non',
  'calendar.util_answer_mine': 'vous avez répondu {answer}',
  'calendar.util_participation_one': '{n} réponse enregistrée sur {total}',
  'calendar.util_participation_many': '{n} réponses enregistrées sur {total}',
  'calendar.util_group_aria_one':
    'Disponibilité de l’équipage : {available} sur {total} disponible',
  'calendar.util_group_aria_many':
    'Disponibilité de l’équipage : {available} sur {total} disponibles',
  'calendar.util_group_all_blocked': 'tout l’équipage est bloqué',
  'calendar.util_group_nobody': 'personne ne s’est enregistré',
  'calendar.util_group_unavailable_one': '{n} indisponible',
  'calendar.util_group_unavailable_many': '{n} indisponibles',
  'calendar.util_word_no_answer': 'sans réponse',
  'calendar.util_counter': '{n} / {total}',
  /* — barre de sélection — */
  'calendar.selbar_announcement': 'Portée : {scope}. Entrée consignera : {kind}.',
  'calendar.selbar_count_many': '{n} plages sélectionnées',
  'calendar.selbar_count_one': '{n} plage sélectionnée',
  'calendar.selbar_other': 'Autre réglage…',
  'calendar.selbar_scope_aria': 'Portée de la sélection',
  'calendar.selbar_toolbar_aria': 'Commandes de la sélection',
  /* — panneau de contraintes — */
  'calendar.constraint_all_occurrences': 'Toutes les occurrences',
  'calendar.constraint_close_aria': 'Fermer le panneau de commande',
  'calendar.constraint_conflict_prompt':
    'Des disponibilités contradictoires sont déjà consignées pour cette période.',
  'calendar.constraint_delete_error': 'La contrainte n’a pu être purgée.',
  'calendar.constraint_end_date': 'Date de fin',
  'calendar.constraint_expires_on': 'Expire le',
  'calendar.constraint_from_this_day': 'À partir de ce jour, jusqu’à l’arrêt',
  'calendar.constraint_keep_existing': 'Maintenir l’existant',
  'calendar.constraint_kind_aria': 'Disponibilité',
  'calendar.constraint_modify_error': 'La contrainte n’a pu être ajustée.',
  'calendar.constraint_occurrence_delete_error': 'L’occurrence n’a pu être purgée.',
  'calendar.constraint_occurrence_modify_error': 'L’occurrence n’a pu être ajustée.',
  'calendar.constraint_overwrite': 'Supplanter',
  'calendar.constraint_recurring_delete_prompt':
    'Cette contrainte est récurrente. Que souhaitez-vous purger ?',
  'calendar.constraint_recurring_modify_prompt':
    'Cette contrainte est récurrente. Que souhaitez-vous ajuster ?',
  'calendar.constraint_start_date': 'Date de début',
  'calendar.constraint_type_punctual': 'Cette plage uniquement',
  'calendar.constraint_type_range': 'Plage de dates',
  'calendar.constraint_type_recurring': 'Récurrent (cycle hebdomadaire)',
  'calendar.constraint_whole_series': 'Tout le cycle',
  /* — boîte de conflit — */
  'calendar.conflict_exception_detail':
    'Vous y avez une séance. Aucun de ces choix n’y touche. Si elle est annulée, vous repassez en {kind}.',
  'calendar.conflict_exception_many': 'n’apparaissent pas dans la liste',
  'calendar.conflict_exception_one': 'n’apparaît pas dans la liste',
  'calendar.conflict_free_many': 'Les {n} autres sont réglés en {kind}',
  'calendar.conflict_free_none': 'Rien d’autre n’est consigné',
  'calendar.conflict_free_one': 'Le 1 autre est réglé en {kind}',
  'calendar.conflict_intent_prefix': 'Vous déclarez',
  'calendar.conflict_keep_many': 'Ces {n} sont maintenus',
  'calendar.conflict_keep_one': 'Ce créneau est maintenu',
  'calendar.conflict_step_announcement': 'Plage {progress} : {label}. Remplacer ou conserver ?',
  'calendar.conflict_title_many': '{n} plages sont déjà consignées',
  'calendar.conflict_title_one': '1 plage est déjà consignée',
  'calendar.conflict_walkthrough_body': 'Nous les passons en revue un par un',
  'calendar.conflict_walkthrough_count_many': '{n} décisions à consigner',
  'calendar.conflict_walkthrough_count_one': '{n} décision à consigner',
  'calendar.conflict_walkthrough_label': 'Au cas par cas',
  'calendar.conflict_kind_available': 'disponible',
  'calendar.conflict_kind_unavailable': 'indisponible',
  'calendar.conflict_overwrite_available_one': 'Le créneau est réglé disponible',
  'calendar.conflict_overwrite_available_many': 'Les {n} sont réglés disponibles',
  'calendar.conflict_overwrite_unavailable_one': 'Le créneau est réglé indisponible',
  'calendar.conflict_overwrite_unavailable_many': 'Les {n} sont réglés indisponibles',
  /* — composition des créneaux d’un vote — */
  'calendar.card_alerts_aria': 'Alertes de disponibilité du registre',
  'calendar.card_full_guild': 'Équipage au complet',
  'calendar.card_members_aria': 'Équipage',
  'calendar.compose_bar_aria': 'Composition des plages d’un scrutin',
  'calendar.compose_confirm_note':
    'Les réponses portées par les plages conservées ne sont pas touchées.',
  'calendar.compose_confirm_responses_many': '{n} réponses',
  'calendar.compose_confirm_responses_one': '{n} réponse',
  'calendar.compose_confirm_seance_label': 'Pour quelle séance d’atelier ?',
  'calendar.compose_confirm_seance_placeholder': 'Sélectionner une séance…',
  'calendar.compose_confirm_slots_many': '{n} plages',
  'calendar.compose_confirm_slots_one': '{n} plage',
  'calendar.compose_confirm_summary_many': '{n} plages proposées.',
  'calendar.compose_confirm_summary_one': '{n} plage proposée.',
  'calendar.compose_confirm_title_modify': 'Ajuster les plages du scrutin',
  'calendar.compose_confirm_warning_many': 'Retirer {slots} purgera {votes} déjà posées.',
  'calendar.compose_confirm_warning_one': 'Retirer {slots} purgera {votes} déjà posée.',
  'calendar.compose_count_many': '{n} plages désignées',
  'calendar.compose_count_none': 'Aucune plage désignée',
  'calendar.compose_count_one': '{n} plage désignée',
  /* — mode Destinée — */
  // Nom du MODE « Destinée » (EXPERIENCE.md §4.4 ter), identique dans les trois thèmes.
  'cta.destiny_mode': 'Destinée',
  'calendar.destiny_next_aria': 'Scrutin suivant',
  'calendar.destiny_prev_aria': 'Scrutin précédent',

  /* ═══ Vote de date ═══ */
  /* — actions, états et alertes — */
  'cta.find_date': "Interroger l'automate des créneaux",
  'cta.guild_calendar': 'Consulter le registre de la mission',
  'cta.save_constraint': 'Enregistrer dans le registre de vapeur',
  'section.slots': "Créneaux validés par l'automate",
  'empty.no_slots': "L'automate ne détecte aucun créneau. Vérifiez les registres des membres.",
  'success.constraint_saved': 'Contrainte enregistrée dans le registre.',
  'alert.missing_player': "{name} n'a pas alimenté le registre.",
  'cta.choose_date': "Verrouiller l'engrenage de la date",
  'cta.cancel_poll': 'Purger le registre de vote',
  'cta.restore_default_layers': "Réinitialiser l'affichage par défaut",
  'success.poll_created': 'Registre de vote activé. Message pneumatique envoyé.',
  'success.vote_cast': 'Réponse enregistrée dans le registre.',
  'cta.confirm_votes': 'Valider dans le registre',
  'cta.withdraw_vote': 'Annuler ma réponse',
  'success.vote_withdrawn': 'Réponse effacée du registre.',
  'alert.all_responded': "Tout l'équipage a répondu au registre.",
  /* — état du vote — */
  'poll.status_title': 'Registre de vote actif',
  'poll.vote_pending': 'Registre de vote — réponse requise',
  'poll.withdraw_error': 'Le retrait a échoué. Réessayez.',
  'poll.cast_error': 'Votre réponse n’a pu être enregistrée. Réessayez.',
  'poll.vote_closed': 'Registre de vote verrouillé.',
  'poll.status_summary': 'Registre ouvert — {responded}/{total} membres ont répondu',
  'poll.missing_prefix': 'N’ont pas alimenté le registre :',
  'poll.responded_prefix': 'Ont alimenté le registre :',
  /* — réponse au vote — */
  'calendar.answer_menu_aria': 'Répondre au scrutin — {slot}',
  'calendar.answer_withdraw': 'Annuler ma réponse',
  /* — création et suivi du vote — */
  'pollui.creation_title': 'Ouvrir un scrutin de date',
  'pollui.creation_computed_title': 'Plages calculées par l’automate',
  'pollui.creation_computed_empty': 'L’automate ne calcule aucune plage disponible.',
  'pollui.creation_load_more_one': '{n} plage de plus',
  'pollui.creation_load_more_many': '{n} plages de plus',
  'pollui.creation_all_shown': 'Toutes les plages calculées sont affichées',
  'pollui.creation_custom_title': 'Plages personnalisées',
  'pollui.creation_add_custom': 'Ajouter une plage personnalisée',
  'pollui.creation_selected_count': '{n} option(s) sélectionnée(s)',
  'pollui.creation_submit': 'Ouvrir le scrutin',
  'pollui.creation_desync_error':
    'Le scrutin a été ouvert, mais son état n’a pu être rafraîchi ici. Rechargez la page pour le voir plutôt que d’ouvrir un autre scrutin.',
  'pollui.creation_error': 'Le scrutin n’a pu être ouvert. Réessayez.',
  'pollui.response_not_saved_aria': 'Non consigné',
  'pollui.response_partial_error':
    '{success}/{total} réponse(s) consignée(s). Réessayez pour les autres.',
  'pollui.status_voters_aria': 'Votants du scrutin',
  'pollui.status_missing_aria': 'N’ont pas encore alimenté le registre pour cette date',
  'pollui.status_choose_confirm': 'Verrouiller {date} — {slot} comme date de la prochaine séance ?',
  'pollui.status_choose_no_vote_warning': "⚠️ Aucun membre n'a voté pour cette date.",

  /* ═══ Annonces ═══ */
  /* — annonces — */
  'announcement.scope_campaign_label': 'Tout le programme',
  'announcement.scope_oneshot_label': 'Cette mission',
  'announcement.scope_scenario_label': 'Cette opération',
  'announcement.publish_cta': 'Diffuser une transmission',
  'announcement.text_placeholder': 'Rédiger une transmission...',
  'announcement.published_notice': 'Transmission diffusée.',
  'announcement.unseen_label': 'Non lue — cliquez pour accuser réception',
  'announcement.publish_error': 'Votre transmission n’a pu être diffusée. Réessayez.',

  /* ═══ Personnages ═══ */
  /* — liste « Personnages » — */
  'my_characters.title': 'Mes automates',
  'my_characters.empty': 'Aucun automate assemblé. Construisez-en un depuis une mission…',
  'my_characters.no_match': 'Aucun automate ne répond à cette recherche.',
  'my_characters.search_label': 'Rechercher un automate',
  'my_characters.sort_niveau': 'Niveau',
  'my_characters.sort_partie': 'Mission',
  'my_characters.sort_nom': 'Désignation',
  'my_characters.create_title': 'À assembler',
  'my_characters.create_entry': 'Assembler un automate-voyageur pour {partie}',
  'my_characters.create_more': 'Voir les {n} autres missions',
  'my_characters.create_more_one': 'Voir l’autre mission',
  'my_characters.create_less': 'Réduire la liste',
  'my_characters.empty_with_entries': 'Aucun automate assemblé pour l’instant.',
  'my_characters.create_entry_hd': 'Assembler un Homme Dragon pour {partie}',
  'characters_list.homme_dragons_load_error':
    'Vos Hommes Dragons n’ont pu être chargés depuis le registre.',
  /* — fiche de personnage — */
  'character.portrait_edit_cta': 'Recalibrer le portrait',
  'character.pdf_crop_edit_cta': 'Recalibrer le cadrage PDF',
  'character.sheet_menu_trigger_aria': 'Commandes de la fiche',
  'character.export_editable_cta': 'Imprimer en PDF (éditable)',
  'character.export_2pages_cta': 'Imprimer en PDF (2 pages)',
  'character.export_equipment_cta': 'Imprimer l’équipement en PDF',
  'character.export_notes_cta': 'Imprimer les notes en PDF',
  'character.export_error': 'Le PDF n’a pu être imprimé par le pneumatique. Réessayez.',
  'character.owner_badge_mj': 'Ingénieur',
  // « Homme Dragon » est un nom propre du système : jamais thématisé (story 33.5).
  'character.nature_dragon': 'Homme Dragon',
  'character.level_badge': 'Niv. {n}',
  'character.party_sheets_tab_label': 'Fiches',
  'character.back_to_partie_cta': 'Retour à la mission',
  'character.no_character_yet':
    'Aucun automate-voyageur assemblé sur cette mission pour l’instant.',
  'characters_sheet.not_found': 'Fiche introuvable au registre.',
  'characters_sheet.access_denied': 'Cette fiche vous est verrouillée.',
  'characters_sheet.load_error': 'La fiche de l’automate ne se charge pas. Réessayez.',
  'characters_sheet.portrait_save_error': 'Le portrait n’a pu être consigné. Réessayez.',
  'characters_sheet.pdf_crop_save_error': 'Le cadrage PDF n’a pu être consigné. Réessayez.',
  'characters_sheet.field_edit_aria': 'Ajuster {label}',
  'characters_sheet.history_load_error': 'Le journal de bord ne se charge pas.',
  'characters_sheet.history_level': 'Niveau {level}',
  'characters_sheet.item_added_by_mj': 'ajouté par l’Ingénieur',
  'characters_sheet.item_edit_aria': 'Ajuster le composant',
  'characters_sheet.item_remove_aria': 'Purger le composant',
  'characters_sheet.notes_load_error': 'Le journal ne se charge pas.',
  'characters_sheet.levelup_title_level': '— Niveau {level}',
  'characters_sheet.levelup_decrease_aria': 'Réduire {stat}',
  'characters_sheet.levelup_increase_aria': 'Relever {stat}',
  'characters_sheet.levelup_attribute_max_sr': 'Déjà au maximum (12)',
  'characters_sheet.levelup_save_error': 'Le recalibrage n’a pu être consigné. Réessayez.',
  'characters_sheet.inventory_contenants_empty': 'Aucun contenant en soute pour le moment.',
  'characters_sheet.inventory_animaux_empty': 'Aucun animal à bord pour le moment.',
  'characters_sheet.inventory_add_contenant_cta': '+ Charger un contenant',
  'characters_sheet.inventory_mj_add_contenant_cta': '+ Charger un contenant (MJ)',
  'characters_sheet.inventory_add_animal_cta': '+ Embarquer un animal',
  'characters_sheet.inventory_mj_add_animal_cta': '+ Embarquer un animal (MJ)',
  /* — évolution (niveau, historique, inventaire, notes) — */
  'evolution.levelup_banner': 'Calibrage niveau [N] disponible',
  'evolution.levelup_cta': 'Recalibrer',
  'evolution.levelup_wizard_title': 'Recalibrage',
  'evolution.levelup_step_pv_pe': 'Distribuer 3 points entre PV et PE',
  'evolution.levelup_step_capability': 'Choisir le module débloqué',
  'evolution.levelup_legendary_journey_text':
    'Une trajectoire légendaire est engagée — aucun réglage supplémentaire requis.',
  'evolution.levelup_confirm_cta': 'Valider le calibrage',
  'evolution.main_sheet_tab_label': 'Fiche technique',
  'evolution.history_tab_label': 'Journal de bord',
  'evolution.history_empty': 'Aucune entrée consignée pour le moment.',
  'evolution.mj_edit_trace': 'recalibré par l’Ingénieur',
  'evolution.landscape_section_title': 'Module paysage/climat',
  'evolution.immunity_section_title': 'Modules d’immunité',
  'evolution.other_capabilities_title': 'Modules installés',
  'evolution.derived_hidden': 'Statistiques verrouillées par l’Ingénieur',
  'evolution.hidden_marker': 'Verrouillé par l’Ingénieur',
  'evolution.inventory_section_title': 'Compartiment de fret',
  'evolution.inventory_add_cta': '+ Charger un composant',
  'evolution.inventory_empty': 'Aucun composant chargé pour le moment.',
  'evolution.inventory_overweight_label': 'Surcharge',
  'evolution.inventory_error': 'Le fret n’a pas pu être mis à jour. Réessayez.',
  'evolution.mj_edit_error': 'La modification n’a pas pu être enregistrée. Réessayez.',
  'evolution.mj_edit_warning_prefix': 'Alerte : ',
  'evolution.inventory_mj_add_cta': '+ Charger un composant (MJ)',
  'evolution.narrative_edit_error': 'La modification n’a pas pu être enregistrée. Réessayez.',
  'evolution.notes_journal_title': 'Journal de bord personnel',
  'evolution.notes_journal_empty': 'Aucune entrée consignée pour le moment.',
  'evolution.notes_add_cta': '+ Consigner une entrée',
  'evolution.note_share_toggle': 'Diffuser à l’équipage',
  'evolution.note_private_label': 'Entrée confidentielle',
  'evolution.note_shared_label': 'Entrée diffusée à l’équipage',
  'evolution.notes_error': 'Le journal de bord n’a pas pu être mis à jour. Réessayez.',
  /* — groupe de joueurs (troupe) — */
  'roster.mj_badge': 'MJ',
  'roster.invite_slot': 'Recruter un mécanicien',
  'roster.collapse_label': "Replier l'équipage",
  'roster.expand_label': "Déplier l'équipage",
  'roster.levelup_badge': 'Calibrage niveau disponible',
  'roster.create_slot_label': 'assembler mon automate-voyageur',
  /* — création de personnage — */
  'character.create_cta': 'Assembler un automate-voyageur',
  'character.choice_deselect_hint': 'Toucher pour désélectionner',
  'character.choice_talents_label': 'Talents',
  'character.choice_advantages_label': 'Avantages',
  'character.choice_required_flag': 'Obligatoire',
  'character.choice_reference_toggle': 'Occupations et actions',
  'character.equipment_group_toggle': '{group}, {n} composants',
  'character.equipment_filter_all': 'Tout l’inventaire',
  'character.equipment_filter_mine': 'Mon chargement',
  'character.equipment_qty_less': 'Décharger un exemplaire de {name}',
  'character.equipment_qty_more': 'Charger un exemplaire de {name}',
  'character.recap_button': 'Récap',
  'character.recap_title': 'Relevé de l’automate',
  'character.recap_cart_title': 'Chargement',
  'character.recap_remove': 'Décharger',
  'character.recap_total': 'Total',
  'character.recap_empty_hint':
    'Les statistiques dérivées seront calculées une fois les attributs assignés.',
  'detail.row_attributes': 'Attributs',
  'detail.row_difficulty': 'Difficulté',
  'detail.row_effect': 'Effet',
  'detail.row_conditions': 'Conditions',
  'detail.narrative_show': 'Consulter le rapport',
  'detail.narrative_hide': 'Masquer le rapport',
  'character.equipment_group_individual': 'Objets',
  'character.equipment_group_contenant': 'Contenants',
  'character.equipment_group_animal': 'Animaux',
  'character.equipment_search_label': 'Rechercher un composant',
  'character.equipment_search_placeholder': 'Nom d’un composant…',
  'character.equipment_budget': 'Budget · {spent} / {total} Po',
  'character.equipment_over_budget': '— dépassement de {n} Po',
  'character.equipment_search_empty': 'Aucun mécanisme ne porte ce nom dans l’atelier…',
  'character.step_class': 'Choisir sa fonction',
  'character.step_type': 'Choisir son mécanisme',
  'character.step_magic': 'Calibrer le module magique',
  'character.step_portrait_intro':
    'Gravez un portrait sur la plaque si vous le souhaitez — étape optionnelle, ignorable sans conséquence.',
  'characters_wizard.loading': 'L’assistant se met en pression…',
  'characters_wizard.step_prev_aria': 'Phase précédente',
  'characters_wizard.step_next_aria': 'Phase suivante',
  'characters_wizard.step_progress': 'Phase {index}/{total} · {label}',
  'characters_wizard.submitting': 'Assemblage…',
  'characters_wizard.summary_aria': 'Relevé de l’automate',
  'characters_wizard.summary_default_title': 'Automate',
  'characters_wizard.load_error_no_module':
    'Cette mécanique de jeu n’a pas encore d’assistant de création.',
  'characters_wizard.load_error':
    'L’assistant de création n’a pu être mis en route. Vérifiez votre connexion et réessayez.',
  'characters_wizard.portrait_upload_warning':
    'Automate assemblé, mais son portrait n’a pu être consigné. Réessayez depuis la fiche.',
  'characters_wizard.already_has_character': 'Vous avez déjà un automate sur cette mission',
  'characters_wizard.invalid_data': 'Données invalides. Vérifiez votre saisie.',
  'characters_wizard.attributes_profile_aria': "Profil d'attributs",
  'characters_wizard.attributes_banner_profile': 'Profil',
  'characters_wizard.attributes_banner_one': '— {n} valeur sur {total} installée',
  'characters_wizard.attributes_banner_many': '— {n} valeurs sur {total} installées',
  'characters_wizard.attributes_chip_remaining': '{value}, encore {n} à installer',
  'characters_wizard.equipment_mode_aria': 'Choisir un mode de chargement',
  'characters_wizard.equipment_mode_kit': 'Kit préassemblé',
  'characters_wizard.equipment_mode_shopping': 'Achat libre',
  'characters_wizard.equipment_filter_aria': 'Filtre du catalogue',
  'characters_wizard.weapon_category_aria': 'Choisir une catégorie d’armement',
  'characters_wizard.weapon_item_aria': 'Choisir son modèle d’arme précis',
  'characters_wizard.weapon_custom_card': 'Assembler une arme libre',
  /* — portrait — */
  'portrait.cropper_choose_image': 'Charger une image',
  'portrait.cropper_area_aria':
    'Zone de cadrage du portrait. Flèches pour déplacer, plus/moins pour zoomer.',
  'portrait.cropper_zoom': 'Zoom',
  'portrait.panel_alt': 'Portrait complet de {name}',
  'portrait.panel_caption': 'Portrait complet',
  'portrait.avatar_aria': 'Portrait de {name}',
  'portrait.avatar_aria_empty': 'Portrait de {name} (aucune image)',

  /* ═══ Homme Dragon ═══ */
  'homme-dragon.create_cta': 'Assembler mon Homme Dragon',
  'homme-dragon.race_label': 'Modèle',
  'homme-dragon.artefact_label': 'Composant emblématique',
  'homme-dragon.created_notice': 'Votre Homme Dragon est opérationnel.',
  'hd.page_back_to_characters': 'Retour à « Automates »',
  'hd.creation_page_title': 'Assembler un Homme Dragon',
  'hd.creation_check_error': 'L’Homme Dragon de cette mission n’a pu être contrôlé. Réessayez.',
  'hd.sheet_load_error': 'La fiche ne se charge pas. Réessayez.',
  'hd.sheet_export_pdf': 'Imprimer en PDF',
  'hd.sheet_export_menu_aria': 'Format de l’impression PDF',
  'hd.sheet_export_editable': 'PDF éditable',
  'hd.sheet_export_2pages': 'PDF 2 pages (à imprimer)',
  'hd.sheet_export_error': 'La fiche n’a pu être imprimée en PDF. Réessayez.',
  'hd.sheet_artefact_change_error': 'L’artefact n’a pu être remplacé. Réessayez.',
  'hd.sheet_cadeau_empty': 'Aucun artefact n’est disponible au catalogue.',
  'hd.sheet_cadeau_choose_btn': 'Sélectionner cet artefact',
  'hd.sheet_cadeau_confirm_strong': 'Ce choix est définitif : le verrou ne s’ouvre plus.',
  'hd.sheet_cadeau_confirm_text':
    'Offrir « {nom} » à l’Homme Dragon ? Il ne pourra plus être ajusté.',
  'hd.sheet_cadeau_confirm_btn': 'Verrouiller ce choix définitif',
  'hd.sheet_cadeau_back_btn': 'Revenir à la sélection',
  'hd.sheet_eveil_empty': 'Aucun pouvoir d’éveil n’est disponible au catalogue.',
  'hd.sheet_aventures_empty': 'Aucune mission enregistrée pour l’instant.',
  'hd.sheet_voyageurs_empty': 'Aucun automate-voyageur pour l’instant.',
  'hd.sheet_aventure_add_empty': 'Aucune mission Ryuutama sans Homme Dragon à ajouter.',
  'hd.sheet_aventure_add_error': 'Cette mission n’a pu être ajoutée. Réessayez.',
  'hd.sheet_aventure_remove_aria': 'Retirer la mission {nom}',
  'hd.sheet_aventure_remove_confirm':
    "Retirer « {nom} » ? Le niveau de l'Homme Dragon peut baisser ; sa fiche, sa réserve et ses choix sont conservés.",
  'hd.sheet_aventure_remove_error': 'Cette mission n’a pu être retirée. Réessayez.',
  'hd.sheet_historique_empty': 'Aucune opération menée pour l’instant.',
  'hd.wizard_step_progress': 'Phase {n}/{total} · {etape}',
  'hd.wizard_more_aria': 'Voir la notice de {nom}',
  'hd.wizard_artefact_empty': 'Aucun artefact n’est disponible pour ce modèle.',
  'hd.wizard_create_conflict_error': 'Cette mission a déjà un Homme Dragon.',
  'hd.wizard_create_error': 'Votre Homme Dragon n’a pu être assemblé. Réessayez.',
  'hd.panel_load_error': 'L’Homme Dragon de cette mission ne se charge pas. Réessayez.',
  'hd.panel_linked_title': 'Homme Dragon de cette mission',
  'hd.panel_linked_help': 'Sa fiche, son niveau et son historique cumulent toutes ses missions.',
  'hd.panel_none_title': 'Aucun Homme Dragon pour cette mission',
  'hd.panel_create_cta': 'Assembler un Homme Dragon pour {partie}',
  'hd.panel_associate_empty': 'Vous n’avez encore aucun autre Homme Dragon à raccorder.',
  'hd.panel_associate_label': 'Raccorder un existant',
  'hd.panel_associate_error': 'Cet Homme Dragon n’a pu être raccordé. Réessayez.',
  'hd.panel_dissociate_confirm':
    'Désaccoupler {nom} de « {partie} » ? Son niveau peut baisser ; sa fiche, sa réserve et ses choix sont conservés.',
  'hd.panel_dissociate_error': 'Cet Homme Dragon n’a pu être désaccouplé. Réessayez.',
  'hd.reserve_autosaved': 'Consignée automatiquement, utilisée pour l’impression PDF.',
  'hd.reserve_pick_btn': 'Sélectionner un souffle',
  'hd.reserve_pick_for_slot': 'Sélectionner un souffle pour l’emplacement {n}',
  'hd.reserve_change_aria': 'Remplacer le souffle de l’emplacement {n} : {nom}',
  'hd.reserve_remove_aria': 'Décharger {nom} de l’emplacement {n}',
  'hd.reserve_save_error': 'La réserve n’a pu être consignée. Réessayez.',
  'hd.reserve_undo_text': '{nom} déchargé de l’emplacement {n}.',
  'hd.reserve_removed_status':
    '{nom} déchargé de l’emplacement {n}. Annulation possible pendant quelques secondes.',
  'hd.reserve_restored_status': '{nom} rechargé dans l’emplacement {n}',
  'hd.reserve_placed_status': '{nom} chargé dans l’emplacement {n}. Réserve consignée',
  'hd.picker_place_btn': 'Charger dans l’emplacement {n}',
  'hd.picker_consult_hint': 'Sélectionnez un souffle de la liste pour lire sa description.',
  'hd.picker_choose_hint': 'Sélectionnez un souffle dans la liste.',
  'hd.picker_slot_gone': 'Cet emplacement n’existe plus au registre.',
  'hd.picker_blocked_announce': 'Chargement impossible dans l’emplacement {n} : {raison}',
  'hd.picker_description_aria': 'Notice : {nom}',
  'core.homme_dragon_sans_aventure': 'Sans mission',
};
