import type { ToneKey } from './grimoire-emeraude';

// Typé d'après le thème de référence : une clé manquante ou en trop est une erreur de compilation.
// Mêmes sections, même ordre que `grimoire-emeraude.ts`.
//
// VOIX — Forêt Ancienne : nature, druides, saisons. TUTOIEMENT partout (jamais « vous »).
// Vocabulaire : sentier (la partie), étape (le scénario), clairière (la séance), cercle (le groupe),
// Guide (le MJ), voyageur, compagnon de route (le personnage), besace, carnet, sifflet, écureuil
// messager, hibou, lune, racine, écorce, planter, graver.
export const foretAncienne: Record<ToneKey, string> = {
  /* ═══ Navigation et coque ═══ */
  /* — menu principal — */
  'nav.my_games': 'Mes pérégrinations',
  'nav.create_game': 'Ouvrir un sentier',
  'nav.logout': 'Quitter la forêt',
  'nav.calendar': 'Calendrier lunaire',
  'nav.account': 'Mon carnet',
  'nav.characters': 'Compagnons',
  /* — coque de l’application — */
  'shell.nav_main_aria': 'Navigation principale de la forêt',
  'shell.banner_close_aria': 'Fermer l’appel de {partie}',
  'shell.badge_polls_aria': '{n} vote(s) attendent ta réponse',
  'shell.badge_announcements_aria': '{n} appel(s) non entendu(s)',
  /* — titres de route — */
  'route.title_confirm_email_change': 'Confirmer la nouvelle adresse du hibou',
  'route.title_rollback_email_change': 'Annuler le changement d’adresse du hibou',
  /* — surfaces partagées — */
  'shared.detail_close_window': 'Fermer la fenêtre de la clairière',
  'shared.detail_close_sheet': 'Fermer la feuille de la clairière',
  /* — barre de contrôles des listes — */
  'list_control_bar.toggle_aria': 'Afficher les filtres et le tri de la forêt',
  'list_control_bar.view_mode_group_aria': 'Densité du feuillage',
  'list_control_bar.view_mode_large_aria': 'Grande clairière',
  'list_control_bar.view_mode_medium_aria': 'Clairière moyenne',
  'list_control_bar.view_mode_compact_aria': 'Sentier resserré',
  'list_control_bar.sort_label': 'Ordonner par',
  'list_control_bar.reset_pill_label': 'Réglages déplacés',

  /* ═══ Textes communs ═══ */
  /* — actions et mots courants — */
  'common.8_caracteres': '8 signes au moins',
  'common.a_savoir': 'Bon à savoir',
  'common.accepter': 'Accepter l’appel',
  'common.ajouter': 'Glisser dans la besace',
  'common.ajouter_une_aventure': 'Ajouter un sentier',
  'common.annonces': 'Appels',
  'common.annuler': 'Abandonner',
  'common.associer': 'Rattacher',
  'common.au': 'Au',
  'common.aucun_scenario_pour_l_instant': 'Aucune étape pour l’instant.',
  'common.aucune_description_disponible': 'Rien n’est dit sur ce point.',
  'common.ce_jour_uniquement': 'Ce jour-là seulement',
  'common.changer': 'Échanger',
  'common.chargement': 'La forêt s’éveille…',
  'common.chargement_2': 'La forêt s’éveille...',
  'common.chargement_en_cours': 'Les feuilles se déplient',
  'common.choisir': '-- Choisir un rôle --',
  'common.cloturer_le_vote': 'Clore le cercle',
  'common.confirmer': 'Confirmer',
  'common.connexion': 'Entrer dans la forêt',
  // Remplacer / Conserver / Au cas par cas : vocabulaire de la boîte de conflit (contrat d’UI, story 36.4).
  'common.conserver': 'Conserver',
  'common.copier': 'Copier le sifflet',
  'common.creer': 'Faire naître',
  'common.creer_un_compte': 'Créer ta place dans la forêt',
  'common.creneau': 'Clairière',
  'common.creneaux_varies': 'clairières variées',
  'common.date_a_definir': 'Date à choisir',
  'common.date_a_definir_2': 'Date à choisir.',
  'common.date_retenue_date': 'Date choisie : {date}',
  'common.designe_pour_le_vote': 'désigné pour le cercle',
  'common.detail': 'Observations',
  'common.detail_du_jour': 'Observations du jour',
  // Mots fonctionnels identiques : états de disponibilité, réponses de vote, libellés de champ courts.
  'common.disponible': 'Disponible',
  'common.dissocier': 'Détacher',
  'common.du': 'Du',
  'common.effet_facultatif': 'Effet (si tu veux)',
  'common.email': 'Adresse du hibou (e-mail)',
  'common.en_savoir_plus': 'Approfondir',
  'common.enregistrement': 'Gravure…',
  'common.enregistrer': 'Graver',
  'common.envoi': 'L’écureuil part…',
  'common.fermer': 'Fermer',
  'common.heure': 'Heure',
  'common.homme_dragon_introuvable': 'Cet Homme Dragon reste introuvable dans la forêt.',
  'common.impossible_d_enregistrer_ce_choix_reessayez': 'Ce choix n’a pas pris racine. Réessaie.',
  'common.impossible_d_enregistrer_ces_disponibilites_reessayez':
    'Ces disponibilités n’ont pas pris racine. Réessaie.',
  'common.impossible_d_enregistrer_la_contrainte': 'La contrainte n’a pas pris racine.',
  'common.impossible_d_enregistrer_la_modification': 'La modification n’a pas pris racine.',
  'common.impossible_de_charger_la_partie_reessayez': 'Ce sentier reste introuvable. Réessaie.',
  'common.impossible_de_charger_le_scenario_reessayez': 'Cette étape reste introuvable. Réessaie.',
  'common.impossible_de_charger_les_scenarios_reessayez':
    'Les étapes restent introuvables. Réessaie.',
  'common.impossible_de_cloturer_le_vote_reessayez': 'Le cercle n’a pas pu être clos. Réessaie.',
  'common.indisponible': 'Indisponible',
  'common.j_ai_deja_un_compte': 'J’ai déjà ma place dans la forêt',
  'common.lancer_le_vote': 'Réunir le cercle',
  'common.lien_invalide': 'Lien invalide : le sentier s’est effacé.',
  'common.lien_invalide_ou_expire_merci_de_refaire_une_demande':
    'Lien invalide ou expiré. Refais une demande.',
  'common.lieu': 'Lieu',
  'common.lire_la_suite': 'Suivre le sentier',
  'common.modifier': 'Remodeler',
  'common.mot_de_passe': 'Parole secrète',
  'common.mot_de_passe_oublie': 'Parole égarée',
  'common.n_max_inscrits': '{n}/{max} inscrits au cercle',
  'common.nom_de_l_animal': 'Nom de l’animal',
  'common.nom_de_l_objet': 'Nom de la trouvaille',
  'common.nom_du_contenant': 'Nom du sac',
  'common.non': 'Non',
  'common.nouveau_mot_de_passe': 'Nouvelle parole secrète',
  'common.oui': 'Oui',
  'common.ouvrir_aux_joueurs': 'Ouvrir au cercle',
  'common.ouvrir_le_scenario_label': 'Ouvrir l’étape {label}',
  'common.ouvrir_le_scenario_label_info': 'Ouvrir l’étape {label} — {info}',
  'common.participants': 'Voyageurs présents',
  'common.partie_introuvable': 'Ce sentier reste introuvable.',
  'common.pas_encore_de_personnage': '(aucun compagnon éveillé)',
  'common.passer_cette_etape': 'Passer ce pas',
  'common.peut_etre': 'Peut-être',
  'common.poids': 'Poids',
  'common.precedent': 'Pas précédent',
  'common.precedent_2': '❮ Pas précédent',
  'common.prix_facultatif': 'Prix (si tu veux)',
  'common.rechercher': 'Fouiller',
  'common.reduire': 'Replier',
  'common.reessayer': 'Retenter ta chance',
  'common.refuser': 'Refuser',
  'common.reinitialiser_la_date': 'Défaire la date',
  'common.rejoindre': 'Rejoindre le cercle',
  'common.remplacer': 'Remplacer',
  'common.renoncer': 'Renoncer',
  'common.repondre_au_vote_label': 'Répondre à l’appel — {label}',
  'common.repondre_au_vote_label_detail': 'Répondre à l’appel — {label} — {detail}',
  'common.resume_de_fin': 'Récit de fin de sentier',
  'common.retirer': 'Ôter',
  'common.retour_a_la_connexion': 'Retour à l’orée de la forêt',
  'common.retour_a_la_partie': 'Retour au sentier',
  'common.revoquer': 'Faire taire',
  'common.scenario_introuvable_revenez_a_la_liste_des_brouillons':
    'Étape introuvable — reviens à la liste des Brouillons.',
  'common.seance_n': 'Séance {n}',
  'common.suivant': 'Pas suivant',
  'common.suivant_2': 'Pas suivant ❯',
  'common.supprimer': 'Arracher',
  'common.title_seance_index': '{title} — Séance {index}',
  'common.titre': 'Titre',
  'common.type': 'Forme',
  'common.une_erreur_inattendue_est_survenue_reessayez': 'Un imprévu a secoué la forêt. Réessaie.',
  'common.valider': 'Valider',
  'common.vote_cloture_sans_date_retenue': 'Cercle clos sans date choisie.',
  'common.vote_de_date': '· vote du cercle',
  'common.vue_agenda': 'Vue agenda',
  'common.vue_mois': 'Vue mois',
  'common.vue_semaine': 'Vue semaine',

  /* ═══ Authentification et invitation ═══ */
  /* — accroche de la bande — */
  'auth.tagline': 'Un feu de camp, des amis, et une date qui arrange tout le monde',
  /* — connexion — */
  'auth.login_invalid': 'Le carnet ne te reconnaît pas : identifiants invalides.',
  'auth.login_reset_required':
    'Ce compte doit être réinitialisé : utilise « Parole égarée ? » pour rouvrir le carnet.',
  'auth.login_throttled': 'Trop de tentatives. Patiente une minute avant de retenter ta chance.',
  'auth.login_unavailable':
    'Le carnet est indisponible pour le moment. Réessaie dans quelques instants.',
  'auth.login_unexpected': 'Une erreur est survenue. Réessaie.',
  'auth.login_invite_only': 'On n’entre dans la forêt que sur invitation.',
  'auth.login_identifier_label': 'Adresse du hibou ou nom de sentier',
  'auth.login_submit': 'Se connecter à la forêt',
  'auth.login_forgot_link': 'Parole égarée ?',
  /* — validation des champs — */
  'auth.field_required': 'Renseignez ce champ.',
  'auth.field_email_invalid': 'Adresse e-mail invalide.',
  'auth.field_pseudo_min': '3 caractères minimum.',
  'auth.field_password_min': '8 caractères minimum.',
  /* — révélation du mot de passe — */
  'auth.password_show': 'Afficher le mot de passe',
  'auth.password_hide': 'Masquer le mot de passe',
  /* — inscription — */
  'auth.register_invite_only':
    'L’inscription se fait uniquement sur invitation. Ouvre un lien d’invitation pour créer ta place dans la forêt.',
  'auth.register_pseudo_label': 'Nom de sentier',
  'auth.register_submit': 'Rejoindre la forêt',
  'auth.register_error':
    'Le compte n’a pas pu être créé (lien invalide, ou adresse ou nom de sentier déjà pris ?).',
  /* — mot de passe oublié et réinitialisation — */
  'auth.forgot_sent':
    'Si un compte existe pour cette adresse, un hibou est parti avec le lien de réinitialisation.',
  'auth.forgot_submit': 'Lâcher le hibou',
  'auth.forgot_error': 'La demande n’est pas partie pour le moment. Réessaie plus tard.',
  'auth.reset_submit': 'Changer de parole',
  'auth.reset_redo_link': 'Redemander un hibou',
  /* — changement d’adresse e-mail — */
  'auth.confirm_email_title': 'Confirmer la nouvelle adresse du hibou',
  'auth.confirm_email_done': 'Le hibou connaît ta nouvelle adresse e-mail.',
  'auth.rollback_email_title': 'Annuler le changement d’adresse du hibou',
  'auth.rollback_done':
    'Ton ancienne adresse est de retour : toutes les sessions actives ont été coupées.',
  'auth.rollback_continue_btn': 'Continuer vers le choix d’une nouvelle parole',
  'auth.rollback_warning':
    'Remettre ton ancienne adresse coupera toutes les sessions actives et te fera choisir une nouvelle parole avant toute reconnexion.',
  'auth.rollback_submit': 'Remettre mon ancienne adresse',
  'auth.rollback_error': 'Lien invalide ou expiré : le sentier est effacé.',
  /* — lien d’invitation — */
  'join.not_found_title': 'Sifflet introuvable',
  'join.not_found_text': 'Ce sifflet d’invitation n’existe pas.',
  'join.title': 'Rejoindre le sentier « {name} »',
  'join.logged_as': 'Tu es connecté sous le nom de',
  'join.login_or_register': 'Connecte-toi ou crée un compte pour rejoindre ce sentier.',
  'join.join_error':
    'Impossible de rejoindre ce sentier (lien invalide, expiré, ou déjà dans le cercle).',

  /* ═══ Compte ═══ */
  /* — profil, mot de passe et e-mail — */
  'account.title': 'Mon carnet de route',
  'account.pseudo_label': 'Nom de sentier',
  'account.email_label': 'Adresse du hibou',
  'account.display_name_label': 'Nom porté aux yeux du cercle',
  'account.cancel_btn': 'Abandonner',
  'account.saved': 'Le carnet a retenu ce nom.',
  'account.error': "Le carnet n'a pas pu retenir ce changement. Réessaie.",
  'account.password_title': 'Changer ta parole secrète',
  'account.current_password_label': 'Parole secrète actuelle',
  'account.new_password_label': 'Nouvelle parole secrète',
  'account.password_save_btn': 'Changer',
  'account.password_saved': 'Ta parole secrète a été changée.',
  'account.password_wrong_current': 'Ce n’est pas la bonne parole secrète.',
  'account.password_error': 'Le carnet n’a pas pu changer ta parole secrète. Réessaie.',
  'account.current_password_for_email_label': 'Parole secrète actuelle',
  'account.new_email_label': 'Nouvelle adresse du hibou',
  'account.email_change_save_btn': 'Lâcher le hibou',
  'account.email_change_saved': 'Un hibou est parti vers la nouvelle adresse.',
  'account.email_change_wrong_current': 'Ce n’est pas la bonne parole secrète.',
  'account.email_change_taken': 'Cette adresse est déjà prise par un autre voyageur.',
  'account.email_change_error': "Le carnet n'a pas pu envoyer la demande. Réessaie.",
  'account.appearance_label': 'Apparence de la forêt',
  /* — calendrier du compte — */
  'account.calendar_layers_title': 'Ce que montre mon calendrier',
  // Couches et intentions du calendrier : verbatim du contrat d’UI (story 36.14), volontairement identiques.
  'account.calendar_layer.mes-indisponibilites': 'Mes indisponibilités',
  'account.calendar_layer.mes-disponibilites': 'Mes disponibilités',
  'account.calendar_layer.mes-seances': 'Mes séances confirmées',
  'account.calendar_layer.votes-en-cours': 'Les votes en cours',
  'account.calendar_layer.inscriptions-ouvertes': 'Les inscriptions ouvertes',
  'account.calendar_layer.disponibilite-groupe': 'La disponibilité du groupe',
  'account.calendar_intents_subtitle': 'Ce que je veux voir en arrivant dans la forêt.',
  'account.calendar_intent.disponibilites': 'Mes disponibilités & indisponibilités',
  'account.calendar_intent.seances': 'Mes séances confirmées',
  'account.calendar_intent.votes': 'Les votes en cours',
  'account.calendar_intent.groupe': 'La disponibilité du groupe',
  /* — identité et homonymie — */
  'identity.character_label': 'Compagnon',
  'identity.player_label': 'Voyageur',
  'identity.homonymy_warning': 'Un autre voyageur de ce sentier porte le même nom affiché que toi.',
  'identity.homonymy_change_cta': 'Choisir un autre nom',
  'identity.homonymy_ignore_cta': 'Laisser tel quel',

  /* ═══ Tableau de bord ═══ */
  /* — tableau de bord — */
  'dashboard.title_invitations': 'Appels de la forêt',
  'dashboard.empty': 'Aucune clairière ouverte. Plante le premier feu…',
  'dashboard.role_prefix': 'Voie :',
  'dashboard.role_mj': 'Guide',
  'dashboard.role_player': 'Voyageur',
  'dashboard.status_closed_badge': 'Achevé',
  'dashboard.section_awaiting': 'Ce qui t’attend',
  'dashboard.section_ongoing': 'En route',
  'dashboard.section_upcoming': 'À l’horizon',
  'dashboard.section_finished': 'Achevées',
  'dashboard.empty_filtered': 'Aucun sentier ne répond à ces critères.',
  'dashboard.filter_role_label': 'Voie',
  'dashboard.filter_role_all': 'Toutes les voies',
  'dashboard.filter_status_label': 'Stade',
  'dashboard.filter_status_all': 'Tous les stades',
  'dashboard.sort_urgence': 'Ce qui presse',
  'dashboard.sort_date': 'Date de clairière',
  'dashboard.sort_nom': 'Nom du sentier',
  'dashboard.sort_type': 'Forme',
  'dashboard.sort_statut': 'Stade',
  'dashboard.hide_finished_label': 'Masquer les sentiers achevés',
  'dashboard.show_finished_btn': 'Afficher les sentiers achevés',
  'dashboard.favorite_add_aria': 'Marquer d’une encoche (favori)',
  'dashboard.favorite_remove_aria': 'Retirer l’encoche (favori)',
  'dashboard.search_label': 'Rechercher un sentier',
  'dashboard.row_signal_count_aria': '{n} chose(s) à faire',
  'dashboard.invitation_invited_by': 'appelé par {pseudo}',

  /* ═══ Parties ═══ */
  /* — formulaire de partie — */
  'partie.new_title': 'Nouveau sentier',
  'partie.edit_title': 'Rebattre le sentier',
  'partie.save_btn': 'Planter',
  'partie.cancel_btn': 'Rebrousser chemin',
  'partie.name_label': 'Nom du sentier',
  'partie.system_label': 'Règles du jeu',
  'partie.kind_label': 'Nature du sentier',
  'partie.description_label': 'Premiers pas (facultatif)',
  'partie.kind_ONE_SHOT': 'Sentier court',
  'partie.kind_CAMPAGNE_LINEAIRE': 'Longue marche',
  'partie.kind_CAMPAGNE_EPISODIQUE': 'Longue marche par étapes',
  'partie.kind_refusal_closed': 'Ce sentier est refermé. Rouvre-le avant d’en changer la nature.',
  'partie.kind_refusal_too_many_scenarios':
    'Ce sentier compte {count} étapes ; un sentier court n’en a qu’une.',
  'partie.courant_choice_title': 'Quelle étape reste en cours ?',
  'partie.courant_choice_help':
    'Une longue marche ne suit qu’une étape à la fois. Les autres redeviendront « à venir » — leurs séances et leurs dates sont conservées.',
  'partie.courant_choice_confirm': 'Prendre ce chemin',
  'partie.cover_add': 'Donner un visage au sentier',
  'partie.cover_change': 'Changer l’image',
  'partie.cover_remove': 'Retirer l’image',
  'partie.cover_uploading': 'L’image prend racine…',
  'partie.cover_upload_error': 'L’image n’a pu prendre racine. Réessaie.',
  'partie.cover_remove_error': 'L’image n’a pu être retirée. Réessaie.',
  'partie.cover_reject_type': 'Seules les images JPEG, PNG et WEBP peuvent être plantées ici.',
  'partie.cover_reject_size': 'Cette image dépasse 5 Mo : choisis-en une plus légère.',
  'partie.save_error': 'Ce sentier n’a pu être tracé. Réessaie.',
  'partie.created_but_cover_failed':
    'Le sentier est bien tracé, mais son image n’a pu prendre racine. Tu peux la redéposer ici.',
  'partie.fields_saved_but_convert_failed':
    'Les autres changements sont enregistrés, mais la nature du sentier n’a pu être changée. Réessaie.',
  /* — détail de partie — */
  'partie.scheduling_title': 'Prochaine clairière',
  'partie.no_session': "Aucune clairière réservée. L'écureuil cherche encore.",
  'partie.members_title': '🌿 Habitants',
  'partie.no_members': 'Aucun habitant de la clairière.',
  'partie.remove_member_btn': 'Renvoyer',
  'partie.no_description': 'La forêt garde ses secrets.',
  'partie.invite_title': 'Appeler depuis la forêt',
  'partie.search_label': 'Nom ou espèce connue',
  'partie.search_btn': 'Fouiller',
  'partie.invite_btn': 'Accueillir',
  'partie.links_title': 'Sifflets de rappel',
  'partie.generate_link': 'Tisser un laissez-passer',
  'partie.notice_invited': 'Sifflet envoyé à {name}.',
  'partie.invite_by_email_label': 'Adresse du hibou destinataire',
  'partie.invite_by_email_btn': 'Envoyer un sifflet',
  'partie.notice_invited_email': 'Sifflet envoyé à {email}.',
  'partie.notice_invite_email_error': 'Le sifflet s’est perdu dans le vent. Réessaie.',
  'partie.reference_sheets_title': 'Grimoires de la clairière',
  // Noms des fiches de référence et de préparation Ryuutama : vocabulaire du système de jeu, identique.
  'partie.asset_journal_cta': 'Journal',
  'partie.asset_carte_cta': 'Carte',
  'partie.asset_download_error': 'Le grimoire s’est enraciné trop profond. Réessaie.',
  'partie.prep_sheets_title': 'Grimoires de préparation (Guide)',
  'partie.asset_monde_cta': 'Monde',
  'partie.asset_monstre_cta': 'Monstre',
  'partie.asset_ville_cta': 'Ville',
  'partie.asset_objectif_chasse_cta': 'Objectif — Chasse',
  'partie.asset_objectif_quete_cta': 'Objectif — Quête',
  'partie.asset_objectif_voyage_cta': 'Objectif — Voyage',
  'partie.asset_oeuf_de_bataille_cta': 'Œuf de bataille',
  'partie.asset_structure_cta': 'Structure',
  'partie.notice_copy': 'Laissez-passer copié dans la gibecière.',
  'partie.edit_btn': 'Rebattre',
  'partie.visibility_btn': 'Voiler des secrets',
  'partie.close_btn': 'Achever le sentier',
  'partie.reopen_btn': 'Reprendre la route',
  'partie.status_closed_label': 'Ce sentier est achevé.',
  'partie.delete_btn': 'Effacer le sentier',
  'partie.invitations_tab_label': 'Appels',
  /* — zones de l’onglet Détails — */
  // Noms CONTRACTUELS des trois zones (Action / Consultation / Référence) : catégories nommées par l’épic,
  // identiques dans les trois thèmes.
  'partie.details_zone_action': 'Action',
  'partie.details_zone_consultation': 'Consultation',
  'partie.details_zone_reference': 'Référence',
  /* — signaux d’état — */
  'partie.signal_personnage_a_creer': 'Façonner son compagnon',
  'partie.signal_vote_en_cours_sans_reponse': 'Réponds à l’appel du vote',
  'partie.signal_compte_rendu_non_redige': 'Récit à graver',
  'partie.signal_homme_dragon_a_creer': 'Façonner son Homme Dragon',
  'partie.signal_aucun_membre_invite': 'Aucun voyageur convié',
  'partie.signal_aucun_scenario_en_cours': 'Aucun sentier en cours',
  'partie.signal_aucune_date_ni_vote': 'Aucune date ni cercle réuni',
  'partie.signal_rapport_fin_manquant': 'Récit de fin manquant',
  'partie.signal_prochaine_seance_connue': 'Prochaine clairière connue',
  'partie.signal_partie_terminee': 'Sentier achevé',
  'partie.signal_more_count': '+{n}',
  /* — états de scénario et de séance — */
  // Noms d’état CONTRACTUELS, IDENTIQUES dans les trois thèmes (story 32.3).
  // « Courant », JAMAIS « En cours » : « en cours » est réservé au VOTE.
  // La paire vote répondu / non répondu porte DEUX libellés distincts (EXPERIENCE.md §5) : la teinte ne
  // doit jamais être la seule différence.
  'status.scenario_brouillon': 'Brouillon',
  'status.scenario_a_venir': 'À venir',
  'status.scenario_courant': 'Courant',
  'status.scenario_passe': 'Passé',
  'status.seance_a_planifier': 'À planifier',
  'status.seance_answer_poll': 'Réponds au vote',
  'status.seance_poll_open': 'Vote en cours',
  'status.seance_inscriptions_ouvertes': 'Inscriptions ouvertes',
  'status.seance_programmee': 'Programmée',
  'status.seance_a_debriefer': 'À débriefer',
  'status.seance_jouee': 'Jouée',
  /* — confidentialité — */
  'parties.confirm_title': 'Ton accord',
  'parties.locks_title': 'Confidentialité de la forêt',
  'parties.locks_load_partie_error':
    'Les informations du sentier n’ont pas pu être chargées. Réessaie.',
  'parties.locks_load_schema_error':
    'Le schéma des règles du jeu n’a pas pu être chargé. Réessaie.',
  'parties.locks_save_error': 'La configuration n’a pas pu être gravée. Réessaie.',
  'parties.locks_access_denied':
    'Accès refusé : seul le Guide de ce sentier peut configurer la confidentialité.',
  'parties.locks_help':
    'Coche les éléments de fiche à voiler aux voyageurs (hors Guide et propriétaire du compagnon). L’enregistrement remplace l’ensemble des verrous actuels de ce sentier.',
  'parties.locks_empty': 'Ces règles du jeu ne laissent rien à voiler.',
  /* — onglets, effectif et liens — */
  'parties.detail_polls_in_progress': '{count} appels de date en cours',
  'parties.detail_remove_member_confirm': 'Renvoyer {name} du sentier « {partie} » ?',
  'parties.detail_delete_confirm':
    'Effacer le sentier « {partie} » ? Cette action est irréversible.',
  'parties.detail_link_expires_short': 'exp.',
  'parties.detail_tab_details': 'Aperçu',
  'parties.detail_tab_scenario': 'Étape',
  'parties.detail_tab_scenarios': 'Étapes',
  'parties.detail_tab_timeline': 'Parcours',
  'parties.roster_aria_levelup': '{label} — prêt à grandir',
  'parties.roster_aria_role': '{label} — place dans le cercle : {role}',
  'parties.roster_aria_mj': '{name} — Guide',
  'parties.roster_aria_no_character': '{name} — aucun compagnon éveillé',
  'parties.roster_aria_character': '{name} — {character}',
  'parties.roster_aria_character_class': '{name} — {character} ({class})',
  'parties.roster_aria_create': '{name} — {action}',
  /* — distribution d’XP — */
  'evolution.xp_distribute_cta': 'Partager les récits',
  'evolution.xp_panel_title': 'Partage des récits',
  'evolution.xp_history_title': 'Récits partagés',
  'evolution.xp_history_empty': "Aucun récit partagé pour l'instant.",
  'evolution.xp_note_label': 'Note du récit',
  'evolution.xp_confirm_btn': 'Confier ce récit au cercle',
  'evolution.xp_bonus_link': '+ éclat',
  'evolution.xp_levelup_warning': '{name} va grandir',
  'parties.xp_suggested': 'Part suggérée : {amount} XP',
  'parties.xp_current': '{xp} XP récoltés jusqu’ici',
  'parties.xp_amount_label': 'Part',
  'parties.xp_select_one_error': 'Choisis au moins un compagnon avant de partager.',
  'parties.xp_distribute_error': 'Le partage n’a pas pu être gravé. Réessaie.',
  'parties.xp_rules_title': 'Calcul des anciens',
  'parties.xp_history_unknown_character': 'Compagnon inconnu',
  'parties.xp_history_bonus_badge': 'éclat',

  /* ═══ Scénarios et séances ═══ */
  /* — formulaire et scénario unique — */
  'scenarios.fill_label': '{count} / {max} inscrits au cercle (min. {min})',
  'scenarios.form_title': 'Nouvelle étape',
  'scenarios.form_description_label': 'Premiers mots (facultatif)',
  'scenarios.form_duree_heures_label': 'Durée de la marche en heures (facultatif)',
  'scenarios.form_duree_seances_label': 'Durée de la marche en séances (facultatif)',
  'scenarios.form_save_error': 'L’étape n’a pas pu être gravée.',
  'scenarios.one_shot_not_found': 'Aucune étape trouvée sur ce sentier.',
  'scenarios.one_shot_open_error': 'L’étape n’a pas pu être ouverte au cercle. Réessaie.',
  /* — liste et chronologie — */
  'scenarios.list_title': 'Étapes',
  'scenarios.list_new_button': '+ Nouvelle étape',
  'scenarios.timeline_title': 'Parcours',
  'scenarios.timeline_load_error': 'Le parcours reste introuvable. Réessaie.',
  'scenarios.timeline_count_one': '{n} étape',
  'scenarios.timeline_count_many': '{n} étapes',
  'scenarios.timeline_not_planned': 'Pas encore tracé',
  'scenarios.timeline_since': 'en route depuis le {date}',
  'scenarios.timeline_from': 'dès le {date}',
  /* — séances — */
  'scenarios.seances_delete_button': 'Arracher cette séance',
  'scenarios.seances_min_aria': 'Nombre minimum de voyageurs inscrits',
  'scenarios.seances_max_aria': 'Nombre maximum de voyageurs inscrits',
  'scenarios.seances_set_capacity': 'Fixer la taille du cercle',
  'scenarios.seances_edit_capacity': 'Changer la taille du cercle',
  'scenarios.seances_desinscrire': 'Me retirer de la clairière',
  'scenarios.seances_inscrire': 'Rejoindre la clairière',
  'scenarios.seances_heure_malformed':
    '⚠️ Valeur gardée non reconnue ("{raw}"), champ laissé vide — graver sans la corriger l\'effacera.',
  'scenarios.seances_lieu_placeholder': 'sous le grand chêne, chez Marc…',
  'scenarios.seances_note_placeholder': 'pense aux dés et à la lanterne…',
  'scenarios.seances_save_infos': 'Graver les informations pratiques',
  'scenarios.seances_compte_rendu_placeholder': 'Récit de la séance…',
  'scenarios.seances_compte_rendu_aria': 'Récit de la séance',
  'scenarios.seances_save_compte_rendu': 'Graver le récit',
  'scenarios.seances_compte_rendu_empty': 'Aucun récit pour cette séance pour le moment.',
  'scenarios.seances_choose_error': 'Cette date n’a pas pu être choisie. Réessaie.',
  'scenarios.seances_capacity_error': 'La taille du cercle n’a pas pu être fixée. Réessaie.',
  'scenarios.seances_inscrire_error': 'Tu n’as pas pu rejoindre la clairière. Réessaie.',
  'scenarios.seances_desinscrire_error': 'Tu n’as pas pu te retirer de la clairière. Réessaie.',
  'scenarios.seances_delete_error': 'Cette séance n’a pas pu être arrachée. Réessaie.',
  'scenarios.seances_reset_error': 'La date n’a pas pu être défaite. Réessaie.',
  'scenarios.seances_infos_error':
    'Les informations pratiques n’ont pas pu être gravées. Réessaie.',
  'scenarios.seances_compte_rendu_error': 'Le récit n’a pas pu être gravé. Réessaie.',
  'scenarios.seances_refresh_error':
    'Action faite, mais l’affichage ne s’est pas rafraîchi. Recharge la page.',
  'scenarios.seances_delete_confirm_dated':
    'Cette séance a une date choisie. L’arracher quand même ? Cette action est définitive.',
  'scenarios.seances_delete_confirm': 'Arracher cette séance ? Cette action est définitive.',
  'scenarios.seances_reset_confirm':
    'Défaire la date de cette séance ? Un nouveau cercle pourra être réuni.',
  /* — lecture du scénario — */
  'scenarios.read_resume_empty': 'Aucun récit de fin pour l’instant.',
  'scenarios.read_resume_edit': 'Remodeler le récit de fin',
  'scenarios.read_resume_write': 'Graver le récit de fin',
  'scenarios.read_journal_title': 'Carnet associé',
  'scenarios.read_auto_associate': 'Rattachement automatique',
  'scenarios.read_note_shared_aria': 'Note partagée avec le cercle',
  'scenarios.read_note_private_aria': 'Note privée, gardée pour toi',
  'scenarios.read_note_private_hint':
    'Note privée — déverrouille-la (🔒) pour qu’elle apparaisse dans la rétrospective.',
  'scenarios.read_journal_empty': 'Tu n’as encore rien gravé dans ton carnet.',
  'scenarios.read_retrospective_title': 'Carnet de la rétrospective',
  'scenarios.read_participate': 'Se joindre à cette étape',
  'scenarios.read_journal_load_error': 'Ton carnet ne s’ouvre pas.',
  'scenarios.read_participate_error': 'Tu n’as pas pu te joindre à cette étape.',
  'scenarios.read_setting_error': 'Ce réglage n’a pas pu être remodelé.',
  'scenarios.read_note_visibility_error': 'La visibilité de cette note n’a pas pu être remodelée.',
  'scenarios.read_note_association_error': 'Ce rattachement n’a pas pu être mis à jour.',
  /* — éditeur du scénario — */
  'scenarios.editor_pencil_title': 'le titre de l’étape',
  'scenarios.editor_pencil_duree_heures': 'la durée de la marche en heures',
  'scenarios.editor_pencil_duree_seances': 'la durée de la marche en séances',
  'scenarios.editor_mark_courant': 'Marquer comme Courant',
  'scenarios.editor_close': 'Achever cette étape',
  'scenarios.editor_add_seance': 'Ouvrir une séance',
  'scenarios.editor_resume_empty_hint':
    'Aucun récit de fin pour l’instant — rédige-le pour clore la rétrospective.',
  'scenarios.editor_save_resume': 'Graver le récit de fin',
  'scenarios.editor_no_participants': 'Aucun voyageur pour l’instant.',
  'scenarios.editor_documents_title': 'Feuilles de l’étape',
  'scenarios.editor_library_title': 'Réserve de la longue marche',
  'scenarios.editor_library_doc_suffix': '— réserve de la longue marche',
  'scenarios.editor_documents_load_error': 'Les feuilles restent introuvables. Réessaie.',
  'scenarios.editor_participants_load_error':
    'La liste des voyageurs n’a pas pu être chargée. Réessaie.',
  'scenarios.editor_upload_error': 'La feuille n’a pas pu être déposée. Réessaie.',
  'scenarios.editor_mark_courant_error': 'Cette étape n’a pas pu être marquée Courant.',
  'scenarios.editor_close_error': 'Cette étape n’a pas pu être achevée.',
  'scenarios.editor_add_seance_error': 'La séance n’a pas pu être ouverte.',
  'scenarios.editor_resume_save_error': 'Le récit de fin n’a pas pu être gravé.',
  'scenarios.editor_download_error': 'La feuille n’a pas pu être récupérée.',

  /* ═══ Calendrier ═══ */
  /* — barre d’affichage et légende — */
  // Barre d’affichage et légende : verbatim du contrat d’UI (story 36.14), identiques sauf là où un
  // pronom impose le vouvoiement ou le tutoiement du thème.
  'calendar.display.trigger': 'Affichage',
  'calendar.display.trigger_aria': 'Régler l’affichage du calendrier lunaire',
  'calendar.display.section_visible': 'Ce que je vois',
  'calendar.display.show_legend': 'Afficher la légende',
  'calendar.display.filtered_badge': 'Affichage filtré · {n} sur {total} · Rétablir',
  'calendar.legend.title': 'Légende des sentes',
  'calendar.legend.group_obvious': 'Se lisent sans effort',
  'calendar.legend.group_needs': 'Demandent la légende',
  'calendar.legend.entry.available': 'Je suis disponible',
  'calendar.legend.entry.unavailable': 'Je suis indisponible',
  'calendar.legend.entry.seance': 'Séance confirmée — tu es pris',
  'calendar.legend.entry.vote': 'Créneau proposé au vote',
  'calendar.legend.entry.poll_track': 'Participation : la piste = le cercle',
  'calendar.legend.entry.group': 'Disponibilité du groupe',
  'calendar.legend.entry.none': 'Personne ne s’est prononcé',
  /* — agenda — */
  'calendar.agenda.section_awaiting': 'Ce qui t’attend',
  'calendar.agenda.section_scheduled': 'Ce qui est prévu',
  'calendar.agenda.section_past': 'Ce qui est derrière',
  // Badges d’état de l’Agenda : CONTRACTUELS et identiques (EXPERIENCE.md §5, paire « Réponds au vote » / « Vote en cours »).
  'calendar.agenda.badge_answer_poll': 'Réponds au vote',
  'calendar.agenda.badge_poll_open': 'Vote en cours',
  'calendar.agenda.badge_signup': 'S’inscrire',
  'calendar.agenda.badge_signed_up': 'Inscrit',
  'calendar.agenda.badge_debrief': 'Débriefer',
  'calendar.agenda.empty': 'Rien ne t’attend, rien n’est prévu.',
  'calendar.agenda.badge_to_seal': 'À sceller',
  'calendar.agenda.poll_open': 'Cercle réuni',
  'calendar.agenda.responded_count': '{n} sur {total} habitants ont répondu',
  'calendar.agenda.slots_proposed': '{n} clairières proposées',
  'calendar.agenda.missing_voters': 'manquent encore : {names}',
  'calendar.agenda.no_date': 'date à choisir',
  'calendar.agenda.no_date_proposed': 'Aucune clairière proposée',
  'calendar.agenda.action_launch_poll': 'Réunir le cercle',
  'calendar.agenda.action_seal': 'Planter',
  'calendar.agenda.action_expand': 'Déployer',
  'calendar.agenda.action_collapse': 'Resserrer',
  'calendar.agenda.seal_confirm_title': 'Planter le drapeau sur ce créneau ?',
  'calendar.agenda.seal_confirm_body':
    'La séance se tiendra à ce créneau et le vote se refermera. Les autres créneaux proposés disparaîtront.',
  'calendar.agenda_missing_more_one': '{listed} et {rest} autre voyageur',
  'calendar.agenda_missing_more_many': '{listed} et {rest} autres voyageurs',
  /* — vue calendrier (navigation, composition, chargement) — */
  'calendar.agg_counts_aria': 'Disponibilités de la forêt',
  'calendar.agg_available_title': 'Disponibles',
  'calendar.agg_unknown_title': 'Inconnus',
  'calendar.agg_unavailable_title': 'Indisponibles',
  'calendar.slots_list_aria': 'Clairières disponibles',
  'calendar.rail_empty': 'Aucun jour à explorer',
  'calendar.rail_status_unknown': 'Rien de prévu',
  'calendar.layer_group_aria': 'Couches affichées du calendrier lunaire',
  'calendar.view_back': '← Retour',
  'calendar.view_compose_arm': 'Marquer des dates',
  'calendar.view_toggle_aria': 'Vue du calendrier lunaire',
  'calendar.view_toggle_month_short': 'Mois',
  'calendar.view_toggle_week_short': 'Sem.',
  'calendar.view_toggle_agenda_short': 'Agenda',
  'calendar.view_no_poll': 'Aucun cercle de date en cours.',
  'calendar.view_locked_seance_hint':
    'L’appel de la séance sélectionnée se lance depuis la fiche de l’étape.',
  'calendar.view_group_label': '{slot} — {available}/{total} voyageurs disponibles',
  'calendar.view_group_unavailable_detail': '{n} indisponible(s)',
  'calendar.view_compose_target_poll': 'Clairières du cercle : {label}',
  'calendar.view_compose_target_new': 'Clairières d’un nouveau cercle',
  'calendar.view_compose_blocked_min': 'Un cercle demande au moins deux clairières.',
  'calendar.view_compose_blocked_max': 'Quarante clairières au maximum.',
  'calendar.view_compose_blocked_no_seance':
    'Aucune séance n’attend de cercle : un cercle se rattache toujours à une séance.',
  'calendar.view_compose_stale_voters':
    'Une nouvelle réponse est arrivée depuis l’avertissement — revalide pour voir le chiffre à jour.',
  'calendar.view_compose_save_error': 'Ces clairières n’ont pas pu être marquées. Réessaie.',
  'calendar.view_batch_conflict_labels':
    'Ces clairières se contredisent entre elles ({labels}). Rien n’a été marqué.',
  'calendar.view_batch_conflict_plain':
    'Ces clairières se contredisent entre elles. Rien n’a été marqué.',
  'calendar.view_conflict_in_progress':
    'Un conflit est déjà en cours de résolution. Termine-le avant de recommencer.',
  'calendar.view_cell_unknown': 'Clairière inconnue',
  'calendar.view_selection_none': 'sur aucune clairière',
  'calendar.view_selection_one': 'le {cell}',
  'calendar.view_selection_many': 'sur {n} clairières, du {from} au {to}',
  'calendar.view_seal_error': 'Cette clairière n’a pas pu être plantée. Réessaie.',
  'calendar.view_range_error': 'La date de début doit être avant ou égale à la date de fin.',
  'calendar.view_load_declarations_error': 'Les disponibilités restent introuvables.',
  'calendar.view_load_slots_error': 'Les clairières restent introuvables.',
  'calendar.view_load_calendar_error':
    'Le calendrier lunaire reste introuvable pour cette période.',
  /* — vue mois — */
  'calendar.month_prev_aria': 'Lune précédente',
  'calendar.month_next_aria': 'Lune suivante',
  'calendar.month_today_aria': 'Revenir à la lune actuelle',
  'calendar.month_cell_instructions':
    "Espace : sélectionner la journée entière. Touches 1, 2, 3 : sélectionner respectivement le matin, l'après-midi ou le soir. Maj plus flèches : étendre la sélection. Entrée : valider la sélection avec ce qu'affiche la barre. Échap : annuler.",
  'calendar.month_day_today_aria': "{day} (aujourd'hui)",
  'calendar.month_status_unknown': 'non marqué',
  /* — vue semaine — */
  'calendar.week_decl_available': 'Dispo',
  'calendar.week_decl_punctual': 'Ponctuel',
  'calendar.week_decl_recurring': 'Récurrent',
  'calendar.week_decl_unavailable': 'Indispo',
  'calendar.week_next_aria': 'Semaine suivante dans la forêt',
  'calendar.week_prev_aria': 'Semaine précédente dans la forêt',
  'calendar.week_status_available': 'disponible',
  'calendar.week_status_unavailable': 'indisponible',
  'calendar.week_status_unknown': 'inconnu',
  'calendar.week_today_aria': 'Revenir à la semaine d’aujourd’hui',
  /* — mots d’état et de participation — */
  'calendar.util_answer_yes': 'oui',
  'calendar.util_answer_maybe': 'peut-être',
  'calendar.util_answer_no': 'non',
  'calendar.util_answer_mine': 'tu as dit {answer}',
  'calendar.util_participation_one': '{n} réponse récoltée sur {total}',
  'calendar.util_participation_many': '{n} réponses récoltées sur {total}',
  'calendar.util_group_aria_one': 'Disponibilité du cercle : {available} sur {total} disponible',
  'calendar.util_group_aria_many': 'Disponibilité du cercle : {available} sur {total} disponibles',
  'calendar.util_group_all_blocked': 'tout le cercle est empêché',
  'calendar.util_group_nobody': "personne ne s'est prononcé",
  'calendar.util_group_unavailable_one': '{n} indisponible',
  'calendar.util_group_unavailable_many': '{n} indisponibles',
  'calendar.util_word_no_answer': 'sans réponse',
  'calendar.util_counter': '{n} / {total}',
  /* — barre de sélection — */
  'calendar.selbar_announcement': 'Portée : {scope}. Entrée marquera : {kind}.',
  'calendar.selbar_count_many': '{n} clairières sélectionnées',
  'calendar.selbar_count_one': '{n} clairière sélectionnée',
  'calendar.selbar_other': 'Autre chemin…',
  'calendar.selbar_scope_aria': 'Étendue de la sélection dans la forêt',
  'calendar.selbar_toolbar_aria': 'Actions de la forêt sur la sélection',
  /* — panneau de contraintes — */
  'calendar.constraint_all_occurrences': 'Toutes les répétitions',
  'calendar.constraint_close_aria': 'Fermer le panneau de la clairière',
  'calendar.constraint_conflict_prompt':
    'Des disponibilités contradictoires sont déjà marquées pour cette période.',
  'calendar.constraint_delete_error': 'La contrainte n’a pas pu être arrachée.',
  'calendar.constraint_end_date': 'Date de fin',
  'calendar.constraint_expires_on': 'Se fane le',
  'calendar.constraint_from_this_day': 'À partir de ce jour, jusqu’au bout',
  'calendar.constraint_keep_existing': 'Laisser l’existant',
  'calendar.constraint_kind_aria': 'Disponibilité',
  'calendar.constraint_modify_error': 'La contrainte n’a pas pu être remodelée.',
  'calendar.constraint_occurrence_delete_error': 'L’occurrence n’a pas pu être arrachée.',
  'calendar.constraint_occurrence_modify_error': 'L’occurrence n’a pas pu être remodelée.',
  'calendar.constraint_overwrite': 'Écraser',
  'calendar.constraint_recurring_delete_prompt':
    'Cette contrainte est récurrente. Que veux-tu arracher ?',
  'calendar.constraint_recurring_modify_prompt':
    'Cette contrainte est récurrente. Que veux-tu remodeler ?',
  'calendar.constraint_start_date': 'Date de début',
  'calendar.constraint_type_punctual': 'Cette clairière seulement',
  'calendar.constraint_type_range': 'Sentier de dates',
  'calendar.constraint_type_recurring': 'Récurrent (comme la lune, chaque semaine)',
  'calendar.constraint_whole_series': 'Toute la série',
  /* — boîte de conflit — */
  'calendar.conflict_exception_detail':
    "Tu y as une séance. Aucun de ces choix n'y touche. Si elle est annulée, tu redeviens {kind}.",
  'calendar.conflict_exception_many': 'ne sont pas dans la liste',
  'calendar.conflict_exception_one': "n'est pas dans la liste",
  'calendar.conflict_free_many': 'Les {n} autres basculent en {kind}',
  'calendar.conflict_free_none': 'Rien d’autre n’est marqué',
  'calendar.conflict_free_one': 'Le 1 autre bascule en {kind}',
  'calendar.conflict_intent_prefix': 'Tu déclares',
  'calendar.conflict_keep_many': 'Ces {n} restent comme ils sont',
  'calendar.conflict_keep_one': 'Ce créneau reste comme il est',
  'calendar.conflict_step_announcement': 'Clairière {progress} : {label}. Remplacer ou conserver ?',
  'calendar.conflict_title_many': '{n} clairières sont déjà marquées',
  'calendar.conflict_title_one': '1 clairière est déjà marquée',
  'calendar.conflict_walkthrough_body': 'On les passe en revue un par un',
  'calendar.conflict_walkthrough_count_many': '{n} décisions à prendre',
  'calendar.conflict_walkthrough_count_one': '{n} décision à prendre',
  'calendar.conflict_walkthrough_label': 'Au cas par cas',
  'calendar.conflict_kind_available': 'disponible',
  'calendar.conflict_kind_unavailable': 'indisponible',
  'calendar.conflict_overwrite_available_one': 'Le créneau devient disponible',
  'calendar.conflict_overwrite_available_many': 'Les {n} deviennent disponibles',
  'calendar.conflict_overwrite_unavailable_one': 'Le créneau devient indisponible',
  'calendar.conflict_overwrite_unavailable_many': 'Les {n} deviennent indisponibles',
  /* — composition des créneaux d’un vote — */
  'calendar.card_alerts_aria': 'Signaux de disponibilité de la forêt',
  'calendar.card_full_guild': 'Cercle au complet',
  'calendar.card_members_aria': 'Habitants',
  'calendar.compose_bar_aria': 'Composition des clairières d’un cercle',
  'calendar.compose_confirm_note':
    'Les réponses portées par les clairières conservées ne sont pas touchées.',
  'calendar.compose_confirm_responses_many': '{n} réponses',
  'calendar.compose_confirm_responses_one': '{n} réponse',
  'calendar.compose_confirm_seance_label': 'Pour quelle séance ?',
  'calendar.compose_confirm_seance_placeholder': 'Choisir une séance…',
  'calendar.compose_confirm_slots_many': '{n} clairières',
  'calendar.compose_confirm_slots_one': '{n} clairière',
  'calendar.compose_confirm_summary_many': '{n} clairières proposées.',
  'calendar.compose_confirm_summary_one': '{n} clairière proposée.',
  'calendar.compose_confirm_title_modify': 'Remodeler les clairières du cercle',
  'calendar.compose_confirm_warning_many': 'Retirer {slots} arrachera {votes} déjà posées.',
  'calendar.compose_confirm_warning_one': 'Retirer {slots} arrachera {votes} déjà posée.',
  'calendar.compose_count_many': '{n} clairières désignées',
  'calendar.compose_count_none': 'Aucune clairière désignée',
  'calendar.compose_count_one': '{n} clairière désignée',
  /* — mode Destinée — */
  // Nom du MODE « Destinée » (EXPERIENCE.md §4.4 ter), identique dans les trois thèmes.
  'cta.destiny_mode': 'Destinée',
  'calendar.destiny_next_aria': 'Cercle suivant',
  'calendar.destiny_prev_aria': 'Cercle précédent',

  /* ═══ Vote de date ═══ */
  /* — actions, états et alertes — */
  'cta.find_date': "Envoyer l'écureuil messager",
  'cta.guild_calendar': 'Voir la forêt des disponibilités',
  'cta.save_constraint': 'Marquer le territoire',
  'section.slots': 'Clairières disponibles',
  'empty.no_slots':
    'Aucune clairière libre. La forêt est dense, demande aux membres leurs disponibilités.',
  'success.constraint_saved': 'Territoire marqué dans la forêt.',
  'alert.missing_player': "{name} n'a pas encore parcouru la forêt.",
  'cta.choose_date': 'Planter le drapeau de la clairière',
  'cta.cancel_poll': 'Disperser les feuilles du vote',
  'cta.restore_default_layers': 'Revenir à la clairière par défaut',
  'success.poll_created': "L'écureuil a transmis l'appel du vote.",
  'success.vote_cast': "L'écureuil a transmis ta réponse.",
  'cta.confirm_votes': 'Transmettre mes réponses',
  'cta.withdraw_vote': 'Effacer ma réponse',
  'success.vote_withdrawn': "L'écureuil a effacé ta réponse.",
  'alert.all_responded': "Tous les habitants ont répondu à l'appel.",
  /* — état du vote — */
  'poll.status_title': 'Vote en cours dans la forêt',
  'poll.vote_pending': "L'écureuil attend ta réponse au vote",
  'poll.withdraw_error': "L'écureuil n'a pas pu effacer ta réponse. Réessaie.",
  'poll.cast_error': "L'écureuil n'a pas pu transmettre ta réponse. Réessaie.",
  'poll.vote_closed': 'Le vote de la forêt est terminé.',
  'poll.status_summary': 'Vote ouvert — {responded}/{total} habitants ont répondu',
  'poll.missing_prefix': 'N’ont pas parcouru la forêt :',
  'poll.responded_prefix': 'Ont parcouru la forêt :',
  /* — réponse au vote — */
  'calendar.answer_menu_aria': 'Répondre à l’appel — {slot}',
  'calendar.answer_withdraw': 'Effacer ma réponse',
  /* — création et suivi du vote — */
  'pollui.creation_title': 'Réunir un cercle de date',
  'pollui.creation_computed_title': 'Clairières repérées',
  'pollui.creation_computed_empty': 'Aucune clairière repérée pour l’instant.',
  'pollui.creation_load_more_one': '{n} clairière de plus',
  'pollui.creation_load_more_many': '{n} clairières de plus',
  'pollui.creation_all_shown': 'Toutes les clairières repérées sont affichées',
  'pollui.creation_custom_title': 'Clairières à ta façon',
  'pollui.creation_add_custom': 'Ajouter une clairière à ta façon',
  'pollui.creation_selected_count': '{n} option(s) cueillie(s)',
  'pollui.creation_submit': 'Réunir le cercle',
  'pollui.creation_desync_error':
    'Le cercle a été réuni, mais son état n’a pas pu être rafraîchi ici. Recharge la page pour le voir plutôt que de réunir un autre cercle.',
  'pollui.creation_error': 'Le cercle n’a pas pu être réuni. Réessaie.',
  'pollui.response_not_saved_aria': 'Non gravé',
  'pollui.response_partial_error':
    '{success}/{total} réponse(s) gravée(s). Réessaie pour les autres.',
  'pollui.status_voters_aria': 'Voix du cercle',
  'pollui.status_missing_aria': 'N’ont pas encore répondu à l’appel pour cette date',
  'pollui.status_choose_confirm': 'Planter {date} — {slot} comme date de la prochaine séance ?',
  'pollui.status_choose_no_vote_warning': '⚠️ Aucun habitant n’a voté pour cette date.',

  /* ═══ Annonces ═══ */
  /* — annonces — */
  'announcement.scope_campaign_label': 'Toute la longue marche',
  'announcement.scope_oneshot_label': 'Ce sentier court',
  'announcement.scope_scenario_label': 'Cette étape',
  'announcement.publish_cta': 'Lancer un appel dans la forêt',
  'announcement.text_placeholder': 'Composer un appel...',
  'announcement.published_notice': "L'appel résonne dans la forêt.",
  'announcement.unseen_label': 'Non entendu — clique pour marquer comme entendu',
  'announcement.publish_error': 'Ton appel n’a pas pu être lancé. Réessaie.',

  /* ═══ Personnages ═══ */
  /* — liste « Personnages » — */
  'my_characters.title': 'Mes compagnons de route',
  'my_characters.empty': 'Aucun compagnon éveillé. Façonne-en un depuis un sentier…',
  'my_characters.no_match': 'Aucun compagnon ne répond à cette recherche.',
  'my_characters.search_label': 'Rechercher un compagnon',
  'my_characters.sort_niveau': 'Niveau',
  'my_characters.sort_partie': 'Sentier',
  'my_characters.sort_nom': 'Nom du compagnon',
  'my_characters.create_title': 'À éveiller',
  'my_characters.create_entry': 'Éveiller un compagnon de route pour {partie}',
  'my_characters.create_more': 'Voir les {n} autres sentiers',
  'my_characters.create_more_one': 'Voir l’autre sentier',
  'my_characters.create_less': 'Resserrer',
  'my_characters.empty_with_entries': 'Aucun compagnon éveillé pour l’instant.',
  'my_characters.create_entry_hd': 'Éveiller un Homme Dragon pour {partie}',
  'characters_list.homme_dragons_load_error': 'Tes Hommes Dragons n’ont pas pu être chargés.',
  /* — fiche de personnage — */
  'character.portrait_edit_cta': 'Remodeler le portrait',
  'character.pdf_crop_edit_cta': 'Remodeler le cadrage PDF',
  'character.sheet_menu_trigger_aria': 'Gestes sur la fiche',
  'character.export_editable_cta': 'Exporter en PDF (éditable)',
  'character.export_2pages_cta': 'Exporter en PDF (2 pages)',
  'character.export_equipment_cta': 'Exporter l’équipement en PDF',
  'character.export_notes_cta': 'Exporter les notes en PDF',
  'character.export_error': 'Le PDF n’est pas arrivé : l’écureuil s’est perdu en chemin. Réessaie.',
  'character.owner_badge_mj': 'Guide',
  // « Homme Dragon » est un nom propre du système : jamais thématisé (story 33.5).
  'character.nature_dragon': 'Homme Dragon',
  'character.level_badge': 'Niv. {n}',
  'character.party_sheets_tab_label': 'Feuilles',
  'character.back_to_partie_cta': 'Retour au sentier',
  'character.no_character_yet': 'Aucun compagnon de route éveillé sur ce sentier pour l’instant.',
  'characters_sheet.not_found': 'Fiche introuvable dans la forêt.',
  'characters_sheet.access_denied': 'Tu n’as pas accès à cette fiche.',
  'characters_sheet.load_error': 'La fiche du compagnon reste introuvable. Réessaie.',
  'characters_sheet.portrait_save_error': 'Le portrait n’a pas pu être gravé. Réessaie.',
  'characters_sheet.pdf_crop_save_error': 'Le cadrage PDF n’a pas pu être gravé. Réessaie.',
  'characters_sheet.field_edit_aria': 'Remodeler {label}',
  'characters_sheet.history_load_error': 'La mémoire du cercle n’a pas pu être chargée.',
  'characters_sheet.history_level': 'Niveau {level}',
  'characters_sheet.item_added_by_mj': 'ajouté par le Guide',
  'characters_sheet.item_edit_aria': 'Remodeler l’objet',
  'characters_sheet.item_remove_aria': 'Arracher l’objet',
  'characters_sheet.notes_load_error': 'Le carnet reste introuvable.',
  'characters_sheet.levelup_title_level': '— Niveau {level}',
  'characters_sheet.levelup_decrease_aria': 'Diminuer {stat}',
  'characters_sheet.levelup_increase_aria': 'Augmenter {stat}',
  'characters_sheet.levelup_attribute_max_sr': 'Déjà au sommet (12)',
  'characters_sheet.levelup_save_error': 'La croissance n’a pas pu être gravée. Réessaie.',
  'characters_sheet.inventory_contenants_empty': 'Aucun contenant dans la besace pour le moment.',
  'characters_sheet.inventory_animaux_empty': 'Aucun animal compagnon pour le moment.',
  'characters_sheet.inventory_add_contenant_cta': '+ Glisser un contenant dans la besace',
  'characters_sheet.inventory_mj_add_contenant_cta':
    '+ Glisser un contenant du Guide dans la besace',
  'characters_sheet.inventory_add_animal_cta': '+ Ajouter un animal compagnon',
  'characters_sheet.inventory_mj_add_animal_cta': '+ Ajouter un animal compagnon (Guide)',
  /* — évolution (niveau, historique, inventaire, notes) — */
  'evolution.levelup_banner': "Le cercle t'appelle à grandir — niveau [N]",
  'evolution.levelup_cta': 'Gravir un échelon',
  'evolution.levelup_wizard_title': 'Croissance',
  'evolution.levelup_step_pv_pe': 'Répartis 3 points entre PV et PE',
  'evolution.levelup_step_capability': 'Choisir le don qui s’éveille',
  'evolution.levelup_legendary_journey_text':
    'Un chemin légendaire s’ouvre — rien de plus à choisir.',
  'evolution.levelup_confirm_cta': 'Graver cet échelon',
  'evolution.main_sheet_tab_label': 'Feuille',
  'evolution.history_tab_label': 'Mémoire du cercle',
  'evolution.history_empty': 'Aucun souvenir gravé pour le moment.',
  'evolution.mj_edit_trace': 'remodelé par le Guide',
  'evolution.landscape_section_title': 'Paysage/climat de coeur',
  'evolution.immunity_section_title': 'Immunités du cercle',
  'evolution.other_capabilities_title': 'Dons du voyage',
  'evolution.derived_hidden': 'Statistiques voilées par le Guide',
  'evolution.hidden_marker': 'Voilé par le Guide',
  'evolution.inventory_section_title': 'Besace',
  'evolution.inventory_add_cta': '+ Glisser un objet dans la besace',
  'evolution.inventory_empty': 'La besace est vide pour le moment.',
  'evolution.inventory_overweight_label': 'Surchargée',
  'evolution.inventory_error': "La besace n'a pas pu être mise à jour. Réessaie.",
  'evolution.mj_edit_error': "L'édition n'a pas pu être gravée. Réessaie.",
  'evolution.mj_edit_warning_prefix': 'Prends garde : ',
  'evolution.inventory_mj_add_cta': '+ Glisser un objet du Guide dans la besace',
  'evolution.narrative_edit_error': "La modification n'a pas pu être gravée. Réessaie.",
  'evolution.notes_journal_title': 'Carnet du voyageur',
  'evolution.notes_journal_empty': 'Le carnet est vierge pour le moment.',
  'evolution.notes_add_cta': '+ Graver une entrée',
  'evolution.note_share_toggle': 'Partager avec le cercle',
  'evolution.note_private_label': 'Entrée gardée pour toi',
  'evolution.note_shared_label': 'Entrée partagée avec le cercle',
  'evolution.notes_error': "Le carnet n'a pas pu être mis à jour. Réessaie.",
  /* — groupe de joueurs (troupe) — */
  'roster.mj_badge': 'MJ',
  'roster.invite_slot': 'Accueillir un compagnon de route',
  'roster.collapse_label': 'Replier le cercle',
  'roster.expand_label': 'Déplier le cercle',
  'roster.levelup_badge': 'Prêt à grandir',
  'roster.create_slot_label': 'éveiller mon compagnon de route',
  /* — création de personnage — */
  'character.create_cta': 'Éveiller un compagnon de route',
  'character.choice_deselect_hint': 'Toucher pour relâcher ce choix',
  'character.choice_talents_label': 'Talents',
  'character.choice_advantages_label': 'Avantages',
  'character.choice_required_flag': 'Indispensable',
  'character.choice_reference_toggle': 'Occupations et actions',
  'character.equipment_group_toggle': '{group}, {n} trouvailles',
  'character.equipment_filter_all': 'Toute la forêt',
  'character.equipment_filter_mine': 'Ma cueillette',
  'character.equipment_qty_less': 'Reposer un exemplaire de {name}',
  'character.equipment_qty_more': 'Cueillir un exemplaire de {name}',
  'character.recap_button': 'Bilan',
  'character.recap_title': 'Bilan du compagnon',
  'character.recap_cart_title': 'Besace',
  'character.recap_remove': 'Ôter',
  'character.recap_total': 'Total',
  'character.recap_empty_hint':
    'Les statistiques dérivées éclorront une fois les attributs assignés.',
  'detail.row_attributes': 'Attributs',
  'detail.row_difficulty': 'Difficulté',
  'detail.row_effect': 'Effet',
  'detail.row_conditions': 'Conditions',
  'detail.narrative_show': 'Écouter le récit',
  'detail.narrative_hide': 'Taire le récit',
  'character.equipment_group_individual': 'Objets',
  'character.equipment_group_contenant': 'Contenants',
  'character.equipment_group_animal': 'Animaux',
  'character.equipment_search_label': 'Fouiller la forêt',
  'character.equipment_search_placeholder': 'Nom d’une trouvaille…',
  'character.equipment_budget': 'Pécule · {spent} / {total} Po',
  'character.equipment_over_budget': '— {n} Po de trop pour ton pécule',
  'character.equipment_search_empty': 'La forêt ne recèle aucun objet de ce nom…',
  'character.step_class': 'Choisir son rôle dans le cercle',
  'character.step_type': 'Choisir son chemin',
  'character.step_magic': 'Nouer son lien avec les dragons',
  'character.step_portrait_intro':
    "Grave un visage si le cœur t'en dit — cette étape reste facultative, tu peux la traverser sans t'arrêter.",
  'characters_wizard.loading': 'L’assistant se déploie…',
  'characters_wizard.step_prev_aria': 'Pas précédent',
  'characters_wizard.step_next_aria': 'Pas suivant',
  'characters_wizard.step_progress': 'Pas {index}/{total} · {label}',
  'characters_wizard.submitting': 'Éveil…',
  'characters_wizard.summary_aria': 'Bilan du compagnon',
  'characters_wizard.summary_default_title': 'Compagnon',
  'characters_wizard.load_error_no_module':
    'Ces règles du jeu n’ont pas encore d’assistant de création.',
  'characters_wizard.load_error':
    'L’assistant de création n’a pas pu s’éveiller. Vérifie ta connexion et réessaie.',
  'characters_wizard.portrait_upload_warning':
    'Compagnon éveillé, mais son portrait n’a pas pu être gravé. Réessaie depuis la fiche.',
  'characters_wizard.already_has_character': 'Tu as déjà un compagnon sur ce sentier',
  'characters_wizard.invalid_data': 'Données invalides. Vérifie ta saisie.',
  'characters_wizard.attributes_profile_aria': "Profil d'attributs",
  'characters_wizard.attributes_banner_profile': 'Profil',
  'characters_wizard.attributes_banner_one': '— {n} valeur sur {total} plantée',
  'characters_wizard.attributes_banner_many': '— {n} valeurs sur {total} plantées',
  'characters_wizard.attributes_chip_remaining': '{value}, encore {n} à planter',
  'characters_wizard.equipment_mode_aria': 'Choisir comment remplir la besace',
  'characters_wizard.equipment_mode_kit': 'Besace toute prête',
  'characters_wizard.equipment_mode_shopping': 'Cueillette libre',
  'characters_wizard.equipment_filter_aria': 'Filtre de la cueillette',
  'characters_wizard.weapon_category_aria': 'Choisir un type d’arme',
  'characters_wizard.weapon_item_aria': 'Choisir son arme exacte',
  'characters_wizard.weapon_custom_card': 'Façonner une arme libre',
  /* — portrait — */
  'portrait.cropper_choose_image': 'Cueillir une image',
  'portrait.cropper_area_aria':
    'Zone de recadrage du portrait. Flèches pour déplacer, plus ou moins pour agrandir.',
  'portrait.cropper_zoom': 'Zoom',
  'portrait.panel_alt': 'Portrait gravé de {name}',
  'portrait.panel_caption': 'Portrait gravé',
  'portrait.avatar_aria': 'Portrait de {name}',
  'portrait.avatar_aria_empty': 'Portrait de {name} (aucune image)',

  /* ═══ Homme Dragon ═══ */
  'homme-dragon.create_cta': 'Éveiller mon Homme Dragon',
  'homme-dragon.race_label': 'Lignée',
  'homme-dragon.artefact_label': 'Talisman',
  'homme-dragon.created_notice': 'Ton Homme Dragon veille sur la forêt.',
  'hd.page_back_to_characters': 'Retour à « Compagnons »',
  'hd.creation_page_title': 'Éveiller un Homme Dragon',
  'hd.creation_check_error': 'L’Homme Dragon de ce sentier n’a pas pu être vérifié. Réessaie.',
  'hd.sheet_load_error': 'La fiche reste introuvable. Réessaie.',
  'hd.sheet_export_pdf': 'Exporter en PDF',
  'hd.sheet_export_menu_aria': 'Format de l’export PDF',
  'hd.sheet_export_editable': 'PDF éditable',
  'hd.sheet_export_2pages': 'PDF 2 pages (à imprimer)',
  'hd.sheet_export_error': 'La fiche n’a pas pu être exportée en PDF. Réessaie.',
  'hd.sheet_artefact_change_error': 'L’artefact n’a pas pu être changé. Réessaie.',
  'hd.sheet_cadeau_empty': 'Aucun artefact n’est disponible dans la forêt.',
  'hd.sheet_cadeau_choose_btn': 'Choisir cet artefact',
  'hd.sheet_cadeau_confirm_strong': 'Ce choix est définitif : la racine ne se déterre pas.',
  'hd.sheet_cadeau_confirm_text':
    'Offrir « {nom} » à l’Homme Dragon ? Il ne pourra plus être remodelé.',
  'hd.sheet_cadeau_confirm_btn': 'Confirmer ce choix définitif',
  'hd.sheet_cadeau_back_btn': 'Retourner au choix',
  'hd.sheet_eveil_empty': 'Aucun pouvoir d’éveil n’est encore apparu.',
  'hd.sheet_aventures_empty': 'Aucun sentier parcouru pour l’instant.',
  'hd.sheet_voyageurs_empty': 'Aucun compagnon de route pour l’instant.',
  'hd.sheet_aventure_add_empty': 'Aucun sentier Ryuutama sans Homme Dragon à ajouter.',
  'hd.sheet_aventure_add_error': 'Ce sentier n’a pas pu être ajouté. Réessaie.',
  'hd.sheet_aventure_remove_aria': 'Retirer le sentier {nom}',
  'hd.sheet_aventure_remove_confirm':
    'Retirer « {nom} » ? Le niveau de l’Homme Dragon peut baisser ; sa fiche, sa réserve et ses choix sont gardés.',
  'hd.sheet_aventure_remove_error': 'Ce sentier n’a pas pu être retiré. Réessaie.',
  'hd.sheet_historique_empty': 'Aucune étape parcourue pour l’instant.',
  'hd.wizard_step_progress': 'Pas {n}/{total} · {etape}',
  'hd.wizard_more_aria': 'Approfondir {nom}',
  'hd.wizard_artefact_empty': 'Aucun artefact n’est disponible pour cette lignée.',
  'hd.wizard_create_conflict_error': 'Ce sentier a déjà un Homme Dragon.',
  'hd.wizard_create_error': 'Ton Homme Dragon n’a pas pu s’éveiller. Réessaie.',
  'hd.panel_load_error': 'L’Homme Dragon de ce sentier reste introuvable. Réessaie.',
  'hd.panel_linked_title': 'Homme Dragon de ce sentier',
  'hd.panel_linked_help': 'Sa fiche, son niveau et son historique cumulent tous ses sentiers.',
  'hd.panel_none_title': 'Aucun Homme Dragon pour ce sentier',
  'hd.panel_create_cta': 'Éveiller un Homme Dragon pour {partie}',
  'hd.panel_associate_empty': 'Tu n’as encore aucun autre Homme Dragon à rattacher.',
  'hd.panel_associate_label': 'Rattacher un existant',
  'hd.panel_associate_error': 'Cet Homme Dragon n’a pas pu être rattaché. Réessaie.',
  'hd.panel_dissociate_confirm':
    'Détacher {nom} de « {partie} » ? Son niveau peut baisser ; sa fiche, sa réserve et ses choix sont gardés.',
  'hd.panel_dissociate_error': 'Cet Homme Dragon n’a pas pu être détaché. Réessaie.',
  'hd.reserve_autosaved': 'Gravée automatiquement, utilisée pour l’export PDF.',
  'hd.reserve_pick_btn': 'Cueillir un souffle',
  'hd.reserve_pick_for_slot': 'Cueillir un souffle pour l’emplacement {n}',
  'hd.reserve_change_aria': 'Échanger le souffle de l’emplacement {n} : {nom}',
  'hd.reserve_remove_aria': 'Ôter {nom} de l’emplacement {n}',
  'hd.reserve_save_error': 'La réserve n’a pas pu être gravée. Réessaie.',
  'hd.reserve_undo_text': '{nom} ôté de l’emplacement {n}.',
  'hd.reserve_removed_status':
    '{nom} ôté de l’emplacement {n}. Tu peux annuler pendant quelques secondes.',
  'hd.reserve_restored_status': '{nom} reposé dans l’emplacement {n}',
  'hd.reserve_placed_status': '{nom} placé dans l’emplacement {n}. Réserve gravée',
  'hd.picker_place_btn': 'Poser dans l’emplacement {n}',
  'hd.picker_consult_hint': 'Touche un souffle de la liste pour lire sa description.',
  'hd.picker_choose_hint': 'Choisis un souffle dans la liste.',
  'hd.picker_slot_gone': 'Cet emplacement n’existe plus dans la forêt.',
  'hd.picker_blocked_announce': 'Impossible de poser dans l’emplacement {n} : {raison}',
  'hd.picker_description_aria': 'Description : {nom}',
  'core.homme_dragon_sans_aventure': 'Sans sentier',
};
