import type { ToneKey } from './grimoire-emeraude';

// Typé d'après le thème de référence : une clé manquante ou en trop est une erreur de compilation.
export const foretAncienne: Record<ToneKey, string> = {
  /* — navigation — */
  'nav.my_games': 'Mes pérégrinations',
  'nav.create_game': 'Ouvrir un sentier',
  'nav.logout': 'Quitter la forêt',
  'nav.calendar': 'Calendrier',
  'nav.account': 'Mon carnet',
  'nav.characters': 'Compagnons',
  /* — dashboard — */
  'dashboard.title_invitations': 'Appels de la forêt',
  'dashboard.empty': 'Aucune clairière ouverte. Plantez le premier feu…',
  'dashboard.role_prefix': 'Voie :',
  'dashboard.role_mj': 'Guide',
  'dashboard.role_player': 'Voyageur',
  'dashboard.status_closed_badge': 'Achevé',
  /* — signalétique d'état (Story 29.7) — */
  'dashboard.section_awaiting': 'Ce qui t’attend',
  'dashboard.section_ongoing': 'En route',
  'dashboard.section_upcoming': 'À venir',
  'dashboard.section_finished': 'Achevées',
  /* — filtres, tri, favoris (Story 29.8) — */
  'dashboard.empty_filtered': 'Aucun sentier ne répond à ces critères.',
  'dashboard.controls_toggle_aria': 'Afficher les filtres et le tri',
  'dashboard.filter_role_label': 'Voie',
  'dashboard.filter_role_all': 'Tous',
  'dashboard.filter_status_label': 'Statut',
  'dashboard.filter_status_all': 'Tous',
  'dashboard.sort_label': 'Trier par',
  'dashboard.sort_urgence': 'Urgence',
  'dashboard.sort_date': 'Date',
  'dashboard.sort_nom': 'Nom',
  'dashboard.sort_type': 'Type',
  'dashboard.sort_statut': 'Statut',
  'dashboard.hide_finished_label': 'Masquer les sentiers achevés',
  'dashboard.show_finished_btn': 'Afficher les sentiers achevés',
  'dashboard.favorite_add_aria': 'Marquer comme favori',
  'dashboard.favorite_remove_aria': 'Retirer des favoris',
  /* — barre de contrôles partagée (Story 29.9) — */
  'dashboard.search_label': 'Rechercher un sentier',
  'dashboard.row_signal_count_aria': '{n} chose(s) à faire',
  'list_control_bar.toggle_aria': 'Afficher les filtres et le tri',
  'list_control_bar.view_mode_group_aria': 'Densité d’affichage',
  'list_control_bar.view_mode_large_aria': 'Grande vignette',
  'list_control_bar.view_mode_medium_aria': 'Vignette intermédiaire',
  'list_control_bar.view_mode_compact_aria': 'Liste compacte',
  'list_control_bar.sort_label': 'Trier par',
  'list_control_bar.reset_pill_label': 'Réglages modifiés',
  /* — my-characters (Story 29.2) — */
  'my_characters.title': 'Mes compagnons de route',
  'my_characters.empty': 'Aucun compagnon éveillé. Façonnez-en un depuis un sentier…',
  'my_characters.no_match': 'Aucun compagnon ne répond à cette recherche.',
  'my_characters.search_label': 'Rechercher un compagnon',
  'my_characters.sort_niveau': 'Niveau',
  'my_characters.sort_partie': 'Sentier',
  'my_characters.sort_nom': 'Nom',
  /* — section de création (Story 29.16) — */
  'my_characters.create_title': 'À éveiller',
  'my_characters.create_entry': 'Éveiller un compagnon de route pour {partie}',
  'my_characters.create_more': 'Voir les {n} autres',
  'my_characters.create_more_one': 'Voir l’autre',
  'my_characters.create_less': 'Voir moins',
  'my_characters.empty_with_entries': 'Aucun compagnon éveillé pour l’instant.',
  /* — ligne de création de l'Homme Dragon (Story 33.5) — */
  'my_characters.create_entry_hd': 'Créer un Homme Dragon pour {partie}',
  /* — partie-form — */
  'partie.new_title': 'Nouveau sentier',
  'partie.edit_title': 'Rebattre le sentier',
  'partie.save_btn': 'Planter',
  'partie.cancel_btn': 'Rebrousser chemin',
  'partie.name_label': 'Nom du sentier',
  'partie.system_label': 'Système de jeu',
  'partie.kind_label': 'Nature du sentier',
  'partie.description_label': 'Premiers pas (facultatif)',
  'partie.kind_ONE_SHOT': 'Sentier court',
  'partie.kind_CAMPAGNE_LINEAIRE': 'Longue marche',
  'partie.kind_CAMPAGNE_EPISODIQUE': 'Longue marche par étapes',
  'partie.kind_refusal_closed': 'Ce sentier est refermé. Rouvrez-le avant d’en changer la nature.',
  'partie.kind_refusal_too_many_scenarios':
    'Ce sentier compte {count} étapes ; un sentier court n’en a qu’une.',
  'partie.courant_choice_title': 'Quelle étape reste en cours ?',
  'partie.courant_choice_help':
    'Une longue marche ne suit qu’une étape à la fois. Les autres redeviendront « à venir » — leurs séances et leurs dates sont conservées.',
  'partie.courant_choice_confirm': 'Prendre ce chemin',
  'partie.cover_add': 'Donner un visage au sentier',
  'partie.cover_change': 'Changer l’image',
  'partie.cover_remove': 'Retirer l’image',
  'partie.cover_uploading': 'L’image prend racine…',
  'partie.cover_upload_error': 'L’image n’a pu prendre racine. Réessayez.',
  'partie.cover_remove_error': 'L’image n’a pu être retirée. Réessayez.',
  'partie.cover_reject_type': 'Seules les images JPEG, PNG et WEBP peuvent être plantées ici.',
  'partie.cover_reject_size': 'Cette image dépasse 5 Mo : choisissez-en une plus légère.',
  'partie.save_error': 'Ce sentier n’a pu être tracé. Réessayez.',
  'partie.created_but_cover_failed':
    'Le sentier est bien tracé, mais son image n’a pu prendre racine. Vous pouvez la redéposer ici.',
  'partie.fields_saved_but_convert_failed':
    'Les autres changements sont enregistrés, mais la nature du sentier n’a pu être changée. Réessayez.',
  /* — partie-detail — */
  'partie.scheduling_title': 'Prochaine clairière',
  'partie.no_session': "Aucune clairière réservée. L'écureuil cherche encore.",
  'partie.members_title': '🌿 Habitants',
  'partie.no_members': 'Aucun habitant de la clairière.',
  'partie.remove_member_btn': 'Renvoyer',
  'partie.no_description': 'La forêt garde ses secrets.',
  'partie.invite_title': 'Appeler depuis la forêt',
  'partie.search_label': 'Nom ou espèce connue',
  'partie.search_btn': 'Fouiller',
  'partie.invite_btn': 'Accueillir',
  'partie.links_title': 'Sifflets de rappel',
  'partie.generate_link': 'Tisser un laissez-passer',
  'partie.notice_invited': 'Sifflet envoyé à {name}.',
  'partie.invite_by_email_label': 'Adresse du destinataire',
  'partie.invite_by_email_btn': 'Envoyer un sifflet',
  'partie.notice_invited_email': 'Sifflet envoyé à {email}.',
  'partie.notice_invite_email_error': "Le sifflet s'est perdu dans le vent. Réessayez.",
  'partie.reference_sheets_title': 'Grimoires de la clairière',
  'partie.asset_journal_cta': 'Journal',
  'partie.asset_carte_cta': 'Carte',
  'partie.asset_download_error': "Le grimoire s'est enraciné trop profond. Réessayez.",
  'partie.prep_sheets_title': 'Grimoires de la clairière (MJ)',
  'partie.asset_monde_cta': 'Monde',
  'partie.asset_monstre_cta': 'Monstre',
  'partie.asset_ville_cta': 'Ville',
  'partie.asset_objectif_chasse_cta': 'Objectif — Chasse',
  'partie.asset_objectif_quete_cta': 'Objectif — Quête',
  'partie.asset_objectif_voyage_cta': 'Objectif — Voyage',
  'partie.asset_oeuf_de_bataille_cta': 'Œuf de bataille',
  'partie.asset_structure_cta': 'Structure',
  /* — zones de l'onglet Détails (Story 32.2) — noms CONTRACTUELS, identiques dans les trois
     thèmes (même principe que cta.destiny_mode, Story 36.9). */
  'partie.details_zone_action': 'Action',
  'partie.details_zone_consultation': 'Consultation',
  'partie.details_zone_reference': 'Référence',
  /* — états de scénario et de séance (Story 32.3) — libellés CONTRACTUELS, identiques dans les
     trois thèmes : cf. le commentaire complet dans `grimoire-emeraude`. */
  'status.scenario_brouillon': 'Brouillon',
  'status.scenario_a_venir': 'À venir',
  'status.scenario_courant': 'Courant',
  'status.scenario_passe': 'Passé',
  'status.seance_a_planifier': 'À planifier',
  'status.seance_answer_poll': 'Réponds au vote',
  'status.seance_poll_open': 'Vote en cours',
  'status.seance_inscriptions_ouvertes': 'Inscriptions ouvertes',
  'status.seance_programmee': 'Programmée',
  'status.seance_a_debriefer': 'À débriefer',
  'status.seance_jouee': 'Jouée',
  'partie.notice_copy': 'Laissez-passer copié dans la gibecière.',
  'partie.edit_btn': 'Rebattre',
  'partie.visibility_btn': 'Voiler des secrets',
  'partie.close_btn': 'Achever le sentier',
  'partie.reopen_btn': 'Reprendre la route',
  'partie.status_closed_label': 'Ce sentier est achevé.',
  /* — signaux d'état (Story 29.7, FR-12) — */
  'partie.signal_personnage_a_creer': 'Façonner son compagnon',
  'partie.signal_vote_en_cours_sans_reponse': 'Vote en attente',
  'partie.signal_compte_rendu_non_redige': 'Compte-rendu à écrire',
  'partie.signal_homme_dragon_a_creer': 'Façonner son Homme Dragon',
  'partie.signal_aucun_membre_invite': 'Aucun voyageur convié',
  'partie.signal_aucun_scenario_en_cours': 'Aucun sentier en cours',
  'partie.signal_aucune_date_ni_vote': 'Aucune date ni vote',
  'partie.signal_rapport_fin_manquant': 'Récit de fin manquant',
  'partie.signal_prochaine_seance_connue': 'Prochaine étape connue',
  'partie.signal_partie_terminee': 'Sentier achevé',
  'partie.signal_more_count': '+{n}',
  'partie.delete_btn': 'Effacer le sentier',
  'partie.invitations_tab_label': 'Invitations',
  'partie.show_troupe': 'Voir le cercle',
  'partie.hide_troupe': 'Masquer le cercle',
  /* — calendrier & vote — */
  'cta.find_date': "Envoyer l'écureuil messager",
  'cta.guild_calendar': 'Voir la forêt des disponibilités',
  'cta.launch_vote': 'Planter le bâton du vote',
  'cta.save_constraint': 'Marquer le territoire',
  'cta.send_reminder': 'Faire chanter les oiseaux',
  'section.slots': 'Clairières disponibles',
  'section.constraints': 'Zones marquées',
  'empty.no_slots':
    'Aucune clairière libre. La forêt est dense, demandez aux membres leurs disponibilités.',
  'empty.no_constraints': 'Aucun territoire marqué.',
  'success.constraint_saved': 'Territoire marqué dans la forêt.',
  'alert.expiring_soon': "Votre marquage s'efface bientôt. Renouvelez votre présence.",
  'alert.missing_player': "{name} n'a pas encore parcouru la forêt.",
  'status.unavailable_label': 'Absent de la forêt',
  'status.unknown_label': 'Perdu dans les branches',
  'cta.choose_date': 'Planter le drapeau de la clairière',
  'cta.cancel_poll': 'Disperser les feuilles du vote',
  'cta.restore_default_layers': 'Revenir à la clairière par défaut',
  'empty.no_poll': 'Aucun vote en cours dans la forêt.',
  'success.poll_created': "L'écureuil a transmis l'appel du vote.",
  'success.date_chosen': 'La clairière de la séance est choisie.',
  'poll.status_title': 'Vote en cours dans la forêt',
  'poll.vote_pending': "L'écureuil attend ta réponse au vote",
  'success.vote_cast': "L'écureuil a transmis ta réponse.",
  'cta.confirm_votes': 'Transmettre mes réponses',
  'cta.withdraw_vote': 'Retirer ma réponse',
  'success.vote_withdrawn': "L'écureuil a effacé ta réponse.",
  'poll.withdraw_error': "L'écureuil n'a pas pu effacer ta réponse. Réessaie.",
  'poll.cast_error': "L'écureuil n'a pas pu transmettre ta réponse. Réessaie.",
  'poll.vote_closed': 'Le vote de la forêt est terminé.',
  'alert.all_responded': "Tous les habitants ont répondu à l'appel.",
  'poll.status_summary': 'Vote ouvert — {responded}/{total} habitants ont répondu',
  /* — mode Destinée et panneau réduit (Story 36.9) — */
  'cta.destiny_mode': 'Destinée',
  'poll.missing_prefix': 'N’ont pas parcouru la forêt :',
  'poll.responded_prefix': 'Ont parcouru la forêt :',
  /* — annonces (Epic 9) — */
  'announcement.scope_campaign_label': 'Toute la forêt',
  'announcement.scope_oneshot_label': 'Cette expédition',
  'announcement.scope_scenario_label': 'Cette clairière',
  'announcement.publish_cta': 'Lancer un appel dans la forêt',
  'announcement.text_placeholder': 'Composer un appel...',
  'announcement.published_notice': "L'appel résonne dans la forêt.",
  'announcement.unseen_label': 'Non entendu — cliquez pour marquer comme entendu',
  /* — personnages (Palier P3) — */
  'character.create_cta': 'Éveiller un compagnon de route',
  'character.choice_deselect_hint': 'Toucher pour désélectionner',
  'character.choice_talents_label': 'Talents',
  'character.choice_advantages_label': 'Avantages',
  'character.choice_required_flag': 'Obligatoire',
  'character.choice_reference_toggle': 'Occupations et actions',
  'character.equipment_group_toggle': '{group}, {n} objets',
  'character.equipment_filter_all': 'Tout',
  'character.equipment_filter_mine': 'Ma sélection',
  'character.equipment_qty_less': 'Retirer un exemplaire de {name}',
  'character.equipment_qty_more': 'Ajouter un exemplaire de {name}',
  'character.recap_button': 'Récap',
  'character.recap_title': 'Récapitulatif',
  'character.recap_cart_title': 'Panier',
  'character.recap_remove': 'Retirer',
  'character.recap_total': 'Total',
  'character.recap_empty_hint':
    'Les statistiques dérivées apparaîtront une fois les attributs assignés.',
  'detail.row_attributes': 'Attributs',
  'detail.row_difficulty': 'Difficulté',
  'detail.row_effect': 'Effet',
  'detail.row_conditions': 'Conditions',
  'detail.narrative_show': 'Lire le récit',
  'detail.narrative_hide': 'Masquer le récit',
  'character.equipment_group_individual': 'Objets',
  'character.equipment_group_contenant': 'Contenants',
  'character.equipment_group_animal': 'Animaux',
  'character.equipment_search_label': 'Rechercher un objet',
  'character.equipment_search_placeholder': 'Rechercher un objet…',
  'character.equipment_budget': 'Budget · {spent} / {total} Po',
  'character.equipment_over_budget': '— dépassement de {n} Po',
  'character.equipment_search_empty': 'La forêt ne recèle aucun objet de ce nom…',
  'character.tab_label': 'Personnages',
  'character.step_class': 'Choisir son rôle dans le cercle',
  'character.step_type': 'Choisir son chemin',
  'character.step_magic': 'Nouer son lien avec les dragons',
  'character.step_portrait_intro':
    "Grave un visage si le cœur t'en dit — cette étape reste facultative, tu peux la traverser sans t'arrêter.",
  'character.portrait_missing': 'Aucun visage gravé — la forêt garde son mystère',
  'character.portrait_edit_cta': 'Modifier le portrait',
  // Story 31.1 — clé manquante ici depuis l'origine (présente dans les deux autres thèmes) :
  // le bouton de recadrage PDF s'affichait avec un texte vide en Forêt Ancienne. Corrigé au
  // passage puisque cette story déplace précisément cette clé dans le nouveau menu.
  'character.pdf_crop_edit_cta': 'Ajuster le cadrage PDF',
  'character.sheet_menu_trigger_aria': 'Actions de la fiche',
  'character.export_editable_cta': 'Exporter en PDF (éditable)',
  'character.export_2pages_cta': 'Exporter en PDF (2 pages)',
  'character.export_equipment_cta': "Exporter l'équipement en PDF",
  'character.export_notes_cta': 'Exporter les notes en PDF',
  'character.export_error': "L'écureuil s'est perdu en chemin. Réessayez.",
  'character.owner_badge_mj': 'Guide',
  /* « Homme Dragon » est un nom propre du système : jamais thématisé (Story 33.5). */
  'character.nature_dragon': 'Homme Dragon',
  'character.level_badge': 'Niv. {n}',
  'character.party_sheets_tab_label': 'Fiches',
  /* — bouton retour vers la partie depuis la fiche d'un personnage — */
  'character.back_to_partie_cta': 'Retour à la partie',
  /* — état vide "Fiches" (Story 29.15) — */
  'character.no_character_yet': 'Aucun compagnon de route éveillé sur cette partie pour l’instant.',
  /* — Homme Dragon (Epic 10, Story 10.1) — */
  'homme-dragon.create_cta': 'Éveiller mon Homme Dragon',
  'homme-dragon.race_label': 'Lignée',
  'homme-dragon.artefact_label': 'Talisman',
  'homme-dragon.created_notice': 'Votre Homme Dragon veille sur la forêt.',
  /* — roster (Story 6.1) — */
  'roster.mj_badge': 'MJ',
  'roster.invite_slot': 'Accueillir un compagnon de route',
  'roster.collapse_label': 'Replier le cercle',
  'roster.expand_label': 'Déplier le cercle',
  'roster.levelup_badge': 'Prêt à grandir',
  /* — slot d'initiale « créer mon personnage » (Story 29.15) — */
  'roster.create_slot_label': 'éveiller mon compagnon de route',
  /* — évolution du personnage (Story 6.2) — */
  'evolution.xp_distribute_cta': 'Partager les récits',
  'evolution.xp_panel_title': 'Partage des récits',
  'evolution.xp_history_title': 'Récits partagés',
  'evolution.xp_history_empty': "Aucun récit partagé pour l'instant.",
  'evolution.xp_note_label': 'Note du récit',
  'evolution.xp_confirm_btn': 'Confier ce récit au cercle',
  'evolution.xp_bonus_link': '+ éclat',
  'evolution.xp_levelup_warning': '{name} va grandir',
  /* — montée de niveau & historique (Story 6.3) — */
  'evolution.levelup_banner': "Le cercle t'appelle à grandir — niveau [N]",
  'evolution.levelup_cta': 'Gravir un échelon',
  'evolution.levelup_wizard_title': 'Croissance',
  'evolution.levelup_step_pv_pe': 'Répartir 3 points entre PV et PE',
  'evolution.levelup_step_capability': 'Choisir le don qui s’éveille',
  'evolution.levelup_legendary_journey_text':
    'Un chemin légendaire s’ouvre — rien de plus à choisir.',
  'evolution.levelup_confirm_cta': 'Graver cet échelon',
  /* — sous-navigation locale de la fiche (Story 29.5) — */
  'evolution.main_sheet_tab_label': 'Feuille',
  'evolution.history_tab_label': 'Mémoire du cercle',
  'evolution.history_empty': 'Aucun souvenir gravé pour le moment.',
  'evolution.mj_edit_trace': 'modifié par le MJ',
  'evolution.landscape_section_title': 'Paysage/climat de coeur',
  'evolution.immunity_section_title': 'Immunités du cercle',
  'evolution.other_capabilities_title': 'Dons du voyage',
  'evolution.derived_hidden': 'Statistiques voilées par le Guide',
  'evolution.hidden_marker': 'Voilé par le Guide',
  'evolution.inventory_section_title': 'Besace',
  'evolution.inventory_add_cta': '+ Glisser un objet dans la besace',
  'evolution.inventory_empty': 'La besace est vide pour le moment.',
  'evolution.inventory_overweight_label': 'Surchargée',
  'evolution.inventory_error': "La besace n'a pas pu être mise à jour. Réessaie.",
  'evolution.mj_edit_error': "L'édition n'a pas pu être gravée. Réessaie.",
  'evolution.mj_edit_warning_prefix': 'Avertissement : ',
  'evolution.inventory_mj_add_cta': '+ Glisser un objet du Guide dans la besace',
  'evolution.narrative_edit_error': "La modification n'a pas pu être gravée. Réessaie.",
  'evolution.notes_journal_title': 'Carnet du voyageur',
  'evolution.notes_journal_empty': 'Le carnet est vierge pour le moment.',
  'evolution.notes_add_cta': '+ Graver une entrée',
  'evolution.note_share_toggle': 'Partager avec le cercle',
  'evolution.note_private_label': 'Entrée gardée pour toi',
  'evolution.note_shared_label': 'Entrée partagée avec le cercle',
  'evolution.notes_error': "Le carnet n'a pas pu être mis à jour. Réessaie.",
  /* — compte — */
  'account.title': 'Mon carnet de route',
  'account.pseudo_label': 'Nom de sentier',
  'account.email_label': 'Sifflet de rappel',
  'account.display_name_label': 'Nom porté aux yeux du cercle',
  'account.save_btn': 'Graver',
  'account.cancel_btn': 'Abandonner',
  'account.saved': 'Le carnet a retenu ce nom.',
  'account.error': "Le carnet n'a pas pu retenir ce changement. Réessaie.",
  'account.password_title': 'Changer de mot de passe',
  'account.current_password_label': 'Mot de passe actuel',
  'account.new_password_label': 'Nouveau mot de passe',
  'account.password_save_btn': 'Changer',
  'account.password_saved': 'Le mot de passe a été changé.',
  'account.password_wrong_current': "Ce n'est pas le bon mot de passe.",
  'account.password_error': "Le carnet n'a pas pu changer le mot de passe. Réessaie.",
  'account.email_change_title': "Changer d'adresse e-mail",
  'account.current_password_for_email_label': 'Mot de passe actuel',
  'account.new_email_label': 'Nouvelle adresse e-mail',
  'account.email_change_save_btn': 'Envoyer',
  'account.email_change_saved': 'Un message est parti vers la nouvelle adresse.',
  'account.email_change_wrong_current': "Ce n'est pas le bon mot de passe.",
  'account.email_change_taken': 'Cette adresse est déjà utilisée par un autre compte.',
  'account.email_change_error': "Le carnet n'a pas pu envoyer la demande. Réessaie.",
  // Story 34.1 — échecs de connexion : chaque texte nomme sa cause par un mot clair.
  'auth.login_invalid': 'Le carnet ne te reconnaît pas : identifiants invalides.',
  'auth.login_reset_required':
    'Ce compte doit être réinitialisé : utilise « Mot de passe oublié ? » pour rouvrir le carnet.',
  'auth.login_throttled': 'Trop de tentatives. Patiente une minute avant de retenter ta chance.',
  'auth.login_unavailable':
    'Le carnet est indisponible pour le moment. Réessaie dans quelques instants.',
  'auth.login_unexpected': 'Une erreur est survenue. Réessaie.',
  // Story 34.2 — libellés du bouton de révélation du mot de passe : neutres, non thématisés.
  'auth.password_show': 'Afficher le mot de passe',
  'auth.password_hide': 'Masquer le mot de passe',
  // Story 34.3 — ligne d'orientation de la connexion et messages de validation des formulaires
  // d'authentification : libellé neutre de référence, identique dans les trois thèmes (chacun nomme
  // la règle) ; l'habillage thématique relève de la revue éditoriale de l'épic 35.
  'auth.login_invite_only': "L'inscription se fait sur invitation.",
  'auth.field_required': 'Renseignez ce champ.',
  'auth.field_email_invalid': 'Adresse e-mail invalide.',
  'auth.field_pseudo_min': '3 caractères minimum.',
  'auth.field_password_min': '8 caractères minimum.',
  // Story 34.4 — accroche de la bande d'authentification : une par thème (EXPERIENCE.md §3).
  'auth.tagline': 'Un feu de camp, des amis, et une date qui arrange tout le monde',
  'account.calendar_layers_title': 'Ce que montre mon calendrier',
  'account.calendar_layer.mes-indisponibilites': 'Mes indisponibilités',
  'account.calendar_layer.mes-disponibilites': 'Mes disponibilités',
  'account.calendar_layer.mes-seances': 'Mes séances confirmées',
  'account.calendar_layer.votes-en-cours': 'Les votes en cours',
  'account.calendar_layer.inscriptions-ouvertes': 'Les inscriptions ouvertes',
  'account.calendar_layer.disponibilite-groupe': 'La disponibilité du groupe',
  /* — vue Agenda (Story 36.11) — badges contractuels (EXPERIENCE.md §5), titres thématisés. */
  'calendar.agenda.section_awaiting': 'Ce qui t’attend',
  'calendar.agenda.section_scheduled': 'Ce qui est prévu',
  'calendar.agenda.section_past': 'Ce qui est derrière',
  'calendar.agenda.badge_answer_poll': 'Réponds au vote',
  'calendar.agenda.badge_poll_open': 'Vote en cours',
  'calendar.agenda.badge_signup': 'S’inscrire',
  'calendar.agenda.badge_signed_up': 'Inscrit',
  'calendar.agenda.badge_debrief': 'Débriefer',
  'calendar.agenda.empty': 'Rien ne t’attend, rien n’est prévu.',
  /* — Agenda du MJ (Story 36.12) — libellés d'état contractuels, appels à l'action thématisés. */
  'calendar.agenda.badge_to_seal': 'À sceller',
  'calendar.agenda.poll_open': 'Vote ouvert',
  'calendar.agenda.responded_count': '{n} sur {total} ont répondu',
  'calendar.agenda.slots_proposed': '{n} créneaux proposés',
  'calendar.agenda.missing_voters': 'il manque {names}',
  'calendar.agenda.no_date': 'sans date',
  'calendar.agenda.no_date_proposed': 'Aucune date proposée',
  'calendar.agenda.action_launch_poll': 'Lancer un vote',
  'calendar.agenda.action_seal': 'Planter',
  'calendar.agenda.action_expand': 'Déployer',
  'calendar.agenda.action_collapse': 'Replier',
  'calendar.agenda.seal_confirm_title': 'Planter le drapeau sur ce créneau ?',
  'calendar.agenda.seal_confirm_body':
    'La séance se tiendra à ce créneau et le vote se refermera. Les autres créneaux proposés disparaîtront.',
  /* — Story 36.14 : la barre repliée, le panneau « Affichage » et la légende —
     🚨 Ces libellés sont IDENTIQUES dans les trois thèmes, comme les six
     `account.calendar_layer.*` : le contrat d'UI les fixe verbatim
     (`contrat-ui-calendrier.html:599-609`, `:655-665`, `:683-686`). La clé existe pour qu'un
     thème futur puisse les teinter — même motif que `cta.destiny_mode` (story 36.9). */
  'calendar.display.trigger': 'Affichage',
  'calendar.display.trigger_aria': "Régler l'affichage du calendrier",
  'calendar.display.section_visible': 'Ce que je vois',
  'calendar.display.show_legend': 'Afficher la légende',
  'calendar.display.filtered_badge': 'Affichage filtré · {n} sur {total} · Rétablir',
  'calendar.legend.title': 'Légende',
  'calendar.legend.group_obvious': 'Se passent d’explication',
  'calendar.legend.group_needs': 'Demandent la légende',
  'calendar.legend.entry.available': 'Je suis disponible',
  'calendar.legend.entry.unavailable': 'Je suis indisponible',
  'calendar.legend.entry.seance': 'Séance confirmée — tu es pris',
  'calendar.legend.entry.vote': 'Créneau proposé au vote',
  'calendar.legend.entry.poll_track': 'Participation : la piste = la troupe',
  'calendar.legend.entry.group': 'Disponibilité du groupe',
  'calendar.legend.entry.none': 'Personne ne s’est prononcé',
  'account.calendar_intents_subtitle': 'Ce que je veux voir en arrivant sur un calendrier.',
  'account.calendar_intent.disponibilites': 'Mes disponibilités & indisponibilités',
  'account.calendar_intent.seances': 'Mes séances confirmées',
  'account.calendar_intent.votes': 'Les votes en cours',
  'account.calendar_intent.groupe': 'La disponibilité du groupe',
  /* — identité — */
  'identity.character_label': 'Personnage',
  'identity.player_label': 'Joueur',
  'identity.homonymy_warning':
    'Un autre voyageur de cette expédition porte le même nom affiché que toi.',
  'identity.homonymy_change_cta': 'Changer mon nom affiché',
  'identity.homonymy_ignore_cta': 'Ignorer',
};
