// Thème de référence : son objet fixe les clés de ton que les autres thèmes doivent porter
// (cf. `ToneKey`). Toute nouvelle clé s'ajoute ici d'abord ; un thème qui l'omet ne compile plus.
export const grimoireEmeraude = {
  /* — navigation — */
  'nav.my_games': 'Mes aventures',
  'nav.create_game': 'Lancer une quête',
  'nav.logout': 'Fermer le grimoire',
  'nav.calendar': 'Calendrier',
  'nav.account': 'Mon grimoire',
  'nav.characters': 'Personnages',
  /* — dashboard — */
  'dashboard.title_invitations': 'Invitations reçues',
  'dashboard.empty': 'Nulle quête en cours. Forgez la première…',
  'dashboard.role_prefix': 'Rang :',
  'dashboard.role_mj': 'Maître',
  'dashboard.role_player': 'Héros',
  'dashboard.status_closed_badge': 'Terminée',
  /* — signalétique d'état (Story 29.7) — */
  'dashboard.section_awaiting': 'Ce qui t’attend',
  'dashboard.section_ongoing': 'En cours',
  'dashboard.section_upcoming': 'À venir',
  'dashboard.section_finished': 'Terminées',
  /* — filtres, tri, favoris (Story 29.8) — */
  'dashboard.empty_filtered': 'Aucun grimoire ne répond à ces critères.',
  'dashboard.controls_toggle_aria': 'Afficher les filtres et le tri',
  'dashboard.filter_role_label': 'Rang',
  'dashboard.filter_role_all': 'Tous',
  'dashboard.filter_status_label': 'Statut',
  'dashboard.filter_status_all': 'Tous',
  'dashboard.sort_label': 'Trier par',
  'dashboard.sort_urgence': 'Urgence',
  'dashboard.sort_date': 'Date',
  'dashboard.sort_nom': 'Nom',
  'dashboard.sort_type': 'Type',
  'dashboard.sort_statut': 'Statut',
  'dashboard.hide_finished_label': 'Masquer les grimoires clos',
  'dashboard.show_finished_btn': 'Afficher les grimoires clos',
  'dashboard.favorite_add_aria': 'Marquer comme favori',
  'dashboard.favorite_remove_aria': 'Retirer des favoris',
  /* — barre de contrôles partagée (Story 29.9) — */
  'dashboard.search_label': 'Rechercher un grimoire',
  'dashboard.row_signal_count_aria': '{n} chose(s) à faire',
  'list_control_bar.toggle_aria': 'Afficher les filtres et le tri',
  'list_control_bar.view_mode_group_aria': 'Densité d’affichage',
  'list_control_bar.view_mode_large_aria': 'Grande vignette',
  'list_control_bar.view_mode_medium_aria': 'Vignette intermédiaire',
  'list_control_bar.view_mode_compact_aria': 'Liste compacte',
  'list_control_bar.sort_label': 'Trier par',
  'list_control_bar.reset_pill_label': 'Réglages modifiés',
  /* — my-characters (Story 29.2) — */
  'my_characters.title': 'Mes personnages',
  'my_characters.empty': 'Nul personnage forgé. Créez-en un depuis une quête…',
  'my_characters.no_match': 'Aucun personnage ne répond à cette recherche.',
  'my_characters.search_label': 'Rechercher un personnage',
  'my_characters.sort_niveau': 'Niveau',
  'my_characters.sort_partie': 'Partie',
  'my_characters.sort_nom': 'Nom',
  /* — section de création (Story 29.16) — */
  'my_characters.create_title': 'À forger',
  'my_characters.create_entry': 'Créer un voyageur pour {partie}',
  'my_characters.create_more': 'Voir les {n} autres',
  'my_characters.create_more_one': 'Voir l’autre',
  'my_characters.create_less': 'Voir moins',
  'my_characters.empty_with_entries': 'Nul voyageur forgé pour l’instant.',
  /* — ligne de création de l'Homme Dragon (Story 33.5) — */
  'my_characters.create_entry_hd': 'Créer un Homme Dragon pour {partie}',
  /* — partie-form — */
  'partie.new_title': 'Nouvelle quête',
  'partie.edit_title': 'Retranscrire le parchemin',
  'partie.save_btn': 'Inscrire',
  'partie.cancel_btn': 'Refermer',
  'partie.name_label': 'Nom du grimoire',
  'partie.system_label': 'Système de jeu',
  'partie.kind_label': 'Nature de la quête',
  'partie.description_label': 'Préambule (facultatif)',
  'partie.kind_ONE_SHOT': 'Quête unique',
  'partie.kind_CAMPAGNE_LINEAIRE': 'Chronique',
  'partie.kind_CAMPAGNE_EPISODIQUE': 'Chronique épisodique',
  'partie.kind_refusal_closed': 'Ce grimoire est clos. Rouvrez-le avant d’en changer la nature.',
  'partie.kind_refusal_too_many_scenarios':
    'Ce grimoire compte {count} scénarios ; une quête unique n’en porte qu’un.',
  'partie.courant_choice_title': 'Quel scénario reste en cours ?',
  'partie.courant_choice_help':
    'Une chronique ne suit qu’un scénario à la fois. Les autres repasseront « à venir » — leurs séances et leurs dates sont conservées.',
  'partie.courant_choice_confirm': 'Sceller ce choix',
  'partie.cover_add': 'Enluminer ce grimoire',
  'partie.cover_change': 'Changer l’enluminure',
  'partie.cover_remove': 'Retirer l’enluminure',
  'partie.cover_uploading': 'L’enluminure se fixe sur le parchemin…',
  'partie.cover_upload_error': 'L’enluminure n’a pu être fixée. Réessayez.',
  'partie.cover_remove_error': 'L’enluminure n’a pu être retirée. Réessayez.',
  'partie.cover_reject_type': 'Seules les images JPEG, PNG et WEBP peuvent enluminer un grimoire.',
  'partie.cover_reject_size': 'Cette image dépasse 5 Mo : choisissez-en une plus légère.',
  'partie.save_error': 'Ce grimoire n’a pu être inscrit. Réessayez.',
  'partie.created_but_cover_failed':
    'Le grimoire est bien inscrit, mais son enluminure n’a pu être fixée. Vous pouvez la redéposer ici.',
  'partie.fields_saved_but_convert_failed':
    'Les autres modifications sont enregistrées, mais la nature du grimoire n’a pu être changée. Réessayez.',
  /* — partie-detail — */
  'partie.scheduling_title': 'Prochaine séance',
  'partie.no_session': "Aucune séance convoquée. Consultez l'oracle des créneaux.",
  'partie.members_title': '⚔ Compagnons',
  'partie.no_members': "Nulle âme pour l'instant.",
  'partie.remove_member_btn': 'Retirer',
  'partie.no_description': 'Ce grimoire est muet.',
  'partie.invite_title': 'Convoquer un compagnon',
  'partie.search_label': 'Nom ou signe distinctif',
  'partie.search_btn': 'Scruter',
  'partie.invite_btn': 'Convoquer',
  'partie.links_title': "Parchemins d'invocation",
  'partie.generate_link': 'Tisser un parchemin',
  'partie.notice_invited': 'Missive envoyée à {name}.',
  'partie.invite_by_email_label': 'Adresse du destinataire',
  'partie.invite_by_email_btn': 'Envoyer une missive',
  'partie.notice_invited_email': 'Missive envoyée à {email}.',
  'partie.notice_invite_email_error': "La missive n'a pu être envoyée. Réessayez.",
  'partie.reference_sheets_title': 'Grimoires de référence',
  'partie.asset_journal_cta': 'Journal',
  'partie.asset_carte_cta': 'Carte',
  'partie.asset_download_error': "Ce grimoire n'a pas pu être déterré. Réessayez.",
  'partie.prep_sheets_title': 'Grimoires de préparation (MJ)',
  'partie.asset_monde_cta': 'Monde',
  'partie.asset_monstre_cta': 'Monstre',
  'partie.asset_ville_cta': 'Ville',
  'partie.asset_objectif_chasse_cta': 'Objectif — Chasse',
  'partie.asset_objectif_quete_cta': 'Objectif — Quête',
  'partie.asset_objectif_voyage_cta': 'Objectif — Voyage',
  'partie.asset_oeuf_de_bataille_cta': 'Œuf de bataille',
  'partie.asset_structure_cta': 'Structure',
  /* — zones de l'onglet Détails (Story 32.2) — noms CONTRACTUELS, identiques dans les trois
     thèmes (même principe que cta.destiny_mode, Story 36.9) : ce sont les trois catégories que
     l'épic nomme explicitement (Action/Consultation/Référence), pas un intitulé libre à décliner
     par thème. La clé existe pour qu'un thème futur puisse malgré tout les teinter. */
  'partie.details_zone_action': 'Action',
  'partie.details_zone_consultation': 'Consultation',
  'partie.details_zone_reference': 'Référence',
  /* — états de scénario et de séance (Story 32.3) — noms CONTRACTUELS, IDENTIQUES dans les trois
     thèmes, exactement comme les trois zones ci-dessus et `cta.destiny_mode` (story 36.9) : ce
     sont des noms d'état fixés par la conception, pas des intitulés à décliner par univers. La
     clé existe pour qu'un thème futur puisse malgré tout les teinter.
     🚨 « Courant », JAMAIS « En cours » : le bouton voisin de `scenario-editor` dit déjà
     « Marquer comme Courant », et « en cours » reste réservé au VOTE — deux choses différentes
     ne peuvent pas porter le même mot.
     🚨 La paire vote répondu / non répondu porte DEUX libellés distincts (contrat EXPERIENCE.md
     §5, déjà appliqué par l'Agenda) : la teinte ne doit jamais être la seule différence. */
  'status.scenario_brouillon': 'Brouillon',
  'status.scenario_a_venir': 'À venir',
  'status.scenario_courant': 'Courant',
  'status.scenario_passe': 'Passé',
  'status.seance_a_planifier': 'À planifier',
  'status.seance_answer_poll': 'Réponds au vote',
  'status.seance_poll_open': 'Vote en cours',
  'status.seance_inscriptions_ouvertes': 'Inscriptions ouvertes',
  'status.seance_programmee': 'Programmée',
  'status.seance_a_debriefer': 'À débriefer',
  'status.seance_jouee': 'Jouée',
  'partie.notice_copy': 'Parchemin copié dans la besace.',
  'partie.edit_btn': 'Retranscrire',
  'partie.visibility_btn': 'Sceller des secrets',
  'partie.close_btn': 'Clore le grimoire',
  'partie.reopen_btn': 'Rouvrir le grimoire',
  'partie.status_closed_label': 'Ce grimoire est clos.',
  /* — signaux d'état (Story 29.7, FR-12) — */
  'partie.signal_personnage_a_creer': 'Créer son héros',
  'partie.signal_vote_en_cours_sans_reponse': 'Vote en attente',
  'partie.signal_compte_rendu_non_redige': 'Compte-rendu à écrire',
  'partie.signal_homme_dragon_a_creer': 'Créer son Homme Dragon',
  'partie.signal_aucun_membre_invite': 'Aucun compagnon convoqué',
  'partie.signal_aucun_scenario_en_cours': 'Aucune quête en cours',
  'partie.signal_aucune_date_ni_vote': 'Aucune date ni vote',
  'partie.signal_rapport_fin_manquant': 'Récit de fin manquant',
  'partie.signal_prochaine_seance_connue': 'Prochaine séance connue',
  'partie.signal_partie_terminee': 'Grimoire clos',
  'partie.signal_more_count': '+{n}',
  'partie.delete_btn': 'Brûler le parchemin',
  'partie.invitations_tab_label': 'Invitations',
  'partie.show_troupe': 'Voir la troupe',
  'partie.hide_troupe': 'Masquer la troupe',
  /* — calendrier & vote — */
  'cta.find_date': "Consulter l'oracle des créneaux",
  'cta.guild_calendar': 'Voir le grimoire des disponibilités',
  'cta.launch_vote': 'Ouvrir le parchemin du vote',
  'cta.save_constraint': 'Inscrire dans le grimoire',
  'cta.send_reminder': 'Envoyer une missive',
  'section.slots': 'Fenêtres de la destinée',
  'section.constraints': 'Contraintes inscrites',
  'empty.no_slots': "L'oracle ne voit aucun créneau libre. Les parchemins manquent de données.",
  'empty.no_constraints': 'Aucune contrainte inscrite dans le grimoire.',
  'success.constraint_saved': 'Contrainte gravée dans le parchemin.',
  'alert.expiring_soon': 'Votre parchemin expire bientôt. Renouvelez le sort.',
  'alert.missing_player': "{name} n'a pas encore consulté l'oracle.",
  'status.unavailable_label': 'Indisponible',
  'status.unknown_label': 'Mystère',
  'cta.choose_date': 'Sceller ce créneau',
  'cta.cancel_poll': 'Brûler le parchemin de vote',
  'cta.restore_default_layers': 'Rétablir mon grimoire par défaut',
  'empty.no_poll': 'Aucun vote en cours dans ce grimoire.',
  'success.poll_created': 'Vote ouvert. Les membres ont été avertis.',
  'success.date_chosen': 'La date est gravée dans le grimoire.',
  'poll.status_title': 'Vote en cours',
  'poll.vote_pending': 'Vote de date en cours — parchemin en attente',
  'success.vote_cast': 'Réponse inscrite dans le grimoire.',
  'cta.confirm_votes': 'Sceller mes réponses',
  'cta.withdraw_vote': 'Retirer ma réponse',
  'success.vote_withdrawn': 'Réponse retirée du grimoire.',
  'poll.withdraw_error': 'Le retrait a échoué. Réessayez.',
  'poll.cast_error': 'Impossible d’enregistrer ta réponse. Réessayez.',
  'poll.vote_closed': "Ce vote est clos. L'oracle a tranché.",
  'alert.all_responded': 'Tous les compagnons ont répondu au vote.',
  'poll.status_summary': 'Vote ouvert — {responded}/{total} compagnons ont répondu',
  /* — mode Destinée et panneau réduit (Story 36.9) — */
  // Nom du MODE, identique dans les trois thèmes : « ✦ Destinée » est le nom que la spec lui
  // donne (EXPERIENCE.md §4.4 ter), au même titre que « Vue mois ». La clé existe pour qu'un
  // thème futur puisse le teinter, pas pour qu'il change aujourd'hui.
  'cta.destiny_mode': 'Destinée',
  'poll.missing_prefix': 'N’ont pas consulté l’oracle :',
  'poll.responded_prefix': 'Ont consulté l’oracle :',
  /* — annonces (Epic 9) — */
  'announcement.scope_campaign_label': 'Toute la campagne',
  'announcement.scope_oneshot_label': 'Cette quête',
  'announcement.scope_scenario_label': 'Ce chapitre',
  'announcement.publish_cta': 'Proclamer une annonce',
  'announcement.text_placeholder': 'Rédiger une annonce...',
  'announcement.published_notice': 'Annonce proclamée.',
  'announcement.unseen_label': 'Non lue — cliquez pour marquer comme lue',
  /* — personnages (Palier P3) — */
  'character.create_cta': 'Créer un voyageur',
  'character.choice_deselect_hint': 'Toucher pour désélectionner',
  'character.choice_talents_label': 'Talents',
  'character.choice_advantages_label': 'Avantages',
  'character.choice_required_flag': 'Obligatoire',
  'character.choice_reference_toggle': 'Occupations et actions',
  'character.equipment_group_toggle': '{group}, {n} objets',
  'character.equipment_filter_all': 'Tout',
  'character.equipment_filter_mine': 'Ma sélection',
  'character.equipment_qty_less': 'Retirer un exemplaire de {name}',
  'character.equipment_qty_more': 'Ajouter un exemplaire de {name}',
  'character.recap_button': 'Récap',
  'character.recap_title': 'Récapitulatif',
  'character.recap_cart_title': 'Panier',
  'character.recap_remove': 'Retirer',
  'character.recap_total': 'Total',
  'character.recap_empty_hint':
    'Les statistiques dérivées apparaîtront une fois les attributs assignés.',
  'detail.row_attributes': 'Attributs',
  'detail.row_difficulty': 'Difficulté',
  'detail.row_effect': 'Effet',
  'detail.row_conditions': 'Conditions',
  'detail.narrative_show': 'Lire le récit',
  'detail.narrative_hide': 'Masquer le récit',
  'character.equipment_group_individual': 'Objets',
  'character.equipment_group_contenant': 'Contenants',
  'character.equipment_group_animal': 'Animaux',
  'character.equipment_search_label': 'Rechercher un objet',
  'character.equipment_search_placeholder': 'Rechercher un objet…',
  'character.equipment_budget': 'Budget · {spent} / {total} Po',
  'character.equipment_over_budget': '— dépassement de {n} Po',
  'character.equipment_search_empty': 'Aucun objet ne répond à cet appel…',
  'character.tab_label': 'Personnages',
  'character.step_class': 'Choisir sa vocation',
  'character.step_type': 'Choisir sa voie',
  'character.step_magic': 'Sceller son lien avec la magie',
  'character.step_portrait_intro':
    'Ajoute un portrait si tu le souhaites — cette étape est entièrement facultative et peut être passée à tout moment.',
  'character.portrait_missing': 'Aucun portrait — le conteur imagine un visage',
  'character.portrait_edit_cta': 'Modifier le portrait',
  'character.pdf_crop_edit_cta': 'Ajuster le cadrage PDF',
  'character.sheet_menu_trigger_aria': 'Actions de la fiche',
  'character.export_editable_cta': 'Exporter en PDF (éditable)',
  'character.export_2pages_cta': 'Exporter en PDF (2 pages)',
  'character.export_equipment_cta': "Exporter l'équipement en PDF",
  'character.export_notes_cta': 'Exporter les notes en PDF',
  'character.export_error': "Le parchemin n'a pas pu être copié. Réessayez.",
  'character.owner_badge_mj': 'Maître',
  /* « Homme Dragon » est un nom propre du système : jamais thématisé (Story 33.5). */
  'character.nature_dragon': 'Homme Dragon',
  'character.level_badge': 'Niv. {n}',
  'character.party_sheets_tab_label': 'Fiches',
  /* — bouton retour vers la partie depuis la fiche d'un personnage — */
  'character.back_to_partie_cta': 'Retour à la partie',
  /* — état vide "Fiches" (Story 29.15) — */
  'character.no_character_yet': 'Aucun personnage créé sur cette partie pour l’instant.',
  /* — Homme Dragon (Epic 10, Story 10.1) — */
  'homme-dragon.create_cta': 'Créer mon Homme Dragon',
  'homme-dragon.race_label': 'Race',
  'homme-dragon.artefact_label': 'Artefact',
  'homme-dragon.created_notice': 'Votre Homme Dragon a pris vie.',
  /* — roster (Story 6.1) — */
  'roster.mj_badge': 'MJ',
  'roster.invite_slot': 'Convier un compagnon',
  'roster.collapse_label': 'Replier la troupe',
  'roster.expand_label': 'Déplier la troupe',
  'roster.levelup_badge': 'Montée de niveau disponible',
  /* — slot d'initiale « créer mon personnage » (Story 29.15) — */
  'roster.create_slot_label': 'créer mon personnage',
  /* — évolution du personnage (Story 6.2) — */
  'evolution.xp_distribute_cta': "Distribuer de l'XP",
  'evolution.xp_panel_title': "Distribution d'XP",
  'evolution.xp_history_title': "Historique des distributions d'XP",
  'evolution.xp_history_empty': 'Aucune distribution gravée pour le moment.',
  'evolution.xp_note_label': 'Note de session',
  'evolution.xp_confirm_btn': 'Sceller la distribution',
  'evolution.xp_bonus_link': '+ bonus',
  'evolution.xp_levelup_warning': '{name} franchira un niveau',
  /* — montée de niveau & historique (Story 6.3) — */
  'evolution.levelup_banner': 'Niveau [N] disponible !',
  'evolution.levelup_cta': 'Level up !',
  'evolution.levelup_wizard_title': 'Montée de niveau',
  'evolution.levelup_step_pv_pe': 'Répartir 3 points entre PV et PE',
  'evolution.levelup_step_capability': 'Choisir la capacité débloquée',
  'evolution.levelup_legendary_journey_text':
    'Un voyage légendaire vous attend — aucun choix supplémentaire à faire.',
  'evolution.levelup_confirm_cta': 'Valider ce niveau',
  /* — sous-navigation locale de la fiche (Story 29.5) — */
  'evolution.main_sheet_tab_label': 'Fiche',
  'evolution.history_tab_label': 'Historique',
  'evolution.history_empty': 'Aucun instantané pour le moment.',
  'evolution.mj_edit_trace': 'modifié par le MJ',
  'evolution.landscape_section_title': 'Paysage/Climat favori',
  'evolution.immunity_section_title': 'Immunités',
  'evolution.other_capabilities_title': 'Autres capacités',
  'evolution.derived_hidden': 'Statistiques masquées par le MJ',
  'evolution.hidden_marker': 'Masqué par le MJ',
  /* — inventaire chiffré (Story 6.4) — */
  'evolution.inventory_section_title': 'Inventaire',
  'evolution.inventory_add_cta': '+ Ajouter un objet',
  'evolution.inventory_empty': "Aucun objet dans l'inventaire pour le moment.",
  'evolution.inventory_overweight_label': 'Surchargé',
  'evolution.inventory_error': "L'inventaire n'a pas pu être mis à jour. Réessayez.",
  /* — édition MJ sans contrainte (Story 6.6) — */
  'evolution.mj_edit_error': "L'édition n'a pas pu être enregistrée. Réessayez.",
  'evolution.mj_edit_warning_prefix': 'Avertissement : ',
  'evolution.inventory_mj_add_cta': '+ Ajouter un objet (MJ)',
  'evolution.narrative_edit_error': "La modification n'a pas pu être enregistrée. Réessayez.",
  /* — journal de notes personnelles (Story 6.5) — */
  'evolution.notes_journal_title': 'Journal de notes',
  'evolution.notes_journal_empty': 'Aucune note pour le moment.',
  'evolution.notes_add_cta': '+ Ajouter une entrée',
  'evolution.note_share_toggle': 'Partager avec le groupe',
  'evolution.note_private_label': 'Entrée privée',
  'evolution.note_shared_label': 'Entrée partagée avec le groupe',
  'evolution.notes_error': "Le journal n'a pas pu être mis à jour. Réessayez.",
  /* — compte — */
  'account.title': 'Mon grimoire personnel',
  'account.pseudo_label': 'Signe de reconnaissance',
  'account.email_label': 'Sceau de correspondance',
  'account.display_name_label': 'Nom affiché aux autres voyageurs',
  'account.save_btn': 'Sceller',
  'account.cancel_btn': 'Renoncer',
  'account.saved': 'Le grimoire a retenu ce nom.',
  'account.error': "Le grimoire n'a pas pu retenir ce changement. Réessayez.",
  'account.password_title': 'Renouveler le sortilège de passage',
  'account.current_password_label': 'Sortilège actuel',
  'account.new_password_label': 'Nouveau sortilège',
  'account.password_save_btn': 'Renouveler',
  'account.password_saved': 'Le sortilège de passage a été renouvelé.',
  'account.password_wrong_current': "Ce sortilège n'est pas le bon.",
  'account.password_error': "Le grimoire n'a pas pu renouveler le sortilège. Réessayez.",
  'account.email_change_title': 'Changer de sceau de correspondance',
  'account.current_password_for_email_label': 'Sortilège actuel',
  'account.new_email_label': 'Nouveau sceau de correspondance',
  'account.email_change_save_btn': 'Envoyer le message',
  'account.email_change_saved': 'Un message est parti vers le nouveau sceau.',
  'account.email_change_wrong_current': "Ce sortilège n'est pas le bon.",
  'account.email_change_taken': 'Un autre voyageur porte déjà ce sceau.',
  'account.email_change_error': "Le grimoire n'a pas pu envoyer la demande. Réessayez.",
  // Story 34.1 — échecs de connexion : chaque texte nomme sa cause par un mot clair.
  'auth.login_invalid': 'Le grimoire ne vous reconnaît pas : identifiants invalides.',
  'auth.login_reset_required':
    'Ce compte doit être réinitialisé : utilisez « Mot de passe oublié ? » pour rouvrir le grimoire.',
  'auth.login_throttled':
    'Trop de tentatives. Patientez une minute avant de frapper de nouveau à la porte du grimoire.',
  'auth.login_unavailable':
    'Le grimoire est indisponible pour le moment. Réessayez dans quelques instants.',
  'auth.login_unexpected': 'Une erreur est survenue. Réessayez.',
  // Story 34.2 — libellés du bouton de révélation du mot de passe : neutres, non thématisés.
  'auth.password_show': 'Afficher le mot de passe',
  'auth.password_hide': 'Masquer le mot de passe',
  // Story 34.3 — ligne d'orientation de la connexion et messages de validation des formulaires
  // d'authentification : libellé neutre de référence, identique dans les trois thèmes (chacun nomme
  // la règle) ; l'habillage thématique relève de la revue éditoriale de l'épic 35.
  'auth.login_invite_only': "L'inscription se fait sur invitation.",
  'auth.field_required': 'Renseignez ce champ.',
  'auth.field_email_invalid': 'Adresse e-mail invalide.',
  'auth.field_pseudo_min': '3 caractères minimum.',
  'auth.field_password_min': '8 caractères minimum.',
  // Story 34.4 — accroche de la bande d'authentification : une par thème (EXPERIENCE.md §3).
  'auth.tagline': "Trouvez le soir où le grimoire s'ouvre",
  'account.calendar_layers_title': 'Ce que révèle mon calendrier',
  'account.calendar_layer.mes-indisponibilites': 'Mes indisponibilités',
  'account.calendar_layer.mes-disponibilites': 'Mes disponibilités',
  'account.calendar_layer.mes-seances': 'Mes séances confirmées',
  'account.calendar_layer.votes-en-cours': 'Les votes en cours',
  'account.calendar_layer.inscriptions-ouvertes': 'Les inscriptions ouvertes',
  'account.calendar_layer.disponibilite-groupe': 'La disponibilité du groupe',
  /* — vue Agenda (Story 36.11) — les libellés de BADGE sont contractuels et identiques dans
     les trois thèmes : EXPERIENCE.md §5 impose « Réponds au vote » / « Vote en cours » comme
     la paire qui distingue à-faire et fait. Seuls les titres de section et le vide varient. */
  'calendar.agenda.section_awaiting': 'Ce qui t’attend',
  'calendar.agenda.section_scheduled': 'Ce qui est annoncé',
  'calendar.agenda.section_past': 'Ce qui est révolu',
  'calendar.agenda.badge_answer_poll': 'Réponds au vote',
  'calendar.agenda.badge_poll_open': 'Vote en cours',
  'calendar.agenda.badge_signup': 'S’inscrire',
  'calendar.agenda.badge_signed_up': 'Inscrit',
  'calendar.agenda.badge_debrief': 'Débriefer',
  'calendar.agenda.empty': 'Rien ne t’attend, rien n’est annoncé.',
  /* — Agenda du MJ (Story 36.12) — même règle : les LIBELLÉS D'ÉTAT et les gabarits chiffrés
     sont contractuels et identiques partout, seuls les titres et les appels à l'action
     prennent le registre du thème. */
  'calendar.agenda.badge_to_seal': 'À sceller',
  'calendar.agenda.poll_open': 'Vote ouvert',
  'calendar.agenda.responded_count': '{n} sur {total} ont répondu',
  'calendar.agenda.slots_proposed': '{n} créneaux proposés',
  'calendar.agenda.missing_voters': 'il manque {names}',
  'calendar.agenda.no_date': 'sans date',
  'calendar.agenda.no_date_proposed': 'Aucune date proposée',
  'calendar.agenda.action_launch_poll': 'Lancer un vote',
  'calendar.agenda.action_seal': 'Sceller',
  'calendar.agenda.action_expand': 'Déplier',
  'calendar.agenda.action_collapse': 'Replier',
  'calendar.agenda.seal_confirm_title': 'Sceller ce créneau ?',
  'calendar.agenda.seal_confirm_body':
    'La séance sera fixée à ce créneau et le vote se refermera. Les autres créneaux proposés disparaîtront.',
  /* — Story 36.14 : la barre repliée, le panneau « Affichage » et la légende —
     🚨 Ces libellés sont IDENTIQUES dans les trois thèmes, comme les six
     `account.calendar_layer.*` : le contrat d'UI les fixe verbatim
     (`contrat-ui-calendrier.html:599-609`, `:655-665`, `:683-686`). La clé existe pour qu'un
     thème futur puisse les teinter — même motif que `cta.destiny_mode` (story 36.9). */
  'calendar.display.trigger': 'Affichage',
  'calendar.display.trigger_aria': "Régler l'affichage du calendrier",
  'calendar.display.section_visible': 'Ce que je vois',
  'calendar.display.show_legend': 'Afficher la légende',
  'calendar.display.filtered_badge': 'Affichage filtré · {n} sur {total} · Rétablir',
  'calendar.legend.title': 'Légende',
  'calendar.legend.group_obvious': 'Se passent d’explication',
  'calendar.legend.group_needs': 'Demandent la légende',
  'calendar.legend.entry.available': 'Je suis disponible',
  'calendar.legend.entry.unavailable': 'Je suis indisponible',
  'calendar.legend.entry.seance': 'Séance confirmée — tu es pris',
  'calendar.legend.entry.vote': 'Créneau proposé au vote',
  'calendar.legend.entry.poll_track': 'Participation : la piste = la troupe',
  'calendar.legend.entry.group': 'Disponibilité du groupe',
  'calendar.legend.entry.none': 'Personne ne s’est prononcé',
  'account.calendar_intents_subtitle': 'Ce que je veux voir en arrivant sur un calendrier.',
  'account.calendar_intent.disponibilites': 'Mes disponibilités & indisponibilités',
  'account.calendar_intent.seances': 'Mes séances confirmées',
  'account.calendar_intent.votes': 'Les votes en cours',
  'account.calendar_intent.groupe': 'La disponibilité du groupe',
  /* — identité — */
  'identity.character_label': 'Personnage',
  'identity.player_label': 'Joueur',
  'identity.homonymy_warning':
    'Un autre membre de cette partie porte le même nom affiché que vous.',
  'identity.homonymy_change_cta': 'Changer mon nom affiché',
  'identity.homonymy_ignore_cta': 'Ignorer',
};

/** Ensemble des clés de ton, dérivé du thème de référence. */
export type ToneKey = keyof typeof grimoireEmeraude;
