// Thème de référence : son objet fixe les clés de ton que les autres thèmes doivent porter
// (cf. `ToneKey`). Toute nouvelle clé s'ajoute ici d'abord ; un thème qui l'omet ne compile plus.
//
// Les clés sont regroupées par fonctionnalité, dans le MÊME ordre et sous les mêmes titres dans les
// trois fichiers de thème : un thème se relit d'un seul tenant, sans ouvrir un autre fichier.
//
// VOIX — Grimoire Émeraude : magie, bibliothèque, parchemins. VOUVOIEMENT partout (jamais « tu »).
// Vocabulaire : grimoire (la partie), chapitre (le scénario), voyageur (le personnage), compagnon,
// Maître (le MJ), oracle, sceau, sortilège, parchemin, missive, enluminure, sceller, inscrire.
// Textes CONTRACTUELS, identiques dans les trois thèmes : `status.*`, `character.nature_dragon`,
// `auth.password_*`, `auth.field_*`, badges de l'Agenda — voir docs/textes-classement.md.
// Les autres textes volontairement identiques sont recensés par NEUTRAL_KEYS (theme-tone.service.spec.ts) :
// une clé identique dans les trois thèmes hors de cette liste fait échouer les tests.
export const grimoireEmeraude = {
  /* ═══ Navigation et coque ═══ */
  /* — menu principal — */
  'nav.my_games': 'Mes aventures',
  'nav.create_game': 'Lancer une quête',
  'nav.logout': 'Fermer le grimoire',
  'nav.calendar': 'Almanach',
  'nav.account': 'Mon grimoire',
  'nav.characters': 'Personnages',
  /* — coque de l’application — */
  'shell.nav_main_aria': 'Navigation principale du grimoire',
  'shell.banner_close_aria': 'Fermer la missive de {partie}',
  'shell.badge_polls_aria': '{n} vote(s) attendent votre réponse',
  'shell.badge_announcements_aria': '{n} proclamation(s) non lue(s)',
  /* — titres de route — */
  'route.title_confirm_email_change': 'Confirmer le changement de sceau',
  'route.title_rollback_email_change': 'Annuler le changement de sceau',
  /* — surfaces partagées — */
  'shared.detail_close_window': 'Refermer la fenêtre du grimoire',
  'shared.detail_close_sheet': 'Refermer le folio',
  /* — barre de contrôles des listes — */
  'list_control_bar.toggle_aria': 'Afficher les filtres et le tri de l’index',
  'list_control_bar.view_mode_group_aria': 'Densité de lecture',
  'list_control_bar.view_mode_large_aria': 'Grand folio',
  'list_control_bar.view_mode_medium_aria': 'Folio intermédiaire',
  'list_control_bar.view_mode_compact_aria': 'Index compact',
  'list_control_bar.sort_label': 'Ranger par',
  'list_control_bar.reset_pill_label': 'Réglages altérés',

  /* ═══ Textes communs ═══ */
  /* — actions et mots courants — */
  'common.8_caracteres': '8 caractères au moins',
  'common.a_savoir': 'Note du scribe',
  'common.accepter': 'Accepter l’invitation',
  'common.ajouter': 'Ajouter au grimoire',
  'common.ajouter_une_aventure': 'Inscrire une aventure',
  'common.annonces': 'Proclamations',
  'common.annuler': 'Renoncer',
  'common.associer': 'Relier',
  'common.au': 'Au',
  'common.aucun_scenario_pour_l_instant': 'Aucun chapitre pour l’instant.',
  'common.aucune_description_disponible': 'Aucune description n’est consignée.',
  'common.ce_jour_uniquement': 'Ce jour seulement',
  'common.changer': 'Changer',
  'common.chargement': 'Le grimoire s’ouvre…',
  'common.chargement_2': 'Le grimoire s’ouvre...',
  'common.chargement_en_cours': 'Les pages se tournent',
  'common.choisir': '-- Choisir une vocation --',
  'common.cloturer_le_vote': 'Clore le conseil',
  'common.confirmer': 'Sceller',
  'common.connexion': 'Entrer dans le grimoire',
  // Remplacer / Conserver / Au cas par cas : vocabulaire de la boîte de conflit (contrat d’UI, story 36.4).
  'common.conserver': 'Conserver',
  'common.copier': 'Copier le parchemin',
  'common.creer': 'Forger',
  'common.creer_un_compte': 'Inscrire son nom au grimoire',
  'common.creneau': 'Fenêtre',
  'common.creneaux_varies': 'fenêtres variées',
  'common.date_a_definir': 'Date à fixer',
  'common.date_a_definir_2': 'Date à fixer.',
  'common.date_retenue_date': 'Date scellée : {date}',
  'common.designe_pour_le_vote': 'désigné pour le conseil',
  'common.detail': 'Précisions',
  'common.detail_du_jour': 'Précisions du jour',
  // Mots fonctionnels identiques : états de disponibilité, réponses de vote, libellés de champ courts.
  'common.disponible': 'Disponible',
  'common.dissocier': 'Délier',
  'common.du': 'Du',
  'common.effet_facultatif': 'Effet (si vous le souhaitez)',
  'common.email': 'Sceau (e-mail)',
  'common.en_savoir_plus': 'Consulter la glose',
  'common.enregistrement': 'Inscription…',
  'common.enregistrer': 'Inscrire',
  'common.envoi': 'Envoi de la missive…',
  'common.fermer': 'Refermer',
  'common.heure': 'Heure',
  'common.homme_dragon_introuvable': 'Cet Homme Dragon se cache : introuvable.',
  'common.impossible_d_enregistrer_ce_choix_reessayez': 'Ce choix n’a pu être inscrit. Réessayez.',
  'common.impossible_d_enregistrer_ces_disponibilites_reessayez':
    'Ces disponibilités n’ont pu être inscrites. Réessayez.',
  'common.impossible_d_enregistrer_la_contrainte': 'La contrainte n’a pu être inscrite.',
  'common.impossible_d_enregistrer_la_modification': 'La modification n’a pu être inscrite.',
  'common.impossible_de_charger_la_partie_reessayez': 'Ce grimoire ne s’ouvre pas. Réessayez.',
  'common.impossible_de_charger_le_scenario_reessayez': 'Ce chapitre ne s’ouvre pas. Réessayez.',
  'common.impossible_de_charger_les_scenarios_reessayez':
    'Les chapitres ne s’ouvrent pas. Réessayez.',
  'common.impossible_de_cloturer_le_vote_reessayez': 'Le conseil n’a pu être clos. Réessayez.',
  'common.indisponible': 'Indisponible',
  'common.j_ai_deja_un_compte': 'Mon nom figure déjà au grimoire',
  'common.lancer_le_vote': 'Convoquer le conseil',
  'common.lien_invalide': 'Lien invalide : le sceau est rompu.',
  'common.lien_invalide_ou_expire_merci_de_refaire_une_demande':
    'Lien invalide ou expiré. Veuillez refaire une demande.',
  'common.lieu': 'Lieu',
  'common.lire_la_suite': 'Poursuivre la lecture',
  'common.modifier': 'Retoucher',
  'common.mot_de_passe': 'Sortilège de passage',
  'common.mot_de_passe_oublie': 'Sortilège oublié',
  'common.n_max_inscrits': '{n}/{max} inscrits au grimoire',
  'common.nom_de_l_animal': 'Nom de la bête',
  'common.nom_de_l_objet': 'Nom de l’objet',
  'common.nom_du_contenant': 'Nom du contenant',
  'common.non': 'Non',
  'common.nouveau_mot_de_passe': 'Nouveau sortilège',
  'common.oui': 'Oui',
  'common.ouvrir_aux_joueurs': 'Ouvrir aux compagnons',
  'common.ouvrir_le_scenario_label': 'Ouvrir le chapitre {label}',
  'common.ouvrir_le_scenario_label_info': 'Ouvrir le chapitre {label} — {info}',
  'common.participants': 'Compagnons présents',
  'common.partie_introuvable': 'Ce grimoire demeure introuvable.',
  'common.pas_encore_de_personnage': '(aucun voyageur forgé)',
  'common.passer_cette_etape': 'Passer ce feuillet',
  'common.peut_etre': 'Peut-être',
  'common.poids': 'Poids',
  'common.precedent': 'Page précédente',
  'common.precedent_2': '❮ Page précédente',
  'common.prix_facultatif': 'Prix (si vous le souhaitez)',
  'common.rechercher': 'Scruter',
  'common.reduire': 'Replier le folio',
  'common.reessayer': 'Reprendre l’incantation',
  'common.refuser': 'Décliner',
  'common.reinitialiser_la_date': 'Effacer la date scellée',
  'common.rejoindre': 'Rejoindre le grimoire',
  'common.remplacer': 'Remplacer',
  'common.renoncer': 'Se raviser',
  'common.repondre_au_vote_label': 'Répondre à l’appel du conseil — {label}',
  'common.repondre_au_vote_label_detail': 'Répondre à l’appel du conseil — {label} — {detail}',
  'common.resume_de_fin': 'Récit de clôture',
  'common.retirer': 'Retirer',
  'common.retour_a_la_connexion': 'Retour à la porte du grimoire',
  'common.retour_a_la_partie': 'Retour au grimoire',
  'common.revoquer': 'Révoquer',
  'common.scenario_introuvable_revenez_a_la_liste_des_brouillons':
    'Chapitre introuvable — revenez à la liste des Brouillons.',
  'common.seance_n': 'Séance {n}',
  'common.suivant': 'Page suivante',
  'common.suivant_2': 'Page suivante ❯',
  'common.supprimer': 'Effacer',
  'common.title_seance_index': '{title} — Séance {index}',
  'common.titre': 'Titre',
  'common.type': 'Nature',
  'common.une_erreur_inattendue_est_survenue_reessayez':
    'Un sortilège inattendu a échoué. Réessayez.',
  'common.valider': 'Entériner',
  'common.vote_cloture_sans_date_retenue': 'Conseil clos sans date scellée.',
  'common.vote_de_date': '· vote du conseil',
  'common.vue_agenda': 'Vue agenda',
  'common.vue_mois': 'Vue mois',
  'common.vue_semaine': 'Vue semaine',

  /* ═══ Authentification et invitation ═══ */
  /* — accroche de la bande — */
  'auth.tagline': "Trouvez le soir où le grimoire s'ouvre",
  /* — connexion — */
  'auth.login_invalid': 'Le grimoire ne vous reconnaît pas : identifiants invalides.',
  'auth.login_reset_required':
    'Ce compte doit être réinitialisé : utilisez « Sortilège oublié ? » pour rouvrir le grimoire.',
  'auth.login_throttled':
    'Trop de tentatives. Patientez une minute avant de frapper de nouveau à la porte du grimoire.',
  'auth.login_unavailable':
    'Le grimoire est indisponible pour le moment. Réessayez dans quelques instants.',
  'auth.login_unexpected': 'Une erreur est survenue. Réessayez dans un instant.',
  'auth.login_invite_only': 'L’inscription au grimoire se fait sur invitation.',
  'auth.login_identifier_label': 'Sceau ou signe de reconnaissance',
  'auth.login_submit': 'Se connecter au grimoire',
  'auth.login_forgot_link': 'Sortilège oublié ?',
  /* — validation des champs — */
  'auth.field_required': 'Renseignez ce champ.',
  'auth.field_email_invalid': 'Adresse e-mail invalide.',
  'auth.field_pseudo_min': '3 caractères minimum.',
  'auth.field_password_min': '8 caractères minimum.',
  /* — révélation du mot de passe — */
  'auth.password_show': 'Afficher le mot de passe',
  'auth.password_hide': 'Masquer le mot de passe',
  /* — inscription — */
  'auth.register_invite_only':
    'L’inscription se fait uniquement sur invitation. Ouvrez un lien d’invitation pour créer votre compte au grimoire.',
  'auth.register_pseudo_label': 'Signe de reconnaissance',
  'auth.register_submit': 'Inscrire mon nom',
  'auth.register_error':
    'Le compte n’a pu être créé (lien invalide, ou e-mail ou signe de reconnaissance déjà pris ?).',
  /* — mot de passe oublié et réinitialisation — */
  'auth.forgot_sent':
    'Si un compte existe pour cette adresse, une missive de réinitialisation a été envoyée.',
  'auth.forgot_submit': 'Envoyer la missive',
  'auth.forgot_error': 'La demande n’a pu être envoyée pour le moment. Réessayez plus tard.',
  'auth.reset_submit': 'Renouveler le sortilège',
  'auth.reset_redo_link': 'Refaire une demande de sortilège',
  /* — changement d’adresse e-mail — */
  'auth.confirm_email_title': 'Confirmer le changement de sceau',
  'auth.confirm_email_done': 'Votre sceau de correspondance a été changé.',
  'auth.rollback_email_title': 'Annuler le changement de sceau',
  'auth.rollback_done':
    'Votre ancienne adresse a été rétablie : toutes les sessions actives ont été refermées.',
  'auth.rollback_continue_btn': 'Continuer vers le renouvellement du sortilège',
  'auth.rollback_warning':
    'Rétablir votre ancienne adresse refermera toutes les sessions actives et exigera de renouveler votre sortilège avant toute reconnexion.',
  'auth.rollback_submit': 'Rétablir mon ancienne adresse',
  'auth.rollback_error': 'Lien invalide ou expiré : le sceau ne tient plus.',
  /* — lien d’invitation — */
  'join.not_found_title': 'Parchemin introuvable',
  'join.not_found_text': 'Ce parchemin d’invitation n’existe pas.',
  'join.title': 'Rejoindre le grimoire « {name} »',
  'join.logged_as': 'Vous êtes connecté sous le nom de',
  'join.login_or_register': 'Connectez-vous ou créez un compte pour rejoindre ce grimoire.',
  'join.join_error': 'Impossible de rejoindre ce grimoire (lien invalide, expiré, ou déjà membre).',

  /* ═══ Compte ═══ */
  /* — profil, mot de passe et e-mail — */
  'account.title': 'Mon grimoire personnel',
  'account.pseudo_label': 'Signe de reconnaissance',
  'account.email_label': 'Sceau de correspondance',
  'account.display_name_label': 'Nom affiché aux autres voyageurs',
  'account.cancel_btn': 'Renoncer',
  'account.saved': 'Le grimoire a retenu ce nom.',
  'account.error': "Le grimoire n'a pas pu retenir ce changement. Réessayez.",
  'account.password_title': 'Renouveler le sortilège de passage',
  'account.current_password_label': 'Sortilège actuel',
  'account.new_password_label': 'Nouveau sortilège',
  'account.password_save_btn': 'Renouveler',
  'account.password_saved': 'Le sortilège de passage a été renouvelé.',
  'account.password_wrong_current': "Ce sortilège n'est pas le bon.",
  'account.password_error': "Le grimoire n'a pas pu renouveler le sortilège. Réessayez.",
  'account.current_password_for_email_label': 'Sortilège actuel',
  'account.new_email_label': 'Nouveau sceau de correspondance',
  'account.email_change_save_btn': 'Envoyer le message',
  'account.email_change_saved': 'Un message est parti vers le nouveau sceau.',
  'account.email_change_wrong_current': "Ce sortilège n'est pas le bon.",
  'account.email_change_taken': 'Un autre voyageur porte déjà ce sceau.',
  'account.email_change_error': "Le grimoire n'a pas pu envoyer la demande. Réessayez.",
  'account.appearance_label': 'Apparence du grimoire',
  /* — calendrier du compte — */
  'account.calendar_layers_title': 'Ce que révèle mon calendrier',
  // Couches et intentions du calendrier : verbatim du contrat d’UI (story 36.14), volontairement identiques.
  'account.calendar_layer.mes-indisponibilites': 'Mes indisponibilités',
  'account.calendar_layer.mes-disponibilites': 'Mes disponibilités',
  'account.calendar_layer.mes-seances': 'Mes séances confirmées',
  'account.calendar_layer.votes-en-cours': 'Les votes en cours',
  'account.calendar_layer.inscriptions-ouvertes': 'Les inscriptions ouvertes',
  'account.calendar_layer.disponibilite-groupe': 'La disponibilité du groupe',
  'account.calendar_intents_subtitle': 'Ce que je veux voir en ouvrant l’almanach.',
  'account.calendar_intent.disponibilites': 'Mes disponibilités & indisponibilités',
  'account.calendar_intent.seances': 'Mes séances confirmées',
  'account.calendar_intent.votes': 'Les votes en cours',
  'account.calendar_intent.groupe': 'La disponibilité du groupe',
  /* — identité et homonymie — */
  'identity.character_label': 'Voyageur',
  'identity.player_label': 'Compagnon',
  'identity.homonymy_warning':
    'Un autre compagnon de ce grimoire porte le même nom affiché que vous.',
  'identity.homonymy_change_cta': 'Changer mon nom affiché',
  'identity.homonymy_ignore_cta': 'Passer outre',

  /* ═══ Tableau de bord ═══ */
  /* — tableau de bord — */
  'dashboard.title_invitations': 'Missives reçues',
  'dashboard.empty': 'Nulle quête en cours. Forgez la première…',
  'dashboard.role_prefix': 'Rang :',
  'dashboard.role_mj': 'Maître',
  'dashboard.role_player': 'Héros',
  'dashboard.status_closed_badge': 'Close',
  'dashboard.section_awaiting': 'Ce qui vous attend',
  'dashboard.section_ongoing': 'En cours',
  'dashboard.section_upcoming': 'À venir',
  'dashboard.section_finished': 'Closes',
  'dashboard.empty_filtered': 'Aucun grimoire ne répond à ces critères.',
  'dashboard.filter_role_label': 'Rang',
  'dashboard.filter_role_all': 'Tous les rangs',
  'dashboard.filter_status_label': 'Phase',
  'dashboard.filter_status_all': 'Toutes les phases',
  'dashboard.sort_urgence': 'Urgence',
  'dashboard.sort_date': 'Date',
  'dashboard.sort_nom': 'Nom',
  'dashboard.sort_type': 'Nature',
  'dashboard.sort_statut': 'Phase',
  'dashboard.hide_finished_label': 'Masquer les grimoires clos',
  'dashboard.show_finished_btn': 'Afficher les grimoires clos',
  'dashboard.favorite_add_aria': 'Marquer d’un signet (favori)',
  'dashboard.favorite_remove_aria': 'Retirer le signet (favori)',
  'dashboard.search_label': 'Rechercher un grimoire',
  'dashboard.row_signal_count_aria': '{n} chose(s) à accomplir',
  'dashboard.invitation_invited_by': 'convié par {pseudo}',

  /* ═══ Parties ═══ */
  /* — formulaire de partie — */
  'partie.new_title': 'Nouvelle quête',
  'partie.edit_title': 'Retranscrire le parchemin',
  'partie.save_btn': 'Inscrire',
  'partie.cancel_btn': 'Refermer',
  'partie.name_label': 'Nom du grimoire',
  'partie.system_label': 'Livre de règles',
  'partie.kind_label': 'Nature de la quête',
  'partie.description_label': 'Préambule (facultatif)',
  'partie.kind_ONE_SHOT': 'Quête unique',
  'partie.kind_CAMPAGNE_LINEAIRE': 'Chronique',
  'partie.kind_CAMPAGNE_EPISODIQUE': 'Chronique épisodique',
  'partie.kind_refusal_closed': 'Ce grimoire est clos. Rouvrez-le avant d’en changer la nature.',
  'partie.kind_refusal_too_many_scenarios':
    'Ce grimoire compte {count} chapitres ; une quête unique n’en porte qu’un.',
  'partie.courant_choice_title': 'Quel chapitre reste en cours ?',
  'partie.courant_choice_help':
    'Une chronique ne suit qu’un chapitre à la fois. Les autres repasseront « à venir » — leurs séances et leurs dates sont conservées.',
  'partie.courant_choice_confirm': 'Sceller ce choix',
  'partie.cover_add': 'Enluminer ce grimoire',
  'partie.cover_change': 'Changer l’enluminure',
  'partie.cover_remove': 'Retirer l’enluminure',
  'partie.cover_uploading': 'L’enluminure se fixe sur le parchemin…',
  'partie.cover_upload_error': 'L’enluminure n’a pu être fixée. Réessayez.',
  'partie.cover_remove_error': 'L’enluminure n’a pu être retirée. Réessayez.',
  'partie.cover_reject_type': 'Seules les images JPEG, PNG et WEBP peuvent enluminer un grimoire.',
  'partie.cover_reject_size': 'Cette image dépasse 5 Mo : choisissez-en une plus légère.',
  'partie.save_error': 'Ce grimoire n’a pu être inscrit. Réessayez.',
  'partie.created_but_cover_failed':
    'Le grimoire est bien inscrit, mais son enluminure n’a pu être fixée. Vous pouvez la redéposer ici.',
  'partie.fields_saved_but_convert_failed':
    'Les autres modifications sont enregistrées, mais la nature du grimoire n’a pu être changée. Réessayez.',
  /* — détail de partie — */
  'partie.scheduling_title': 'Prochaine séance au grimoire',
  'partie.no_session': "Aucune séance convoquée. Consultez l'oracle des créneaux.",
  'partie.members_title': '⚔ Compagnons',
  'partie.no_members': "Nulle âme pour l'instant.",
  'partie.remove_member_btn': 'Retirer',
  'partie.no_description': 'Ce grimoire est muet.',
  'partie.invite_title': 'Convoquer un compagnon',
  'partie.search_label': 'Nom ou signe distinctif',
  'partie.search_btn': 'Scruter',
  'partie.invite_btn': 'Convoquer',
  'partie.links_title': "Parchemins d'invocation",
  'partie.generate_link': 'Tisser un parchemin',
  'partie.notice_invited': 'Missive envoyée à {name}.',
  'partie.invite_by_email_label': 'Sceau du destinataire',
  'partie.invite_by_email_btn': 'Envoyer une missive',
  'partie.notice_invited_email': 'Missive envoyée à {email}.',
  'partie.notice_invite_email_error': "La missive n'a pu être envoyée. Réessayez.",
  'partie.reference_sheets_title': 'Grimoires de référence',
  // Noms des fiches de référence et de préparation Ryuutama : vocabulaire du système de jeu, identique.
  'partie.asset_journal_cta': 'Journal',
  'partie.asset_carte_cta': 'Carte',
  'partie.asset_download_error': "Ce grimoire n'a pas pu être déterré. Réessayez.",
  'partie.prep_sheets_title': 'Grimoires de préparation (MJ)',
  'partie.asset_monde_cta': 'Monde',
  'partie.asset_monstre_cta': 'Monstre',
  'partie.asset_ville_cta': 'Ville',
  'partie.asset_objectif_chasse_cta': 'Objectif — Chasse',
  'partie.asset_objectif_quete_cta': 'Objectif — Quête',
  'partie.asset_objectif_voyage_cta': 'Objectif — Voyage',
  'partie.asset_oeuf_de_bataille_cta': 'Œuf de bataille',
  'partie.asset_structure_cta': 'Structure',
  'partie.notice_copy': 'Parchemin copié dans la besace.',
  'partie.edit_btn': 'Retranscrire',
  'partie.visibility_btn': 'Sceller des secrets',
  'partie.close_btn': 'Clore le grimoire',
  'partie.reopen_btn': 'Rouvrir le grimoire',
  'partie.status_closed_label': 'Ce grimoire est clos.',
  'partie.delete_btn': 'Brûler le parchemin',
  'partie.invitations_tab_label': 'Missives',
  /* — zones de l’onglet Détails — */
  // Noms CONTRACTUELS des trois zones (Action / Consultation / Référence) : catégories nommées par l’épic,
  // identiques dans les trois thèmes.
  'partie.details_zone_action': 'Action',
  'partie.details_zone_consultation': 'Consultation',
  'partie.details_zone_reference': 'Référence',
  /* — signaux d’état — */
  'partie.signal_personnage_a_creer': 'Créer son héros',
  'partie.signal_vote_en_cours_sans_reponse': 'Répondez au vote',
  'partie.signal_compte_rendu_non_redige': 'Chronique à rédiger',
  'partie.signal_homme_dragon_a_creer': 'Créer son Homme Dragon',
  'partie.signal_aucun_membre_invite': 'Aucun compagnon convoqué',
  'partie.signal_aucun_scenario_en_cours': 'Aucune quête en cours',
  'partie.signal_aucune_date_ni_vote': 'Aucune date ni conseil',
  'partie.signal_rapport_fin_manquant': 'Récit de clôture manquant',
  'partie.signal_prochaine_seance_connue': 'Prochaine séance inscrite',
  'partie.signal_partie_terminee': 'Grimoire clos',
  'partie.signal_more_count': '+{n}',
  /* — états de scénario et de séance — */
  // Noms d’état CONTRACTUELS, IDENTIQUES dans les trois thèmes (story 32.3).
  // « Courant », JAMAIS « En cours » : « en cours » est réservé au VOTE.
  // La paire vote répondu / non répondu porte DEUX libellés distincts (EXPERIENCE.md §5) : la teinte ne
  // doit jamais être la seule différence.
  'status.scenario_brouillon': 'Brouillon',
  'status.scenario_a_venir': 'À venir',
  'status.scenario_courant': 'Courant',
  'status.scenario_passe': 'Passé',
  'status.seance_a_planifier': 'À planifier',
  'status.seance_answer_poll': 'Réponds au vote',
  'status.seance_poll_open': 'Vote en cours',
  'status.seance_inscriptions_ouvertes': 'Inscriptions ouvertes',
  'status.seance_programmee': 'Programmée',
  'status.seance_a_debriefer': 'À débriefer',
  'status.seance_jouee': 'Jouée',
  /* — confidentialité — */
  'parties.confirm_title': 'Votre accord',
  'parties.locks_title': 'Confidentialité des secrets',
  'parties.locks_load_partie_error':
    'Les informations du grimoire n’ont pu être chargées. Réessayez.',
  'parties.locks_load_schema_error': 'Le schéma du livre de règles n’a pu être chargé. Réessayez.',
  'parties.locks_save_error': 'La configuration n’a pu être inscrite. Réessayez.',
  'parties.locks_access_denied':
    'Accès refusé : seul le Maître de ce grimoire peut configurer la confidentialité.',
  'parties.locks_help':
    'Cochez les éléments de fiche à masquer aux joueurs (hors Maître et propriétaire du personnage). L’enregistrement remplace l’ensemble des verrous actuels de ce grimoire.',
  'parties.locks_empty': 'Ce livre de règles ne déclare aucun élément scellable.',
  /* — onglets, effectif et liens — */
  'parties.detail_polls_in_progress': '{count} votes de date en cours',
  'parties.detail_remove_member_confirm': 'Retirer {name} du grimoire « {partie} » ?',
  'parties.detail_delete_confirm':
    'Brûler le grimoire « {partie} » ? Cette action est irréversible.',
  'parties.detail_link_expires_short': 'exp.',
  'parties.detail_tab_details': 'Détails',
  'parties.detail_tab_scenario': 'Chapitre',
  'parties.detail_tab_scenarios': 'Chapitres',
  'parties.detail_tab_timeline': 'Chronologie',
  'parties.roster_aria_levelup': '{label} — niveau supérieur disponible',
  'parties.roster_aria_role': '{label} — office : {role}',
  'parties.roster_aria_mj': '{name} — Maître',
  'parties.roster_aria_no_character': '{name} — aucun voyageur forgé',
  'parties.roster_aria_character': '{name} — {character}',
  'parties.roster_aria_character_class': '{name} — {character} ({class})',
  'parties.roster_aria_create': '{name} — {action}',
  /* — distribution d’XP — */
  'evolution.xp_distribute_cta': "Distribuer de l'XP",
  'evolution.xp_panel_title': "Distribution d'XP",
  'evolution.xp_history_title': "Historique des distributions d'XP",
  'evolution.xp_history_empty': 'Aucune distribution gravée pour le moment.',
  'evolution.xp_note_label': 'Note de session',
  'evolution.xp_confirm_btn': 'Sceller la distribution',
  'evolution.xp_bonus_link': '+ faveur',
  'evolution.xp_levelup_warning': '{name} franchira un niveau',
  'parties.xp_suggested': 'Montant conseillé par l’oracle : {amount} XP',
  'parties.xp_current': '{xp} XP actuels',
  'parties.xp_amount_label': 'Montant',
  'parties.xp_select_one_error': 'Choisissez au moins un voyageur avant de distribuer.',
  'parties.xp_distribute_error': 'La distribution n’a pu être inscrite. Réessayez.',
  'parties.xp_rules_title': 'Calcul de l’oracle',
  'parties.xp_history_unknown_character': 'Voyageur inconnu',
  'parties.xp_history_bonus_badge': 'faveur',

  /* ═══ Scénarios et séances ═══ */
  /* — formulaire et scénario unique — */
  'scenarios.fill_label': '{count} / {max} inscrits au grimoire (min. {min})',
  'scenarios.form_title': 'Nouveau chapitre',
  'scenarios.form_description_label': 'Résumé du chapitre (facultatif)',
  'scenarios.form_duree_heures_label': 'Durée estimée en heures (facultatif)',
  'scenarios.form_duree_seances_label': 'Durée estimée en séances (facultatif)',
  'scenarios.form_save_error': 'Le chapitre n’a pu être inscrit.',
  'scenarios.one_shot_not_found': 'Aucun chapitre trouvé pour ce grimoire.',
  'scenarios.one_shot_open_error': 'Le chapitre n’a pu être ouvert aux compagnons. Réessayez.',
  /* — liste et chronologie — */
  'scenarios.list_title': 'Chapitres',
  'scenarios.list_new_button': '+ Nouveau chapitre',
  'scenarios.timeline_title': 'Chronologie',
  'scenarios.timeline_load_error': 'La chronologie ne s’ouvre pas. Réessayez.',
  'scenarios.timeline_count_one': '{n} chapitre',
  'scenarios.timeline_count_many': '{n} chapitres',
  'scenarios.timeline_not_planned': 'Pas encore daté',
  'scenarios.timeline_since': 'depuis le {date}',
  'scenarios.timeline_from': 'à partir du {date}',
  /* — séances — */
  'scenarios.seances_delete_button': 'Effacer cette séance',
  'scenarios.seances_min_aria': 'Nombre minimum de compagnons inscrits',
  'scenarios.seances_max_aria': 'Nombre maximum de compagnons inscrits',
  'scenarios.seances_set_capacity': 'Fixer la capacité',
  'scenarios.seances_edit_capacity': 'Retoucher la capacité',
  'scenarios.seances_desinscrire': 'Retirer mon nom',
  'scenarios.seances_inscrire': 'Inscrire mon nom',
  'scenarios.seances_heure_malformed':
    '⚠️ Valeur consignée non reconnue ("{raw}"), champ laissé vide — inscrire sans la corriger l\'effacera.',
  'scenarios.seances_lieu_placeholder': 'dans la bibliothèque de Marc, en visio…',
  'scenarios.seances_note_placeholder': 'pensez aux dés et à l’encre…',
  'scenarios.seances_save_infos': 'Inscrire les informations pratiques',
  'scenarios.seances_compte_rendu_placeholder': 'Chronique de la séance…',
  'scenarios.seances_compte_rendu_aria': 'Chronique de la séance',
  'scenarios.seances_save_compte_rendu': 'Inscrire la chronique',
  'scenarios.seances_compte_rendu_empty': 'Aucune chronique pour cette séance pour le moment.',
  'scenarios.seances_choose_error': 'Cette date n’a pu être scellée. Réessayez.',
  'scenarios.seances_capacity_error': 'La capacité n’a pu être fixée. Réessayez.',
  'scenarios.seances_inscrire_error': 'Votre nom n’a pu être inscrit. Réessayez.',
  'scenarios.seances_desinscrire_error': 'Votre nom n’a pu être retiré. Réessayez.',
  'scenarios.seances_delete_error': 'Cette séance n’a pu être effacée. Réessayez.',
  'scenarios.seances_reset_error': 'La date n’a pu être effacée. Réessayez.',
  'scenarios.seances_infos_error': 'Les informations pratiques n’ont pu être inscrites. Réessayez.',
  'scenarios.seances_compte_rendu_error': 'La chronique n’a pu être inscrite. Réessayez.',
  'scenarios.seances_refresh_error':
    'Action accomplie, mais la page ne s’est pas rafraîchie. Rechargez-la.',
  'scenarios.seances_delete_confirm_dated':
    'Cette séance a une date scellée. L’effacer quand même ? Cette action est définitive.',
  'scenarios.seances_delete_confirm': 'Effacer cette séance ? Cette action est définitive.',
  'scenarios.seances_reset_confirm':
    'Effacer la date de cette séance ? Un nouveau conseil pourra être convoqué.',
  /* — lecture du scénario — */
  'scenarios.read_resume_empty': 'Aucun récit de clôture pour l’instant.',
  'scenarios.read_resume_edit': 'Retoucher le récit de clôture',
  'scenarios.read_resume_write': 'Rédiger le récit de clôture',
  'scenarios.read_journal_title': 'Journal associé',
  'scenarios.read_auto_associate': 'Liaison automatique',
  'scenarios.read_note_shared_aria': 'Note confiée aux compagnons',
  'scenarios.read_note_private_aria': 'Note privée, scellée',
  'scenarios.read_note_private_hint':
    'Note scellée — brisez le sceau (🔒) pour qu’elle apparaisse dans la rétrospective.',
  'scenarios.read_journal_empty': 'Vous n’avez encore rien inscrit au journal.',
  'scenarios.read_retrospective_title': 'Chroniques de la rétrospective',
  'scenarios.read_participate': 'Rejoindre ce chapitre',
  'scenarios.read_journal_load_error': 'Votre journal ne s’ouvre pas.',
  'scenarios.read_participate_error': 'Vous n’avez pu rejoindre ce chapitre.',
  'scenarios.read_setting_error': 'Ce réglage n’a pu être retouché.',
  'scenarios.read_note_visibility_error': 'La visibilité de cette note n’a pu être retouchée.',
  'scenarios.read_note_association_error': 'Cette liaison n’a pu être mise à jour.',
  /* — éditeur du scénario — */
  'scenarios.editor_pencil_title': 'le titre du chapitre',
  'scenarios.editor_pencil_duree_heures': 'la durée estimée en heures',
  'scenarios.editor_pencil_duree_seances': 'la durée estimée en séances',
  'scenarios.editor_mark_courant': 'Désigner comme Courant',
  'scenarios.editor_close': 'Clore ce chapitre',
  'scenarios.editor_add_seance': 'Inscrire une séance',
  'scenarios.editor_resume_empty_hint':
    'Aucun récit de clôture pour l’instant — rédigez-le pour clore la rétrospective.',
  'scenarios.editor_save_resume': 'Inscrire le récit de clôture',
  'scenarios.editor_no_participants': 'Aucun compagnon pour l’instant.',
  'scenarios.editor_documents_title': 'Parchemins du chapitre',
  'scenarios.editor_library_title': 'Bibliothèque de la chronique',
  'scenarios.editor_library_doc_suffix': '— bibliothèque de la chronique',
  'scenarios.editor_documents_load_error': 'Les parchemins ne s’ouvrent pas. Réessayez.',
  'scenarios.editor_participants_load_error':
    'La liste des compagnons n’a pu être chargée. Réessayez.',
  'scenarios.editor_upload_error': 'Le parchemin n’a pu être déposé. Réessayez.',
  'scenarios.editor_mark_courant_error': 'Ce chapitre n’a pu être désigné Courant.',
  'scenarios.editor_close_error': 'Ce chapitre n’a pu être clos.',
  'scenarios.editor_add_seance_error': 'La séance n’a pu être inscrite.',
  'scenarios.editor_resume_save_error': 'Le récit de clôture n’a pu être inscrit.',
  'scenarios.editor_download_error': 'Le parchemin n’a pu être récupéré.',

  /* ═══ Calendrier ═══ */
  /* — barre d’affichage et légende — */
  // Barre d’affichage et légende : verbatim du contrat d’UI (story 36.14), identiques sauf là où un
  // pronom impose le vouvoiement ou le tutoiement du thème.
  'calendar.display.trigger': 'Affichage',
  'calendar.display.trigger_aria': 'Régler l’affichage de l’almanach',
  'calendar.display.section_visible': 'Ce que je vois',
  'calendar.display.show_legend': 'Afficher la légende',
  'calendar.display.filtered_badge': 'Affichage filtré · {n} sur {total} · Rétablir',
  'calendar.legend.title': 'Légende du grimoire',
  'calendar.legend.group_obvious': 'Parlent d’eux-mêmes',
  'calendar.legend.group_needs': 'Réclament la légende',
  'calendar.legend.entry.available': 'Je suis disponible',
  'calendar.legend.entry.unavailable': 'Je suis indisponible',
  'calendar.legend.entry.seance': 'Séance confirmée — vous êtes pris',
  'calendar.legend.entry.vote': 'Créneau proposé au vote',
  'calendar.legend.entry.poll_track': 'Participation : la piste = la troupe',
  'calendar.legend.entry.group': 'Disponibilité du groupe',
  'calendar.legend.entry.none': 'Personne ne s’est prononcé',
  /* — agenda — */
  'calendar.agenda.section_awaiting': 'Ce qui vous attend',
  'calendar.agenda.section_scheduled': 'Ce qui est annoncé',
  'calendar.agenda.section_past': 'Ce qui est révolu',
  // Badges d’état de l’Agenda : CONTRACTUELS et identiques (EXPERIENCE.md §5, paire « Réponds au vote » / « Vote en cours »).
  'calendar.agenda.badge_answer_poll': 'Réponds au vote',
  'calendar.agenda.badge_poll_open': 'Vote en cours',
  'calendar.agenda.badge_signup': 'S’inscrire',
  'calendar.agenda.badge_signed_up': 'Inscrit',
  'calendar.agenda.badge_debrief': 'Débriefer',
  'calendar.agenda.empty': 'Rien ne vous attend, rien n’est annoncé.',
  'calendar.agenda.badge_to_seal': 'À sceller',
  'calendar.agenda.poll_open': 'Conseil ouvert',
  'calendar.agenda.responded_count': '{n} sur {total} compagnons ont répondu',
  'calendar.agenda.slots_proposed': '{n} fenêtres proposées',
  'calendar.agenda.missing_voters': 'il manque encore {names}',
  'calendar.agenda.no_date': 'date à sceller',
  'calendar.agenda.no_date_proposed': 'Aucune fenêtre proposée',
  'calendar.agenda.action_launch_poll': 'Convoquer le conseil',
  'calendar.agenda.action_seal': 'Sceller',
  'calendar.agenda.action_expand': 'Déplier',
  'calendar.agenda.action_collapse': 'Replier',
  'calendar.agenda.seal_confirm_title': 'Sceller ce créneau ?',
  'calendar.agenda.seal_confirm_body':
    'La séance sera fixée à ce créneau et le vote se refermera. Les autres créneaux proposés disparaîtront.',
  'calendar.agenda_missing_more_one': '{listed} et {rest} autre compagnon',
  'calendar.agenda_missing_more_many': '{listed} et {rest} autres compagnons',
  /* — vue calendrier (navigation, composition, chargement) — */
  'calendar.agg_counts_aria': 'Disponibilités consignées',
  'calendar.agg_available_title': 'Disponibles',
  'calendar.agg_unknown_title': 'Inconnus',
  'calendar.agg_unavailable_title': 'Indisponibles',
  'calendar.slots_list_aria': 'Fenêtres disponibles',
  'calendar.rail_empty': 'Aucun jour à consulter',
  'calendar.rail_status_unknown': 'Rien d’inscrit',
  'calendar.layer_group_aria': 'Couches affichées de l’almanach',
  'calendar.view_back': '← Retour',
  'calendar.view_compose_arm': 'Inscrire des dates',
  'calendar.view_toggle_aria': 'Vue de l’almanach',
  'calendar.view_toggle_month_short': 'Mois',
  'calendar.view_toggle_week_short': 'Sem.',
  'calendar.view_toggle_agenda_short': 'Agenda',
  'calendar.view_no_poll': 'Aucun conseil de date en cours.',
  'calendar.view_locked_seance_hint':
    'Le conseil de la séance sélectionnée se convoque depuis la fiche du chapitre.',
  'calendar.view_group_label': '{slot} — {available}/{total} compagnons disponibles',
  'calendar.view_group_unavailable_detail': '{n} indisponible(s)',
  'calendar.view_compose_target_poll': 'Fenêtres du conseil : {label}',
  'calendar.view_compose_target_new': 'Fenêtres d’un nouveau conseil',
  'calendar.view_compose_blocked_min': 'Un conseil demande au moins deux fenêtres.',
  'calendar.view_compose_blocked_max': 'Quarante fenêtres au maximum.',
  'calendar.view_compose_blocked_no_seance':
    'Aucune séance n’attend de conseil : un conseil se rattache toujours à une séance.',
  'calendar.view_compose_stale_voters':
    'Une nouvelle réponse est venue s’inscrire depuis l’avertissement — revalidez pour voir le chiffre à jour.',
  'calendar.view_compose_save_error': 'Ces fenêtres n’ont pu être inscrites. Réessayez.',
  'calendar.view_batch_conflict_labels':
    'Ces fenêtres se contredisent entre elles ({labels}). Rien n’a été inscrit.',
  'calendar.view_batch_conflict_plain':
    'Ces fenêtres se contredisent entre elles. Rien n’a été inscrit.',
  'calendar.view_conflict_in_progress':
    'Un conflit est déjà en cours de résolution. Terminez-le avant de recommencer.',
  'calendar.view_cell_unknown': 'Fenêtre inconnue',
  'calendar.view_selection_none': 'sur aucune fenêtre',
  'calendar.view_selection_one': 'le {cell}',
  'calendar.view_selection_many': 'sur {n} fenêtres, du {from} au {to}',
  'calendar.view_seal_error': 'Cette fenêtre n’a pu être scellée. Réessayez.',
  'calendar.view_range_error': 'La date de début doit précéder la date de fin, ou lui être égale.',
  'calendar.view_load_declarations_error': 'Les disponibilités ne s’ouvrent pas.',
  'calendar.view_load_slots_error': 'Les fenêtres ne s’ouvrent pas.',
  'calendar.view_load_calendar_error': 'L’almanach ne s’ouvre pas pour cette période.',
  /* — vue mois — */
  'calendar.month_prev_aria': 'Mois précédent de l’almanach',
  'calendar.month_next_aria': 'Mois suivant de l’almanach',
  'calendar.month_today_aria': 'Revenir au mois courant de l’almanach',
  'calendar.month_cell_instructions':
    "Espace : sélectionner la journée entière. Touches 1, 2, 3 : sélectionner respectivement le matin, l'après-midi ou le soir. Maj plus flèches : étendre la sélection. Entrée : valider la sélection avec ce qu'affiche la barre. Échap : annuler.",
  'calendar.month_day_today_aria': "{day} (aujourd'hui)",
  'calendar.month_status_unknown': 'non inscrit',
  /* — vue semaine — */
  'calendar.week_decl_available': 'Dispo',
  'calendar.week_decl_punctual': 'Ponctuel',
  'calendar.week_decl_recurring': 'Récurrent',
  'calendar.week_decl_unavailable': 'Indispo',
  'calendar.week_next_aria': 'Semaine suivante de l’almanach',
  'calendar.week_prev_aria': 'Semaine précédente de l’almanach',
  'calendar.week_status_available': 'disponible',
  'calendar.week_status_unavailable': 'indisponible',
  'calendar.week_status_unknown': 'inconnu',
  'calendar.week_today_aria': 'Revenir à la semaine courante de l’almanach',
  /* — mots d’état et de participation — */
  'calendar.util_answer_yes': 'oui',
  'calendar.util_answer_maybe': 'peut-être',
  'calendar.util_answer_no': 'non',
  'calendar.util_answer_mine': 'vous avez dit {answer}',
  'calendar.util_participation_one': '{n} réponse inscrite sur {total}',
  'calendar.util_participation_many': '{n} réponses inscrites sur {total}',
  'calendar.util_group_aria_one': 'Disponibilité de la troupe : {available} sur {total} disponible',
  'calendar.util_group_aria_many':
    'Disponibilité de la troupe : {available} sur {total} disponibles',
  'calendar.util_group_all_blocked': 'tous les compagnons sont empêchés',
  'calendar.util_group_nobody': 'nul ne s’est prononcé',
  'calendar.util_group_unavailable_one': '{n} indisponible',
  'calendar.util_group_unavailable_many': '{n} indisponibles',
  'calendar.util_word_no_answer': 'sans réponse',
  'calendar.util_counter': '{n} / {total}',
  /* — barre de sélection — */
  'calendar.selbar_announcement': 'Portée : {scope}. Entrée inscrira : {kind}.',
  'calendar.selbar_count_many': '{n} fenêtres sélectionnées',
  'calendar.selbar_count_one': '{n} fenêtre sélectionnée',
  'calendar.selbar_other': 'Autrement…',
  'calendar.selbar_scope_aria': 'Étendue de la sélection',
  'calendar.selbar_toolbar_aria': 'Actions du grimoire sur la sélection',
  /* — panneau de contraintes — */
  'calendar.constraint_all_occurrences': 'Toutes les récurrences',
  'calendar.constraint_close_aria': 'Refermer le panneau du grimoire',
  'calendar.constraint_conflict_prompt':
    'Des disponibilités contradictoires sont déjà inscrites pour cette période.',
  'calendar.constraint_delete_error': 'La contrainte n’a pu être effacée.',
  'calendar.constraint_end_date': 'Date de fin',
  'calendar.constraint_expires_on': 'S’éteint le',
  'calendar.constraint_from_this_day': 'À partir de ce jour, jusqu’au terme',
  'calendar.constraint_keep_existing': "Garder l'existant",
  'calendar.constraint_kind_aria': 'Disponibilité',
  'calendar.constraint_modify_error': 'La contrainte n’a pu être retouchée.',
  'calendar.constraint_occurrence_delete_error': 'L’occurrence n’a pu être effacée.',
  'calendar.constraint_occurrence_modify_error': 'L’occurrence n’a pu être retouchée.',
  'calendar.constraint_overwrite': 'Réécrire',
  'calendar.constraint_recurring_delete_prompt':
    'Cette contrainte est récurrente. Que souhaitez-vous effacer ?',
  'calendar.constraint_recurring_modify_prompt':
    'Cette contrainte est récurrente. Que souhaitez-vous retoucher ?',
  'calendar.constraint_start_date': 'Date de début',
  'calendar.constraint_type_punctual': 'Cette fenêtre seulement',
  'calendar.constraint_type_range': 'Étendue de dates',
  'calendar.constraint_type_recurring': 'Récurrent (semaine après semaine)',
  'calendar.constraint_whole_series': 'La série entière',
  /* — boîte de conflit — */
  'calendar.conflict_exception_detail':
    'Vous y avez une séance. Aucun de ces choix n’y touche. Si elle est annulée, vous redevenez {kind}.',
  'calendar.conflict_exception_many': 'ne figurent pas dans la liste',
  'calendar.conflict_exception_one': 'ne figure pas dans la liste',
  'calendar.conflict_free_many': 'Les {n} autres passent en {kind}',
  'calendar.conflict_free_none': 'Rien d’autre n’est inscrit',
  'calendar.conflict_free_one': 'Le 1 autre passe en {kind}',
  'calendar.conflict_intent_prefix': 'Vous inscrivez',
  'calendar.conflict_keep_many': 'Ces {n} demeurent tels quels',
  'calendar.conflict_keep_one': 'Ce créneau demeure tel quel',
  'calendar.conflict_step_announcement': 'Fenêtre {progress} : {label}. Remplacer ou conserver ?',
  'calendar.conflict_title_many': '{n} fenêtres sont déjà inscrites',
  'calendar.conflict_title_one': '1 fenêtre est déjà inscrite',
  'calendar.conflict_walkthrough_body': 'Nous les parcourons un par un',
  'calendar.conflict_walkthrough_count_many': '{n} décisions à sceller',
  'calendar.conflict_walkthrough_count_one': '{n} décision à sceller',
  'calendar.conflict_walkthrough_label': 'Au cas par cas',
  'calendar.conflict_kind_available': 'disponible',
  'calendar.conflict_kind_unavailable': 'indisponible',
  'calendar.conflict_overwrite_available_one': 'Le créneau est inscrit disponible',
  'calendar.conflict_overwrite_available_many': 'Les {n} sont inscrits disponibles',
  'calendar.conflict_overwrite_unavailable_one': 'Le créneau est inscrit indisponible',
  'calendar.conflict_overwrite_unavailable_many': 'Les {n} sont inscrits indisponibles',
  /* — composition des créneaux d’un vote — */
  'calendar.card_alerts_aria': 'Avis de disponibilité de l’oracle',
  'calendar.card_full_guild': 'Compagnie au complet',
  'calendar.card_members_aria': 'Compagnons',
  'calendar.compose_bar_aria': 'Composition des fenêtres d’un conseil',
  'calendar.compose_confirm_note':
    'Les réponses portées par les fenêtres conservées ne sont pas touchées.',
  'calendar.compose_confirm_responses_many': '{n} réponses',
  'calendar.compose_confirm_responses_one': '{n} réponse',
  'calendar.compose_confirm_seance_label': 'Pour quelle séance du grimoire ?',
  'calendar.compose_confirm_seance_placeholder': 'Désigner une séance…',
  'calendar.compose_confirm_slots_many': '{n} fenêtres',
  'calendar.compose_confirm_slots_one': '{n} fenêtre',
  'calendar.compose_confirm_summary_many': '{n} fenêtres proposées.',
  'calendar.compose_confirm_summary_one': '{n} fenêtre proposée.',
  'calendar.compose_confirm_title_modify': 'Retoucher les fenêtres du conseil',
  'calendar.compose_confirm_warning_many': 'Retirer {slots} effacera {votes} déjà posées.',
  'calendar.compose_confirm_warning_one': 'Retirer {slots} effacera {votes} déjà posée.',
  'calendar.compose_count_many': '{n} fenêtres désignées',
  'calendar.compose_count_none': 'Aucune fenêtre désignée',
  'calendar.compose_count_one': '{n} fenêtre désignée',
  /* — mode Destinée — */
  // Nom du MODE « Destinée » (EXPERIENCE.md §4.4 ter), identique dans les trois thèmes.
  'cta.destiny_mode': 'Destinée',
  'calendar.destiny_next_aria': 'Conseil suivant',
  'calendar.destiny_prev_aria': 'Conseil précédent',

  /* ═══ Vote de date ═══ */
  /* — actions, états et alertes — */
  'cta.find_date': "Consulter l'oracle des créneaux",
  'cta.guild_calendar': 'Voir le grimoire des disponibilités',
  'cta.save_constraint': 'Inscrire dans le grimoire',
  'section.slots': 'Fenêtres de la destinée',
  'empty.no_slots': "L'oracle ne voit aucun créneau libre. Les parchemins manquent de données.",
  'success.constraint_saved': 'Contrainte gravée dans le parchemin.',
  'alert.missing_player': "{name} n'a pas encore consulté l'oracle.",
  'cta.choose_date': 'Sceller ce créneau',
  'cta.cancel_poll': 'Brûler le parchemin de vote',
  'cta.restore_default_layers': 'Rétablir mon grimoire par défaut',
  'success.poll_created': 'Conseil convoqué. Les compagnons ont été avertis.',
  'success.vote_cast': 'Réponse inscrite dans le grimoire.',
  'cta.confirm_votes': 'Sceller mes réponses',
  'cta.withdraw_vote': 'Reprendre ma réponse',
  'success.vote_withdrawn': 'Réponse retirée du grimoire.',
  'alert.all_responded': 'Tous les compagnons ont répondu au vote.',
  /* — état du vote — */
  'poll.status_title': 'Vote en cours',
  'poll.vote_pending': 'Vote de date en cours — parchemin en attente',
  'poll.withdraw_error': 'Votre réponse n’a pu être reprise. Réessayez.',
  'poll.cast_error': 'Votre réponse n’a pu être inscrite. Réessayez.',
  'poll.vote_closed': "Ce vote est clos. L'oracle a tranché.",
  'poll.status_summary': 'Vote ouvert — {responded}/{total} compagnons ont répondu',
  'poll.missing_prefix': 'N’ont pas consulté l’oracle :',
  'poll.responded_prefix': 'Ont consulté l’oracle :',
  /* — réponse au vote — */
  'calendar.answer_menu_aria': 'Répondre à l’appel du conseil — {slot}',
  'calendar.answer_withdraw': 'Reprendre ma réponse',
  /* — création et suivi du vote — */
  'pollui.creation_title': 'Convoquer un conseil de date',
  'pollui.creation_computed_title': 'Fenêtres calculées par l’oracle',
  'pollui.creation_computed_empty': 'L’oracle ne calcule aucune fenêtre disponible.',
  'pollui.creation_load_more_one': '{n} fenêtre de plus',
  'pollui.creation_load_more_many': '{n} fenêtres de plus',
  'pollui.creation_all_shown': 'Toutes les fenêtres calculées sont affichées',
  'pollui.creation_custom_title': 'Fenêtres à votre façon',
  'pollui.creation_add_custom': 'Ajouter une fenêtre à votre façon',
  'pollui.creation_selected_count': '{n} option(s) retenue(s)',
  'pollui.creation_submit': 'Convoquer le conseil',
  'pollui.creation_desync_error':
    'Le conseil a été convoqué, mais son état n’a pu être rafraîchi ici. Rechargez la page pour le voir plutôt que de convoquer un autre conseil.',
  'pollui.creation_error': 'Le conseil n’a pu être convoqué. Réessayez.',
  'pollui.response_not_saved_aria': 'Non inscrit',
  'pollui.response_partial_error':
    '{success}/{total} réponse(s) inscrite(s). Réessayez pour les autres.',
  'pollui.status_voters_aria': 'Votants du conseil',
  'pollui.status_missing_aria': 'N’ont pas encore consulté l’oracle pour cette date',
  'pollui.status_choose_confirm': 'Sceller {date} — {slot} comme date de la prochaine séance ?',
  'pollui.status_choose_no_vote_warning': '⚠️ Aucun compagnon n’a voté pour cette date.',

  /* ═══ Annonces ═══ */
  /* — annonces — */
  'announcement.scope_campaign_label': 'Toute la chronique',
  'announcement.scope_oneshot_label': 'Cette quête',
  'announcement.scope_scenario_label': 'Ce chapitre',
  'announcement.publish_cta': 'Proclamer une annonce',
  'announcement.text_placeholder': 'Rédiger une annonce...',
  'announcement.published_notice': 'Annonce proclamée.',
  'announcement.unseen_label': 'Non lue — cliquez pour marquer comme lue',
  'announcement.publish_error': 'Votre proclamation n’a pu être publiée. Réessayez.',

  /* ═══ Personnages ═══ */
  /* — liste « Personnages » — */
  'my_characters.title': 'Mes personnages',
  'my_characters.empty': 'Nul personnage forgé. Créez-en un depuis une quête…',
  'my_characters.no_match': 'Aucun voyageur ne répond à cette recherche.',
  'my_characters.search_label': 'Rechercher un voyageur',
  'my_characters.sort_niveau': 'Niveau',
  'my_characters.sort_partie': 'Grimoire',
  'my_characters.sort_nom': 'Nom du voyageur',
  'my_characters.create_title': 'À forger',
  'my_characters.create_entry': 'Créer un voyageur pour {partie}',
  'my_characters.create_more': 'Voir les {n} autres grimoires',
  'my_characters.create_more_one': 'Voir l’autre grimoire',
  'my_characters.create_less': 'Voir moins',
  'my_characters.empty_with_entries': 'Nul voyageur forgé pour l’instant.',
  'my_characters.create_entry_hd': 'Créer un Homme Dragon pour {partie}',
  'characters_list.homme_dragons_load_error':
    'Vos Hommes Dragons n’ont pu être chargés depuis le grimoire.',
  /* — fiche de personnage — */
  'character.portrait_edit_cta': 'Retoucher le portrait',
  'character.pdf_crop_edit_cta': 'Ajuster le cadrage PDF',
  'character.sheet_menu_trigger_aria': 'Actions de la fiche',
  'character.export_editable_cta': 'Transcrire en PDF (éditable)',
  'character.export_2pages_cta': 'Transcrire en PDF (2 pages)',
  'character.export_equipment_cta': 'Transcrire l’équipement en PDF',
  'character.export_notes_cta': 'Transcrire les notes en PDF',
  'character.export_error': 'Le PDF n’a pu être transcrit. Réessayez.',
  'character.owner_badge_mj': 'Maître',
  // « Homme Dragon » est un nom propre du système : jamais thématisé (story 33.5).
  'character.nature_dragon': 'Homme Dragon',
  'character.level_badge': 'Niv. {n}',
  'character.party_sheets_tab_label': 'Folios',
  'character.back_to_partie_cta': 'Retour au grimoire',
  'character.no_character_yet': 'Aucun voyageur forgé sur ce grimoire pour l’instant.',
  'characters_sheet.not_found': 'Fiche introuvable dans le grimoire.',
  'characters_sheet.access_denied': 'Cette fiche vous est scellée.',
  'characters_sheet.load_error': 'La fiche du voyageur ne s’ouvre pas. Réessayez.',
  'characters_sheet.portrait_save_error': 'Le portrait n’a pu être inscrit. Réessayez.',
  'characters_sheet.pdf_crop_save_error': 'Le cadrage PDF n’a pu être inscrit. Réessayez.',
  'characters_sheet.field_edit_aria': 'Retoucher {label}',
  'characters_sheet.history_load_error': 'L’historique ne s’ouvre pas.',
  'characters_sheet.history_level': 'Niveau {level}',
  'characters_sheet.item_added_by_mj': 'ajouté par le Maître',
  'characters_sheet.item_edit_aria': 'Retoucher l’objet',
  'characters_sheet.item_remove_aria': 'Effacer l’objet',
  'characters_sheet.notes_load_error': 'Le journal ne s’ouvre pas.',
  'characters_sheet.levelup_title_level': '— Niveau {level}',
  'characters_sheet.levelup_decrease_aria': 'Amoindrir {stat}',
  'characters_sheet.levelup_increase_aria': 'Accroître {stat}',
  'characters_sheet.levelup_attribute_max_sr': 'Déjà au plus haut (12)',
  'characters_sheet.levelup_save_error': 'La montée de niveau n’a pu être inscrite. Réessayez.',
  'characters_sheet.inventory_contenants_empty': 'Aucun contenant dans le coffre pour le moment.',
  'characters_sheet.inventory_animaux_empty': 'Aucune bête pour le moment.',
  'characters_sheet.inventory_add_contenant_cta': '+ Ranger un contenant',
  'characters_sheet.inventory_mj_add_contenant_cta': '+ Ranger un contenant (MJ)',
  'characters_sheet.inventory_add_animal_cta': '+ Accueillir un animal',
  'characters_sheet.inventory_mj_add_animal_cta': '+ Accueillir un animal (MJ)',
  /* — évolution (niveau, historique, inventaire, notes) — */
  'evolution.levelup_banner': 'Niveau [N] : le grimoire vous appelle !',
  'evolution.levelup_cta': 'Monter de niveau',
  'evolution.levelup_wizard_title': 'Montée de niveau',
  'evolution.levelup_step_pv_pe': 'Répartir 3 points entre PV et PE',
  'evolution.levelup_step_capability': 'Choisir la capacité débloquée',
  'evolution.levelup_legendary_journey_text':
    'Un voyage légendaire vous attend — aucun choix supplémentaire à faire.',
  'evolution.levelup_confirm_cta': 'Valider ce niveau',
  'evolution.main_sheet_tab_label': 'Fiche',
  'evolution.history_tab_label': 'Historique',
  'evolution.history_empty': 'Aucun instantané pour le moment.',
  'evolution.mj_edit_trace': 'retouché par le Maître',
  'evolution.landscape_section_title': 'Paysage/Climat favori',
  'evolution.immunity_section_title': 'Immunités',
  'evolution.other_capabilities_title': 'Autres capacités',
  'evolution.derived_hidden': 'Statistiques masquées par le Maître',
  'evolution.hidden_marker': 'Masqué par le Maître',
  'evolution.inventory_section_title': 'Coffre',
  'evolution.inventory_add_cta': '+ Ranger un objet',
  'evolution.inventory_empty': 'Aucun objet dans le coffre pour le moment.',
  'evolution.inventory_overweight_label': 'Trop lourd',
  'evolution.inventory_error': 'Le coffre n’a pu être mis à jour. Réessayez.',
  'evolution.mj_edit_error': 'L’édition n’a pu être inscrite. Réessayez.',
  'evolution.mj_edit_warning_prefix': 'Mise en garde : ',
  'evolution.inventory_mj_add_cta': '+ Ranger un objet (MJ)',
  'evolution.narrative_edit_error': 'La modification n’a pu être inscrite. Réessayez.',
  'evolution.notes_journal_title': 'Journal de notes',
  'evolution.notes_journal_empty': 'Aucune note inscrite pour le moment.',
  'evolution.notes_add_cta': '+ Inscrire une entrée',
  'evolution.note_share_toggle': 'Partager avec les compagnons',
  'evolution.note_private_label': 'Entrée scellée',
  'evolution.note_shared_label': 'Entrée partagée avec les compagnons',
  'evolution.notes_error': 'Le journal n’a pu être mis à jour. Réessayez.',
  /* — groupe de joueurs (troupe) — */
  'roster.mj_badge': 'MJ',
  'roster.invite_slot': 'Convier un compagnon',
  'roster.collapse_label': 'Replier la troupe',
  'roster.expand_label': 'Déplier la troupe',
  'roster.levelup_badge': 'Montée de niveau disponible',
  'roster.create_slot_label': 'créer mon personnage',
  /* — création de personnage — */
  'character.create_cta': 'Créer un voyageur',
  'character.choice_deselect_hint': 'Toucher pour retirer ce choix',
  'character.choice_talents_label': 'Talents',
  'character.choice_advantages_label': 'Avantages',
  'character.choice_required_flag': 'Requis',
  'character.choice_reference_toggle': 'Occupations et actions',
  'character.equipment_group_toggle': '{group}, {n} objets',
  'character.equipment_filter_all': 'Tout le rayon',
  'character.equipment_filter_mine': 'Mon choix',
  'character.equipment_qty_less': 'Retirer un exemplaire de {name}',
  'character.equipment_qty_more': 'Ajouter un exemplaire de {name}',
  'character.recap_button': 'Résumé',
  'character.recap_title': 'Résumé du voyageur',
  'character.recap_cart_title': 'Coffre',
  'character.recap_remove': 'Retirer',
  'character.recap_total': 'Total',
  'character.recap_empty_hint':
    'Les statistiques dérivées se révéleront une fois les attributs assignés.',
  'detail.row_attributes': 'Attributs',
  'detail.row_difficulty': 'Difficulté',
  'detail.row_effect': 'Effet',
  'detail.row_conditions': 'Conditions',
  'detail.narrative_show': 'Lire le récit',
  'detail.narrative_hide': 'Refermer le récit',
  'character.equipment_group_individual': 'Objets',
  'character.equipment_group_contenant': 'Contenants',
  'character.equipment_group_animal': 'Animaux',
  'character.equipment_search_label': 'Rechercher un objet',
  'character.equipment_search_placeholder': 'Nom d’un objet…',
  'character.equipment_budget': 'Bourse · {spent} / {total} Po',
  'character.equipment_over_budget': '— {n} Po de trop',
  'character.equipment_search_empty': 'Aucun objet ne répond à cet appel…',
  'character.step_class': 'Choisir sa vocation',
  'character.step_type': 'Choisir sa voie',
  'character.step_magic': 'Sceller son lien avec la magie',
  'character.step_portrait_intro':
    'Ajoutez un portrait si vous le souhaitez — cette étape est entièrement facultative et peut être passée à tout moment.',
  'characters_wizard.loading': 'L’assistant ouvre ses pages…',
  'characters_wizard.step_prev_aria': 'Page précédente',
  'characters_wizard.step_next_aria': 'Page suivante',
  'characters_wizard.step_progress': 'Page {index}/{total} · {label}',
  'characters_wizard.submitting': 'Forge…',
  'characters_wizard.summary_aria': 'Récapitulatif du voyageur',
  'characters_wizard.summary_default_title': 'Voyageur',
  'characters_wizard.load_error_no_module':
    'Ce livre de règles n’a pas encore d’assistant de création.',
  'characters_wizard.load_error':
    'L’assistant de création n’a pu être ouvert. Vérifiez votre connexion et réessayez.',
  'characters_wizard.portrait_upload_warning':
    'Voyageur forgé, mais son portrait n’a pu être inscrit. Réessayez depuis la fiche.',
  'characters_wizard.already_has_character': 'Vous avez déjà un voyageur sur ce grimoire',
  'characters_wizard.invalid_data': 'Données invalides. Relisez votre saisie.',
  'characters_wizard.attributes_profile_aria': "Profil d'attributs",
  'characters_wizard.attributes_banner_profile': 'Profil',
  'characters_wizard.attributes_banner_one': '— {n} valeur sur {total} inscrite',
  'characters_wizard.attributes_banner_many': '— {n} valeurs sur {total} inscrites',
  'characters_wizard.attributes_chip_remaining': '{value}, encore {n} à inscrire',
  'characters_wizard.equipment_mode_aria': 'Choisir comment s’équiper',
  'characters_wizard.equipment_mode_kit': 'Nécessaire préparé',
  'characters_wizard.equipment_mode_shopping': 'Emplettes libres',
  'characters_wizard.equipment_filter_aria': 'Filtre du catalogue du grimoire',
  'characters_wizard.weapon_category_aria': "Choisir une catégorie d'arme",
  'characters_wizard.weapon_item_aria': 'Choisir son arme précise',
  'characters_wizard.weapon_custom_card': 'Forger une arme libre',
  /* — portrait — */
  'portrait.cropper_choose_image': 'Choisir une image',
  'portrait.cropper_area_aria':
    'Zone de recadrage du portrait. Flèches pour déplacer, plus/moins pour zoomer.',
  'portrait.cropper_zoom': 'Zoom',
  'portrait.panel_alt': 'Portrait enluminé de {name}',
  'portrait.panel_caption': 'Portrait enluminé',
  'portrait.avatar_aria': 'Portrait de {name}',
  'portrait.avatar_aria_empty': 'Portrait de {name} (aucune image)',

  /* ═══ Homme Dragon ═══ */
  'homme-dragon.create_cta': 'Créer mon Homme Dragon',
  'homme-dragon.race_label': 'Race',
  'homme-dragon.artefact_label': 'Artefact',
  'homme-dragon.created_notice': 'Votre Homme Dragon a pris vie.',
  'hd.page_back_to_characters': 'Retour à « Personnages »',
  'hd.creation_page_title': 'Forger un Homme Dragon',
  'hd.creation_check_error': 'L’Homme Dragon de cette aventure n’a pu être vérifié. Réessayez.',
  'hd.sheet_load_error': 'La fiche ne s’ouvre pas. Réessayez.',
  'hd.sheet_export_pdf': 'Transcrire en PDF',
  'hd.sheet_export_menu_aria': 'Format de la transcription PDF',
  'hd.sheet_export_editable': 'PDF éditable',
  'hd.sheet_export_2pages': 'PDF 2 pages (à imprimer)',
  'hd.sheet_export_error': 'La fiche n’a pu être transcrite en PDF. Réessayez.',
  'hd.sheet_artefact_change_error': 'L’artefact n’a pu être changé. Réessayez.',
  'hd.sheet_cadeau_empty': 'Aucun artefact n’est disponible dans le grimoire.',
  'hd.sheet_cadeau_choose_btn': 'Élire cet artefact',
  'hd.sheet_cadeau_confirm_strong': 'Ce choix est définitif : le sceau ne se brise pas.',
  'hd.sheet_cadeau_confirm_text':
    'Offrir « {nom} » à l’Homme Dragon ? Il ne pourra plus être retouché.',
  'hd.sheet_cadeau_confirm_btn': 'Sceller ce choix définitif',
  'hd.sheet_cadeau_back_btn': 'Revenir au choix',
  'hd.sheet_eveil_empty': 'Aucun pouvoir d’éveil n’est consigné.',
  'hd.sheet_aventures_empty': 'Aucune aventure inscrite pour l’instant.',
  'hd.sheet_voyageurs_empty': "Aucun voyageur pour l'instant.",
  'hd.sheet_aventure_add_empty': 'Aucune aventure Ryuutama sans Homme Dragon à ajouter.',
  'hd.sheet_aventure_add_error': 'Cette aventure n’a pu être ajoutée. Réessayez.',
  'hd.sheet_aventure_remove_aria': 'Retirer l’aventure {nom}',
  'hd.sheet_aventure_remove_confirm':
    'Retirer « {nom} » ? Le niveau de l’Homme Dragon peut baisser ; sa fiche, sa réserve et ses choix demeurent.',
  'hd.sheet_aventure_remove_error': 'Cette aventure n’a pu être retirée. Réessayez.',
  'hd.sheet_historique_empty': 'Aucun chapitre joué pour l’instant.',
  'hd.wizard_step_progress': 'Page {n}/{total} · {etape}',
  'hd.wizard_more_aria': 'Consulter la glose de {nom}',
  'hd.wizard_artefact_empty': 'Aucun artefact n’est consigné pour cette race.',
  'hd.wizard_create_conflict_error': 'Cette aventure a déjà un Homme Dragon.',
  'hd.wizard_create_error': 'Votre Homme Dragon n’a pu être forgé. Réessayez.',
  'hd.panel_load_error': 'L’Homme Dragon de cette aventure ne s’ouvre pas. Réessayez.',
  'hd.panel_linked_title': 'Homme Dragon de cette aventure',
  'hd.panel_linked_help': 'Sa fiche, son niveau et son historique cumulent toutes ses aventures.',
  'hd.panel_none_title': 'Aucun Homme Dragon pour cette aventure',
  'hd.panel_create_cta': 'Forger un Homme Dragon pour {partie}',
  'hd.panel_associate_empty': 'Vous n’avez encore aucun autre Homme Dragon à relier.',
  'hd.panel_associate_label': 'Relier un existant',
  'hd.panel_associate_error': 'Cet Homme Dragon n’a pu être relié. Réessayez.',
  'hd.panel_dissociate_confirm':
    'Délier {nom} de « {partie} » ? Son niveau peut baisser ; sa fiche, sa réserve et ses choix demeurent.',
  'hd.panel_dissociate_error': 'Cet Homme Dragon n’a pu être délié. Réessayez.',
  'hd.reserve_autosaved': 'Inscrite automatiquement, utilisée pour la transcription PDF.',
  'hd.reserve_pick_btn': 'Choisir un souffle',
  'hd.reserve_pick_for_slot': "Choisir un souffle pour l'emplacement {n}",
  'hd.reserve_change_aria': "Changer le souffle de l'emplacement {n} : {nom}",
  'hd.reserve_remove_aria': "Retirer {nom} de l'emplacement {n}",
  'hd.reserve_save_error': 'La réserve n’a pu être inscrite. Réessayez.',
  'hd.reserve_undo_text': "{nom} retiré de l'emplacement {n}.",
  'hd.reserve_removed_status':
    "{nom} retiré de l'emplacement {n}. Annuler disponible pendant quelques secondes.",
  'hd.reserve_restored_status': '{nom} replacé dans l’emplacement {n}',
  'hd.reserve_placed_status': '{nom} placé dans l’emplacement {n}. Réserve inscrite',
  'hd.picker_place_btn': "Mettre dans l'emplacement {n}",
  'hd.picker_consult_hint': 'Consultez un souffle de la liste pour lire sa description.',
  'hd.picker_choose_hint': 'Choisissez un souffle dans la liste.',
  'hd.picker_slot_gone': 'Cet emplacement n’existe plus au grimoire.',
  'hd.picker_blocked_announce': "Placement impossible dans l'emplacement {n} : {raison}",
  'hd.picker_description_aria': 'Glose : {nom}',
  'core.homme_dragon_sans_aventure': 'Sans aventure',
};

/** Ensemble des clés de ton, dérivé du thème de référence. */
export type ToneKey = keyof typeof grimoireEmeraude;
