// Thème de référence : son objet fixe les clés de ton que les autres thèmes doivent porter
// (cf. `ToneKey`). Toute nouvelle clé s'ajoute ici d'abord ; un thème qui l'omet ne compile plus.
export const grimoireEmeraude = {
  /* — navigation — */
  'nav.my_games': 'Mes aventures',
  'nav.create_game': 'Lancer une quête',
  'nav.logout': 'Fermer le grimoire',
  'nav.calendar': 'Calendrier',
  'nav.account': 'Mon grimoire',
  'nav.characters': 'Personnages',
  /* — dashboard — */
  'dashboard.title_invitations': 'Invitations reçues',
  'dashboard.empty': 'Nulle quête en cours. Forgez la première…',
  'dashboard.role_prefix': 'Rang :',
  'dashboard.role_mj': 'Maître',
  'dashboard.role_player': 'Héros',
  'dashboard.status_closed_badge': 'Terminée',
  /* — signalétique d'état (Story 29.7) — */
  'dashboard.section_awaiting': 'Ce qui t’attend',
  'dashboard.section_ongoing': 'En cours',
  'dashboard.section_upcoming': 'À venir',
  'dashboard.section_finished': 'Terminées',
  /* — filtres, tri, favoris (Story 29.8) — */
  'dashboard.empty_filtered': 'Aucun grimoire ne répond à ces critères.',
  'dashboard.filter_role_label': 'Rang',
  'dashboard.filter_role_all': 'Tous',
  'dashboard.filter_status_label': 'Statut',
  'dashboard.filter_status_all': 'Tous',
  'dashboard.sort_urgence': 'Urgence',
  'dashboard.sort_date': 'Date',
  'dashboard.sort_nom': 'Nom',
  'dashboard.sort_type': 'Type',
  'dashboard.sort_statut': 'Statut',
  'dashboard.hide_finished_label': 'Masquer les grimoires clos',
  'dashboard.show_finished_btn': 'Afficher les grimoires clos',
  'dashboard.favorite_add_aria': 'Marquer comme favori',
  'dashboard.favorite_remove_aria': 'Retirer des favoris',
  /* — barre de contrôles partagée (Story 29.9) — */
  'dashboard.search_label': 'Rechercher un grimoire',
  'dashboard.row_signal_count_aria': '{n} chose(s) à faire',
  'list_control_bar.toggle_aria': 'Afficher les filtres et le tri',
  'list_control_bar.view_mode_group_aria': 'Densité d’affichage',
  'list_control_bar.view_mode_large_aria': 'Grande vignette',
  'list_control_bar.view_mode_medium_aria': 'Vignette intermédiaire',
  'list_control_bar.view_mode_compact_aria': 'Liste compacte',
  'list_control_bar.sort_label': 'Trier par',
  'list_control_bar.reset_pill_label': 'Réglages modifiés',
  /* — my-characters (Story 29.2) — */
  'my_characters.title': 'Mes personnages',
  'my_characters.empty': 'Nul personnage forgé. Créez-en un depuis une quête…',
  'my_characters.no_match': 'Aucun personnage ne répond à cette recherche.',
  'my_characters.search_label': 'Rechercher un personnage',
  'my_characters.sort_niveau': 'Niveau',
  'my_characters.sort_partie': 'Partie',
  'my_characters.sort_nom': 'Nom',
  /* — section de création (Story 29.16) — */
  'my_characters.create_title': 'À forger',
  'my_characters.create_entry': 'Créer un voyageur pour {partie}',
  'my_characters.create_more': 'Voir les {n} autres',
  'my_characters.create_more_one': 'Voir l’autre',
  'my_characters.create_less': 'Voir moins',
  'my_characters.empty_with_entries': 'Nul voyageur forgé pour l’instant.',
  /* — ligne de création de l'Homme Dragon (Story 33.5) — */
  'my_characters.create_entry_hd': 'Créer un Homme Dragon pour {partie}',
  /* — partie-form — */
  'partie.new_title': 'Nouvelle quête',
  'partie.edit_title': 'Retranscrire le parchemin',
  'partie.save_btn': 'Inscrire',
  'partie.cancel_btn': 'Refermer',
  'partie.name_label': 'Nom du grimoire',
  'partie.system_label': 'Système de jeu',
  'partie.kind_label': 'Nature de la quête',
  'partie.description_label': 'Préambule (facultatif)',
  'partie.kind_ONE_SHOT': 'Quête unique',
  'partie.kind_CAMPAGNE_LINEAIRE': 'Chronique',
  'partie.kind_CAMPAGNE_EPISODIQUE': 'Chronique épisodique',
  'partie.kind_refusal_closed': 'Ce grimoire est clos. Rouvrez-le avant d’en changer la nature.',
  'partie.kind_refusal_too_many_scenarios':
    'Ce grimoire compte {count} scénarios ; une quête unique n’en porte qu’un.',
  'partie.courant_choice_title': 'Quel scénario reste en cours ?',
  'partie.courant_choice_help':
    'Une chronique ne suit qu’un scénario à la fois. Les autres repasseront « à venir » — leurs séances et leurs dates sont conservées.',
  'partie.courant_choice_confirm': 'Sceller ce choix',
  'partie.cover_add': 'Enluminer ce grimoire',
  'partie.cover_change': 'Changer l’enluminure',
  'partie.cover_remove': 'Retirer l’enluminure',
  'partie.cover_uploading': 'L’enluminure se fixe sur le parchemin…',
  'partie.cover_upload_error': 'L’enluminure n’a pu être fixée. Réessayez.',
  'partie.cover_remove_error': 'L’enluminure n’a pu être retirée. Réessayez.',
  'partie.cover_reject_type': 'Seules les images JPEG, PNG et WEBP peuvent enluminer un grimoire.',
  'partie.cover_reject_size': 'Cette image dépasse 5 Mo : choisissez-en une plus légère.',
  'partie.save_error': 'Ce grimoire n’a pu être inscrit. Réessayez.',
  'partie.created_but_cover_failed':
    'Le grimoire est bien inscrit, mais son enluminure n’a pu être fixée. Vous pouvez la redéposer ici.',
  'partie.fields_saved_but_convert_failed':
    'Les autres modifications sont enregistrées, mais la nature du grimoire n’a pu être changée. Réessayez.',
  /* — partie-detail — */
  'partie.scheduling_title': 'Prochaine séance',
  'partie.no_session': "Aucune séance convoquée. Consultez l'oracle des créneaux.",
  'partie.members_title': '⚔ Compagnons',
  'partie.no_members': "Nulle âme pour l'instant.",
  'partie.remove_member_btn': 'Retirer',
  'partie.no_description': 'Ce grimoire est muet.',
  'partie.invite_title': 'Convoquer un compagnon',
  'partie.search_label': 'Nom ou signe distinctif',
  'partie.search_btn': 'Scruter',
  'partie.invite_btn': 'Convoquer',
  'partie.links_title': "Parchemins d'invocation",
  'partie.generate_link': 'Tisser un parchemin',
  'partie.notice_invited': 'Missive envoyée à {name}.',
  'partie.invite_by_email_label': 'Adresse du destinataire',
  'partie.invite_by_email_btn': 'Envoyer une missive',
  'partie.notice_invited_email': 'Missive envoyée à {email}.',
  'partie.notice_invite_email_error': "La missive n'a pu être envoyée. Réessayez.",
  'partie.reference_sheets_title': 'Grimoires de référence',
  'partie.asset_journal_cta': 'Journal',
  'partie.asset_carte_cta': 'Carte',
  'partie.asset_download_error': "Ce grimoire n'a pas pu être déterré. Réessayez.",
  'partie.prep_sheets_title': 'Grimoires de préparation (MJ)',
  'partie.asset_monde_cta': 'Monde',
  'partie.asset_monstre_cta': 'Monstre',
  'partie.asset_ville_cta': 'Ville',
  'partie.asset_objectif_chasse_cta': 'Objectif — Chasse',
  'partie.asset_objectif_quete_cta': 'Objectif — Quête',
  'partie.asset_objectif_voyage_cta': 'Objectif — Voyage',
  'partie.asset_oeuf_de_bataille_cta': 'Œuf de bataille',
  'partie.asset_structure_cta': 'Structure',
  /* — zones de l'onglet Détails (Story 32.2) — noms CONTRACTUELS, identiques dans les trois
     thèmes (même principe que cta.destiny_mode, Story 36.9) : ce sont les trois catégories que
     l'épic nomme explicitement (Action/Consultation/Référence), pas un intitulé libre à décliner
     par thème. La clé existe pour qu'un thème futur puisse malgré tout les teinter. */
  'partie.details_zone_action': 'Action',
  'partie.details_zone_consultation': 'Consultation',
  'partie.details_zone_reference': 'Référence',
  /* — états de scénario et de séance (Story 32.3) — noms CONTRACTUELS, IDENTIQUES dans les trois
     thèmes, exactement comme les trois zones ci-dessus et `cta.destiny_mode` (story 36.9) : ce
     sont des noms d'état fixés par la conception, pas des intitulés à décliner par univers. La
     clé existe pour qu'un thème futur puisse malgré tout les teinter.
     🚨 « Courant », JAMAIS « En cours » : le bouton voisin de `scenario-editor` dit déjà
     « Marquer comme Courant », et « en cours » reste réservé au VOTE — deux choses différentes
     ne peuvent pas porter le même mot.
     🚨 La paire vote répondu / non répondu porte DEUX libellés distincts (contrat EXPERIENCE.md
     §5, déjà appliqué par l'Agenda) : la teinte ne doit jamais être la seule différence. */
  'status.scenario_brouillon': 'Brouillon',
  'status.scenario_a_venir': 'À venir',
  'status.scenario_courant': 'Courant',
  'status.scenario_passe': 'Passé',
  'status.seance_a_planifier': 'À planifier',
  'status.seance_answer_poll': 'Réponds au vote',
  'status.seance_poll_open': 'Vote en cours',
  'status.seance_inscriptions_ouvertes': 'Inscriptions ouvertes',
  'status.seance_programmee': 'Programmée',
  'status.seance_a_debriefer': 'À débriefer',
  'status.seance_jouee': 'Jouée',
  'partie.notice_copy': 'Parchemin copié dans la besace.',
  'partie.edit_btn': 'Retranscrire',
  'partie.visibility_btn': 'Sceller des secrets',
  'partie.close_btn': 'Clore le grimoire',
  'partie.reopen_btn': 'Rouvrir le grimoire',
  'partie.status_closed_label': 'Ce grimoire est clos.',
  /* — signaux d'état (Story 29.7, FR-12) — */
  'partie.signal_personnage_a_creer': 'Créer son héros',
  'partie.signal_vote_en_cours_sans_reponse': 'Vote en attente',
  'partie.signal_compte_rendu_non_redige': 'Compte-rendu à écrire',
  'partie.signal_homme_dragon_a_creer': 'Créer son Homme Dragon',
  'partie.signal_aucun_membre_invite': 'Aucun compagnon convoqué',
  'partie.signal_aucun_scenario_en_cours': 'Aucune quête en cours',
  'partie.signal_aucune_date_ni_vote': 'Aucune date ni vote',
  'partie.signal_rapport_fin_manquant': 'Récit de fin manquant',
  'partie.signal_prochaine_seance_connue': 'Prochaine séance connue',
  'partie.signal_partie_terminee': 'Grimoire clos',
  'partie.signal_more_count': '+{n}',
  'partie.delete_btn': 'Brûler le parchemin',
  'partie.invitations_tab_label': 'Invitations',
  /* — calendrier & vote — */
  'cta.find_date': "Consulter l'oracle des créneaux",
  'cta.guild_calendar': 'Voir le grimoire des disponibilités',
  'cta.save_constraint': 'Inscrire dans le grimoire',
  'section.slots': 'Fenêtres de la destinée',
  'empty.no_slots': "L'oracle ne voit aucun créneau libre. Les parchemins manquent de données.",
  'success.constraint_saved': 'Contrainte gravée dans le parchemin.',
  'alert.missing_player': "{name} n'a pas encore consulté l'oracle.",
  'cta.choose_date': 'Sceller ce créneau',
  'cta.cancel_poll': 'Brûler le parchemin de vote',
  'cta.restore_default_layers': 'Rétablir mon grimoire par défaut',
  'success.poll_created': 'Vote ouvert. Les membres ont été avertis.',
  'poll.status_title': 'Vote en cours',
  'poll.vote_pending': 'Vote de date en cours — parchemin en attente',
  'success.vote_cast': 'Réponse inscrite dans le grimoire.',
  'cta.confirm_votes': 'Sceller mes réponses',
  'cta.withdraw_vote': 'Retirer ma réponse',
  'success.vote_withdrawn': 'Réponse retirée du grimoire.',
  'poll.withdraw_error': 'Le retrait a échoué. Réessayez.',
  'poll.cast_error': 'Impossible d’enregistrer ta réponse. Réessayez.',
  'poll.vote_closed': "Ce vote est clos. L'oracle a tranché.",
  'alert.all_responded': 'Tous les compagnons ont répondu au vote.',
  'poll.status_summary': 'Vote ouvert — {responded}/{total} compagnons ont répondu',
  /* — mode Destinée et panneau réduit (Story 36.9) — */
  // Nom du MODE, identique dans les trois thèmes : « ✦ Destinée » est le nom que la spec lui
  // donne (EXPERIENCE.md §4.4 ter), au même titre que « Vue mois ». La clé existe pour qu'un
  // thème futur puisse le teinter, pas pour qu'il change aujourd'hui.
  'cta.destiny_mode': 'Destinée',
  'poll.missing_prefix': 'N’ont pas consulté l’oracle :',
  'poll.responded_prefix': 'Ont consulté l’oracle :',
  /* — annonces (Epic 9) — */
  'announcement.scope_campaign_label': 'Toute la campagne',
  'announcement.scope_oneshot_label': 'Cette quête',
  'announcement.scope_scenario_label': 'Ce chapitre',
  'announcement.publish_cta': 'Proclamer une annonce',
  'announcement.text_placeholder': 'Rédiger une annonce...',
  'announcement.published_notice': 'Annonce proclamée.',
  'announcement.unseen_label': 'Non lue — cliquez pour marquer comme lue',
  /* — personnages (Palier P3) — */
  'character.create_cta': 'Créer un voyageur',
  'character.choice_deselect_hint': 'Toucher pour désélectionner',
  'character.choice_talents_label': 'Talents',
  'character.choice_advantages_label': 'Avantages',
  'character.choice_required_flag': 'Obligatoire',
  'character.choice_reference_toggle': 'Occupations et actions',
  'character.equipment_group_toggle': '{group}, {n} objets',
  'character.equipment_filter_all': 'Tout',
  'character.equipment_filter_mine': 'Ma sélection',
  'character.equipment_qty_less': 'Retirer un exemplaire de {name}',
  'character.equipment_qty_more': 'Ajouter un exemplaire de {name}',
  'character.recap_button': 'Récap',
  'character.recap_title': 'Récapitulatif',
  'character.recap_cart_title': 'Panier',
  'character.recap_remove': 'Retirer',
  'character.recap_total': 'Total',
  'character.recap_empty_hint':
    'Les statistiques dérivées apparaîtront une fois les attributs assignés.',
  'detail.row_attributes': 'Attributs',
  'detail.row_difficulty': 'Difficulté',
  'detail.row_effect': 'Effet',
  'detail.row_conditions': 'Conditions',
  'detail.narrative_show': 'Lire le récit',
  'detail.narrative_hide': 'Masquer le récit',
  'character.equipment_group_individual': 'Objets',
  'character.equipment_group_contenant': 'Contenants',
  'character.equipment_group_animal': 'Animaux',
  'character.equipment_search_label': 'Rechercher un objet',
  'character.equipment_search_placeholder': 'Rechercher un objet…',
  'character.equipment_budget': 'Budget · {spent} / {total} Po',
  'character.equipment_over_budget': '— dépassement de {n} Po',
  'character.equipment_search_empty': 'Aucun objet ne répond à cet appel…',
  'character.step_class': 'Choisir sa vocation',
  'character.step_type': 'Choisir sa voie',
  'character.step_magic': 'Sceller son lien avec la magie',
  'character.step_portrait_intro':
    'Ajoute un portrait si tu le souhaites — cette étape est entièrement facultative et peut être passée à tout moment.',
  'character.portrait_edit_cta': 'Modifier le portrait',
  'character.pdf_crop_edit_cta': 'Ajuster le cadrage PDF',
  'character.sheet_menu_trigger_aria': 'Actions de la fiche',
  'character.export_editable_cta': 'Exporter en PDF (éditable)',
  'character.export_2pages_cta': 'Exporter en PDF (2 pages)',
  'character.export_equipment_cta': "Exporter l'équipement en PDF",
  'character.export_notes_cta': 'Exporter les notes en PDF',
  'character.export_error': "Le parchemin n'a pas pu être copié. Réessayez.",
  'character.owner_badge_mj': 'Maître',
  /* « Homme Dragon » est un nom propre du système : jamais thématisé (Story 33.5). */
  'character.nature_dragon': 'Homme Dragon',
  'character.level_badge': 'Niv. {n}',
  'character.party_sheets_tab_label': 'Fiches',
  /* — bouton retour vers la partie depuis la fiche d'un personnage — */
  'character.back_to_partie_cta': 'Retour à la partie',
  /* — état vide "Fiches" (Story 29.15) — */
  'character.no_character_yet': 'Aucun personnage créé sur cette partie pour l’instant.',
  /* — Homme Dragon (Epic 10, Story 10.1) — */
  'homme-dragon.create_cta': 'Créer mon Homme Dragon',
  'homme-dragon.race_label': 'Race',
  'homme-dragon.artefact_label': 'Artefact',
  'homme-dragon.created_notice': 'Votre Homme Dragon a pris vie.',
  /* — roster (Story 6.1) — */
  'roster.mj_badge': 'MJ',
  'roster.invite_slot': 'Convier un compagnon',
  'roster.collapse_label': 'Replier la troupe',
  'roster.expand_label': 'Déplier la troupe',
  'roster.levelup_badge': 'Montée de niveau disponible',
  /* — slot d'initiale « créer mon personnage » (Story 29.15) — */
  'roster.create_slot_label': 'créer mon personnage',
  /* — évolution du personnage (Story 6.2) — */
  'evolution.xp_distribute_cta': "Distribuer de l'XP",
  'evolution.xp_panel_title': "Distribution d'XP",
  'evolution.xp_history_title': "Historique des distributions d'XP",
  'evolution.xp_history_empty': 'Aucune distribution gravée pour le moment.',
  'evolution.xp_note_label': 'Note de session',
  'evolution.xp_confirm_btn': 'Sceller la distribution',
  'evolution.xp_bonus_link': '+ bonus',
  'evolution.xp_levelup_warning': '{name} franchira un niveau',
  /* — montée de niveau & historique (Story 6.3) — */
  'evolution.levelup_banner': 'Niveau [N] disponible !',
  'evolution.levelup_cta': 'Level up !',
  'evolution.levelup_wizard_title': 'Montée de niveau',
  'evolution.levelup_step_pv_pe': 'Répartir 3 points entre PV et PE',
  'evolution.levelup_step_capability': 'Choisir la capacité débloquée',
  'evolution.levelup_legendary_journey_text':
    'Un voyage légendaire vous attend — aucun choix supplémentaire à faire.',
  'evolution.levelup_confirm_cta': 'Valider ce niveau',
  /* — sous-navigation locale de la fiche (Story 29.5) — */
  'evolution.main_sheet_tab_label': 'Fiche',
  'evolution.history_tab_label': 'Historique',
  'evolution.history_empty': 'Aucun instantané pour le moment.',
  'evolution.mj_edit_trace': 'modifié par le MJ',
  'evolution.landscape_section_title': 'Paysage/Climat favori',
  'evolution.immunity_section_title': 'Immunités',
  'evolution.other_capabilities_title': 'Autres capacités',
  'evolution.derived_hidden': 'Statistiques masquées par le MJ',
  'evolution.hidden_marker': 'Masqué par le MJ',
  /* — inventaire chiffré (Story 6.4) — */
  'evolution.inventory_section_title': 'Inventaire',
  'evolution.inventory_add_cta': '+ Ajouter un objet',
  'evolution.inventory_empty': "Aucun objet dans l'inventaire pour le moment.",
  'evolution.inventory_overweight_label': 'Surchargé',
  'evolution.inventory_error': "L'inventaire n'a pas pu être mis à jour. Réessayez.",
  /* — édition MJ sans contrainte (Story 6.6) — */
  'evolution.mj_edit_error': "L'édition n'a pas pu être enregistrée. Réessayez.",
  'evolution.mj_edit_warning_prefix': 'Avertissement : ',
  'evolution.inventory_mj_add_cta': '+ Ajouter un objet (MJ)',
  'evolution.narrative_edit_error': "La modification n'a pas pu être enregistrée. Réessayez.",
  /* — journal de notes personnelles (Story 6.5) — */
  'evolution.notes_journal_title': 'Journal de notes',
  'evolution.notes_journal_empty': 'Aucune note pour le moment.',
  'evolution.notes_add_cta': '+ Ajouter une entrée',
  'evolution.note_share_toggle': 'Partager avec le groupe',
  'evolution.note_private_label': 'Entrée privée',
  'evolution.note_shared_label': 'Entrée partagée avec le groupe',
  'evolution.notes_error': "Le journal n'a pas pu être mis à jour. Réessayez.",
  /* — compte — */
  'account.title': 'Mon grimoire personnel',
  'account.pseudo_label': 'Signe de reconnaissance',
  'account.email_label': 'Sceau de correspondance',
  'account.display_name_label': 'Nom affiché aux autres voyageurs',
  'account.cancel_btn': 'Renoncer',
  'account.saved': 'Le grimoire a retenu ce nom.',
  'account.error': "Le grimoire n'a pas pu retenir ce changement. Réessayez.",
  'account.password_title': 'Renouveler le sortilège de passage',
  'account.current_password_label': 'Sortilège actuel',
  'account.new_password_label': 'Nouveau sortilège',
  'account.password_save_btn': 'Renouveler',
  'account.password_saved': 'Le sortilège de passage a été renouvelé.',
  'account.password_wrong_current': "Ce sortilège n'est pas le bon.",
  'account.password_error': "Le grimoire n'a pas pu renouveler le sortilège. Réessayez.",
  'account.current_password_for_email_label': 'Sortilège actuel',
  'account.new_email_label': 'Nouveau sceau de correspondance',
  'account.email_change_save_btn': 'Envoyer le message',
  'account.email_change_saved': 'Un message est parti vers le nouveau sceau.',
  'account.email_change_wrong_current': "Ce sortilège n'est pas le bon.",
  'account.email_change_taken': 'Un autre voyageur porte déjà ce sceau.',
  'account.email_change_error': "Le grimoire n'a pas pu envoyer la demande. Réessayez.",
  // Story 34.1 — échecs de connexion : chaque texte nomme sa cause par un mot clair.
  'auth.login_invalid': 'Le grimoire ne vous reconnaît pas : identifiants invalides.',
  'auth.login_reset_required':
    'Ce compte doit être réinitialisé : utilisez « Mot de passe oublié ? » pour rouvrir le grimoire.',
  'auth.login_throttled':
    'Trop de tentatives. Patientez une minute avant de frapper de nouveau à la porte du grimoire.',
  'auth.login_unavailable':
    'Le grimoire est indisponible pour le moment. Réessayez dans quelques instants.',
  'auth.login_unexpected': 'Une erreur est survenue. Réessayez.',
  // Story 34.2 — libellés du bouton de révélation du mot de passe : neutres, non thématisés.
  'auth.password_show': 'Afficher le mot de passe',
  'auth.password_hide': 'Masquer le mot de passe',
  // Story 34.3 — ligne d'orientation de la connexion et messages de validation des formulaires
  // d'authentification : libellé neutre de référence, identique dans les trois thèmes (chacun nomme
  // la règle) ; l'habillage thématique relève de la revue éditoriale de l'épic 35.
  'auth.login_invite_only': "L'inscription se fait sur invitation.",
  'auth.field_required': 'Renseignez ce champ.',
  'auth.field_email_invalid': 'Adresse e-mail invalide.',
  'auth.field_pseudo_min': '3 caractères minimum.',
  'auth.field_password_min': '8 caractères minimum.',
  // Story 34.4 — accroche de la bande d'authentification : une par thème (EXPERIENCE.md §3).
  'auth.tagline': "Trouvez le soir où le grimoire s'ouvre",
  'account.calendar_layers_title': 'Ce que révèle mon calendrier',
  'account.calendar_layer.mes-indisponibilites': 'Mes indisponibilités',
  'account.calendar_layer.mes-disponibilites': 'Mes disponibilités',
  'account.calendar_layer.mes-seances': 'Mes séances confirmées',
  'account.calendar_layer.votes-en-cours': 'Les votes en cours',
  'account.calendar_layer.inscriptions-ouvertes': 'Les inscriptions ouvertes',
  'account.calendar_layer.disponibilite-groupe': 'La disponibilité du groupe',
  /* — vue Agenda (Story 36.11) — les libellés de BADGE sont contractuels et identiques dans
     les trois thèmes : EXPERIENCE.md §5 impose « Réponds au vote » / « Vote en cours » comme
     la paire qui distingue à-faire et fait. Seuls les titres de section et le vide varient. */
  'calendar.agenda.section_awaiting': 'Ce qui t’attend',
  'calendar.agenda.section_scheduled': 'Ce qui est annoncé',
  'calendar.agenda.section_past': 'Ce qui est révolu',
  'calendar.agenda.badge_answer_poll': 'Réponds au vote',
  'calendar.agenda.badge_poll_open': 'Vote en cours',
  'calendar.agenda.badge_signup': 'S’inscrire',
  'calendar.agenda.badge_signed_up': 'Inscrit',
  'calendar.agenda.badge_debrief': 'Débriefer',
  'calendar.agenda.empty': 'Rien ne t’attend, rien n’est annoncé.',
  /* — Agenda du MJ (Story 36.12) — même règle : les LIBELLÉS D'ÉTAT et les gabarits chiffrés
     sont contractuels et identiques partout, seuls les titres et les appels à l'action
     prennent le registre du thème. */
  'calendar.agenda.badge_to_seal': 'À sceller',
  'calendar.agenda.poll_open': 'Vote ouvert',
  'calendar.agenda.responded_count': '{n} sur {total} ont répondu',
  'calendar.agenda.slots_proposed': '{n} créneaux proposés',
  'calendar.agenda.missing_voters': 'il manque {names}',
  'calendar.agenda.no_date': 'sans date',
  'calendar.agenda.no_date_proposed': 'Aucune date proposée',
  'calendar.agenda.action_launch_poll': 'Lancer un vote',
  'calendar.agenda.action_seal': 'Sceller',
  'calendar.agenda.action_expand': 'Déplier',
  'calendar.agenda.action_collapse': 'Replier',
  'calendar.agenda.seal_confirm_title': 'Sceller ce créneau ?',
  'calendar.agenda.seal_confirm_body':
    'La séance sera fixée à ce créneau et le vote se refermera. Les autres créneaux proposés disparaîtront.',
  /* — Story 36.14 : la barre repliée, le panneau « Affichage » et la légende —
     🚨 Ces libellés sont IDENTIQUES dans les trois thèmes, comme les six
     `account.calendar_layer.*` : le contrat d'UI les fixe verbatim
     (`contrat-ui-calendrier.html:599-609`, `:655-665`, `:683-686`). La clé existe pour qu'un
     thème futur puisse les teinter — même motif que `cta.destiny_mode` (story 36.9). */
  'calendar.display.trigger': 'Affichage',
  'calendar.display.trigger_aria': "Régler l'affichage du calendrier",
  'calendar.display.section_visible': 'Ce que je vois',
  'calendar.display.show_legend': 'Afficher la légende',
  'calendar.display.filtered_badge': 'Affichage filtré · {n} sur {total} · Rétablir',
  'calendar.legend.title': 'Légende',
  'calendar.legend.group_obvious': 'Se passent d’explication',
  'calendar.legend.group_needs': 'Demandent la légende',
  'calendar.legend.entry.available': 'Je suis disponible',
  'calendar.legend.entry.unavailable': 'Je suis indisponible',
  'calendar.legend.entry.seance': 'Séance confirmée — tu es pris',
  'calendar.legend.entry.vote': 'Créneau proposé au vote',
  'calendar.legend.entry.poll_track': 'Participation : la piste = la troupe',
  'calendar.legend.entry.group': 'Disponibilité du groupe',
  'calendar.legend.entry.none': 'Personne ne s’est prononcé',
  'account.calendar_intents_subtitle': 'Ce que je veux voir en arrivant sur un calendrier.',
  'account.calendar_intent.disponibilites': 'Mes disponibilités & indisponibilités',
  'account.calendar_intent.seances': 'Mes séances confirmées',
  'account.calendar_intent.votes': 'Les votes en cours',
  'account.calendar_intent.groupe': 'La disponibilité du groupe',
  /* — identité — */
  'identity.character_label': 'Personnage',
  'identity.player_label': 'Joueur',
  'identity.homonymy_warning':
    'Un autre membre de cette partie porte le même nom affiché que vous.',
  'identity.homonymy_change_cta': 'Changer mon nom affiché',
  'identity.homonymy_ignore_cta': 'Ignorer',
  /* — textes communs (Story 35.2) — */
  'common.8_caracteres': '8+ caractères',
  'common.a_savoir': 'À savoir',
  'common.accepter': 'Accepter',
  'common.ajouter': 'Ajouter',
  'common.ajouter_une_aventure': 'Ajouter une aventure',
  'common.annonces': 'Annonces',
  'common.annuler': 'Annuler',
  'common.associer': 'Associer',
  'common.au': 'Au',
  'common.aucun_scenario_pour_l_instant': "Aucun scénario pour l'instant.",
  'common.aucune_description_disponible': 'Aucune description disponible.',
  'common.ce_jour_uniquement': 'Ce jour uniquement',
  'common.changer': 'Changer',
  'common.chargement': 'Chargement…',
  'common.chargement_2': 'Chargement...',
  'common.chargement_en_cours': 'Chargement en cours',
  'common.choisir': '-- Choisir --',
  'common.cloturer_le_vote': 'Clôturer le vote',
  'common.confirmer': 'Confirmer',
  'common.connexion': 'Connexion',
  'common.conserver': 'Conserver',
  'common.copier': 'Copier',
  'common.creer': 'Créer',
  'common.creer_un_compte': 'Créer un compte',
  'common.creneau': 'Créneau',
  'common.creneaux_varies': 'créneaux variés',
  'common.date_a_definir': 'Date à définir',
  'common.date_a_definir_2': 'Date à définir.',
  'common.date_retenue_date': 'Date retenue : {date}',
  'common.designe_pour_le_vote': 'désigné pour le vote',
  'common.detail': 'Détail',
  'common.detail_du_jour': 'Détail du jour',
  'common.disponible': 'Disponible',
  'common.dissocier': 'Dissocier',
  'common.du': 'Du',
  'common.effet_facultatif': 'Effet (facultatif)',
  'common.email': 'Email',
  'common.en_savoir_plus': 'En savoir plus',
  'common.enregistrement': 'Enregistrement…',
  'common.enregistrer': 'Enregistrer',
  'common.envoi': 'Envoi…',
  'common.fermer': 'Fermer',
  'common.heure': 'Heure',
  'common.homme_dragon_introuvable': 'Homme Dragon introuvable.',
  'common.impossible_d_enregistrer_ce_choix_reessayez':
    "Impossible d'enregistrer ce choix. Réessayez.",
  'common.impossible_d_enregistrer_ces_disponibilites_reessayez':
    'Impossible d’enregistrer ces disponibilités. Réessayez.',
  'common.impossible_d_enregistrer_la_contrainte': "Impossible d'enregistrer la contrainte.",
  'common.impossible_d_enregistrer_la_modification': 'Impossible d’enregistrer la modification.',
  'common.impossible_de_charger_la_partie_reessayez': 'Impossible de charger la partie. Réessayez.',
  'common.impossible_de_charger_le_scenario_reessayez':
    'Impossible de charger le scénario. Réessayez.',
  'common.impossible_de_charger_les_scenarios_reessayez':
    'Impossible de charger les scénarios. Réessayez.',
  'common.impossible_de_cloturer_le_vote_reessayez': 'Impossible de clôturer le vote. Réessayez.',
  'common.indisponible': 'Indisponible',
  'common.j_ai_deja_un_compte': "J'ai déjà un compte",
  'common.lancer_le_vote': 'Lancer le vote',
  'common.lien_invalide': 'Lien invalide.',
  'common.lien_invalide_ou_expire_merci_de_refaire_une_demande':
    'Lien invalide ou expiré. Merci de refaire une demande.',
  'common.lieu': 'Lieu',
  'common.lire_la_suite': 'Lire la suite',
  'common.modifier': 'Modifier',
  'common.mot_de_passe': 'Mot de passe',
  'common.mot_de_passe_oublie': 'Mot de passe oublié',
  'common.n_max_inscrits': '{n}/{max} inscrits',
  'common.nom_de_l_animal': "Nom de l'animal",
  'common.nom_de_l_objet': "Nom de l'objet",
  'common.nom_du_contenant': 'Nom du contenant',
  'common.non': 'Non',
  'common.nouveau_mot_de_passe': 'Nouveau mot de passe',
  'common.oui': 'Oui',
  'common.ouvrir_aux_joueurs': 'Ouvrir aux joueurs',
  'common.ouvrir_le_scenario_label': 'Ouvrir le scénario {label}',
  'common.ouvrir_le_scenario_label_info': 'Ouvrir le scénario {label} — {info}',
  'common.participants': 'Participants',
  'common.partie_introuvable': 'Partie introuvable.',
  'common.pas_encore_de_personnage': '(pas encore de personnage)',
  'common.passer_cette_etape': 'Passer cette étape',
  'common.peut_etre': 'Peut-être',
  'common.poids': 'Poids',
  'common.precedent': 'Précédent',
  'common.precedent_2': '❮ Précédent',
  'common.prix_facultatif': 'Prix (facultatif)',
  'common.rechercher': 'Rechercher',
  'common.reduire': 'Réduire',
  'common.reessayer': 'Réessayer',
  'common.refuser': 'Refuser',
  'common.reinitialiser_la_date': 'Réinitialiser la date',
  'common.rejoindre': 'Rejoindre',
  'common.remplacer': 'Remplacer',
  'common.renoncer': 'Renoncer',
  'common.repondre_au_vote_label': 'Répondre au vote — {label}',
  'common.repondre_au_vote_label_detail': 'Répondre au vote — {label} — {detail}',
  'common.resume_de_fin': 'Résumé de fin',
  'common.retirer': 'Retirer',
  'common.retour_a_la_connexion': 'Retour à la connexion',
  'common.retour_a_la_partie': 'Retour à la partie',
  'common.revoquer': 'Révoquer',
  'common.scenario_introuvable_revenez_a_la_liste_des_brouillons':
    'Scénario introuvable — revenez à la liste des Brouillons.',
  'common.seance_n': 'Séance {n}',
  'common.suivant': 'Suivant',
  'common.suivant_2': 'Suivant ❯',
  'common.supprimer': 'Supprimer',
  'common.title_seance_index': '{title} — Séance {index}',
  'common.titre': 'Titre',
  'common.type': 'Type',
  'common.une_erreur_inattendue_est_survenue_reessayez':
    'Une erreur inattendue est survenue. Réessayez.',
  'common.valider': 'Valider',
  'common.vote_cloture_sans_date_retenue': 'Vote clôturé sans date retenue.',
  'common.vote_de_date': '· vote de date',
  'common.vue_agenda': 'Vue agenda',
  'common.vue_mois': 'Vue mois',
  'common.vue_semaine': 'Vue semaine',
  /* — textes migrés : auth (Story 35.2) — */
  'route.title_confirm_email_change': "Confirmer le changement d'e-mail",
  'route.title_rollback_email_change': "Annuler le changement d'e-mail",
  'auth.login_identifier_label': 'Email ou pseudo',
  'auth.login_submit': 'Se connecter',
  'auth.login_forgot_link': 'Mot de passe oublié ?',
  'auth.register_invite_only':
    "L'inscription se fait uniquement sur invitation. Ouvre un lien d'invitation pour créer ton compte.",
  'auth.register_pseudo_label': 'Pseudo',
  'auth.register_submit': 'Créer le compte',
  'auth.register_error':
    'Impossible de créer le compte (lien invalide, ou email/pseudo déjà pris ?).',
  'auth.forgot_sent':
    'Si un compte existe pour cette adresse, un e-mail de réinitialisation a été envoyé.',
  'auth.forgot_submit': 'Envoyer le lien',
  'auth.forgot_error': "Impossible d'envoyer la demande pour le moment. Réessaie plus tard.",
  'auth.reset_submit': 'Réinitialiser',
  'auth.reset_redo_link': 'Refaire une demande',
  'auth.confirm_email_title': "Confirmer le changement d'adresse e-mail",
  'auth.confirm_email_done': 'Votre adresse e-mail a été changée.',
  'auth.rollback_email_title': "Annuler le changement d'adresse e-mail",
  'auth.rollback_done':
    'Votre ancienne adresse a été restaurée et toutes les sessions actives ont été coupées.',
  'auth.rollback_continue_btn': 'Continuer vers la réinitialisation du mot de passe',
  'auth.rollback_warning':
    'Restaurer votre ancienne adresse coupera toutes les sessions actives et exigera une réinitialisation de votre mot de passe avant toute reconnexion.',
  'auth.rollback_submit': 'Restaurer mon ancienne adresse',
  'auth.rollback_error': 'Lien invalide ou expiré.',
  'join.not_found_title': 'Lien introuvable',
  'join.not_found_text': "Ce lien d'invitation n'existe pas.",
  'join.title': 'Rejoindre « {name} »',
  'join.logged_as': 'Tu es connecté en tant que',
  'join.login_or_register': 'Connecte-toi ou crée un compte pour rejoindre cette partie.',
  'join.join_error': 'Impossible de rejoindre (lien invalide, expiré, ou déjà membre).',
  'account.appearance_label': 'Apparence',
  'announcement.publish_error': 'Impossible de publier l’annonce. Réessayez.',
  'dashboard.invitation_invited_by': 'invité par {pseudo}',
  'shell.nav_main_aria': 'Navigation principale',
  'shell.banner_close_aria': 'Fermer la notification de {partie}',
  'shell.badge_polls_aria': '{n} vote(s) en attente de réponse',
  'shell.badge_announcements_aria': '{n} annonce(s) non lue(s)',
  /* — textes migrés : calendar-a (Story 35.2) — */
  'calendar.agg_counts_aria': 'Disponibilités',
  'calendar.agg_available_title': 'Disponibles',
  'calendar.agg_unknown_title': 'Inconnus',
  'calendar.agg_unavailable_title': 'Indisponibles',
  'calendar.slots_list_aria': 'Créneaux disponibles',
  'calendar.agenda_missing_more_one': '{listed} et {rest} autre',
  'calendar.agenda_missing_more_many': '{listed} et {rest} autres',
  'calendar.rail_empty': 'Aucun jour à détailler',
  'calendar.rail_status_unknown': 'Rien de prévu',
  'calendar.month_prev_aria': 'Mois précédent',
  'calendar.month_next_aria': 'Mois suivant',
  'calendar.month_today_aria': 'Revenir au mois actuel',
  'calendar.month_cell_instructions':
    "Espace : sélectionner la journée entière. Touches 1, 2, 3 : sélectionner respectivement le matin, l'après-midi ou le soir. Maj plus flèches : étendre la sélection. Entrée : valider la sélection avec ce qu'affiche la barre. Échap : annuler.",
  'calendar.month_day_today_aria': "{day} (aujourd'hui)",
  'calendar.month_status_unknown': 'non déclaré',
  'calendar.layer_group_aria': 'Couches affichées du calendrier',
  'calendar.util_answer_yes': 'oui',
  'calendar.util_answer_maybe': 'peut-être',
  'calendar.util_answer_no': 'non',
  'calendar.util_answer_mine': 'tu as dit {answer}',
  'calendar.util_participation_one': '{n} réponse sur {total}',
  'calendar.util_participation_many': '{n} réponses sur {total}',
  'calendar.util_group_aria_one': 'Disponibilité du groupe : {available} sur {total} disponible',
  'calendar.util_group_aria_many': 'Disponibilité du groupe : {available} sur {total} disponibles',
  'calendar.util_group_all_blocked': 'tout le monde est bloqué',
  'calendar.util_group_nobody': "personne ne s'est prononcé",
  'calendar.util_group_unavailable_one': '{n} indisponible',
  'calendar.util_group_unavailable_many': '{n} indisponibles',
  'calendar.util_word_no_answer': 'sans réponse',
  'calendar.view_back': '← Retour',
  'calendar.view_compose_arm': 'Ajouter des dates',
  'calendar.view_toggle_aria': 'Vue du calendrier',
  'calendar.view_toggle_month_short': 'Mois',
  'calendar.view_toggle_week_short': 'Sem.',
  'calendar.view_toggle_agenda_short': 'Agenda',
  'calendar.view_no_poll': 'Aucun vote de date en cours.',
  'calendar.view_locked_seance_hint': 'Vote pour la séance sélectionnée depuis la fiche scénario.',
  'calendar.view_group_label': '{slot} — {available}/{total} disponibles',
  'calendar.view_group_unavailable_detail': '{n} indisponible(s)',
  'calendar.view_compose_target_poll': 'Créneaux du vote : {label}',
  'calendar.view_compose_target_new': 'Créneaux d’un nouveau vote',
  'calendar.view_compose_blocked_min': 'Un vote demande au moins deux créneaux.',
  'calendar.view_compose_blocked_max': 'Quarante créneaux au maximum.',
  'calendar.view_compose_blocked_no_seance':
    'Aucune séance n’attend un vote : un vote se rattache toujours à une séance.',
  'calendar.view_compose_stale_voters':
    'Une nouvelle réponse est arrivée depuis l’avertissement — revalidez pour voir le chiffre à jour.',
  'calendar.view_compose_save_error': 'Impossible d’enregistrer ces créneaux. Réessayez.',
  'calendar.view_batch_conflict_labels':
    "Ces créneaux se contredisent entre eux ({labels}). Rien n'a été enregistré.",
  'calendar.view_batch_conflict_plain':
    "Ces créneaux se contredisent entre eux. Rien n'a été enregistré.",
  'calendar.view_conflict_in_progress':
    'Une résolution de conflit est déjà en cours. Terminez-la avant de recommencer.',
  'calendar.view_cell_unknown': 'Créneau inconnu',
  'calendar.view_selection_none': 'sur aucun créneau',
  'calendar.view_selection_one': 'le {cell}',
  'calendar.view_selection_many': 'sur {n} créneaux, du {from} au {to}',
  'calendar.view_seal_error': 'Impossible de sceller ce créneau. Réessayez.',
  'calendar.view_range_error': 'La date de début doit être avant ou égale à la date de fin.',
  'calendar.view_load_declarations_error': 'Impossible de charger les disponibilités.',
  'calendar.view_load_slots_error': 'Impossible de charger les créneaux.',
  'calendar.view_load_calendar_error': 'Impossible de charger le calendrier pour cette période.',
  /* — textes migrés : calendar-b (Story 35.2) — */
  'calendar.answer_menu_aria': 'Répondre au vote — {slot}',
  'calendar.answer_withdraw': 'Retirer ma réponse',
  'calendar.card_alerts_aria': 'Alertes disponibilité',
  'calendar.card_full_guild': 'Guilde complète',
  'calendar.card_members_aria': 'Membres',
  'calendar.compose_bar_aria': "Composition des créneaux d'un vote",
  'calendar.compose_confirm_note':
    'Les réponses portées par les créneaux conservés ne sont pas touchées.',
  'calendar.compose_confirm_responses_many': '{n} réponses',
  'calendar.compose_confirm_responses_one': '{n} réponse',
  'calendar.compose_confirm_seance_label': 'Pour quelle séance ?',
  'calendar.compose_confirm_seance_placeholder': 'Choisir une séance…',
  'calendar.compose_confirm_slots_many': '{n} créneaux',
  'calendar.compose_confirm_slots_one': '{n} créneau',
  'calendar.compose_confirm_summary_many': '{n} créneaux proposés.',
  'calendar.compose_confirm_summary_one': '{n} créneau proposé.',
  'calendar.compose_confirm_title_modify': 'Modifier les créneaux du vote',
  'calendar.compose_confirm_warning_many': 'Retirer {slots} supprimera {votes} déjà posées.',
  'calendar.compose_confirm_warning_one': 'Retirer {slots} supprimera {votes} déjà posée.',
  'calendar.compose_count_many': '{n} créneaux désignés',
  'calendar.compose_count_none': 'Aucun créneau désigné',
  'calendar.compose_count_one': '{n} créneau désigné',
  'calendar.conflict_exception_detail':
    "Tu y as une séance. Aucun de ces choix n'y touche. Si elle est annulée, tu redeviens {kind}.",
  'calendar.conflict_exception_many': 'ne sont pas dans la liste',
  'calendar.conflict_exception_one': "n'est pas dans la liste",
  'calendar.conflict_free_many': 'Les {n} autres passent en {kind}',
  'calendar.conflict_free_none': "Rien d'autre n'est enregistré",
  'calendar.conflict_free_one': 'Le 1 autre passe en {kind}',
  'calendar.conflict_intent_prefix': 'Tu déclares',
  'calendar.conflict_keep_many': 'Ces {n} restent comme ils sont',
  'calendar.conflict_keep_one': 'Ce créneau reste comme il est',
  'calendar.conflict_overwrite_many': 'Les {n} deviennent',
  'calendar.conflict_overwrite_one': 'Le créneau devient',
  'calendar.conflict_step_announcement': 'Créneau {progress} : {label}. Remplacer ou conserver ?',
  'calendar.conflict_title_many': '{n} créneaux sont déjà déclarés',
  'calendar.conflict_title_one': '1 créneau est déjà déclaré',
  'calendar.conflict_walkthrough_body': 'On les passe en revue un par un',
  'calendar.conflict_walkthrough_count_many': '{n} décisions à prendre',
  'calendar.conflict_walkthrough_count_one': '{n} décision à prendre',
  'calendar.conflict_walkthrough_label': 'Au cas par cas',
  'calendar.constraint_all_occurrences': 'Toutes les occurrences',
  'calendar.constraint_close_aria': 'Fermer le panneau',
  'calendar.constraint_conflict_prompt':
    'Des disponibilités contradictoires existent déjà pour cette période.',
  'calendar.constraint_delete_error': 'Impossible de supprimer la contrainte.',
  'calendar.constraint_end_date': 'Date de fin',
  'calendar.constraint_expires_on': 'Expire le',
  'calendar.constraint_from_this_day': "De ce jour jusqu'à la fin",
  'calendar.constraint_keep_existing': "Garder l'existant",
  'calendar.constraint_kind_aria': 'Disponibilité',
  'calendar.constraint_modify_error': 'Impossible de modifier la contrainte.',
  'calendar.constraint_occurrence_delete_error': "Impossible de supprimer l'occurrence.",
  'calendar.constraint_occurrence_modify_error': "Impossible de modifier l'occurrence.",
  'calendar.constraint_overwrite': 'Écraser',
  'calendar.constraint_recurring_delete_prompt':
    'Cette contrainte est récurrente. Que souhaitez-vous supprimer ?',
  'calendar.constraint_recurring_modify_prompt':
    'Cette contrainte est récurrente. Que souhaitez-vous modifier ?',
  'calendar.constraint_start_date': 'Date de début',
  'calendar.constraint_type_punctual': 'Ce créneau uniquement',
  'calendar.constraint_type_range': 'Plage de dates',
  'calendar.constraint_type_recurring': 'Récurrent (chaque semaine)',
  'calendar.constraint_whole_series': 'Toute la série',
  'calendar.destiny_next_aria': 'Vote suivant',
  'calendar.destiny_prev_aria': 'Vote précédent',
  'calendar.selbar_announcement': 'Portée : {scope}. Entrée validera : {kind}.',
  'calendar.selbar_count_many': '{n} créneaux sélectionnés',
  'calendar.selbar_count_one': '{n} créneau sélectionné',
  'calendar.selbar_other': 'Autre…',
  'calendar.selbar_scope_aria': 'Portée de la sélection',
  'calendar.selbar_toolbar_aria': 'Actions sur la sélection',
  'calendar.week_decl_available': 'Dispo',
  'calendar.week_decl_punctual': 'Ponctuel',
  'calendar.week_decl_recurring': 'Récurrent',
  'calendar.week_decl_unavailable': 'Indispo',
  'calendar.week_next_aria': 'Semaine suivante',
  'calendar.week_prev_aria': 'Semaine précédente',
  'calendar.week_status_available': 'disponible',
  'calendar.week_status_unavailable': 'indisponible',
  'calendar.week_status_unknown': 'inconnu',
  'calendar.week_today_aria': 'Revenir à la semaine actuelle',
  /* — textes migrés : characters-sheet (Story 35.2) — */
  'characters_sheet.not_found': 'Fiche introuvable.',
  'characters_sheet.access_denied': "Vous n'avez pas accès à cette fiche.",
  'characters_sheet.load_error': 'Impossible de charger la fiche de personnage. Réessayez.',
  'characters_sheet.portrait_save_error': "Le portrait n'a pas pu être enregistré. Réessayez.",
  'characters_sheet.pdf_crop_save_error': 'Le cadrage PDF n’a pas pu être enregistré. Réessayez.',
  'characters_sheet.field_edit_aria': 'Modifier {label}',
  'characters_sheet.history_load_error': "L'historique n'a pas pu être chargé.",
  'characters_sheet.history_level': 'Niveau {level}',
  'characters_sheet.item_added_by_mj': 'ajouté par le MJ',
  'characters_sheet.item_edit_aria': "Modifier l'objet",
  'characters_sheet.item_remove_aria': "Supprimer l'objet",
  'characters_sheet.notes_load_error': "Le journal n'a pas pu être chargé.",
  'characters_sheet.levelup_title_level': '— Niveau {level}',
  'characters_sheet.levelup_decrease_aria': 'Diminuer {stat}',
  'characters_sheet.levelup_increase_aria': 'Augmenter {stat}',
  'characters_sheet.levelup_attribute_max_sr': 'Déjà au maximum (12)',
  'characters_sheet.levelup_save_error':
    'La montée de niveau n’a pas pu être enregistrée. Réessayez.',
  'characters_sheet.inventory_contenants_empty': 'Aucun contenant pour le moment.',
  'characters_sheet.inventory_animaux_empty': 'Aucun animal pour le moment.',
  'characters_sheet.inventory_add_contenant_cta': '+ Ajouter un contenant',
  'characters_sheet.inventory_mj_add_contenant_cta': '+ Ajouter un contenant (MJ)',
  'characters_sheet.inventory_add_animal_cta': '+ Ajouter un animal',
  'characters_sheet.inventory_mj_add_animal_cta': '+ Ajouter un animal (MJ)',
  'characters_list.homme_dragons_load_error': 'Vos Hommes Dragons n’ont pas pu être chargés.',
  /* — textes migrés : characters-wizard (Story 35.2) — */
  'characters_wizard.loading': "Chargement de l'assistant…",
  'characters_wizard.step_prev_aria': 'Étape précédente',
  'characters_wizard.step_next_aria': 'Étape suivante',
  'characters_wizard.step_progress': 'Étape {index}/{total} · {label}',
  'characters_wizard.submitting': 'Création…',
  'characters_wizard.summary_aria': 'Récapitulatif du voyageur',
  'characters_wizard.summary_default_title': 'Voyageur',
  'characters_wizard.load_error_no_module':
    "Ce système de jeu n'a pas encore d'assistant de création.",
  'characters_wizard.load_error':
    "Impossible de charger l'assistant de création. Vérifiez votre connexion et réessayez.",
  'characters_wizard.portrait_upload_warning':
    "Personnage créé, mais le portrait n'a pas pu être enregistré. Réessayez depuis la fiche.",
  'characters_wizard.already_has_character': 'Vous avez déjà un personnage sur cette partie',
  'characters_wizard.invalid_data': 'Données invalides. Vérifiez votre saisie.',
  'characters_wizard.attributes_profile_aria': "Profil d'attributs",
  'characters_wizard.attributes_banner_profile': 'Profil',
  'characters_wizard.attributes_banner_one': '— {n} valeur sur {total} placée',
  'characters_wizard.attributes_banner_many': '— {n} valeurs sur {total} placées',
  'characters_wizard.attributes_chip_remaining': '{value}, encore {n} à placer',
  'characters_wizard.equipment_mode_aria': "Choisir un mode d'équipement",
  'characters_wizard.equipment_mode_kit': 'Nécessaire pré-fait',
  'characters_wizard.equipment_mode_shopping': 'Achat libre',
  'characters_wizard.equipment_filter_aria': 'Filtre du catalogue',
  'characters_wizard.weapon_category_aria': "Choisir une catégorie d'arme",
  'characters_wizard.weapon_item_aria': 'Choisir son arme précise',
  'characters_wizard.weapon_custom_card': 'Créer une arme libre',
  'portrait.cropper_choose_image': 'Choisir une image',
  'portrait.cropper_area_aria':
    'Zone de recadrage du portrait. Flèches pour déplacer, plus/moins pour zoomer.',
  'portrait.cropper_zoom': 'Zoom',
  'portrait.panel_alt': 'Portrait complet de {name}',
  'portrait.panel_caption': 'Portrait complet',
  'portrait.avatar_aria': 'Portrait de {name}',
  'portrait.avatar_aria_empty': 'Portrait de {name} (aucune image)',
  /* — textes migrés : homme-dragon (Story 35.2) — */
  'hd.page_back_to_characters': 'Retour à « Personnages »',
  'hd.creation_page_title': 'Créer un Homme Dragon',
  'hd.creation_check_error': "Impossible de vérifier l'Homme Dragon de cette aventure. Réessayez.",
  'hd.sheet_load_error': 'Impossible de charger la fiche. Réessayez.',
  'hd.sheet_export_pdf': 'Exporter en PDF',
  'hd.sheet_export_menu_aria': "Format de l'export PDF",
  'hd.sheet_export_editable': 'PDF éditable',
  'hd.sheet_export_2pages': 'PDF 2 pages (à imprimer)',
  'hd.sheet_export_error': "Impossible d'exporter la fiche en PDF. Réessayez.",
  'hd.sheet_artefact_change_error': "Impossible de changer d'artefact. Réessayez.",
  'hd.sheet_cadeau_empty': 'Aucun artefact disponible.',
  'hd.sheet_cadeau_choose_btn': 'Choisir cet artefact',
  'hd.sheet_cadeau_confirm_strong': 'Ce choix est définitif.',
  'hd.sheet_cadeau_confirm_text':
    "Offrir « {nom} » à l'Homme Dragon ? Il ne pourra plus être modifié.",
  'hd.sheet_cadeau_confirm_btn': 'Confirmer ce choix définitif',
  'hd.sheet_cadeau_back_btn': 'Revenir au choix',
  'hd.sheet_eveil_empty': "Aucun pouvoir d'éveil disponible.",
  'hd.sheet_aventures_empty': "Aucune aventure pour l'instant.",
  'hd.sheet_voyageurs_empty': "Aucun voyageur pour l'instant.",
  'hd.sheet_aventure_add_empty': 'Aucune aventure Ryuutama sans Homme Dragon à ajouter.',
  'hd.sheet_aventure_add_error': "Impossible d'ajouter cette aventure. Réessayez.",
  'hd.sheet_aventure_remove_aria': 'Retirer l’aventure {nom}',
  'hd.sheet_aventure_remove_confirm':
    "Retirer « {nom} » ? Le niveau de l'Homme Dragon peut baisser ; sa fiche, sa réserve et ses choix sont conservés.",
  'hd.sheet_aventure_remove_error': 'Impossible de retirer cette aventure. Réessayez.',
  'hd.sheet_historique_empty': "Aucun scénario joué pour l'instant.",
  'hd.wizard_step_progress': 'Étape {n}/{total} · {etape}',
  'hd.wizard_more_aria': 'En savoir plus sur {nom}',
  'hd.wizard_artefact_empty': "Aucun artefact n'est disponible pour cette race.",
  'hd.wizard_create_conflict_error': 'Cette aventure a déjà un Homme Dragon.',
  'hd.wizard_create_error': 'Impossible de créer votre Homme Dragon. Réessayez.',
  'hd.panel_load_error': "Impossible de charger l'Homme Dragon de cette aventure. Réessayez.",
  'hd.panel_linked_title': 'Homme Dragon de cette aventure',
  'hd.panel_linked_help': 'Sa fiche, son niveau et son historique cumulent toutes ses aventures.',
  'hd.panel_none_title': 'Aucun Homme Dragon pour cette aventure',
  'hd.panel_create_cta': 'Créer un Homme Dragon pour {partie}',
  'hd.panel_associate_empty': "Vous n'avez encore aucun autre Homme Dragon à associer.",
  'hd.panel_associate_label': 'Associer un existant',
  'hd.panel_associate_error': "Impossible d'associer cet Homme Dragon. Réessayez.",
  'hd.panel_dissociate_confirm':
    'Dissocier {nom} de « {partie} » ? Son niveau peut baisser ; sa fiche, sa réserve et ses choix sont conservés.',
  'hd.panel_dissociate_error': 'Impossible de dissocier cet Homme Dragon. Réessayez.',
  'hd.reserve_autosaved': "Enregistrée automatiquement, utilisée pour l'export PDF.",
  'hd.reserve_pick_btn': 'Choisir un souffle',
  'hd.reserve_pick_for_slot': "Choisir un souffle pour l'emplacement {n}",
  'hd.reserve_change_aria': "Changer le souffle de l'emplacement {n} : {nom}",
  'hd.reserve_remove_aria': "Retirer {nom} de l'emplacement {n}",
  'hd.reserve_save_error': "Impossible d'enregistrer la réserve. Réessayez.",
  'hd.reserve_undo_text': "{nom} retiré de l'emplacement {n}.",
  'hd.reserve_removed_status':
    "{nom} retiré de l'emplacement {n}. Annuler disponible pendant quelques secondes.",
  'hd.reserve_restored_status': "{nom} remis dans l'emplacement {n}",
  'hd.reserve_placed_status': "{nom} placé dans l'emplacement {n}. Réserve enregistrée",
  'hd.picker_place_btn': "Mettre dans l'emplacement {n}",
  'hd.picker_consult_hint': 'Consultez un souffle de la liste pour lire sa description.',
  'hd.picker_choose_hint': 'Choisissez un souffle dans la liste.',
  'hd.picker_slot_gone': "Cet emplacement n'existe plus.",
  'hd.picker_blocked_announce': "Placement impossible dans l'emplacement {n} : {raison}",
  'hd.picker_description_aria': 'Description : {nom}',
  /* — textes migrés : parties-poll (Story 35.2) — */
  'parties.confirm_title': 'Confirmation',
  'parties.locks_title': 'Confidentialité',
  'parties.locks_load_partie_error':
    'Impossible de charger les informations de la partie. Réessayez.',
  'parties.locks_load_schema_error':
    'Impossible de charger le schéma du système de jeu. Réessayez.',
  'parties.locks_save_error': 'Impossible d’enregistrer la configuration. Réessayez.',
  'parties.locks_access_denied':
    'Accès refusé : seul le MJ de cette partie peut configurer la confidentialité.',
  'parties.locks_help':
    "Cochez les éléments de fiche à masquer aux joueurs (hors MJ et propriétaire du personnage). L'enregistrement remplace l'ensemble des verrous actuels de cette partie.",
  'parties.locks_empty': 'Ce système de jeu ne déclare aucun élément verrouillable.',
  'parties.detail_polls_in_progress': '{count} votes de date en cours',
  'parties.detail_remove_member_confirm': 'Retirer {name} de « {partie} » ?',
  'parties.detail_delete_confirm': 'Supprimer « {partie} » ? Cette action est irréversible.',
  'parties.detail_link_expires_short': 'exp.',
  'parties.detail_tab_details': 'Détails',
  'parties.detail_tab_scenario': 'Scénario',
  'parties.detail_tab_scenarios': 'Scénarios',
  'parties.detail_tab_timeline': 'Chronologie',
  'parties.roster_aria_levelup': '{label} — montée de niveau disponible',
  'parties.roster_aria_role': '{label} — rôle : {role}',
  'parties.roster_aria_mj': '{name} — MJ',
  'parties.roster_aria_no_character': '{name} — aucun personnage créé',
  'parties.xp_suggested': 'Montant suggéré : {amount} XP',
  'parties.xp_current': '{xp} XP actuel',
  'parties.xp_amount_label': 'Montant',
  'parties.xp_select_one_error': 'Sélectionnez au moins un personnage avant de distribuer.',
  'parties.xp_distribute_error': 'La distribution n’a pas pu être enregistrée. Réessayez.',
  'parties.xp_rules_title': 'Calcul assisté',
  'parties.xp_history_unknown_character': 'Personnage inconnu',
  'parties.xp_history_bonus_badge': 'bonus',
  'pollui.creation_title': 'Créer un vote de date',
  'pollui.creation_computed_title': 'Créneaux calculés',
  'pollui.creation_computed_empty': 'Aucun créneau calculé disponible.',
  'pollui.creation_load_more_one': '{n} créneau calculé de plus',
  'pollui.creation_load_more_many': '{n} créneaux calculés de plus',
  'pollui.creation_all_shown': 'Tous les créneaux calculés sont affichés',
  'pollui.creation_custom_title': 'Créneaux personnalisés',
  'pollui.creation_add_custom': 'Ajouter un créneau personnalisé',
  'pollui.creation_selected_count': '{n} option(s) sélectionnée(s)',
  'pollui.creation_submit': 'Ouvrir le vote',
  'pollui.creation_desync_error':
    'Le vote a été créé, mais son état n’a pas pu être rafraîchi ici. Rechargez la page pour le voir plutôt que de recréer un vote.',
  'pollui.creation_error': 'Impossible de créer le vote. Réessayez.',
  'pollui.response_not_saved_aria': 'Non enregistré',
  'pollui.response_partial_error':
    '{success}/{total} réponse(s) enregistrée(s). Réessayez pour les autres.',
  'pollui.status_voters_aria': 'Votants',
  'pollui.status_missing_aria': "N'ont pas encore répondu pour cette date",
  'pollui.status_choose_confirm': 'Confirmer {date} — {slot} comme date de la prochaine séance ?',
  'pollui.status_choose_no_vote_warning': "⚠️ Aucun membre n'a voté pour cette date.",
  /* — textes migrés : scenarios (Story 35.2) — */
  'scenarios.fill_label': '{count} / {max} inscrits (min. {min})',
  'scenarios.form_title': 'Nouveau scénario',
  'scenarios.form_description_label': 'Description (optionnel)',
  'scenarios.form_duree_heures_label': 'Durée en heures (optionnel)',
  'scenarios.form_duree_seances_label': 'Durée en séances (optionnel)',
  'scenarios.form_save_error': "Impossible d'enregistrer le scénario.",
  'scenarios.one_shot_not_found': 'Aucun scénario trouvé pour cette Partie.',
  'scenarios.one_shot_open_error': "Impossible d'ouvrir le scénario aux joueurs. Réessayez.",
  'scenarios.list_title': 'Scénarios',
  'scenarios.list_new_button': '+ Nouveau scénario',
  'scenarios.timeline_title': 'Chronologie',
  'scenarios.timeline_load_error': 'Impossible de charger la chronologie. Réessayez.',
  'scenarios.timeline_count_one': '{n} scénario',
  'scenarios.timeline_count_many': '{n} scénarios',
  'scenarios.timeline_not_planned': 'Non planifié',
  'scenarios.timeline_since': 'depuis le {date}',
  'scenarios.timeline_from': 'à partir du {date}',
  'scenarios.seances_delete_button': 'Supprimer cette séance',
  'scenarios.seances_min_aria': "Nombre minimum d'inscrits",
  'scenarios.seances_max_aria': "Nombre maximum d'inscrits",
  'scenarios.seances_set_capacity': 'Définir la capacité',
  'scenarios.seances_edit_capacity': 'Modifier la capacité',
  'scenarios.seances_desinscrire': 'Se désinscrire',
  'scenarios.seances_inscrire': "S'inscrire",
  'scenarios.seances_heure_malformed':
    '⚠️ Valeur stockée non reconnue ("{raw}"), champ affiché vide — enregistrer sans la corriger l\'effacera.',
  'scenarios.seances_lieu_placeholder': 'chez Marc, en visio…',
  'scenarios.seances_note_placeholder': 'pensez aux dés…',
  'scenarios.seances_save_infos': 'Enregistrer les informations pratiques',
  'scenarios.seances_compte_rendu_placeholder': 'Compte-rendu de la séance…',
  'scenarios.seances_compte_rendu_aria': 'Compte-rendu de la séance',
  'scenarios.seances_save_compte_rendu': 'Enregistrer le compte-rendu',
  'scenarios.seances_compte_rendu_empty': 'Aucun compte-rendu pour cette séance pour le moment.',
  'scenarios.seances_choose_error': 'Impossible de choisir cette date. Réessayez.',
  'scenarios.seances_capacity_error': 'Impossible de définir la capacité. Réessayez.',
  'scenarios.seances_inscrire_error': 'Impossible de vous inscrire. Réessayez.',
  'scenarios.seances_desinscrire_error': 'Impossible de vous désinscrire. Réessayez.',
  'scenarios.seances_delete_error': 'Impossible de supprimer cette séance. Réessayez.',
  'scenarios.seances_reset_error': 'Impossible de réinitialiser la date. Réessayez.',
  'scenarios.seances_infos_error':
    'Impossible d’enregistrer les informations pratiques. Réessayez.',
  'scenarios.seances_compte_rendu_error': 'Impossible d’enregistrer le compte-rendu. Réessayez.',
  'scenarios.seances_refresh_error':
    'Action effectuée, mais impossible de rafraîchir l’affichage. Rechargez la page.',
  'scenarios.seances_delete_confirm_dated':
    'Cette séance a une date validée. La supprimer quand même ? Cette action est définitive.',
  'scenarios.seances_delete_confirm': 'Supprimer cette séance ? Cette action est définitive.',
  'scenarios.seances_reset_confirm':
    'Réinitialiser la date de cette séance ? Un nouveau vote pourra être lancé.',
  'scenarios.read_resume_empty': 'Aucun résumé pour l’instant.',
  'scenarios.read_resume_edit': 'Modifier le résumé de fin',
  'scenarios.read_resume_write': 'Rédiger le résumé de fin',
  'scenarios.read_journal_title': 'Journal associé',
  'scenarios.read_auto_associate': 'Association automatique',
  'scenarios.read_note_shared_aria': 'Note partagée',
  'scenarios.read_note_private_aria': 'Note privée',
  'scenarios.read_note_private_hint':
    "Note privée — déverrouillez-la (🔒) pour qu'elle apparaisse dans la rétrospective.",
  'scenarios.read_journal_empty': 'Vous n’avez pas encore d’entrée de journal.',
  'scenarios.read_retrospective_title': 'Journal de la rétrospective',
  'scenarios.read_participate': 'Participer à cette enquête',
  'scenarios.read_journal_load_error': 'Impossible de charger votre journal.',
  'scenarios.read_participate_error': 'Impossible de participer à ce scénario.',
  'scenarios.read_setting_error': 'Impossible de modifier ce réglage.',
  'scenarios.read_note_visibility_error': 'Impossible de modifier la visibilité de cette note.',
  'scenarios.read_note_association_error': 'Impossible de mettre à jour cette association.',
  'scenarios.editor_pencil_title': 'le titre',
  'scenarios.editor_pencil_duree_heures': 'la durée en heures',
  'scenarios.editor_pencil_duree_seances': 'la durée en séances',
  'scenarios.editor_mark_courant': 'Marquer comme Courant',
  'scenarios.editor_close': 'Clôturer le scénario',
  'scenarios.editor_add_seance': 'Ajouter une séance',
  'scenarios.editor_resume_empty_hint':
    'Aucun résumé pour l’instant — rédigez-le pour clore la rétrospective.',
  'scenarios.editor_save_resume': 'Enregistrer le résumé de fin',
  'scenarios.editor_no_participants': 'Aucun participant pour l’instant.',
  'scenarios.editor_documents_title': 'Documents du scénario',
  'scenarios.editor_library_title': 'Bibliothèque de campagne',
  'scenarios.editor_library_doc_suffix': '— bibliothèque campagne',
  'scenarios.editor_documents_load_error': 'Impossible de charger les documents. Réessayez.',
  'scenarios.editor_participants_load_error': 'Impossible de charger les participants. Réessayez.',
  'scenarios.editor_upload_error': "Impossible d'envoyer le document. Réessayez.",
  'scenarios.editor_mark_courant_error': 'Impossible de marquer ce scénario comme Courant.',
  'scenarios.editor_close_error': 'Impossible de clôturer ce scénario.',
  'scenarios.editor_add_seance_error': 'Impossible d’ajouter une séance.',
  'scenarios.editor_resume_save_error': 'Impossible d’enregistrer le résumé de fin.',
  'scenarios.editor_download_error': 'Impossible de télécharger le document.',
  /* — textes migrés : shared-core (Story 35.2) — */
  'shared.detail_close_window': 'Fermer la fenêtre',
  'shared.detail_close_sheet': 'Fermer la feuille',
  'core.parties_kind_one_shot': 'One-shot',
  'core.parties_kind_campagne': 'Campagne',
  'core.parties_kind_campagne_episodique': 'Campagne épisodique',
  'core.homme_dragon_sans_aventure': 'Sans aventure',
};

/** Ensemble des clés de ton, dérivé du thème de référence. */
export type ToneKey = keyof typeof grimoireEmeraude;
