// AD-13 : la liste des thèmes valides est déclarée une seule fois, dans @master-jdr/shared —
// ré-exportée ici pour que les sites d'appel existants (import depuis ce fichier) continuent de
// fonctionner sans modification.
import type { Theme } from '@master-jdr/shared';
export type { Theme } from '@master-jdr/shared';
export { THEMES } from '@master-jdr/shared';

export const THEME_NAMES: Record<Theme, string> = {
  'grimoire-emeraude': 'Grimoire Émeraude',
  'foret-ancienne': 'Forêt Ancienne',
  'medieval-steampunk': 'Médiéval Steampunk',
};

export const TONE_MAP: Record<Theme, Record<string, string>> = {
  /* ═══════════════════════════════════════════════════════ GRIMOIRE ÉMERAUDE */
  'grimoire-emeraude': {
    /* — navigation — */
    'nav.my_games': 'Mes aventures',
    'nav.create_game': 'Lancer une quête',
    'nav.logout': 'Fermer le grimoire',
    'nav.calendar': 'Calendrier',
    'nav.account': 'Mon grimoire',
    'nav.characters': 'Personnages',
    /* — dashboard — */
    'dashboard.title_invitations': 'Invitations reçues',
    'dashboard.empty': 'Nulle quête en cours. Forgez la première…',
    'dashboard.role_prefix': 'Rang :',
    'dashboard.role_mj': 'Maître',
    'dashboard.role_player': 'Héros',
    'dashboard.status_closed_badge': 'Terminée',
    /* — signalétique d'état (Story 29.7) — */
    'dashboard.section_awaiting': 'Ce qui t’attend',
    'dashboard.section_ongoing': 'En cours',
    'dashboard.section_upcoming': 'À venir',
    'dashboard.section_finished': 'Terminées',
    /* — filtres, tri, favoris (Story 29.8) — */
    'dashboard.empty_filtered': 'Aucun grimoire ne répond à ces critères.',
    'dashboard.controls_toggle_aria': 'Afficher les filtres et le tri',
    'dashboard.filter_role_label': 'Rang',
    'dashboard.filter_role_all': 'Tous',
    'dashboard.filter_status_label': 'Statut',
    'dashboard.filter_status_all': 'Tous',
    'dashboard.sort_label': 'Trier par',
    'dashboard.sort_urgence': 'Urgence',
    'dashboard.sort_date': 'Date',
    'dashboard.sort_nom': 'Nom',
    'dashboard.sort_type': 'Type',
    'dashboard.sort_statut': 'Statut',
    'dashboard.hide_finished_label': 'Masquer les grimoires clos',
    'dashboard.show_finished_btn': 'Afficher les grimoires clos',
    'dashboard.favorite_add_aria': 'Marquer comme favori',
    'dashboard.favorite_remove_aria': 'Retirer des favoris',
    /* — barre de contrôles partagée (Story 29.9) — */
    'dashboard.search_label': 'Rechercher un grimoire',
    'dashboard.row_signal_count_aria': '{n} chose(s) à faire',
    'list_control_bar.toggle_aria': 'Afficher les filtres et le tri',
    'list_control_bar.view_mode_group_aria': 'Densité d’affichage',
    'list_control_bar.view_mode_large_aria': 'Grande vignette',
    'list_control_bar.view_mode_medium_aria': 'Vignette intermédiaire',
    'list_control_bar.view_mode_compact_aria': 'Liste compacte',
    'list_control_bar.sort_label': 'Trier par',
    'list_control_bar.reset_pill_label': 'Réglages modifiés',
    /* — my-characters (Story 29.2) — */
    'my_characters.title': 'Mes personnages',
    'my_characters.empty': 'Nul personnage forgé. Créez-en un depuis une quête…',
    'my_characters.no_match': 'Aucun personnage ne répond à cette recherche.',
    'my_characters.search_label': 'Rechercher un personnage',
    'my_characters.sort_niveau': 'Niveau',
    'my_characters.sort_partie': 'Partie',
    'my_characters.sort_nom': 'Nom',
    /* — partie-form — */
    'partie.new_title': 'Nouvelle quête',
    'partie.edit_title': 'Retranscrire le parchemin',
    'partie.save_btn': 'Inscrire',
    'partie.cancel_btn': 'Refermer',
    'partie.name_label': 'Nom du grimoire',
    'partie.system_label': 'Système de jeu',
    'partie.kind_label': 'Nature de la quête',
    'partie.description_label': 'Préambule (facultatif)',
    'partie.kind_ONE_SHOT': 'Quête unique',
    'partie.kind_CAMPAGNE_LINEAIRE': 'Chronique',
    'partie.kind_CAMPAGNE_EPISODIQUE': 'Chronique épisodique',
    'partie.kind_refusal_closed': 'Ce grimoire est clos. Rouvrez-le avant d’en changer la nature.',
    'partie.kind_refusal_too_many_scenarios':
      'Ce grimoire compte {count} scénarios ; une quête unique n’en porte qu’un.',
    'partie.courant_choice_title': 'Quel scénario reste en cours ?',
    'partie.courant_choice_help':
      'Une chronique ne suit qu’un scénario à la fois. Les autres repasseront « à venir » — leurs séances et leurs dates sont conservées.',
    'partie.courant_choice_confirm': 'Sceller ce choix',
    'partie.cover_add': 'Enluminer ce grimoire',
    'partie.cover_change': 'Changer l’enluminure',
    'partie.cover_remove': 'Retirer l’enluminure',
    'partie.cover_uploading': 'L’enluminure se fixe sur le parchemin…',
    'partie.cover_upload_error': 'L’enluminure n’a pu être fixée. Réessayez.',
    'partie.cover_remove_error': 'L’enluminure n’a pu être retirée. Réessayez.',
    'partie.cover_reject_type':
      'Seules les images JPEG, PNG et WEBP peuvent enluminer un grimoire.',
    'partie.cover_reject_size': 'Cette image dépasse 5 Mo : choisissez-en une plus légère.',
    'partie.save_error': 'Ce grimoire n’a pu être inscrit. Réessayez.',
    'partie.created_but_cover_failed':
      'Le grimoire est bien inscrit, mais son enluminure n’a pu être fixée. Vous pouvez la redéposer ici.',
    'partie.fields_saved_but_convert_failed':
      'Les autres modifications sont enregistrées, mais la nature du grimoire n’a pu être changée. Réessayez.',
    /* — partie-detail — */
    'partie.scheduling_title': 'Prochaine séance',
    'partie.no_session': "Aucune séance convoquée. Consultez l'oracle des créneaux.",
    'partie.members_title': '⚔ Compagnons',
    'partie.no_members': "Nulle âme pour l'instant.",
    'partie.remove_member_btn': 'Retirer',
    'partie.no_description': 'Ce grimoire est muet.',
    'partie.invite_title': 'Convoquer un compagnon',
    'partie.search_label': 'Nom ou signe distinctif',
    'partie.search_btn': 'Scruter',
    'partie.invite_btn': 'Convoquer',
    'partie.links_title': "Parchemins d'invocation",
    'partie.generate_link': 'Tisser un parchemin',
    'partie.notice_invited': 'Missive envoyée à {name}.',
    'partie.invite_by_email_label': 'Adresse du destinataire',
    'partie.invite_by_email_btn': 'Envoyer une missive',
    'partie.notice_invited_email': 'Missive envoyée à {email}.',
    'partie.notice_invite_email_error': "La missive n'a pu être envoyée. Réessayez.",
    'partie.reference_sheets_title': 'Grimoires de référence',
    'partie.asset_journal_cta': 'Journal',
    'partie.asset_carte_cta': 'Carte',
    'partie.asset_download_error': "Ce grimoire n'a pas pu être déterré. Réessayez.",
    'partie.prep_sheets_title': 'Grimoires de préparation (MJ)',
    'partie.asset_monde_cta': 'Monde',
    'partie.asset_monstre_cta': 'Monstre',
    'partie.asset_ville_cta': 'Ville',
    'partie.asset_objectif_chasse_cta': 'Objectif — Chasse',
    'partie.asset_objectif_quete_cta': 'Objectif — Quête',
    'partie.asset_objectif_voyage_cta': 'Objectif — Voyage',
    'partie.asset_oeuf_de_bataille_cta': 'Œuf de bataille',
    'partie.asset_structure_cta': 'Structure',
    'partie.notice_copy': 'Parchemin copié dans la besace.',
    'partie.edit_btn': 'Retranscrire',
    'partie.close_btn': 'Clore le grimoire',
    'partie.reopen_btn': 'Rouvrir le grimoire',
    'partie.status_closed_label': 'Ce grimoire est clos.',
    /* — signaux d'état (Story 29.7, FR-12) — */
    'partie.signal_personnage_a_creer': 'Créer son héros',
    'partie.signal_vote_en_cours_sans_reponse': 'Vote en attente',
    'partie.signal_compte_rendu_non_redige': 'Compte-rendu à écrire',
    'partie.signal_homme_dragon_a_creer': 'Créer son Homme Dragon',
    'partie.signal_aucun_membre_invite': 'Aucun compagnon convoqué',
    'partie.signal_aucun_scenario_en_cours': 'Aucune quête en cours',
    'partie.signal_aucune_date_ni_vote': 'Aucune date ni vote',
    'partie.signal_rapport_fin_manquant': 'Récit de fin manquant',
    'partie.signal_prochaine_seance_connue': 'Prochaine séance connue',
    'partie.signal_partie_terminee': 'Grimoire clos',
    'partie.signal_more_count': '+{n}',
    'partie.delete_btn': 'Brûler le parchemin',
    'partie.invitations_tab_label': 'Invitations',
    'partie.show_troupe': 'Voir la troupe',
    'partie.hide_troupe': 'Masquer la troupe',
    /* — calendrier & vote — */
    'cta.find_date': "Consulter l'oracle des créneaux",
    'cta.guild_calendar': 'Voir le grimoire des disponibilités',
    'cta.launch_vote': 'Ouvrir le parchemin du vote',
    'cta.save_constraint': 'Inscrire dans le grimoire',
    'cta.send_reminder': 'Envoyer une missive',
    'section.slots': 'Fenêtres de la destinée',
    'section.constraints': 'Contraintes inscrites',
    'empty.no_slots': "L'oracle ne voit aucun créneau libre. Les parchemins manquent de données.",
    'empty.no_constraints': 'Aucune contrainte inscrite dans le grimoire.',
    'success.constraint_saved': 'Contrainte gravée dans le parchemin.',
    'alert.expiring_soon': 'Votre parchemin expire bientôt. Renouvelez le sort.',
    'alert.missing_player': "{name} n'a pas encore consulté l'oracle.",
    'status.unavailable_label': 'Indisponible',
    'status.unknown_label': 'Mystère',
    'cta.choose_date': 'Sceller ce créneau',
    'cta.cancel_poll': 'Brûler le parchemin de vote',
    'cta.restore_default_layers': 'Rétablir mon grimoire par défaut',
    'empty.no_poll': 'Aucun vote en cours dans ce grimoire.',
    'success.poll_created': 'Vote ouvert. Les membres ont été avertis.',
    'success.date_chosen': 'La date est gravée dans le grimoire.',
    'poll.status_title': 'Vote en cours',
    'poll.vote_pending': 'Vote de date en cours — parchemin en attente',
    'success.vote_cast': 'Réponse inscrite dans le grimoire.',
    'cta.confirm_votes': 'Sceller mes réponses',
    'cta.withdraw_vote': 'Retirer ma réponse',
    'success.vote_withdrawn': 'Réponse retirée du grimoire.',
    'poll.withdraw_error': 'Le retrait a échoué. Réessayez.',
    'poll.cast_error': 'Impossible d’enregistrer ta réponse. Réessayez.',
    'poll.vote_closed': "Ce vote est clos. L'oracle a tranché.",
    'alert.all_responded': 'Tous les compagnons ont répondu au vote.',
    'poll.status_summary': 'Vote ouvert — {responded}/{total} compagnons ont répondu',
    /* — mode Destinée et panneau réduit (Story 36.9) — */
    // Nom du MODE, identique dans les trois thèmes : « ✦ Destinée » est le nom que la spec lui
    // donne (EXPERIENCE.md §4.4 ter), au même titre que « Vue mois ». La clé existe pour qu'un
    // thème futur puisse le teinter, pas pour qu'il change aujourd'hui.
    'cta.destiny_mode': 'Destinée',
    'poll.missing_prefix': 'N’ont pas consulté l’oracle :',
    'poll.responded_prefix': 'Ont consulté l’oracle :',
    /* — annonces (Epic 9) — */
    'announcement.scope_campaign_label': 'Toute la campagne',
    'announcement.scope_oneshot_label': 'Cette quête',
    'announcement.scope_scenario_label': 'Ce chapitre',
    'announcement.publish_cta': 'Proclamer une annonce',
    'announcement.text_placeholder': 'Rédiger une annonce...',
    'announcement.published_notice': 'Annonce proclamée.',
    'announcement.unseen_label': 'Non lue — cliquez pour marquer comme lue',
    /* — personnages (Palier P3) — */
    'character.create_cta': 'Créer un voyageur',
    'character.tab_label': 'Personnages',
    'character.step_class': 'Choisir sa vocation',
    'character.step_type': 'Choisir sa voie',
    'character.step_magic': 'Sceller son lien avec la magie',
    'character.step_portrait_intro':
      'Ajoute un portrait si tu le souhaites — cette étape est entièrement facultative et peut être passée à tout moment.',
    'character.portrait_missing': 'Aucun portrait — le conteur imagine un visage',
    'character.portrait_edit_cta': 'Modifier le portrait',
    'character.pdf_crop_edit_cta': 'Ajuster le cadrage PDF',
    'character.export_editable_cta': 'Exporter en PDF (éditable)',
    'character.export_2pages_cta': 'Exporter en PDF (2 pages)',
    'character.export_equipment_cta': "Exporter l'équipement en PDF",
    'character.export_notes_cta': 'Exporter les notes en PDF',
    'character.export_error': "Le parchemin n'a pas pu être copié. Réessayez.",
    'character.owner_badge_mj': 'Maître',
    'character.level_badge': 'Niv. {n}',
    'character.my_sheet_tab_label': 'Ma fiche',
    /* — Homme Dragon (Epic 10, Story 10.1) — */
    'homme-dragon.create_cta': 'Créer mon Homme Dragon',
    'homme-dragon.race_label': 'Race',
    'homme-dragon.artefact_label': 'Artefact',
    'homme-dragon.created_notice': 'Votre Homme Dragon a pris vie.',
    /* — roster (Story 6.1) — */
    'roster.mj_badge': 'MJ',
    'roster.invite_slot': 'Convier un compagnon',
    'roster.collapse_label': 'Replier la troupe',
    'roster.expand_label': 'Déplier la troupe',
    'roster.levelup_badge': 'Montée de niveau disponible',
    /* — évolution du personnage (Story 6.2) — */
    'evolution.xp_distribute_cta': "Distribuer de l'XP",
    'evolution.xp_panel_title': "Distribution d'XP",
    'evolution.xp_history_title': "Historique des distributions d'XP",
    'evolution.xp_history_empty': 'Aucune distribution gravée pour le moment.',
    'evolution.xp_note_label': 'Note de session',
    'evolution.xp_confirm_btn': 'Sceller la distribution',
    'evolution.xp_bonus_link': '+ bonus',
    'evolution.xp_levelup_warning': '{name} franchira un niveau',
    /* — montée de niveau & historique (Story 6.3) — */
    'evolution.levelup_banner': 'Niveau [N] disponible !',
    'evolution.levelup_cta': 'Level up !',
    'evolution.levelup_wizard_title': 'Montée de niveau',
    'evolution.levelup_step_pv_pe': 'Répartir 3 points entre PV et PE',
    'evolution.levelup_step_capability': 'Choisir la capacité débloquée',
    'evolution.levelup_legendary_journey_text':
      'Un voyage légendaire vous attend — aucun choix supplémentaire à faire.',
    'evolution.levelup_confirm_cta': 'Valider ce niveau',
    /* — sous-navigation locale de la fiche (Story 29.5) — */
    'evolution.main_sheet_tab_label': 'Fiche',
    'evolution.history_tab_label': 'Historique',
    'evolution.history_empty': 'Aucun instantané pour le moment.',
    'evolution.mj_edit_trace': 'modifié par le MJ',
    'evolution.landscape_section_title': 'Paysage/Climat favori',
    'evolution.immunity_section_title': 'Immunités',
    'evolution.other_capabilities_title': 'Autres capacités',
    /* — inventaire chiffré (Story 6.4) — */
    'evolution.inventory_section_title': 'Inventaire',
    'evolution.inventory_add_cta': '+ Ajouter un objet',
    'evolution.inventory_empty': "Aucun objet dans l'inventaire pour le moment.",
    'evolution.inventory_overweight_label': 'Surchargé',
    'evolution.inventory_error': "L'inventaire n'a pas pu être mis à jour. Réessayez.",
    /* — édition MJ sans contrainte (Story 6.6) — */
    'evolution.mj_edit_error': "L'édition n'a pas pu être enregistrée. Réessayez.",
    'evolution.mj_edit_warning_prefix': 'Avertissement : ',
    'evolution.inventory_mj_add_cta': '+ Ajouter un objet (MJ)',
    'evolution.narrative_edit_error': "La modification n'a pas pu être enregistrée. Réessayez.",
    /* — journal de notes personnelles (Story 6.5) — */
    'evolution.notes_journal_title': 'Journal de notes',
    'evolution.notes_journal_empty': 'Aucune note pour le moment.',
    'evolution.notes_add_cta': '+ Ajouter une entrée',
    'evolution.note_share_toggle': 'Partager avec le groupe',
    'evolution.note_private_label': 'Entrée privée',
    'evolution.note_shared_label': 'Entrée partagée avec le groupe',
    'evolution.notes_error': "Le journal n'a pas pu être mis à jour. Réessayez.",
    /* — compte — */
    'account.title': 'Mon grimoire personnel',
    'account.pseudo_label': 'Signe de reconnaissance',
    'account.email_label': 'Sceau de correspondance',
    'account.display_name_label': 'Nom affiché aux autres voyageurs',
    'account.save_btn': 'Sceller',
    'account.cancel_btn': 'Renoncer',
    'account.saved': 'Le grimoire a retenu ce nom.',
    'account.error': "Le grimoire n'a pas pu retenir ce changement. Réessayez.",
    'account.password_title': 'Renouveler le sortilège de passage',
    'account.current_password_label': 'Sortilège actuel',
    'account.new_password_label': 'Nouveau sortilège',
    'account.password_save_btn': 'Renouveler',
    'account.password_saved': 'Le sortilège de passage a été renouvelé.',
    'account.password_wrong_current': "Ce sortilège n'est pas le bon.",
    'account.password_error': "Le grimoire n'a pas pu renouveler le sortilège. Réessayez.",
    'account.email_change_title': 'Changer de sceau de correspondance',
    'account.current_password_for_email_label': 'Sortilège actuel',
    'account.new_email_label': 'Nouveau sceau de correspondance',
    'account.email_change_save_btn': 'Envoyer le message',
    'account.email_change_saved': 'Un message est parti vers le nouveau sceau.',
    'account.email_change_wrong_current': "Ce sortilège n'est pas le bon.",
    'account.email_change_taken': 'Un autre voyageur porte déjà ce sceau.',
    'account.email_change_error': "Le grimoire n'a pas pu envoyer la demande. Réessayez.",
    'account.calendar_layers_title': 'Ce que révèle mon calendrier',
    'account.calendar_layer.mes-indisponibilites': 'Mes indisponibilités',
    'account.calendar_layer.mes-disponibilites': 'Mes disponibilités',
    'account.calendar_layer.mes-seances': 'Mes séances confirmées',
    'account.calendar_layer.votes-en-cours': 'Les votes en cours',
    'account.calendar_layer.inscriptions-ouvertes': 'Les inscriptions ouvertes',
    'account.calendar_layer.disponibilite-groupe': 'La disponibilité du groupe',
    /* — vue Agenda (Story 36.11) — les libellés de BADGE sont contractuels et identiques dans
       les trois thèmes : EXPERIENCE.md §5 impose « Réponds au vote » / « Vote en cours » comme
       la paire qui distingue à-faire et fait. Seuls les titres de section et le vide varient. */
    'calendar.agenda.section_awaiting': 'Ce qui t’attend',
    'calendar.agenda.section_scheduled': 'Ce qui est annoncé',
    'calendar.agenda.section_past': 'Ce qui est révolu',
    'calendar.agenda.badge_answer_poll': 'Réponds au vote',
    'calendar.agenda.badge_poll_open': 'Vote en cours',
    'calendar.agenda.badge_signup': 'S’inscrire',
    'calendar.agenda.badge_signed_up': 'Inscrit',
    'calendar.agenda.badge_debrief': 'Débriefer',
    'calendar.agenda.empty': 'Rien ne t’attend, rien n’est annoncé.',
    /* — Agenda du MJ (Story 36.12) — même règle : les LIBELLÉS D'ÉTAT et les gabarits chiffrés
       sont contractuels et identiques partout, seuls les titres et les appels à l'action
       prennent le registre du thème. */
    'calendar.agenda.badge_to_seal': 'À sceller',
    'calendar.agenda.poll_open': 'Vote ouvert',
    'calendar.agenda.responded_count': '{n} sur {total} ont répondu',
    'calendar.agenda.slots_proposed': '{n} créneaux proposés',
    'calendar.agenda.missing_voters': 'il manque {names}',
    'calendar.agenda.no_date': 'sans date',
    'calendar.agenda.no_date_proposed': 'Aucune date proposée',
    'calendar.agenda.action_launch_poll': 'Lancer un vote',
    'calendar.agenda.action_seal': 'Sceller',
    'calendar.agenda.action_expand': 'Déplier',
    'calendar.agenda.action_collapse': 'Replier',
    'calendar.agenda.seal_confirm_title': 'Sceller ce créneau ?',
    'calendar.agenda.seal_confirm_body':
      'La séance sera fixée à ce créneau et le vote se refermera. Les autres créneaux proposés disparaîtront.',
    /* — identité — */
    'identity.character_label': 'Personnage',
    'identity.player_label': 'Joueur',
    'identity.homonymy_warning':
      'Un autre membre de cette partie porte le même nom affiché que vous.',
    'identity.homonymy_change_cta': 'Changer mon nom affiché',
    'identity.homonymy_ignore_cta': 'Ignorer',
  },

  /* ══════════════════════════════════════════════════════════ FORÊT ANCIENNE */
  'foret-ancienne': {
    /* — navigation — */
    'nav.my_games': 'Mes pérégrinations',
    'nav.create_game': 'Ouvrir un sentier',
    'nav.logout': 'Quitter la forêt',
    'nav.calendar': 'Calendrier',
    'nav.account': 'Mon carnet',
    'nav.characters': 'Compagnons',
    /* — dashboard — */
    'dashboard.title_invitations': 'Appels de la forêt',
    'dashboard.empty': 'Aucune clairière ouverte. Plantez le premier feu…',
    'dashboard.role_prefix': 'Voie :',
    'dashboard.role_mj': 'Guide',
    'dashboard.role_player': 'Voyageur',
    'dashboard.status_closed_badge': 'Achevé',
    /* — signalétique d'état (Story 29.7) — */
    'dashboard.section_awaiting': 'Ce qui t’attend',
    'dashboard.section_ongoing': 'En route',
    'dashboard.section_upcoming': 'À venir',
    'dashboard.section_finished': 'Achevées',
    /* — filtres, tri, favoris (Story 29.8) — */
    'dashboard.empty_filtered': 'Aucun sentier ne répond à ces critères.',
    'dashboard.controls_toggle_aria': 'Afficher les filtres et le tri',
    'dashboard.filter_role_label': 'Voie',
    'dashboard.filter_role_all': 'Tous',
    'dashboard.filter_status_label': 'Statut',
    'dashboard.filter_status_all': 'Tous',
    'dashboard.sort_label': 'Trier par',
    'dashboard.sort_urgence': 'Urgence',
    'dashboard.sort_date': 'Date',
    'dashboard.sort_nom': 'Nom',
    'dashboard.sort_type': 'Type',
    'dashboard.sort_statut': 'Statut',
    'dashboard.hide_finished_label': 'Masquer les sentiers achevés',
    'dashboard.show_finished_btn': 'Afficher les sentiers achevés',
    'dashboard.favorite_add_aria': 'Marquer comme favori',
    'dashboard.favorite_remove_aria': 'Retirer des favoris',
    /* — barre de contrôles partagée (Story 29.9) — */
    'dashboard.search_label': 'Rechercher un sentier',
    'dashboard.row_signal_count_aria': '{n} chose(s) à faire',
    'list_control_bar.toggle_aria': 'Afficher les filtres et le tri',
    'list_control_bar.view_mode_group_aria': 'Densité d’affichage',
    'list_control_bar.view_mode_large_aria': 'Grande vignette',
    'list_control_bar.view_mode_medium_aria': 'Vignette intermédiaire',
    'list_control_bar.view_mode_compact_aria': 'Liste compacte',
    'list_control_bar.sort_label': 'Trier par',
    'list_control_bar.reset_pill_label': 'Réglages modifiés',
    /* — my-characters (Story 29.2) — */
    'my_characters.title': 'Mes compagnons de route',
    'my_characters.empty': 'Aucun compagnon éveillé. Façonnez-en un depuis un sentier…',
    'my_characters.no_match': 'Aucun compagnon ne répond à cette recherche.',
    'my_characters.search_label': 'Rechercher un compagnon',
    'my_characters.sort_niveau': 'Niveau',
    'my_characters.sort_partie': 'Sentier',
    'my_characters.sort_nom': 'Nom',
    /* — partie-form — */
    'partie.new_title': 'Nouveau sentier',
    'partie.edit_title': 'Rebattre le sentier',
    'partie.save_btn': 'Planter',
    'partie.cancel_btn': 'Rebrousser chemin',
    'partie.name_label': 'Nom du sentier',
    'partie.system_label': 'Système de jeu',
    'partie.kind_label': 'Nature du sentier',
    'partie.description_label': 'Premiers pas (facultatif)',
    'partie.kind_ONE_SHOT': 'Sentier court',
    'partie.kind_CAMPAGNE_LINEAIRE': 'Longue marche',
    'partie.kind_CAMPAGNE_EPISODIQUE': 'Longue marche par étapes',
    'partie.kind_refusal_closed':
      'Ce sentier est refermé. Rouvrez-le avant d’en changer la nature.',
    'partie.kind_refusal_too_many_scenarios':
      'Ce sentier compte {count} étapes ; un sentier court n’en a qu’une.',
    'partie.courant_choice_title': 'Quelle étape reste en cours ?',
    'partie.courant_choice_help':
      'Une longue marche ne suit qu’une étape à la fois. Les autres redeviendront « à venir » — leurs séances et leurs dates sont conservées.',
    'partie.courant_choice_confirm': 'Prendre ce chemin',
    'partie.cover_add': 'Donner un visage au sentier',
    'partie.cover_change': 'Changer l’image',
    'partie.cover_remove': 'Retirer l’image',
    'partie.cover_uploading': 'L’image prend racine…',
    'partie.cover_upload_error': 'L’image n’a pu prendre racine. Réessayez.',
    'partie.cover_remove_error': 'L’image n’a pu être retirée. Réessayez.',
    'partie.cover_reject_type': 'Seules les images JPEG, PNG et WEBP peuvent être plantées ici.',
    'partie.cover_reject_size': 'Cette image dépasse 5 Mo : choisissez-en une plus légère.',
    'partie.save_error': 'Ce sentier n’a pu être tracé. Réessayez.',
    'partie.created_but_cover_failed':
      'Le sentier est bien tracé, mais son image n’a pu prendre racine. Vous pouvez la redéposer ici.',
    'partie.fields_saved_but_convert_failed':
      'Les autres changements sont enregistrés, mais la nature du sentier n’a pu être changée. Réessayez.',
    /* — partie-detail — */
    'partie.scheduling_title': 'Prochaine clairière',
    'partie.no_session': "Aucune clairière réservée. L'écureuil cherche encore.",
    'partie.members_title': '🌿 Habitants',
    'partie.no_members': 'Aucun habitant de la clairière.',
    'partie.remove_member_btn': 'Renvoyer',
    'partie.no_description': 'La forêt garde ses secrets.',
    'partie.invite_title': 'Appeler depuis la forêt',
    'partie.search_label': 'Nom ou espèce connue',
    'partie.search_btn': 'Fouiller',
    'partie.invite_btn': 'Accueillir',
    'partie.links_title': 'Sifflets de rappel',
    'partie.generate_link': 'Tisser un laissez-passer',
    'partie.notice_invited': 'Sifflet envoyé à {name}.',
    'partie.invite_by_email_label': 'Adresse du destinataire',
    'partie.invite_by_email_btn': 'Envoyer un sifflet',
    'partie.notice_invited_email': 'Sifflet envoyé à {email}.',
    'partie.notice_invite_email_error': "Le sifflet s'est perdu dans le vent. Réessayez.",
    'partie.reference_sheets_title': 'Grimoires de la clairière',
    'partie.asset_journal_cta': 'Journal',
    'partie.asset_carte_cta': 'Carte',
    'partie.asset_download_error': "Le grimoire s'est enraciné trop profond. Réessayez.",
    'partie.prep_sheets_title': 'Grimoires de la clairière (MJ)',
    'partie.asset_monde_cta': 'Monde',
    'partie.asset_monstre_cta': 'Monstre',
    'partie.asset_ville_cta': 'Ville',
    'partie.asset_objectif_chasse_cta': 'Objectif — Chasse',
    'partie.asset_objectif_quete_cta': 'Objectif — Quête',
    'partie.asset_objectif_voyage_cta': 'Objectif — Voyage',
    'partie.asset_oeuf_de_bataille_cta': 'Œuf de bataille',
    'partie.asset_structure_cta': 'Structure',
    'partie.notice_copy': 'Laissez-passer copié dans la gibecière.',
    'partie.edit_btn': 'Rebattre',
    'partie.close_btn': 'Achever le sentier',
    'partie.reopen_btn': 'Reprendre la route',
    'partie.status_closed_label': 'Ce sentier est achevé.',
    /* — signaux d'état (Story 29.7, FR-12) — */
    'partie.signal_personnage_a_creer': 'Façonner son compagnon',
    'partie.signal_vote_en_cours_sans_reponse': 'Vote en attente',
    'partie.signal_compte_rendu_non_redige': 'Compte-rendu à écrire',
    'partie.signal_homme_dragon_a_creer': 'Façonner son Homme Dragon',
    'partie.signal_aucun_membre_invite': 'Aucun voyageur convié',
    'partie.signal_aucun_scenario_en_cours': 'Aucun sentier en cours',
    'partie.signal_aucune_date_ni_vote': 'Aucune date ni vote',
    'partie.signal_rapport_fin_manquant': 'Récit de fin manquant',
    'partie.signal_prochaine_seance_connue': 'Prochaine étape connue',
    'partie.signal_partie_terminee': 'Sentier achevé',
    'partie.signal_more_count': '+{n}',
    'partie.delete_btn': 'Effacer le sentier',
    'partie.invitations_tab_label': 'Invitations',
    'partie.show_troupe': 'Voir le cercle',
    'partie.hide_troupe': 'Masquer le cercle',
    /* — calendrier & vote — */
    'cta.find_date': "Envoyer l'écureuil messager",
    'cta.guild_calendar': 'Voir la forêt des disponibilités',
    'cta.launch_vote': 'Planter le bâton du vote',
    'cta.save_constraint': 'Marquer le territoire',
    'cta.send_reminder': 'Faire chanter les oiseaux',
    'section.slots': 'Clairières disponibles',
    'section.constraints': 'Zones marquées',
    'empty.no_slots':
      'Aucune clairière libre. La forêt est dense, demandez aux membres leurs disponibilités.',
    'empty.no_constraints': 'Aucun territoire marqué.',
    'success.constraint_saved': 'Territoire marqué dans la forêt.',
    'alert.expiring_soon': "Votre marquage s'efface bientôt. Renouvelez votre présence.",
    'alert.missing_player': "{name} n'a pas encore parcouru la forêt.",
    'status.unavailable_label': 'Absent de la forêt',
    'status.unknown_label': 'Perdu dans les branches',
    'cta.choose_date': 'Planter le drapeau de la clairière',
    'cta.cancel_poll': 'Disperser les feuilles du vote',
    'cta.restore_default_layers': 'Revenir à la clairière par défaut',
    'empty.no_poll': 'Aucun vote en cours dans la forêt.',
    'success.poll_created': "L'écureuil a transmis l'appel du vote.",
    'success.date_chosen': 'La clairière de la séance est choisie.',
    'poll.status_title': 'Vote en cours dans la forêt',
    'poll.vote_pending': "L'écureuil attend ta réponse au vote",
    'success.vote_cast': "L'écureuil a transmis ta réponse.",
    'cta.confirm_votes': 'Transmettre mes réponses',
    'cta.withdraw_vote': 'Retirer ma réponse',
    'success.vote_withdrawn': "L'écureuil a effacé ta réponse.",
    'poll.withdraw_error': "L'écureuil n'a pas pu effacer ta réponse. Réessaie.",
    'poll.cast_error': "L'écureuil n'a pas pu transmettre ta réponse. Réessaie.",
    'poll.vote_closed': 'Le vote de la forêt est terminé.',
    'alert.all_responded': "Tous les habitants ont répondu à l'appel.",
    'poll.status_summary': 'Vote ouvert — {responded}/{total} habitants ont répondu',
    /* — mode Destinée et panneau réduit (Story 36.9) — */
    'cta.destiny_mode': 'Destinée',
    'poll.missing_prefix': 'N’ont pas parcouru la forêt :',
    'poll.responded_prefix': 'Ont parcouru la forêt :',
    /* — annonces (Epic 9) — */
    'announcement.scope_campaign_label': 'Toute la forêt',
    'announcement.scope_oneshot_label': 'Cette expédition',
    'announcement.scope_scenario_label': 'Cette clairière',
    'announcement.publish_cta': 'Lancer un appel dans la forêt',
    'announcement.text_placeholder': 'Composer un appel...',
    'announcement.published_notice': "L'appel résonne dans la forêt.",
    'announcement.unseen_label': 'Non entendu — cliquez pour marquer comme entendu',
    /* — personnages (Palier P3) — */
    'character.create_cta': 'Éveiller un compagnon de route',
    'character.tab_label': 'Personnages',
    'character.step_class': 'Choisir son rôle dans le cercle',
    'character.step_type': 'Choisir son chemin',
    'character.step_magic': 'Nouer son lien avec les dragons',
    'character.step_portrait_intro':
      "Grave un visage si le cœur t'en dit — cette étape reste facultative, tu peux la traverser sans t'arrêter.",
    'character.portrait_missing': 'Aucun visage gravé — la forêt garde son mystère',
    'character.portrait_edit_cta': 'Modifier le portrait',
    'character.export_editable_cta': 'Exporter en PDF (éditable)',
    'character.export_2pages_cta': 'Exporter en PDF (2 pages)',
    'character.export_equipment_cta': "Exporter l'équipement en PDF",
    'character.export_notes_cta': 'Exporter les notes en PDF',
    'character.export_error': "L'écureuil s'est perdu en chemin. Réessayez.",
    'character.owner_badge_mj': 'Guide',
    'character.level_badge': 'Niv. {n}',
    'character.my_sheet_tab_label': 'Ma fiche',
    /* — Homme Dragon (Epic 10, Story 10.1) — */
    'homme-dragon.create_cta': 'Éveiller mon Homme Dragon',
    'homme-dragon.race_label': 'Lignée',
    'homme-dragon.artefact_label': 'Talisman',
    'homme-dragon.created_notice': 'Votre Homme Dragon veille sur la forêt.',
    /* — roster (Story 6.1) — */
    'roster.mj_badge': 'MJ',
    'roster.invite_slot': 'Accueillir un compagnon de route',
    'roster.collapse_label': 'Replier le cercle',
    'roster.expand_label': 'Déplier le cercle',
    'roster.levelup_badge': 'Prêt à grandir',
    /* — évolution du personnage (Story 6.2) — */
    'evolution.xp_distribute_cta': 'Partager les récits',
    'evolution.xp_panel_title': 'Partage des récits',
    'evolution.xp_history_title': 'Récits partagés',
    'evolution.xp_history_empty': "Aucun récit partagé pour l'instant.",
    'evolution.xp_note_label': 'Note du récit',
    'evolution.xp_confirm_btn': 'Confier ce récit au cercle',
    'evolution.xp_bonus_link': '+ éclat',
    'evolution.xp_levelup_warning': '{name} va grandir',
    /* — montée de niveau & historique (Story 6.3) — */
    'evolution.levelup_banner': "Le cercle t'appelle à grandir — niveau [N]",
    'evolution.levelup_cta': 'Gravir un échelon',
    'evolution.levelup_wizard_title': 'Croissance',
    'evolution.levelup_step_pv_pe': 'Répartir 3 points entre PV et PE',
    'evolution.levelup_step_capability': 'Choisir le don qui s’éveille',
    'evolution.levelup_legendary_journey_text':
      'Un chemin légendaire s’ouvre — rien de plus à choisir.',
    'evolution.levelup_confirm_cta': 'Graver cet échelon',
    /* — sous-navigation locale de la fiche (Story 29.5) — */
    'evolution.main_sheet_tab_label': 'Feuille',
    'evolution.history_tab_label': 'Mémoire du cercle',
    'evolution.history_empty': 'Aucun souvenir gravé pour le moment.',
    'evolution.mj_edit_trace': 'modifié par le MJ',
    'evolution.landscape_section_title': 'Paysage/climat de coeur',
    'evolution.immunity_section_title': 'Immunités du cercle',
    'evolution.other_capabilities_title': 'Dons du voyage',
    'evolution.inventory_section_title': 'Besace',
    'evolution.inventory_add_cta': '+ Glisser un objet dans la besace',
    'evolution.inventory_empty': 'La besace est vide pour le moment.',
    'evolution.inventory_overweight_label': 'Surchargée',
    'evolution.inventory_error': "La besace n'a pas pu être mise à jour. Réessaie.",
    'evolution.mj_edit_error': "L'édition n'a pas pu être gravée. Réessaie.",
    'evolution.mj_edit_warning_prefix': 'Avertissement : ',
    'evolution.inventory_mj_add_cta': '+ Glisser un objet du Guide dans la besace',
    'evolution.narrative_edit_error': "La modification n'a pas pu être gravée. Réessaie.",
    'evolution.notes_journal_title': 'Carnet du voyageur',
    'evolution.notes_journal_empty': 'Le carnet est vierge pour le moment.',
    'evolution.notes_add_cta': '+ Graver une entrée',
    'evolution.note_share_toggle': 'Partager avec le cercle',
    'evolution.note_private_label': 'Entrée gardée pour toi',
    'evolution.note_shared_label': 'Entrée partagée avec le cercle',
    'evolution.notes_error': "Le carnet n'a pas pu être mis à jour. Réessaie.",
    /* — compte — */
    'account.title': 'Mon carnet de route',
    'account.pseudo_label': 'Nom de sentier',
    'account.email_label': 'Sifflet de rappel',
    'account.display_name_label': 'Nom porté aux yeux du cercle',
    'account.save_btn': 'Graver',
    'account.cancel_btn': 'Abandonner',
    'account.saved': 'Le carnet a retenu ce nom.',
    'account.error': "Le carnet n'a pas pu retenir ce changement. Réessaie.",
    'account.password_title': 'Changer de mot de passe',
    'account.current_password_label': 'Mot de passe actuel',
    'account.new_password_label': 'Nouveau mot de passe',
    'account.password_save_btn': 'Changer',
    'account.password_saved': 'Le mot de passe a été changé.',
    'account.password_wrong_current': "Ce n'est pas le bon mot de passe.",
    'account.password_error': "Le carnet n'a pas pu changer le mot de passe. Réessaie.",
    'account.email_change_title': "Changer d'adresse e-mail",
    'account.current_password_for_email_label': 'Mot de passe actuel',
    'account.new_email_label': 'Nouvelle adresse e-mail',
    'account.email_change_save_btn': 'Envoyer',
    'account.email_change_saved': 'Un message est parti vers la nouvelle adresse.',
    'account.email_change_wrong_current': "Ce n'est pas le bon mot de passe.",
    'account.email_change_taken': 'Cette adresse est déjà utilisée par un autre compte.',
    'account.email_change_error': "Le carnet n'a pas pu envoyer la demande. Réessaie.",
    'account.calendar_layers_title': 'Ce que montre mon calendrier',
    'account.calendar_layer.mes-indisponibilites': 'Mes indisponibilités',
    'account.calendar_layer.mes-disponibilites': 'Mes disponibilités',
    'account.calendar_layer.mes-seances': 'Mes séances confirmées',
    'account.calendar_layer.votes-en-cours': 'Les votes en cours',
    'account.calendar_layer.inscriptions-ouvertes': 'Les inscriptions ouvertes',
    'account.calendar_layer.disponibilite-groupe': 'La disponibilité du groupe',
    /* — vue Agenda (Story 36.11) — badges contractuels (EXPERIENCE.md §5), titres thématisés. */
    'calendar.agenda.section_awaiting': 'Ce qui t’attend',
    'calendar.agenda.section_scheduled': 'Ce qui est prévu',
    'calendar.agenda.section_past': 'Ce qui est derrière',
    'calendar.agenda.badge_answer_poll': 'Réponds au vote',
    'calendar.agenda.badge_poll_open': 'Vote en cours',
    'calendar.agenda.badge_signup': 'S’inscrire',
    'calendar.agenda.badge_signed_up': 'Inscrit',
    'calendar.agenda.badge_debrief': 'Débriefer',
    'calendar.agenda.empty': 'Rien ne t’attend, rien n’est prévu.',
    /* — Agenda du MJ (Story 36.12) — libellés d'état contractuels, appels à l'action thématisés. */
    'calendar.agenda.badge_to_seal': 'À sceller',
    'calendar.agenda.poll_open': 'Vote ouvert',
    'calendar.agenda.responded_count': '{n} sur {total} ont répondu',
    'calendar.agenda.slots_proposed': '{n} créneaux proposés',
    'calendar.agenda.missing_voters': 'il manque {names}',
    'calendar.agenda.no_date': 'sans date',
    'calendar.agenda.no_date_proposed': 'Aucune date proposée',
    'calendar.agenda.action_launch_poll': 'Lancer un vote',
    'calendar.agenda.action_seal': 'Planter',
    'calendar.agenda.action_expand': 'Déployer',
    'calendar.agenda.action_collapse': 'Replier',
    'calendar.agenda.seal_confirm_title': 'Planter le drapeau sur ce créneau ?',
    'calendar.agenda.seal_confirm_body':
      'La séance se tiendra à ce créneau et le vote se refermera. Les autres créneaux proposés disparaîtront.',
    /* — identité — */
    'identity.character_label': 'Personnage',
    'identity.player_label': 'Joueur',
    'identity.homonymy_warning':
      'Un autre voyageur de cette expédition porte le même nom affiché que toi.',
    'identity.homonymy_change_cta': 'Changer mon nom affiché',
    'identity.homonymy_ignore_cta': 'Ignorer',
  },

  /* ════════════════════════════════════════════════════ MÉDIÉVAL STEAMPUNK */
  'medieval-steampunk': {
    /* — navigation — */
    'nav.my_games': 'Mes expéditions',
    'nav.create_game': 'Initier une mission',
    'nav.logout': 'Couper la vapeur',
    'nav.calendar': 'Calendrier',
    'nav.account': 'Mon établi',
    'nav.characters': 'Automates',
    /* — dashboard — */
    'dashboard.title_invitations': 'Transmissions reçues',
    'dashboard.empty': 'Aucune manufacture active. Lancez la première…',
    'dashboard.role_prefix': 'Poste :',
    'dashboard.role_mj': 'Ingénieur',
    'dashboard.role_player': 'Mécanicien',
    'dashboard.status_closed_badge': 'Démantelée',
    /* — signalétique d'état (Story 29.7) — */
    'dashboard.section_awaiting': 'À traiter',
    'dashboard.section_ongoing': 'En service',
    'dashboard.section_upcoming': 'À venir',
    'dashboard.section_finished': 'Démantelées',
    /* — filtres, tri, favoris (Story 29.8) — */
    'dashboard.empty_filtered': 'Aucune manufacture ne répond à ces critères.',
    'dashboard.controls_toggle_aria': 'Afficher les filtres et le tri',
    'dashboard.filter_role_label': 'Poste',
    'dashboard.filter_role_all': 'Tous',
    'dashboard.filter_status_label': 'Statut',
    'dashboard.filter_status_all': 'Tous',
    'dashboard.sort_label': 'Trier par',
    'dashboard.sort_urgence': 'Urgence',
    'dashboard.sort_date': 'Date',
    'dashboard.sort_nom': 'Nom',
    'dashboard.sort_type': 'Type',
    'dashboard.sort_statut': 'Statut',
    'dashboard.hide_finished_label': 'Masquer les manufactures démantelées',
    'dashboard.show_finished_btn': 'Afficher les manufactures démantelées',
    'dashboard.favorite_add_aria': 'Marquer comme favori',
    'dashboard.favorite_remove_aria': 'Retirer des favoris',
    /* — barre de contrôles partagée (Story 29.9) — */
    'dashboard.search_label': 'Rechercher une manufacture',
    'dashboard.row_signal_count_aria': '{n} intervention(s) à mener',
    'list_control_bar.toggle_aria': 'Afficher les filtres et le tri',
    'list_control_bar.view_mode_group_aria': 'Densité d’affichage',
    'list_control_bar.view_mode_large_aria': 'Grande vignette',
    'list_control_bar.view_mode_medium_aria': 'Vignette intermédiaire',
    'list_control_bar.view_mode_compact_aria': 'Liste compacte',
    'list_control_bar.sort_label': 'Trier par',
    'list_control_bar.reset_pill_label': 'Réglages modifiés',
    /* — my-characters (Story 29.2) — */
    'my_characters.title': 'Mes automates',
    'my_characters.empty': 'Aucun automate assemblé. Construisez-en un depuis une mission…',
    'my_characters.no_match': 'Aucun automate ne répond à cette recherche.',
    'my_characters.search_label': 'Rechercher un automate',
    'my_characters.sort_niveau': 'Niveau',
    'my_characters.sort_partie': 'Mission',
    'my_characters.sort_nom': 'Nom',
    /* — partie-form — */
    'partie.new_title': 'Nouvelle mission',
    'partie.edit_title': 'Recalibrer la mission',
    'partie.save_btn': 'Valider',
    'partie.cancel_btn': 'Annuler',
    'partie.name_label': 'Nom de la mission',
    'partie.system_label': 'Système de jeu',
    'partie.kind_label': 'Régime de la mission',
    'partie.description_label': 'Note de service (facultatif)',
    'partie.kind_ONE_SHOT': 'Mission unique',
    'partie.kind_CAMPAGNE_LINEAIRE': 'Programme',
    'partie.kind_CAMPAGNE_EPISODIQUE': 'Programme à cycles',
    'partie.kind_refusal_closed':
      'Cette mission est close. Rouvrez-la avant d’en changer le régime.',
    'partie.kind_refusal_too_many_scenarios':
      'Cette mission compte {count} opérations ; une mission unique n’en a qu’une.',
    'partie.courant_choice_title': 'Quelle opération reste en cours ?',
    'partie.courant_choice_help':
      'Un programme n’exécute qu’une opération à la fois. Les autres repasseront « à venir » — leurs séances et leurs dates sont conservées.',
    'partie.courant_choice_confirm': 'Verrouiller ce réglage',
    'partie.cover_add': 'Ajouter une plaque d’identification',
    'partie.cover_change': 'Changer la plaque',
    'partie.cover_remove': 'Retirer la plaque',
    'partie.cover_uploading': 'Gravure de la plaque en cours…',
    'partie.cover_upload_error': 'La plaque n’a pu être gravée. Réessayez.',
    'partie.cover_remove_error': 'La plaque n’a pu être retirée. Réessayez.',
    'partie.cover_reject_type': 'Seuls les formats JPEG, PNG et WEBP sont admis.',
    'partie.cover_reject_size': 'Ce fichier dépasse 5 Mo : réduisez-le avant dépôt.',
    'partie.save_error': 'Cette mission n’a pu être enregistrée. Réessayez.',
    'partie.created_but_cover_failed':
      'La mission est bien enregistrée, mais sa plaque n’a pu être gravée. Vous pouvez la redéposer ici.',
    'partie.fields_saved_but_convert_failed':
      'Les autres modifications sont enregistrées, mais le régime de la mission n’a pu être changé. Réessayez.',
    /* — partie-detail — */
    'partie.scheduling_title': 'Prochaine mission',
    'partie.no_session': "Aucune mission planifiée. Interrogez l'automate.",
    'partie.members_title': '⚙ Équipage',
    'partie.no_members': 'Aucun mécanicien à bord.',
    'partie.remove_member_btn': 'Débarquer',
    'partie.no_description': 'Dossier technique vierge.',
    'partie.invite_title': 'Recruter un mécanicien',
    'partie.search_label': 'Matricule ou appellation',
    'partie.search_btn': 'Scanner',
    'partie.invite_btn': 'Enrôler',
    'partie.links_title': "Télégrammes d'invitation",
    'partie.generate_link': "Forger un badge d'accès",
    'partie.notice_invited': 'Télégramme envoyé à {name}.',
    'partie.invite_by_email_label': 'Adresse du destinataire',
    'partie.invite_by_email_btn': 'Expédier un télégramme',
    'partie.notice_invited_email': 'Télégramme expédié à {email}.',
    'partie.notice_invite_email_error': "Le télégramme n'a pas pu être expédié. Réessayez.",
    'partie.reference_sheets_title': 'Manuels de référence',
    'partie.asset_journal_cta': 'Journal',
    'partie.asset_carte_cta': 'Carte',
    'partie.asset_download_error': "Échec de l'impression du manuel. Réessayez.",
    'partie.prep_sheets_title': 'Manuels de préparation (MJ)',
    'partie.asset_monde_cta': 'Monde',
    'partie.asset_monstre_cta': 'Monstre',
    'partie.asset_ville_cta': 'Ville',
    'partie.asset_objectif_chasse_cta': 'Objectif — Chasse',
    'partie.asset_objectif_quete_cta': 'Objectif — Quête',
    'partie.asset_objectif_voyage_cta': 'Objectif — Voyage',
    'partie.asset_oeuf_de_bataille_cta': 'Œuf de bataille',
    'partie.asset_structure_cta': 'Structure',
    'partie.notice_copy': 'Badge copié dans le carnet de bord.',
    'partie.edit_btn': 'Recalibrer',
    'partie.close_btn': "Mettre à l'arrêt",
    'partie.reopen_btn': 'Remettre en service',
    'partie.status_closed_label': "Cette machine est à l'arrêt.",
    /* — signaux d'état (Story 29.7, FR-12) — */
    'partie.signal_personnage_a_creer': 'Assembler son automate',
    'partie.signal_vote_en_cours_sans_reponse': 'Vote en attente',
    'partie.signal_compte_rendu_non_redige': 'Rapport à rédiger',
    'partie.signal_homme_dragon_a_creer': 'Assembler son Homme Dragon',
    'partie.signal_aucun_membre_invite': 'Aucun mécanicien recruté',
    'partie.signal_aucun_scenario_en_cours': 'Aucune mission en cours',
    'partie.signal_aucune_date_ni_vote': 'Aucune date ni vote',
    'partie.signal_rapport_fin_manquant': 'Rapport de fin manquant',
    'partie.signal_prochaine_seance_connue': 'Prochaine séance connue',
    'partie.signal_partie_terminee': 'Machine démantelée',
    'partie.signal_more_count': '+{n}',
    'partie.delete_btn': 'Démanteler',
    'partie.invitations_tab_label': 'Invitations',
    'partie.show_troupe': "Voir l'équipage",
    'partie.hide_troupe': "Masquer l'équipage",
    /* — calendrier & vote — */
    'cta.find_date': "Interroger l'automate des créneaux",
    'cta.guild_calendar': 'Consulter le registre de la mission',
    'cta.launch_vote': 'Actionner le registre de vote',
    'cta.save_constraint': 'Enregistrer dans le registre de vapeur',
    'cta.send_reminder': 'Envoyer un message pneumatique',
    'section.slots': "Créneaux validés par l'automate",
    'section.constraints': 'Registre de contraintes',
    'empty.no_slots': "L'automate ne détecte aucun créneau. Vérifiez les registres des membres.",
    'empty.no_constraints': 'Aucune contrainte dans le registre de vapeur.',
    'success.constraint_saved': 'Contrainte enregistrée dans le registre.',
    'alert.expiring_soon': 'La pression baisse — votre registre expire bientôt.',
    'alert.missing_player': "{name} n'a pas alimenté le registre.",
    'status.unavailable_label': 'Hors-service',
    'status.unknown_label': 'Signal inconnu',
    'cta.choose_date': "Verrouiller l'engrenage de la date",
    'cta.cancel_poll': 'Purger le registre de vote',
    'cta.restore_default_layers': "Réinitialiser l'affichage par défaut",
    'empty.no_poll': 'Aucun registre de vote actif.',
    'success.poll_created': 'Registre de vote activé. Message pneumatique envoyé.',
    'success.date_chosen': "L'engrenage est verrouillé. Séance confirmée.",
    'poll.status_title': 'Registre de vote actif',
    'poll.vote_pending': 'Registre de vote — réponse requise',
    'success.vote_cast': 'Réponse enregistrée dans le registre.',
    'cta.confirm_votes': 'Valider dans le registre',
    'cta.withdraw_vote': 'Retirer ma réponse',
    'success.vote_withdrawn': 'Réponse effacée du registre.',
    'poll.withdraw_error': 'Le retrait a échoué. Réessayez.',
    'poll.cast_error': 'Impossible d’enregistrer ta réponse. Réessayez.',
    'poll.vote_closed': 'Registre de vote verrouillé.',
    'alert.all_responded': "Tout l'équipage a répondu au registre.",
    'poll.status_summary': 'Registre ouvert — {responded}/{total} membres ont répondu',
    /* — mode Destinée et panneau réduit (Story 36.9) — */
    'cta.destiny_mode': 'Destinée',
    'poll.missing_prefix': 'N’ont pas alimenté le registre :',
    'poll.responded_prefix': 'Ont alimenté le registre :',
    /* — annonces (Epic 9) — */
    'announcement.scope_campaign_label': 'Toute la mission',
    'announcement.scope_oneshot_label': 'Cette opération',
    'announcement.scope_scenario_label': 'Ce dossier',
    'announcement.publish_cta': 'Diffuser une transmission',
    'announcement.text_placeholder': 'Rédiger une transmission...',
    'announcement.published_notice': 'Transmission diffusée.',
    'announcement.unseen_label': 'Non lue — cliquez pour accuser réception',
    /* — personnages (Palier P3) — */
    'character.create_cta': 'Assembler un automate-voyageur',
    'character.tab_label': 'Personnages',
    'character.step_class': 'Choisir sa fonction',
    'character.step_type': 'Choisir son mécanisme',
    'character.step_magic': 'Calibrer le module magique',
    'character.step_portrait_intro':
      'Grave un portrait sur la plaque si tu le souhaites — étape optionnelle, ignorable sans conséquence.',
    'character.portrait_missing': 'Aucun portrait gravé sur la plaque',
    'character.portrait_edit_cta': 'Recalibrer le portrait',
    'character.pdf_crop_edit_cta': 'Recalibrer le cadrage PDF',
    'character.export_editable_cta': 'Exporter en PDF (éditable)',
    'character.export_2pages_cta': 'Exporter en PDF (2 pages)',
    'character.export_equipment_cta': "Exporter l'équipement en PDF",
    'character.export_notes_cta': 'Exporter les notes en PDF',
    'character.export_error': "Échec de l'impression pneumatique. Réessayez.",
    'character.owner_badge_mj': 'Ingénieur',
    'character.level_badge': 'Niv. {n}',
    'character.my_sheet_tab_label': 'Ma fiche',
    /* — Homme Dragon (Epic 10, Story 10.1) — */
    'homme-dragon.create_cta': 'Assembler mon Homme Dragon',
    'homme-dragon.race_label': 'Modèle',
    'homme-dragon.artefact_label': 'Composant emblématique',
    'homme-dragon.created_notice': 'Votre Homme Dragon est opérationnel.',
    /* — roster (Story 6.1) — */
    'roster.mj_badge': 'MJ',
    'roster.invite_slot': 'Recruter un mécanicien',
    'roster.collapse_label': "Replier l'équipage",
    'roster.expand_label': "Déplier l'équipage",
    'roster.levelup_badge': 'Calibrage niveau disponible',
    /* — évolution du personnage (Story 6.2) — */
    'evolution.xp_distribute_cta': "Distribuer les crédits d'expérience",
    'evolution.xp_panel_title': "Distribution de crédits d'expérience",
    'evolution.xp_history_title': "Registre des crédits d'expérience",
    'evolution.xp_history_empty': 'Aucune distribution enregistrée dans le registre.',
    'evolution.xp_note_label': 'Note technique',
    'evolution.xp_confirm_btn': 'Valider la distribution',
    'evolution.xp_bonus_link': '+ bonus',
    'evolution.xp_levelup_warning': '{name} va être recalibré au niveau supérieur',
    /* — montée de niveau & historique (Story 6.3) — */
    'evolution.levelup_banner': 'Calibrage niveau [N] disponible',
    'evolution.levelup_cta': 'Recalibrer',
    'evolution.levelup_wizard_title': 'Recalibrage',
    'evolution.levelup_step_pv_pe': 'Répartir 3 points entre PV et PE',
    'evolution.levelup_step_capability': 'Choisir le module débloqué',
    'evolution.levelup_legendary_journey_text':
      'Une trajectoire légendaire est engagée — aucun réglage supplémentaire requis.',
    'evolution.levelup_confirm_cta': 'Valider le calibrage',
    /* — sous-navigation locale de la fiche (Story 29.5) — */
    'evolution.main_sheet_tab_label': 'Fiche technique',
    'evolution.history_tab_label': 'Journal de bord',
    'evolution.history_empty': 'Aucune entrée consignée pour le moment.',
    'evolution.mj_edit_trace': 'recalibré par le MJ',
    'evolution.landscape_section_title': 'Module paysage/climat',
    'evolution.immunity_section_title': 'Modules d’immunité',
    'evolution.other_capabilities_title': 'Modules installés',
    'evolution.inventory_section_title': 'Compartiment de fret',
    'evolution.inventory_add_cta': '+ Charger un composant',
    'evolution.inventory_empty': 'Aucun composant chargé pour le moment.',
    'evolution.inventory_overweight_label': 'Surcharge',
    'evolution.inventory_error': 'Le fret n’a pas pu être mis à jour. Réessayez.',
    'evolution.mj_edit_error': 'La modification n’a pas pu être enregistrée. Réessayez.',
    'evolution.mj_edit_warning_prefix': 'Avertissement : ',
    'evolution.inventory_mj_add_cta': '+ Charger un composant (MJ)',
    'evolution.narrative_edit_error': 'La modification n’a pas pu être enregistrée. Réessayez.',
    'evolution.notes_journal_title': 'Journal de bord personnel',
    'evolution.notes_journal_empty': 'Aucune entrée consignée pour le moment.',
    'evolution.notes_add_cta': '+ Consigner une entrée',
    'evolution.note_share_toggle': 'Diffuser à l’équipage',
    'evolution.note_private_label': 'Entrée confidentielle',
    'evolution.note_shared_label': 'Entrée diffusée à l’équipage',
    'evolution.notes_error': 'Le journal n’a pas pu être mis à jour. Réessayez.',
    /* — compte — */
    'account.title': 'Mon établi',
    'account.pseudo_label': 'Matricule',
    'account.email_label': 'Fréquence de contact',
    'account.display_name_label': 'Nom affiché aux autres membres',
    'account.save_btn': 'Riveter',
    'account.cancel_btn': 'Annuler',
    'account.saved': 'L’établi a retenu ce nom.',
    'account.error': 'L’établi n’a pas pu retenir ce changement. Réessayez.',
    'account.password_title': 'Recalibrer le code d’accès',
    'account.current_password_label': 'Code d’accès actuel',
    'account.new_password_label': 'Nouveau code d’accès',
    'account.password_save_btn': 'Recalibrer',
    'account.password_saved': 'Le code d’accès a été recalibré.',
    'account.password_wrong_current': 'Code d’accès actuel erroné.',
    'account.password_error': 'L’établi n’a pas pu recalibrer le code. Réessayez.',
    'account.email_change_title': 'Recalibrer la fréquence de contact',
    'account.current_password_for_email_label': 'Code d’accès actuel',
    'account.new_email_label': 'Nouvelle fréquence de contact',
    'account.email_change_save_btn': 'Transmettre',
    'account.email_change_saved': 'Un signal est parti vers la nouvelle fréquence.',
    'account.email_change_wrong_current': 'Code d’accès actuel erroné.',
    'account.email_change_taken': 'Cette fréquence est déjà occupée par un autre poste.',
    'account.email_change_error': 'L’établi n’a pas pu transmettre la demande. Réessayez.',
    'account.calendar_layers_title': 'Ce qu’affiche mon calendrier',
    'account.calendar_layer.mes-indisponibilites': 'Mes indisponibilités',
    'account.calendar_layer.mes-disponibilites': 'Mes disponibilités',
    'account.calendar_layer.mes-seances': 'Mes séances confirmées',
    'account.calendar_layer.votes-en-cours': 'Les votes en cours',
    'account.calendar_layer.inscriptions-ouvertes': 'Les inscriptions ouvertes',
    'account.calendar_layer.disponibilite-groupe': 'La disponibilité du groupe',
    /* — vue Agenda (Story 36.11) — badges contractuels (EXPERIENCE.md §5), titres thématisés. */
    'calendar.agenda.section_awaiting': 'À traiter',
    'calendar.agenda.section_scheduled': 'Au programme',
    'calendar.agenda.section_past': 'Aux archives',
    'calendar.agenda.badge_answer_poll': 'Réponds au vote',
    'calendar.agenda.badge_poll_open': 'Vote en cours',
    'calendar.agenda.badge_signup': 'S’inscrire',
    'calendar.agenda.badge_signed_up': 'Inscrit',
    'calendar.agenda.badge_debrief': 'Débriefer',
    'calendar.agenda.empty': 'Aucune tâche, aucune échéance.',
    /* — Agenda du MJ (Story 36.12) — libellés d'état contractuels, appels à l'action thématisés. */
    'calendar.agenda.badge_to_seal': 'À sceller',
    'calendar.agenda.poll_open': 'Scrutin ouvert',
    'calendar.agenda.responded_count': '{n} sur {total} ont répondu',
    'calendar.agenda.slots_proposed': '{n} créneaux proposés',
    'calendar.agenda.missing_voters': 'il manque {names}',
    'calendar.agenda.no_date': 'sans date',
    'calendar.agenda.no_date_proposed': 'Aucune date proposée',
    'calendar.agenda.action_launch_poll': 'Ouvrir un scrutin',
    'calendar.agenda.action_seal': 'Verrouiller',
    'calendar.agenda.action_expand': 'Déployer',
    'calendar.agenda.action_collapse': 'Rétracter',
    'calendar.agenda.seal_confirm_title': 'Verrouiller l’engrenage sur ce créneau ?',
    'calendar.agenda.seal_confirm_body':
      'La séance sera fixée à ce créneau et le scrutin se refermera. Les autres créneaux proposés disparaîtront.',
    /* — identité — */
    'identity.character_label': 'Personnage',
    'identity.player_label': 'Joueur',
    'identity.homonymy_warning':
      'Un autre membre de cette compagnie porte le même nom affiché que vous.',
    'identity.homonymy_change_cta': 'Changer mon nom affiché',
    'identity.homonymy_ignore_cta': 'Ignorer',
  },
};
