export type Theme = 'grimoire-emeraude' | 'foret-ancienne' | 'medieval-steampunk';

export const THEMES: Theme[] = ['grimoire-emeraude', 'foret-ancienne', 'medieval-steampunk'];

export const THEME_NAMES: Record<Theme, string> = {
  'grimoire-emeraude': 'Grimoire Émeraude',
  'foret-ancienne': 'Forêt Ancienne',
  'medieval-steampunk': 'Médiéval Steampunk',
};

export const TONE_MAP: Record<Theme, Record<string, string>> = {
  /* ═══════════════════════════════════════════════════════ GRIMOIRE ÉMERAUDE */
  'grimoire-emeraude': {
    /* — navigation — */
    'nav.my_games': 'Mes aventures',
    'nav.create_game': 'Lancer une quête',
    'nav.mode_joueur': 'Héros',
    'nav.mode_mj': 'Maître',
    'nav.logout': 'Fermer le grimoire',
    'nav.calendar': 'Mes disponibilités',
    /* — dashboard — */
    'dashboard.title_mj': 'Mes rituels',
    'dashboard.empty_mj': 'Nulle quête en cours. Forgez la première…',
    'dashboard.title_invitations': 'Invitations reçues',
    'dashboard.title_player': 'Mes aventures',
    'dashboard.empty_player': "Nulle invitation parvenue. Guettez l'appel.",
    /* — partie-form — */
    'partie.new_title': 'Nouvelle quête',
    'partie.edit_title': 'Retranscrire le parchemin',
    'partie.save_btn': 'Inscrire',
    /* — partie-detail — */
    'partie.scheduling_title': 'Prochaine séance',
    'partie.no_session': "Aucune séance convoquée. Consultez l'oracle des créneaux.",
    'partie.members_title': '⚔ Compagnons',
    'partie.no_members': "Nulle âme pour l'instant.",
    'partie.no_description': 'Ce grimoire est muet.',
    'partie.invite_title': 'Convoquer un compagnon',
    'partie.search_label': 'Nom ou signe distinctif',
    'partie.search_btn': 'Scruter',
    'partie.invite_btn': 'Convoquer',
    'partie.links_title': "Parchemins d'invocation",
    'partie.generate_link': 'Tisser un parchemin',
    'partie.notice_invited': 'Missive envoyée à {name}.',
    'partie.notice_copy': 'Parchemin copié dans la besace.',
    'partie.edit_btn': 'Retranscrire',
    'partie.delete_btn': 'Brûler le parchemin',
    'partie.back_btn': 'Retour au grimoire',
    /* — calendrier & vote — */
    'cta.find_date': "Consulter l'oracle des créneaux",
    'cta.guild_calendar': 'Voir le grimoire des disponibilités',
    'cta.launch_vote': 'Ouvrir le parchemin du vote',
    'cta.save_constraint': 'Inscrire dans le grimoire',
    'cta.send_reminder': 'Envoyer une missive',
    'section.slots': 'Fenêtres de la destinée',
    'section.constraints': 'Contraintes inscrites',
    'empty.no_slots': "L'oracle ne voit aucun créneau libre. Les parchemins manquent de données.",
    'empty.no_constraints': 'Aucune contrainte inscrite dans le grimoire.',
    'success.constraint_saved': 'Contrainte gravée dans le parchemin.',
    'alert.expiring_soon': 'Votre parchemin expire bientôt. Renouvelez le sort.',
    'alert.missing_player': "{name} n'a pas encore consulté l'oracle.",
    'status.unavailable_label': 'Indisponible',
    'status.unknown_label': 'Mystère',
    'cta.choose_date': 'Sceller ce créneau',
    'cta.cancel_poll': 'Brûler le parchemin de vote',
    'empty.no_poll': 'Aucun vote en cours dans ce grimoire.',
    'success.poll_created': 'Vote ouvert. Les membres ont été avertis.',
    'success.date_chosen': 'La date est gravée dans le grimoire.',
    'poll.status_title': 'Vote en cours',
    'poll.vote_pending': 'Vote de date en cours — parchemin en attente',
    'success.vote_cast': 'Réponse inscrite dans le grimoire.',
    'cta.confirm_votes': 'Sceller mes réponses',
    'poll.vote_closed': "Ce vote est clos. L'oracle a tranché.",
    'alert.all_responded': 'Tous les compagnons ont répondu au vote.',
    'poll.status_summary': 'Vote ouvert — {responded}/{total} compagnons ont répondu',
    /* — personnages (Palier P3) — */
    'character.create_cta': 'Créer un voyageur',
    'character.tab_label': 'Personnages',
    'character.step_class': 'Choisir sa vocation',
    'character.step_type': 'Choisir sa voie',
    'character.magic_deferred_notice':
      "La magie s'apprendra plus tard, jeune sorcier — pour l'instant, seuls les dons passifs s'activent.",
    'character.portrait_missing': 'Aucun portrait — le conteur imagine un visage',
    'character.portrait_edit_cta': 'Modifier le portrait',
  },

  /* ══════════════════════════════════════════════════════════ FORÊT ANCIENNE */
  'foret-ancienne': {
    /* — navigation — */
    'nav.my_games': 'Mes pérégrinations',
    'nav.create_game': 'Ouvrir un sentier',
    'nav.mode_joueur': 'Voyageur',
    'nav.mode_mj': 'Guide',
    'nav.logout': 'Quitter la forêt',
    'nav.calendar': 'Mes disponibilités',
    /* — dashboard — */
    'dashboard.title_mj': 'Mes clairières',
    'dashboard.empty_mj': 'Aucune clairière ouverte. Plantez le premier feu…',
    'dashboard.title_invitations': 'Appels de la forêt',
    'dashboard.title_player': 'Mes pérégrinations',
    'dashboard.empty_player': "Nul sentier tracé pour vous. Guettez l'appel.",
    /* — partie-form — */
    'partie.new_title': 'Nouveau sentier',
    'partie.edit_title': 'Rebattre le sentier',
    'partie.save_btn': 'Planter',
    /* — partie-detail — */
    'partie.scheduling_title': 'Prochaine clairière',
    'partie.no_session': "Aucune clairière réservée. L'écureuil cherche encore.",
    'partie.members_title': '🌿 Habitants',
    'partie.no_members': 'Aucun habitant de la clairière.',
    'partie.no_description': 'La forêt garde ses secrets.',
    'partie.invite_title': 'Appeler depuis la forêt',
    'partie.search_label': 'Nom ou espèce connue',
    'partie.search_btn': 'Fouiller',
    'partie.invite_btn': 'Accueillir',
    'partie.links_title': 'Sifflets de rappel',
    'partie.generate_link': 'Tisser un laissez-passer',
    'partie.notice_invited': 'Sifflet envoyé à {name}.',
    'partie.notice_copy': 'Laissez-passer copié dans la gibecière.',
    'partie.edit_btn': 'Rebattre',
    'partie.delete_btn': 'Effacer le sentier',
    'partie.back_btn': 'Rentrer dans la forêt',
    /* — calendrier & vote — */
    'cta.find_date': "Envoyer l'écureuil messager",
    'cta.guild_calendar': 'Voir la forêt des disponibilités',
    'cta.launch_vote': 'Planter le bâton du vote',
    'cta.save_constraint': 'Marquer le territoire',
    'cta.send_reminder': 'Faire chanter les oiseaux',
    'section.slots': 'Clairières disponibles',
    'section.constraints': 'Zones marquées',
    'empty.no_slots':
      'Aucune clairière libre. La forêt est dense, demandez aux membres leurs disponibilités.',
    'empty.no_constraints': 'Aucun territoire marqué.',
    'success.constraint_saved': 'Territoire marqué dans la forêt.',
    'alert.expiring_soon': "Votre marquage s'efface bientôt. Renouvelez votre présence.",
    'alert.missing_player': "{name} n'a pas encore parcouru la forêt.",
    'status.unavailable_label': 'Absent de la forêt',
    'status.unknown_label': 'Perdu dans les branches',
    'cta.choose_date': 'Planter le drapeau de la clairière',
    'cta.cancel_poll': 'Disperser les feuilles du vote',
    'empty.no_poll': 'Aucun vote en cours dans la forêt.',
    'success.poll_created': "L'écureuil a transmis l'appel du vote.",
    'success.date_chosen': 'La clairière de la séance est choisie.',
    'poll.status_title': 'Vote en cours dans la forêt',
    'poll.vote_pending': "L'écureuil attend ta réponse au vote",
    'success.vote_cast': "L'écureuil a transmis ta réponse.",
    'cta.confirm_votes': 'Transmettre mes réponses',
    'poll.vote_closed': 'Le vote de la forêt est terminé.',
    'alert.all_responded': "Tous les habitants ont répondu à l'appel.",
    'poll.status_summary': 'Vote ouvert — {responded}/{total} habitants ont répondu',
    /* — personnages (Palier P3) — */
    'character.create_cta': 'Éveiller un compagnon de route',
    'character.tab_label': 'Personnages',
    'character.step_class': 'Choisir son rôle dans le cercle',
    'character.step_type': 'Choisir son chemin',
    'character.magic_deferred_notice':
      'Les sortilèges des saisons dorment encore — reviens quand le cercle sera prêt.',
    'character.portrait_missing': 'Aucun visage gravé — la forêt garde son mystère',
    'character.portrait_edit_cta': 'Modifier le portrait',
  },

  /* ════════════════════════════════════════════════════ MÉDIÉVAL STEAMPUNK */
  'medieval-steampunk': {
    /* — navigation — */
    'nav.my_games': 'Mes expéditions',
    'nav.create_game': 'Initier une mission',
    'nav.mode_joueur': 'Mécanicien',
    'nav.mode_mj': 'Ingénieur',
    'nav.logout': 'Couper la vapeur',
    'nav.calendar': 'Mes disponibilités',
    /* — dashboard — */
    'dashboard.title_mj': 'Mes manufactures',
    'dashboard.empty_mj': 'Aucune manufacture active. Lancez la première…',
    'dashboard.title_invitations': 'Transmissions reçues',
    'dashboard.title_player': 'Mes missions',
    'dashboard.empty_player': 'Aucune assignation reçue. En attente de transmission.',
    /* — partie-form — */
    'partie.new_title': 'Nouvelle mission',
    'partie.edit_title': 'Recalibrer la mission',
    'partie.save_btn': 'Valider',
    /* — partie-detail — */
    'partie.scheduling_title': 'Prochaine mission',
    'partie.no_session': "Aucune mission planifiée. Interrogez l'automate.",
    'partie.members_title': '⚙ Équipage',
    'partie.no_members': 'Aucun mécanicien à bord.',
    'partie.no_description': 'Dossier technique vierge.',
    'partie.invite_title': 'Recruter un mécanicien',
    'partie.search_label': 'Matricule ou appellation',
    'partie.search_btn': 'Scanner',
    'partie.invite_btn': 'Enrôler',
    'partie.links_title': "Télégrammes d'invitation",
    'partie.generate_link': "Forger un badge d'accès",
    'partie.notice_invited': 'Télégramme envoyé à {name}.',
    'partie.notice_copy': 'Badge copié dans le carnet de bord.',
    'partie.edit_btn': 'Recalibrer',
    'partie.delete_btn': 'Démanteler',
    'partie.back_btn': "Retour à l'atelier",
    /* — calendrier & vote — */
    'cta.find_date': "Interroger l'automate des créneaux",
    'cta.guild_calendar': 'Consulter le registre de la mission',
    'cta.launch_vote': 'Actionner le registre de vote',
    'cta.save_constraint': 'Enregistrer dans le registre de vapeur',
    'cta.send_reminder': 'Envoyer un message pneumatique',
    'section.slots': "Créneaux validés par l'automate",
    'section.constraints': 'Registre de contraintes',
    'empty.no_slots': "L'automate ne détecte aucun créneau. Vérifiez les registres des membres.",
    'empty.no_constraints': 'Aucune contrainte dans le registre de vapeur.',
    'success.constraint_saved': 'Contrainte enregistrée dans le registre.',
    'alert.expiring_soon': 'La pression baisse — votre registre expire bientôt.',
    'alert.missing_player': "{name} n'a pas alimenté le registre.",
    'status.unavailable_label': 'Hors-service',
    'status.unknown_label': 'Signal inconnu',
    'cta.choose_date': "Verrouiller l'engrenage de la date",
    'cta.cancel_poll': 'Purger le registre de vote',
    'empty.no_poll': 'Aucun registre de vote actif.',
    'success.poll_created': 'Registre de vote activé. Message pneumatique envoyé.',
    'success.date_chosen': "L'engrenage est verrouillé. Séance confirmée.",
    'poll.status_title': 'Registre de vote actif',
    'poll.vote_pending': 'Registre de vote — réponse requise',
    'success.vote_cast': 'Réponse enregistrée dans le registre.',
    'cta.confirm_votes': 'Valider dans le registre',
    'poll.vote_closed': 'Registre de vote verrouillé.',
    'alert.all_responded': "Tout l'équipage a répondu au registre.",
    'poll.status_summary': 'Registre ouvert — {responded}/{total} membres ont répondu',
    /* — personnages (Palier P3) — */
    'character.create_cta': 'Assembler un automate-voyageur',
    'character.tab_label': 'Personnages',
    'character.step_class': 'Choisir sa fonction',
    'character.step_type': 'Choisir son mécanisme',
    'character.magic_deferred_notice':
      "Le grimoire à vapeur n'est pas encore calibré pour les formules — les avantages de base restent actifs.",
    'character.portrait_missing': 'Aucun portrait gravé sur la plaque',
    'character.portrait_edit_cta': 'Recalibrer le portrait',
  },
};
