export type Theme = 'grimoire-emeraude' | 'foret-ancienne' | 'medieval-steampunk';

export const THEMES: Theme[] = ['grimoire-emeraude', 'foret-ancienne', 'medieval-steampunk'];

export const THEME_NAMES: Record<Theme, string> = {
  'grimoire-emeraude': 'Grimoire Émeraude',
  'foret-ancienne': 'Forêt Ancienne',
  'medieval-steampunk': 'Médiéval Steampunk',
};

export const TONE_MAP: Record<Theme, Record<string, string>> = {
  /* ═══════════════════════════════════════════════════════ GRIMOIRE ÉMERAUDE */
  'grimoire-emeraude': {
    /* — navigation — */
    'nav.my_games': 'Mes aventures',
    'nav.create_game': 'Lancer une quête',
    'nav.mode_joueur': 'Héros',
    'nav.mode_mj': 'Maître',
    'nav.logout': 'Fermer le grimoire',
    'nav.calendar': 'Mes disponibilités',
    /* — dashboard — */
    'dashboard.title_mj': 'Mes rituels',
    'dashboard.empty_mj': 'Nulle quête en cours. Forgez la première…',
    'dashboard.title_invitations': 'Invitations reçues',
    'dashboard.title_player': 'Mes aventures',
    'dashboard.empty_player': "Nulle invitation parvenue. Guettez l'appel.",
    /* — partie-form — */
    'partie.new_title': 'Nouvelle quête',
    'partie.edit_title': 'Retranscrire le parchemin',
    'partie.save_btn': 'Inscrire',
    /* — partie-detail — */
    'partie.scheduling_title': 'Prochaine séance',
    'partie.no_session': "Aucune séance convoquée. Consultez l'oracle des créneaux.",
    'partie.members_title': '⚔ Compagnons',
    'partie.no_members': "Nulle âme pour l'instant.",
    'partie.remove_member_btn': 'Retirer',
    'partie.no_description': 'Ce grimoire est muet.',
    'partie.invite_title': 'Convoquer un compagnon',
    'partie.search_label': 'Nom ou signe distinctif',
    'partie.search_btn': 'Scruter',
    'partie.invite_btn': 'Convoquer',
    'partie.links_title': "Parchemins d'invocation",
    'partie.generate_link': 'Tisser un parchemin',
    'partie.notice_invited': 'Missive envoyée à {name}.',
    'partie.invite_by_email_label': 'Adresse du destinataire',
    'partie.invite_by_email_btn': 'Envoyer une missive',
    'partie.notice_invited_email': 'Missive envoyée à {email}.',
    'partie.notice_invite_email_error': "La missive n'a pu être envoyée. Réessayez.",
    'partie.notice_copy': 'Parchemin copié dans la besace.',
    'partie.edit_btn': 'Retranscrire',
    'partie.delete_btn': 'Brûler le parchemin',
    'partie.back_btn': 'Retour au grimoire',
    'partie.invitations_tab_label': 'Invitations',
    'partie.show_troupe': 'Voir la troupe',
    'partie.hide_troupe': 'Masquer la troupe',
    /* — calendrier & vote — */
    'cta.find_date': "Consulter l'oracle des créneaux",
    'cta.guild_calendar': 'Voir le grimoire des disponibilités',
    'cta.launch_vote': 'Ouvrir le parchemin du vote',
    'cta.save_constraint': 'Inscrire dans le grimoire',
    'cta.send_reminder': 'Envoyer une missive',
    'section.slots': 'Fenêtres de la destinée',
    'section.constraints': 'Contraintes inscrites',
    'empty.no_slots': "L'oracle ne voit aucun créneau libre. Les parchemins manquent de données.",
    'empty.no_constraints': 'Aucune contrainte inscrite dans le grimoire.',
    'success.constraint_saved': 'Contrainte gravée dans le parchemin.',
    'alert.expiring_soon': 'Votre parchemin expire bientôt. Renouvelez le sort.',
    'alert.missing_player': "{name} n'a pas encore consulté l'oracle.",
    'status.unavailable_label': 'Indisponible',
    'status.unknown_label': 'Mystère',
    'cta.choose_date': 'Sceller ce créneau',
    'cta.cancel_poll': 'Brûler le parchemin de vote',
    'empty.no_poll': 'Aucun vote en cours dans ce grimoire.',
    'success.poll_created': 'Vote ouvert. Les membres ont été avertis.',
    'success.date_chosen': 'La date est gravée dans le grimoire.',
    'poll.status_title': 'Vote en cours',
    'poll.vote_pending': 'Vote de date en cours — parchemin en attente',
    'success.vote_cast': 'Réponse inscrite dans le grimoire.',
    'cta.confirm_votes': 'Sceller mes réponses',
    'poll.vote_closed': "Ce vote est clos. L'oracle a tranché.",
    'alert.all_responded': 'Tous les compagnons ont répondu au vote.',
    'poll.status_summary': 'Vote ouvert — {responded}/{total} compagnons ont répondu',
    /* — personnages (Palier P3) — */
    'character.create_cta': 'Créer un voyageur',
    'character.tab_label': 'Personnages',
    'character.step_class': 'Choisir sa vocation',
    'character.step_type': 'Choisir sa voie',
    'character.magic_deferred_notice':
      "La magie s'apprendra plus tard, jeune sorcier — pour l'instant, seuls les dons passifs s'activent.",
    'character.portrait_missing': 'Aucun portrait — le conteur imagine un visage',
    'character.portrait_edit_cta': 'Modifier le portrait',
    'character.pdf_crop_edit_cta': 'Ajuster le cadrage PDF',
    'character.export_editable_cta': 'Exporter en PDF (éditable)',
    'character.export_2pages_cta': 'Exporter en PDF (2 pages)',
    'character.export_error': "Le parchemin n'a pas pu être copié. Réessayez.",
    'character.owner_badge_mj': 'Maître',
    'character.my_sheet_tab_label': 'Ma fiche',
    /* — roster (Story 6.1) — */
    'roster.mj_badge': 'MJ',
    'roster.invite_slot': 'Convier un compagnon',
    'roster.collapse_label': 'Replier la troupe',
    'roster.expand_label': 'Déplier la troupe',
    'roster.levelup_badge': 'Montée de niveau disponible',
    /* — évolution du personnage (Story 6.2) — */
    'evolution.xp_distribute_cta': "Distribuer de l'XP",
    'evolution.xp_panel_title': "Distribution d'XP",
    'evolution.xp_history_title': "Historique des distributions d'XP",
    'evolution.xp_history_empty': 'Aucune distribution gravée pour le moment.',
    'evolution.xp_note_label': 'Note de session',
    'evolution.xp_confirm_btn': 'Sceller la distribution',
    'evolution.xp_bonus_link': '+ bonus',
    'evolution.xp_levelup_warning': '{name} franchira un niveau',
    /* — montée de niveau & historique (Story 6.3) — */
    'evolution.levelup_banner': 'Niveau [N] disponible !',
    'evolution.levelup_cta': 'Level up !',
    'evolution.levelup_wizard_title': 'Montée de niveau',
    'evolution.levelup_step_pv_pe': 'Répartir 3 points entre PV et PE',
    'evolution.levelup_step_capability': 'Choisir la capacité débloquée',
    'evolution.levelup_legendary_journey_text':
      'Un voyage légendaire vous attend — aucun choix supplémentaire à faire.',
    'evolution.levelup_confirm_cta': 'Valider ce niveau',
    'evolution.history_tab_label': 'Historique',
    'evolution.history_empty': 'Aucun instantané pour le moment.',
    'evolution.mj_edit_trace': 'modifié par le MJ',
    'evolution.landscape_section_title': 'Paysage/Climat favori',
    'evolution.immunity_section_title': 'Immunités',
    'evolution.other_capabilities_title': 'Autres capacités',
    /* — inventaire chiffré (Story 6.4) — */
    'evolution.inventory_section_title': 'Inventaire',
    'evolution.inventory_add_cta': '+ Ajouter un objet',
    'evolution.inventory_empty': "Aucun objet dans l'inventaire pour le moment.",
    'evolution.inventory_overweight_label': 'Surchargé',
    'evolution.inventory_error': "L'inventaire n'a pas pu être mis à jour. Réessayez.",
  },

  /* ══════════════════════════════════════════════════════════ FORÊT ANCIENNE */
  'foret-ancienne': {
    /* — navigation — */
    'nav.my_games': 'Mes pérégrinations',
    'nav.create_game': 'Ouvrir un sentier',
    'nav.mode_joueur': 'Voyageur',
    'nav.mode_mj': 'Guide',
    'nav.logout': 'Quitter la forêt',
    'nav.calendar': 'Mes disponibilités',
    /* — dashboard — */
    'dashboard.title_mj': 'Mes clairières',
    'dashboard.empty_mj': 'Aucune clairière ouverte. Plantez le premier feu…',
    'dashboard.title_invitations': 'Appels de la forêt',
    'dashboard.title_player': 'Mes pérégrinations',
    'dashboard.empty_player': "Nul sentier tracé pour vous. Guettez l'appel.",
    /* — partie-form — */
    'partie.new_title': 'Nouveau sentier',
    'partie.edit_title': 'Rebattre le sentier',
    'partie.save_btn': 'Planter',
    /* — partie-detail — */
    'partie.scheduling_title': 'Prochaine clairière',
    'partie.no_session': "Aucune clairière réservée. L'écureuil cherche encore.",
    'partie.members_title': '🌿 Habitants',
    'partie.no_members': 'Aucun habitant de la clairière.',
    'partie.remove_member_btn': 'Renvoyer',
    'partie.no_description': 'La forêt garde ses secrets.',
    'partie.invite_title': 'Appeler depuis la forêt',
    'partie.search_label': 'Nom ou espèce connue',
    'partie.search_btn': 'Fouiller',
    'partie.invite_btn': 'Accueillir',
    'partie.links_title': 'Sifflets de rappel',
    'partie.generate_link': 'Tisser un laissez-passer',
    'partie.notice_invited': 'Sifflet envoyé à {name}.',
    'partie.invite_by_email_label': 'Adresse du destinataire',
    'partie.invite_by_email_btn': 'Envoyer un sifflet',
    'partie.notice_invited_email': 'Sifflet envoyé à {email}.',
    'partie.notice_invite_email_error': "Le sifflet s'est perdu dans le vent. Réessayez.",
    'partie.notice_copy': 'Laissez-passer copié dans la gibecière.',
    'partie.edit_btn': 'Rebattre',
    'partie.delete_btn': 'Effacer le sentier',
    'partie.back_btn': 'Rentrer dans la forêt',
    'partie.invitations_tab_label': 'Invitations',
    'partie.show_troupe': 'Voir le cercle',
    'partie.hide_troupe': 'Masquer le cercle',
    /* — calendrier & vote — */
    'cta.find_date': "Envoyer l'écureuil messager",
    'cta.guild_calendar': 'Voir la forêt des disponibilités',
    'cta.launch_vote': 'Planter le bâton du vote',
    'cta.save_constraint': 'Marquer le territoire',
    'cta.send_reminder': 'Faire chanter les oiseaux',
    'section.slots': 'Clairières disponibles',
    'section.constraints': 'Zones marquées',
    'empty.no_slots':
      'Aucune clairière libre. La forêt est dense, demandez aux membres leurs disponibilités.',
    'empty.no_constraints': 'Aucun territoire marqué.',
    'success.constraint_saved': 'Territoire marqué dans la forêt.',
    'alert.expiring_soon': "Votre marquage s'efface bientôt. Renouvelez votre présence.",
    'alert.missing_player': "{name} n'a pas encore parcouru la forêt.",
    'status.unavailable_label': 'Absent de la forêt',
    'status.unknown_label': 'Perdu dans les branches',
    'cta.choose_date': 'Planter le drapeau de la clairière',
    'cta.cancel_poll': 'Disperser les feuilles du vote',
    'empty.no_poll': 'Aucun vote en cours dans la forêt.',
    'success.poll_created': "L'écureuil a transmis l'appel du vote.",
    'success.date_chosen': 'La clairière de la séance est choisie.',
    'poll.status_title': 'Vote en cours dans la forêt',
    'poll.vote_pending': "L'écureuil attend ta réponse au vote",
    'success.vote_cast': "L'écureuil a transmis ta réponse.",
    'cta.confirm_votes': 'Transmettre mes réponses',
    'poll.vote_closed': 'Le vote de la forêt est terminé.',
    'alert.all_responded': "Tous les habitants ont répondu à l'appel.",
    'poll.status_summary': 'Vote ouvert — {responded}/{total} habitants ont répondu',
    /* — personnages (Palier P3) — */
    'character.create_cta': 'Éveiller un compagnon de route',
    'character.tab_label': 'Personnages',
    'character.step_class': 'Choisir son rôle dans le cercle',
    'character.step_type': 'Choisir son chemin',
    'character.magic_deferred_notice':
      'Les sortilèges des saisons dorment encore — reviens quand le cercle sera prêt.',
    'character.portrait_missing': 'Aucun visage gravé — la forêt garde son mystère',
    'character.portrait_edit_cta': 'Modifier le portrait',
    'character.export_editable_cta': 'Exporter en PDF (éditable)',
    'character.export_2pages_cta': 'Exporter en PDF (2 pages)',
    'character.export_error': "L'écureuil s'est perdu en chemin. Réessayez.",
    'character.owner_badge_mj': 'Guide',
    'character.my_sheet_tab_label': 'Ma fiche',
    /* — roster (Story 6.1) — */
    'roster.mj_badge': 'MJ',
    'roster.invite_slot': 'Accueillir un compagnon de route',
    'roster.collapse_label': 'Replier le cercle',
    'roster.expand_label': 'Déplier le cercle',
    'roster.levelup_badge': 'Prêt à grandir',
    /* — évolution du personnage (Story 6.2) — */
    'evolution.xp_distribute_cta': 'Partager les récits',
    'evolution.xp_panel_title': 'Partage des récits',
    'evolution.xp_history_title': 'Récits partagés',
    'evolution.xp_history_empty': "Aucun récit partagé pour l'instant.",
    'evolution.xp_note_label': 'Note du récit',
    'evolution.xp_confirm_btn': 'Confier ce récit au cercle',
    'evolution.xp_bonus_link': '+ éclat',
    'evolution.xp_levelup_warning': '{name} va grandir',
    /* — montée de niveau & historique (Story 6.3) — */
    'evolution.levelup_banner': "Le cercle t'appelle à grandir — niveau [N]",
    'evolution.levelup_cta': 'Gravir un échelon',
    'evolution.levelup_wizard_title': 'Croissance',
    'evolution.levelup_step_pv_pe': 'Répartir 3 points entre PV et PE',
    'evolution.levelup_step_capability': 'Choisir le don qui s’éveille',
    'evolution.levelup_legendary_journey_text':
      'Un chemin légendaire s’ouvre — rien de plus à choisir.',
    'evolution.levelup_confirm_cta': 'Graver cet échelon',
    'evolution.history_tab_label': 'Mémoire du cercle',
    'evolution.history_empty': 'Aucun souvenir gravé pour le moment.',
    'evolution.mj_edit_trace': 'modifié par le MJ',
    'evolution.landscape_section_title': 'Paysage/climat de coeur',
    'evolution.immunity_section_title': 'Immunités du cercle',
    'evolution.other_capabilities_title': 'Dons du voyage',
    'evolution.inventory_section_title': 'Besace',
    'evolution.inventory_add_cta': '+ Glisser un objet dans la besace',
    'evolution.inventory_empty': 'La besace est vide pour le moment.',
    'evolution.inventory_overweight_label': 'Surchargée',
    'evolution.inventory_error': "La besace n'a pas pu être mise à jour. Réessaie.",
  },

  /* ════════════════════════════════════════════════════ MÉDIÉVAL STEAMPUNK */
  'medieval-steampunk': {
    /* — navigation — */
    'nav.my_games': 'Mes expéditions',
    'nav.create_game': 'Initier une mission',
    'nav.mode_joueur': 'Mécanicien',
    'nav.mode_mj': 'Ingénieur',
    'nav.logout': 'Couper la vapeur',
    'nav.calendar': 'Mes disponibilités',
    /* — dashboard — */
    'dashboard.title_mj': 'Mes manufactures',
    'dashboard.empty_mj': 'Aucune manufacture active. Lancez la première…',
    'dashboard.title_invitations': 'Transmissions reçues',
    'dashboard.title_player': 'Mes missions',
    'dashboard.empty_player': 'Aucune assignation reçue. En attente de transmission.',
    /* — partie-form — */
    'partie.new_title': 'Nouvelle mission',
    'partie.edit_title': 'Recalibrer la mission',
    'partie.save_btn': 'Valider',
    /* — partie-detail — */
    'partie.scheduling_title': 'Prochaine mission',
    'partie.no_session': "Aucune mission planifiée. Interrogez l'automate.",
    'partie.members_title': '⚙ Équipage',
    'partie.no_members': 'Aucun mécanicien à bord.',
    'partie.remove_member_btn': 'Débarquer',
    'partie.no_description': 'Dossier technique vierge.',
    'partie.invite_title': 'Recruter un mécanicien',
    'partie.search_label': 'Matricule ou appellation',
    'partie.search_btn': 'Scanner',
    'partie.invite_btn': 'Enrôler',
    'partie.links_title': "Télégrammes d'invitation",
    'partie.generate_link': "Forger un badge d'accès",
    'partie.notice_invited': 'Télégramme envoyé à {name}.',
    'partie.invite_by_email_label': 'Adresse du destinataire',
    'partie.invite_by_email_btn': 'Expédier un télégramme',
    'partie.notice_invited_email': 'Télégramme expédié à {email}.',
    'partie.notice_invite_email_error': "Le télégramme n'a pas pu être expédié. Réessayez.",
    'partie.notice_copy': 'Badge copié dans le carnet de bord.',
    'partie.edit_btn': 'Recalibrer',
    'partie.delete_btn': 'Démanteler',
    'partie.back_btn': "Retour à l'atelier",
    'partie.invitations_tab_label': 'Invitations',
    'partie.show_troupe': "Voir l'équipage",
    'partie.hide_troupe': "Masquer l'équipage",
    /* — calendrier & vote — */
    'cta.find_date': "Interroger l'automate des créneaux",
    'cta.guild_calendar': 'Consulter le registre de la mission',
    'cta.launch_vote': 'Actionner le registre de vote',
    'cta.save_constraint': 'Enregistrer dans le registre de vapeur',
    'cta.send_reminder': 'Envoyer un message pneumatique',
    'section.slots': "Créneaux validés par l'automate",
    'section.constraints': 'Registre de contraintes',
    'empty.no_slots': "L'automate ne détecte aucun créneau. Vérifiez les registres des membres.",
    'empty.no_constraints': 'Aucune contrainte dans le registre de vapeur.',
    'success.constraint_saved': 'Contrainte enregistrée dans le registre.',
    'alert.expiring_soon': 'La pression baisse — votre registre expire bientôt.',
    'alert.missing_player': "{name} n'a pas alimenté le registre.",
    'status.unavailable_label': 'Hors-service',
    'status.unknown_label': 'Signal inconnu',
    'cta.choose_date': "Verrouiller l'engrenage de la date",
    'cta.cancel_poll': 'Purger le registre de vote',
    'empty.no_poll': 'Aucun registre de vote actif.',
    'success.poll_created': 'Registre de vote activé. Message pneumatique envoyé.',
    'success.date_chosen': "L'engrenage est verrouillé. Séance confirmée.",
    'poll.status_title': 'Registre de vote actif',
    'poll.vote_pending': 'Registre de vote — réponse requise',
    'success.vote_cast': 'Réponse enregistrée dans le registre.',
    'cta.confirm_votes': 'Valider dans le registre',
    'poll.vote_closed': 'Registre de vote verrouillé.',
    'alert.all_responded': "Tout l'équipage a répondu au registre.",
    'poll.status_summary': 'Registre ouvert — {responded}/{total} membres ont répondu',
    /* — personnages (Palier P3) — */
    'character.create_cta': 'Assembler un automate-voyageur',
    'character.tab_label': 'Personnages',
    'character.step_class': 'Choisir sa fonction',
    'character.step_type': 'Choisir son mécanisme',
    'character.magic_deferred_notice':
      "Le grimoire à vapeur n'est pas encore calibré pour les formules — les avantages de base restent actifs.",
    'character.portrait_missing': 'Aucun portrait gravé sur la plaque',
    'character.portrait_edit_cta': 'Recalibrer le portrait',
    'character.pdf_crop_edit_cta': 'Recalibrer le cadrage PDF',
    'character.export_editable_cta': 'Exporter en PDF (éditable)',
    'character.export_2pages_cta': 'Exporter en PDF (2 pages)',
    'character.export_error': "Échec de l'impression pneumatique. Réessayez.",
    'character.owner_badge_mj': 'Ingénieur',
    'character.my_sheet_tab_label': 'Ma fiche',
    /* — roster (Story 6.1) — */
    'roster.mj_badge': 'MJ',
    'roster.invite_slot': 'Recruter un mécanicien',
    'roster.collapse_label': "Replier l'équipage",
    'roster.expand_label': "Déplier l'équipage",
    'roster.levelup_badge': 'Calibrage niveau disponible',
    /* — évolution du personnage (Story 6.2) — */
    'evolution.xp_distribute_cta': "Distribuer les crédits d'expérience",
    'evolution.xp_panel_title': "Distribution de crédits d'expérience",
    'evolution.xp_history_title': "Registre des crédits d'expérience",
    'evolution.xp_history_empty': 'Aucune distribution enregistrée dans le registre.',
    'evolution.xp_note_label': 'Note technique',
    'evolution.xp_confirm_btn': 'Valider la distribution',
    'evolution.xp_bonus_link': '+ bonus',
    'evolution.xp_levelup_warning': '{name} va être recalibré au niveau supérieur',
    /* — montée de niveau & historique (Story 6.3) — */
    'evolution.levelup_banner': 'Calibrage niveau [N] disponible',
    'evolution.levelup_cta': 'Recalibrer',
    'evolution.levelup_wizard_title': 'Recalibrage',
    'evolution.levelup_step_pv_pe': 'Répartir 3 points entre PV et PE',
    'evolution.levelup_step_capability': 'Choisir le module débloqué',
    'evolution.levelup_legendary_journey_text':
      'Une trajectoire légendaire est engagée — aucun réglage supplémentaire requis.',
    'evolution.levelup_confirm_cta': 'Valider le calibrage',
    'evolution.history_tab_label': 'Journal de bord',
    'evolution.history_empty': 'Aucune entrée consignée pour le moment.',
    'evolution.mj_edit_trace': 'recalibré par le MJ',
    'evolution.landscape_section_title': 'Module paysage/climat',
    'evolution.immunity_section_title': 'Modules d’immunité',
    'evolution.other_capabilities_title': 'Modules installés',
    'evolution.inventory_section_title': 'Compartiment de fret',
    'evolution.inventory_add_cta': '+ Charger un composant',
    'evolution.inventory_empty': 'Aucun composant chargé pour le moment.',
    'evolution.inventory_overweight_label': 'Surcharge',
    'evolution.inventory_error': 'Le fret n’a pas pu être mis à jour. Réessayez.',
  },
};
